import { getCustomMinorImprovement, getCustomOccupation } from './custom-registry'
import { MinorImprovement, Occupation, PlayerActionCard } from '../cards-display/types'
import type { CardDefinition } from '../contract/cards'
import { majorCardDefinitions } from './major'
import { allCommunityCards } from './community/auto-catalog'
import {
  minorImprovementCardsList,
  occupationCardsList,
  implementedMinorImprovementCardsList,
  implementedOccupationCardsList,
  minorImprovementIdsList,
  occupationIdsList,
} from '../cards-display/_lookup-data'

// Base catalog (single-card aggregation) lives in
// `shared/cards-display/_lookup-data.ts` since Sprint S8 — catalog re-exports
// the same shape so callers (server / cards / tests) keep working unchanged.
// We spread to a mutable array because legacy callers (e.g. cards-display/_lookup.ts)
// type the destination as a mutable `MinorImprovement[]` / `Occupation[]`.
export const minorImprovementCards = [...minorImprovementCardsList]
export const occupationCards = [...occupationCardsList]

// Community cards (auto-generated by scripts/generate-register-all.ts)
const communityMinors = allCommunityCards.filter(
  (c): c is MinorImprovement => c instanceof MinorImprovement || c instanceof PlayerActionCard,
)
const communityOccupations = allCommunityCards.filter(
  (c): c is Occupation => c instanceof Occupation,
)

// All cards for reference and developer mode
export const allMinorImprovementCards = [...minorImprovementCards, ...communityMinors]
export const allOccupationCards = [...occupationCards, ...communityOccupations]

// Only implemented cards for normal game dealing (base from cards-display, community kept here)
export const implementedMinorImprovementCards = implementedMinorImprovementCardsList
export const implementedOccupationCards = implementedOccupationCardsList
export const implementedCommunityMinors = communityMinors.filter((c) => c.implemented !== false)
export const implementedCommunityOccupations = communityOccupations.filter((c) => c.implemented !== false)

export const minorImprovementIds = minorImprovementIdsList
export const occupationIds = occupationIdsList
export const getMinorImprovementCard = (id: string) => {
  return allMinorImprovementCards.find((card) => card.id === id)
    ?? getCustomMinorImprovement(id)
}
export const getOccupationCard = (id: string) => {
  return allOccupationCards.find((card) => card.id === id)
    ?? getCustomOccupation(id)
}

/**
 * Unified lookup entry for any card definition (occupation / minor / major).
 * Returns the CardDefinition view; for majors the underlying object is
 * MajorCardData (a CardDefinition superset). Callers needing majors-only
 * fields (e.g. `scoring`) may type-narrow via `as MajorCardData`.
 *
 * Replaces the role getMajorCardEffect played for metadata queries.
 */
export const getCardDefinition = (id: string): CardDefinition | undefined => {
  return (
    getMinorImprovementCard(id)
    ?? getOccupationCard(id)
    ?? majorCardDefinitions.find((c) => c.id === id)
  )
}

/**
 * Mirror of BGA `Card::isField()`: returns true when the played card carries
 * the `isField` metadata flag (set on minor improvements / occupations that
 * BGA marks `$this->field = true`). Used by C80 Rocky Terrain so it can
 * fire its plow trigger on Improvement / Occupation events whose card is
 * itself a field.
 */
export const isFieldCard = (id: string): boolean => {
  return getCardDefinition(id)?.isField === true
}
