// GENERATED by scripts/generate-register-all.ts. Do not edit by hand.
import type { CardSource, CardSourceMeta } from './card-source'
import { A1_Shelter } from './A/A1_Shelter'
import { A10_WoodenShed } from './A/A10_WoodenShed'
import { A100_Curator } from './A/A100_Curator'
import { A101_CookeryOutfitter } from './A/A101_CookeryOutfitter'
import { A102_Grocer } from './A/A102_Grocer'
import { A103_Portmonger } from './A/A103_Portmonger'
import { A104_WoodHarvester } from './A/A104_WoodHarvester'
import { A105_BarrowPusher } from './A/A105_BarrowPusher'
import { A106_SlurrySpreader } from './A/A106_SlurrySpreader'
import { A107_Catcher } from './A/A107_Catcher'
import { A108_MushroomCollector } from './A/A108_MushroomCollector'
import { A109_SmallTrader } from './A/A109_SmallTrader'
import { A11_MudPatch } from './A/A11_MudPatch'
import { A110_Roughcaster } from './A/A110_Roughcaster'
import { A111_WallBuilder } from './A/A111_WallBuilder'
import { A112_ScytheWorker } from './A/A112_ScytheWorker'
import { A113_HeresyTeacher } from './A/A113_HeresyTeacher'
import { A114_SeasonalWorker } from './A/A114_SeasonalWorker'
import { A115_ChiefForester } from './A/A115_ChiefForester'
import { A116_WoodCutter } from './A/A116_WoodCutter'
import { A117_WoodCarrier } from './A/A117_WoodCarrier'
import { A118_Treegardener } from './A/A118_Treegardener'
import { A119_FirewoodCollector } from './A/A119_FirewoodCollector'
import { A12_DrinkingTrough } from './A/A12_DrinkingTrough'
import { A120_ClayHutBuilder } from './A/A120_ClayHutBuilder'
import { A121_ClayPuncher } from './A/A121_ClayPuncher'
import { A122_PanBaker } from './A/A122_PanBaker'
import { A123_FrameBuilder } from './A/A123_FrameBuilder'
import { A124_Knapper } from './A/A124_Knapper'
import { A125_Priest } from './A/A125_Priest'
import { A126_MasterWorkman } from './A/A126_MasterWorkman'
import { A127_Lodger } from './A/A127_Lodger'
import { A128_RiparianBuilder } from './A/A128_RiparianBuilder'
import { A129_Swagman } from './A/A129_Swagman'
import { A13_RenovationCompany } from './A/A13_RenovationCompany'
import { A130_MummysBoy } from './A/A130_MummysBoy'
import { A131_CraftTeacher } from './A/A131_CraftTeacher'
import { A132_Publican } from './A/A132_Publican'
import { A133_Braggart } from './A/A133_Braggart'
import { A134_FullFarmer } from './A/A134_FullFarmer'
import { A135_AnimalReeve } from './A/A135_AnimalReeve'
import { A136_DrudgeryReeve } from './A/A136_DrudgeryReeve'
import { A137_RiverineShepherd } from './A/A137_RiverineShepherd'
import { A138_Harpooner } from './A/A138_Harpooner'
import { A139_HollowWarden } from './A/A139_HollowWarden'
import { A14_CarpentersHammer } from './A/A14_CarpentersHammer'
import { A140_ShovelBearer } from './A/A140_ShovelBearer'
import { A141_TurnipFarmer } from './A/A141_TurnipFarmer'
import { A142_Cordmaker } from './A/A142_Cordmaker'
import { A143_Stonecutter } from './A/A143_Stonecutter'
import { A144_Sequestrator } from './A/A144_Sequestrator'
import { A145_Ropemaker } from './A/A145_Ropemaker'
import { A146_StorehouseSteward } from './A/A146_StorehouseSteward'
import { A147_AnimalDealer } from './A/A147_AnimalDealer'
import { A148_Woolgrower } from './A/A148_Woolgrower'
import { A149_HouseArtist } from './A/A149_HouseArtist'
import { A15_CarpentersAxe } from './A/A15_CarpentersAxe'
import { A150_Stagehand } from './A/A150_Stagehand'
import { A151_Minstrel } from './A/A151_Minstrel'
import { A152_NightSchoolStudent } from './A/A152_NightSchoolStudent'
import { A153_PigOwner } from './A/A153_PigOwner'
import { A154_Paymaster } from './A/A154_Paymaster'
import { A155_Conjurer } from './A/A155_Conjurer'
import { A156_Buyer } from './A/A156_Buyer'
import { A157_Bohemian } from './A/A157_Bohemian'
import { A158_CulinaryArtist } from './A/A158_CulinaryArtist'
import { A159_JoineroftheSea } from './A/A159_JoineroftheSea'
import { A16_RammedClay } from './A/A16_RammedClay'
import { A160_Lutenist } from './A/A160_Lutenist'
import { A161_PatchCaretaker } from './A/A161_PatchCaretaker'
import { A162_ForestTallyman } from './A/A162_ForestTallyman'
import { A163_BuildingExpert } from './A/A163_BuildingExpert'
import { A164_WoodWorker } from './A/A164_WoodWorker'
import { A165_PigBreeder } from './A/A165_PigBreeder'
import { A166_Haydryer } from './A/A166_Haydryer'
import { A167_BreederBuyer } from './A/A167_BreederBuyer'
import { A168_AnimalTeacher } from './A/A168_AnimalTeacher'
import { A169_OffSiter } from './A/A169_OffSiter'
import { A17_ReclamationPlow } from './A/A17_ReclamationPlow'
import { A170_Hayward } from './A/A170_Hayward'
import { A171_Sidekick } from './A/A171_Sidekick'
import { A172_BoatPainter } from './A/A172_BoatPainter'
import { A173_ClayThief } from './A/A173_ClayThief'
import { A174_MasterHora } from './A/A174_MasterHora'
import { A175_HollowGardener } from './A/A175_HollowGardener'
import { A176_Wheelmaker } from './A/A176_Wheelmaker'
import { A177_Middleman } from './A/A177_Middleman'
import { A178_CarpentersBoy } from './A/A178_CarpentersBoy'
import { A179_MountainShepherd } from './A/A179_MountainShepherd'
import { A18_WheelPlow } from './A/A18_WheelPlow'
import { A180_AnimalBrander } from './A/A180_AnimalBrander'
import { A19_Handplow } from './A/A19_Handplow'
import { A2_ShiftingCultivation } from './A/A2_ShiftingCultivation'
import { A20_DoubleTurnPlow } from './A/A20_DoubleTurnPlow'
import { A21_FamilyFriendHome } from './A/A21_FamilyFriendHome'
import { A22_Telegram } from './A/A22_Telegram'
import { A23_StoneCompany } from './A/A23_StoneCompany'
import { A24_ThreshingBoard } from './A/A24_ThreshingBoard'
import { A25_Bassinet } from './A/A25_Bassinet'
import { A26_SleepingCorner } from './A/A26_SleepingCorner'
import { A27_OvenSite } from './A/A27_OvenSite'
import { A28_ForestSchool } from './A/A28_ForestSchool'
import { A29_AleBenches } from './A/A29_AleBenches'
import { A3_PaperKnife } from './A/A3_PaperKnife'
import { A30_BakingSheet } from './A/A30_BakingSheet'
import { A31_DebtSecurity } from './A/A31_DebtSecurity'
import { A32_Manger } from './A/A32_Manger'
import { A33_BigCountry } from './A/A33_BigCountry'
import { A34_Loppers } from './A/A34_Loppers'
import { A35_SwimmingClass } from './A/A35_SwimmingClass'
import { A36_FacadesCarving } from './A/A36_FacadesCarving'
import { A37_Bucksaw } from './A/A37_Bucksaw'
import { A38_WoolBlankets } from './A/A38_WoolBlankets'
import { A39_Chapel } from './A/A39_Chapel'
import { A4_Baseboards } from './A/A4_Baseboards'
import { A40_PottersYard } from './A/A40_PottersYard'
import { A41_VegetableSlicer } from './A/A41_VegetableSlicer'
import { A42_ForestLakeHut } from './A/A42_ForestLakeHut'
import { A43_FarmyardManure } from './A/A43_FarmyardManure'
import { A44_PondHut } from './A/A44_PondHut'
import { A45_FireProtectionPond } from './A/A45_FireProtectionPond'
import { A46_ClawKnife } from './A/A46_ClawKnife'
import { A47_Trellises } from './A/A47_Trellises'
import { A48_ShavingHorse } from './A/A48_ShavingHorse'
import { A49_NestSite } from './A/A49_NestSite'
import { A5_ClayEmbankment } from './A/A5_ClayEmbankment'
import { A50_MilkJug } from './A/A50_MilkJug'
import { A51_DriftNetBoat } from './A/A51_DriftNetBoat'
import { A52_ThrowingAxe } from './A/A52_ThrowingAxe'
import { A53_Claypipe } from './A/A53_Claypipe'
import { A54_Credit } from './A/A54_Credit'
import { A55_JunkRoom } from './A/A55_JunkRoom'
import { A56_Basket } from './A/A56_Basket'
import { A57_MilkingParlor } from './A/A57_MilkingParlor'
import { A58_AsparagusKnife } from './A/A58_AsparagusKnife'
import { A59_PotatoRidger } from './A/A59_PotatoRidger'
import { A6_StorageBarn } from './A/A6_StorageBarn'
import { A60_OrientalFireplace } from './A/A60_OrientalFireplace'
import { A61_WinnowingFan } from './A/A61_WinnowingFan'
import { A62_BeerKeg } from './A/A62_BeerKeg'
import { A63_DutchWindmill } from './A/A63_DutchWindmill'
import { A64_BarleyMill } from './A/A64_BarleyMill'
import { A65_SeedPellets } from './A/A65_SeedPellets'
import { A66_FeedingDish } from './A/A66_FeedingDish'
import { A67_CornScoop } from './A/A67_CornScoop'
import { A68_AsparagusGift } from './A/A68_AsparagusGift'
import { A69_LargeGreenhouse } from './A/A69_LargeGreenhouse'
import { A7_GardenersKnife } from './A/A7_GardenersKnife'
import { A70_LiftingMachine } from './A/A70_LiftingMachine'
import { A71_ClearingSpade } from './A/A71_ClearingSpade'
import { A72_CalciumFertilizers } from './A/A72_CalciumFertilizers'
import { A73_AgriculturalFertilizers } from './A/A73_AgriculturalFertilizers'
import { A74_StableTree } from './A/A74_StableTree'
import { A75_LumberMill } from './A/A75_LumberMill'
import { A76_Cob } from './A/A76_Cob'
import { A77_Hod } from './A/A77_Hod'
import { A78_Canoe } from './A/A78_Canoe'
import { A79_GardenHoe } from './A/A79_GardenHoe'
import { A8_FoodBasket } from './A/A8_FoodBasket'
import { A80_StoneTongs } from './A/A80_StoneTongs'
import { A81_InterimStorage } from './A/A81_InterimStorage'
import { A82_WorkCertificate } from './A/A82_WorkCertificate'
import { A83_ShepherdsCrook } from './A/A83_ShepherdsCrook'
import { A84_Silage } from './A/A84_Silage'
import { A85_Homekeeper } from './A/A85_Homekeeper'
import { A86_AnimalTamer } from './A/A86_AnimalTamer'
import { A87_Conservator } from './A/A87_Conservator'
import { A88_HedgeKeeper } from './A/A88_HedgeKeeper'
import { A89_StablePlanner } from './A/A89_StablePlanner'
import { A9_YoungAnimalMarket } from './A/A9_YoungAnimalMarket'
import { A90_PlowDriver } from './A/A90_PlowDriver'
import { A91_ShiftingCultivator } from './A/A91_ShiftingCultivator'
import { A92_AdoptiveParents } from './A/A92_AdoptiveParents'
import { A93_BedMaker } from './A/A93_BedMaker'
import { A94_LazySowman } from './A/A94_LazySowman'
import { A95_Angler } from './A/A95_Angler'
import { A96_TaskArtisan } from './A/A96_TaskArtisan'
import { A97_Freshman } from './A/A97_Freshman'
import { A98_StableArchitect } from './A/A98_StableArchitect'
import { A99_FellowGrazer } from './A/A99_FellowGrazer'
import { B1_UpscaleLifestyle } from './B/B1_UpscaleLifestyle'
import { B10_Caravan } from './B/B10_Caravan'
import { B100_Clutterer } from './B/B100_Clutterer'
import { B101_FurnitureCarpenter } from './B/B101_FurnitureCarpenter'
import { B102_Consultant } from './B/B102_Consultant'
import { B103_FieldMerchant } from './B/B103_FieldMerchant'
import { B104_SheepWalker } from './B/B104_SheepWalker'
import { B105_CaseBuilder } from './B/B105_CaseBuilder'
import { B106_MoralCrusader } from './B/B106_MoralCrusader'
import { B107_Manservant } from './B/B107_Manservant'
import { B108_OvenFiringBoy } from './B/B108_OvenFiringBoy'
import { B109_PaperMaker } from './B/B109_PaperMaker'
import { B11_Feedyard } from './B/B11_Feedyard'
import { B110_Pavior } from './B/B110_Pavior'
import { B111_Rustic } from './B/B111_Rustic'
import { B112_Silokeeper } from './B/B112_Silokeeper'
import { B113_PatchCaregiver } from './B/B113_PatchCaregiver'
import { B114_Childless } from './B/B114_Childless'
import { B115_TinsmithMaster } from './B/B115_TinsmithMaster'
import { B116_Shoreforester } from './B/B116_Shoreforester'
import { B117_Informant } from './B/B117_Informant'
import { B118_SmallscaleFarmer } from './B/B118_SmallscaleFarmer'
import { B119_Lumberjack } from './B/B119_Lumberjack'
import { B12_Stockyard } from './B/B12_Stockyard'
import { B120_Sweep } from './B/B120_Sweep'
import { B121_Geologist } from './B/B121_Geologist'
import { B122_Mineralogist } from './B/B122_Mineralogist'
import { B123_RoofBallaster } from './B/B123_RoofBallaster'
import { B124_Trimmer } from './B/B124_Trimmer'
import { B125_EstateWorker } from './B/B125_EstateWorker'
import { B126_Carpenter } from './B/B126_Carpenter'
import { B127_Seducer } from './B/B127_Seducer'
import { B128_Plumber } from './B/B128_Plumber'
import { B129_Seatmate } from './B/B129_Seatmate'
import { B13_CarpentersParlor } from './B/B13_CarpentersParlor'
import { B130_FullPeasant } from './B/B130_FullPeasant'
import { B131_Equipper } from './B/B131_Equipper'
import { B132_EstateMaster } from './B/B132_EstateMaster'
import { B133_VillagePeasant } from './B/B133_VillagePeasant'
import { B134_HousebookMaster } from './B/B134_HousebookMaster'
import { B135_NutritionExpert } from './B/B135_NutritionExpert'
import { B136_HouseSteward } from './B/B136_HouseSteward'
import { B137_Wholesaler } from './B/B137_Wholesaler'
import { B138_ForestGuardian } from './B/B138_ForestGuardian'
import { B139_ForestScientist } from './B/B139_ForestScientist'
import { B14_Hawktower } from './B/B14_Hawktower'
import { B140_FarmyardWorker } from './B/B140_FarmyardWorker'
import { B141_FieldCaretaker } from './B/B141_FieldCaretaker'
import { B142_Greengrocer } from './B/B142_Greengrocer'
import { B143_ClayWarden } from './B/B143_ClayWarden'
import { B144_Collier } from './B/B144_Collier'
import { B145_BrushwoodCollector } from './B/B145_BrushwoodCollector'
import { B146_Illusionist } from './B/B146_Illusionist'
import { B147_Huntsman } from './B/B147_Huntsman'
import { B148_PetBroker } from './B/B148_PetBroker'
import { B149_OpenAirFarmer } from './B/B149_OpenAirFarmer'
import { B15_CarpentersBench } from './B/B15_CarpentersBench'
import { B150_LargeScaleFarmer } from './B/B150_LargeScaleFarmer'
import { B151_LittlePeasant } from './B/B151_LittlePeasant'
import { B152_JuniorArtist } from './B/B152_JuniorArtist'
import { B153_Housemaster } from './B/B153_Housemaster'
import { B154_SheepKeeper } from './B/B154_SheepKeeper'
import { B155_ArtTeacher } from './B/B155_ArtTeacher'
import { B156_StorehouseKeeper } from './B/B156_StorehouseKeeper'
import { B157_Salter } from './B/B157_Salter'
import { B158_DistrictManager } from './B/B158_DistrictManager'
import { B159_LieutenantGeneral } from './B/B159_LieutenantGeneral'
import { B16_MiningHammer } from './B/B16_MiningHammer'
import { B160_PubOwner } from './B/B160_PubOwner'
import { B161_Weakling } from './B/B161_Weakling'
import { B162_ForestClearer } from './B/B162_ForestClearer'
import { B163_Pastor } from './B/B163_Pastor'
import { B164_SheepWhisperer } from './B/B164_SheepWhisperer'
import { B165_GameProvider } from './B/B165_GameProvider'
import { B166_CattleFeeder } from './B/B166_CattleFeeder'
import { B167_StableSergeant } from './B/B167_StableSergeant'
import { B168_PastureMaster } from './B/B168_PastureMaster'
import { B169_LivestockSustainer } from './B/B169_LivestockSustainer'
import { B17_ForestPlow } from './B/B17_ForestPlow'
import { B170_CorralBuilder } from './B/B170_CorralBuilder'
import { B171_GreenhouseBuilder } from './B/B171_GreenhouseBuilder'
import { B172_CattleCaregiver } from './B/B172_CattleCaregiver'
import { B173_Sweeper } from './B/B173_Sweeper'
import { B174_RiverbankGardener } from './B/B174_RiverbankGardener'
import { B175_FieldOverseer } from './B/B175_FieldOverseer'
import { B176_VillageIdiot } from './B/B176_VillageIdiot'
import { B177_StoneClawer } from './B/B177_StoneClawer'
import { B178_TagAlong } from './B/B178_TagAlong'
import { B179_WildBoarHunter } from './B/B179_WildBoarHunter'
import { B18_GrasslandHarrow } from './B/B18_GrasslandHarrow'
import { B180_GameTeaser } from './B/B180_GameTeaser'
import { B19_MoldboardPlow } from './B/B19_MoldboardPlow'
import { B2_MiniPasture } from './B/B2_MiniPasture'
import { B20_ChainFloat } from './B/B20_ChainFloat'
import { B21_HayloftBarn } from './B/B21_HayloftBarn'
import { B22_WalkingBoots } from './B/B22_WalkingBoots'
import { B23_FinalScenario } from './B/B23_FinalScenario'
import { B24_Lasso } from './B/B24_Lasso'
import { B25_BreadPaddle } from './B/B25_BreadPaddle'
import { B26_AgrarianFences } from './B/B26_AgrarianFences'
import { B27_Toolbox } from './B/B27_Toolbox'
import { B28_ForestryStudies } from './B/B28_ForestryStudies'
import { B29_CookeryLesson } from './B/B29_CookeryLesson'
import { B3_Moonshine } from './B/B3_Moonshine'
import { B30_WoodPalisades } from './B/B30_WoodPalisades'
import { B31_PotteryYard } from './B/B31_PotteryYard'
import { B32_Kettle } from './B/B32_Kettle'
import { B33_Mantlepiece } from './B/B33_Mantlepiece'
import { B34_SpecialFood } from './B/B34_SpecialFood'
import { B35_HookKnife } from './B/B35_HookKnife'
import { B36_Bottles } from './B/B36_Bottles'
import { B37_Grange } from './B/B37_Grange'
import { B38_FutureBuildingSite } from './B/B38_FutureBuildingSite'
import { B39_Loom } from './B/B39_Loom'
import { B4_WoodPile } from './B/B4_WoodPile'
import { B40_BreweryPond } from './B/B40_BreweryPond'
import { B41_Hauberg } from './B/B41_Hauberg'
import { B42_ForestInn } from './B/B42_ForestInn'
import { B43_Chophouse } from './B/B43_Chophouse'
import { B44_ChickStable } from './B/B44_ChickStable'
import { B45_StrawberryPatch } from './B/B45_StrawberryPatch'
import { B46_ClubHouse } from './B/B46_ClubHouse'
import { B47_HerringPot } from './B/B47_HerringPot'
import { B48_ForestStone } from './B/B48_ForestStone'
import { B49_Scales } from './B/B49_Scales'
import { B5_StoreofExperience } from './B/B5_StoreofExperience'
import { B50_ButterChurn } from './B/B50_ButterChurn'
import { B51_DiggingSpade } from './B/B51_DiggingSpade'
import { B52_GrowingFarm } from './B/B52_GrowingFarm'
import { B53_SculptureCourse } from './B/B53_SculptureCourse'
import { B54_Tumbrel } from './B/B54_Tumbrel'
import { B55_MaintenancePremium } from './B/B55_MaintenancePremium'
import { B56_Brook } from './B/B56_Brook'
import { B57_Scullery } from './B/B57_Scullery'
import { B58_CrackWeeder } from './B/B58_CrackWeeder'
import { B59_FoodChest } from './B/B59_FoodChest'
import { B6_ExcursiontotheQuarry } from './B/B6_ExcursiontotheQuarry'
import { B60_BrewingWater } from './B/B60_BrewingWater'
import { B61_ThreeFieldRotation } from './B/B61_ThreeFieldRotation'
import { B62_Pitchfork } from './B/B62_Pitchfork'
import { B63_Tasting } from './B/B63_Tasting'
import { B64_MillWheel } from './B/B64_MillWheel'
import { B65_GrainDepot } from './B/B65_GrainDepot'
import { B66_SackCart } from './B/B66_SackCart'
import { B67_HandTruck } from './B/B67_HandTruck'
import { B68_Beanfield } from './B/B68_Beanfield'
import { B69_PottersMarket } from './B/B69_PottersMarket'
import { B7_Wage } from './B/B7_Wage'
import { B70_NewPurchase } from './B/B70_NewPurchase'
import { B71_HarvestHouse } from './B/B71_HarvestHouse'
import { B72_LoveforAgriculture } from './B/B72_LoveforAgriculture'
import { B73_GiftBasket } from './B/B73_GiftBasket'
import { B74_ThickForest } from './B/B74_ThickForest'
import { B75_WoodWorkshop } from './B/B75_WoodWorkshop'
import { B76_Ceilings } from './B/B76_Ceilings'
import { B77_LoamPit } from './B/B77_LoamPit'
import { B78_ReedBelt } from './B/B78_ReedBelt'
import { B79_Corf } from './B/B79_Corf'
import { B8_MarketStall } from './B/B8_MarketStall'
import { B80_HardPorcelain } from './B/B80_HardPorcelain'
import { B81_Handcart } from './B/B81_Handcart'
import { B82_ValueAssets } from './B/B82_ValueAssets'
import { B83_MuddyPuddles } from './B/B83_MuddyPuddles'
import { B84_AcornsBasket } from './B/B84_AcornsBasket'
import { B85_FarmHand } from './B/B85_FarmHand'
import { B86_TruffleSearcher } from './B/B86_TruffleSearcher'
import { B87_Cottager } from './B/B87_Cottager'
import { B88_EstablishedPerson } from './B/B88_EstablishedPerson'
import { B89_Groom } from './B/B89_Groom'
import { B9_BeatingRod } from './B/B9_BeatingRod'
import { B90_CooperativePlower } from './B/B90_CooperativePlower'
import { B91_AssistantTiller } from './B/B91_AssistantTiller'
import { B92_LittleStickKnitter } from './B/B92_LittleStickKnitter'
import { B93_Confidant } from './B/B93_Confidant'
import { B94_StockProtector } from './B/B94_StockProtector'
import { B95_MasterBricklayer } from './B/B95_MasterBricklayer'
import { B96_TreeFarmJoiner } from './B/B96_TreeFarmJoiner'
import { B97_Scholar } from './B/B97_Scholar'
import { B98_OrganicFarmer } from './B/B98_OrganicFarmer'
import { B99_Tutor } from './B/B99_Tutor'
import { C1_Overhaul } from './C/C1_Overhaul'
import { C10_BunkBeds } from './C/C10_BunkBeds'
import { C100_Butler } from './C/C100_Butler'
import { C101_StallHolder } from './C/C101_StallHolder'
import { C102_TreeGuard } from './C/C102_TreeGuard'
import { C103_GreenGrocer } from './C/C103_GreenGrocer'
import { C104_Collector } from './C/C104_Collector'
import { C105_BasketCarrier } from './C/C105_BasketCarrier'
import { C106_PotatoHarvester } from './C/C106_PotatoHarvester'
import { C107_Baker } from './C/C107_Baker'
import { C108_Layabout } from './C/C108_Layabout'
import { C109_SchnappsDistiller } from './C/C109_SchnappsDistiller'
import { C11_WildlifeReserve } from './C/C11_WildlifeReserve'
import { C110_HomeBrewer } from './C/C110_HomeBrewer'
import { C111_SmallAnimalBreeder } from './C/C111_SmallAnimalBreeder'
import { C112_Thresher } from './C/C112_Thresher'
import { C113_WinterCaretaker } from './C/C113_WinterCaretaker'
import { C114_SoilScientist } from './C/C114_SoilScientist'
import { C115_Sower } from './C/C115_Sower'
import { C116_FurnitureMaker } from './C/C116_FurnitureMaker'
import { C117_Legworker } from './C/C117_Legworker'
import { C118_WoodCollector } from './C/C118_WoodCollector'
import { C119_SkillfulRenovator } from './C/C119_SkillfulRenovator'
import { C12_CattleFarm } from './C/C12_CattleFarm'
import { C120_AgriculturalLabourer } from './C/C120_AgriculturalLabourer'
import { C121_ClayKneader } from './C/C121_ClayKneader'
import { C122_Bricklayer } from './C/C122_Bricklayer'
import { C123_Freemason } from './C/C123_Freemason'
import { C124_StoneImporter } from './C/C124_StoneImporter'
import { C125_Nightworker } from './C/C125_Nightworker'
import { C126_Excavator } from './C/C126_Excavator'
import { C127_Lover } from './C/C127_Lover'
import { C128_WoodenHutExtender } from './C/C128_WoodenHutExtender'
import { C129_SecondSpouse } from './C/C129_SecondSpouse'
import { C13_WoodSlideHammer } from './C/C13_WoodSlideHammer'
import { C130_OutskirtsDirector } from './C/C130_OutskirtsDirector'
import { C131_PrivateTeacher } from './C/C131_PrivateTeacher'
import { C132_TimberShingleMaker } from './C/C132_TimberShingleMaker'
import { C133_Soldier } from './C/C133_Soldier'
import { C134_CowPrince } from './C/C134_CowPrince'
import { C135_Constable } from './C/C135_Constable'
import { C136_RanchProvost } from './C/C136_RanchProvost'
import { C137_CharcoalBurner } from './C/C137_CharcoalBurner'
import { C138_AnimalFeeder } from './C/C138_AnimalFeeder'
import { C139_BasketmakersWife } from './C/C139_BasketmakersWife'
import { C14_StrawThatchedRoof } from './C/C14_StrawThatchedRoof'
import { C140_PackagingArtist } from './C/C140_PackagingArtist'
import { C141_SheepProvider } from './C/C141_SheepProvider'
import { C142_MarketCrier } from './C/C142_MarketCrier'
import { C143_StoneBuyer } from './C/C143_StoneBuyer'
import { C144_ReedRoofRenovator } from './C/C144_ReedRoofRenovator'
import { C145_ForestReviewer } from './C/C145_ForestReviewer'
import { C146_WorkshopAssistant } from './C/C146_WorkshopAssistant'
import { C147_Cowherd } from './C/C147_Cowherd'
import { C148_MudWallower } from './C/C148_MudWallower'
import { C149_ResourceRecycler } from './C/C149_ResourceRecycler'
import { C15_Trellis } from './C/C15_Trellis'
import { C150_ParrotBreeder } from './C/C150_ParrotBreeder'
import { C151_SowingDirector } from './C/C151_SowingDirector'
import { C152_Puppeteer } from './C/C152_Puppeteer'
import { C153_PatternMaker } from './C/C153_PatternMaker'
import { C154_TwinResearcher } from './C/C154_TwinResearcher'
import { C155_FoodDistributor } from './C/C155_FoodDistributor'
import { C156_HoofCaregiver } from './C/C156_HoofCaregiver'
import { C157_ResourceAnalyzer } from './C/C157_ResourceAnalyzer'
import { C158_ForestCampaigner } from './C/C158_ForestCampaigner'
import { C159_FishermansFriend } from './C/C159_FishermansFriend'
import { C16_FieldFences } from './C/C16_FieldFences'
import { C160_Outrider } from './C/C160_Outrider'
import { C161_PotatoDigger } from './C/C161_PotatoDigger'
import { C162_ForestOwner } from './C/C162_ForestOwner'
import { C163_MaterialDeliveryman } from './C/C163_MaterialDeliveryman'
import { C164_GermanHeathKeeper } from './C/C164_GermanHeathKeeper'
import { C165_GameCatcher } from './C/C165_GameCatcher'
import { C166_CattleWhisperer } from './C/C166_CattleWhisperer'
import { C167_CattleBuyer } from './C/C167_CattleBuyer'
import { C168_AnimalCatcher } from './C/C168_AnimalCatcher'
import { C169_FastMason } from './C/C169_FastMason'
import { C17_NewlyPlowedField } from './C/C17_NewlyPlowedField'
import { C170_AmateurFencer } from './C/C170_AmateurFencer'
import { C171_YoungArtist } from './C/C171_YoungArtist'
import { C172_FieldCounter } from './C/C172_FieldCounter'
import { C173_TopOuter } from './C/C173_TopOuter'
import { C174_StoneCustodian } from './C/C174_StoneCustodian'
import { C175_VillageTeacher } from './C/C175_VillageTeacher'
import { C176_Cleanacre } from './C/C176_Cleanacre'
import { C177_MountainHiker } from './C/C177_MountainHiker'
import { C178_OnSiteReverend } from './C/C178_OnSiteReverend'
import { C179_BovinePioneer } from './C/C179_BovinePioneer'
import { C18_RollOverPlow } from './C/C18_RollOverPlow'
import { C180_Trapper } from './C/C180_Trapper'
import { C19_SwingPlow } from './C/C19_SwingPlow'
import { C2_Stable } from './C/C2_Stable'
import { C20_MolePlow } from './C/C20_MolePlow'
import { C21_HeartofStone } from './C/C21_HeartofStone'
import { C22_BasketChair } from './C/C22_BasketChair'
import { C23_JobContract } from './C/C23_JobContract'
import { C24_BedintheGrainField } from './C/C24_BedintheGrainField'
import { C25_SteamMachine } from './C/C25_SteamMachine'
import { C26_Flail } from './C/C26_Flail'
import { C27_Blueprint } from './C/C27_Blueprint'
import { C28_TeachersDesk } from './C/C28_TeachersDesk'
import { C29_BeerTable } from './C/C29_BeerTable'
import { C3_CarriageTrip } from './C/C3_CarriageTrip'
import { C30_HalfTimberedHouse } from './C/C30_HalfTimberedHouse'
import { C31_WritingChamber } from './C/C31_WritingChamber'
import { C32_AbortOriel } from './C/C32_AbortOriel'
import { C33_GreeningPlan } from './C/C33_GreeningPlan'
import { C34_ElephantgrassPlant } from './C/C34_ElephantgrassPlant'
import { C35_LanternHouse } from './C/C35_LanternHouse'
import { C36_ClayDeposit } from './C/C36_ClayDeposit'
import { C37_DwellingMound } from './C/C37_DwellingMound'
import { C38_Christianity } from './C/C38_Christianity'
import { C39_StudioBoat } from './C/C39_StudioBoat'
import { C4_WritingBoards } from './C/C4_WritingBoards'
import { C40_CanvasSack } from './C/C40_CanvasSack'
import { C41_FarmStore } from './C/C41_FarmStore'
import { C42_RavenousHunger } from './C/C42_RavenousHunger'
import { C43_FarmBuilding } from './C/C43_FarmBuilding'
import { C44_ChickenCoop } from './C/C44_ChickenCoop'
import { C45_Stew } from './C/C45_Stew'
import { C46_Mandoline } from './C/C46_Mandoline'
import { C47_GardenClaw } from './C/C47_GardenClaw'
import { C48_Farmstead } from './C/C48_Farmstead'
import { C49_BeerStall } from './C/C49_BeerStall'
import { C5_Remodeling } from './C/C5_Remodeling'
import { C50_StableYard } from './C/C50_StableYard'
import { C51_FishingNet } from './C/C51_FishingNet'
import { C52_HuntsmansHat } from './C/C52_HuntsmansHat'
import { C53_GypsysCrock } from './C/C53_GypsysCrock'
import { C54_MarketBooth } from './C/C54_MarketBooth'
import { C55_Studio } from './C/C55_Studio'
import { C56_FeedFence } from './C/C56_FeedFence'
import { C57_Crudite } from './C/C57_Crudite'
import { C58_Woodcraft } from './C/C58_Woodcraft'
import { C59_SchnappsDistillery } from './C/C59_SchnappsDistillery'
import { C6_StoneClearing } from './C/C6_StoneClearing'
import { C60_SmallPottersOven } from './C/C60_SmallPottersOven'
import { C61_BeerStein } from './C/C61_BeerStein'
import { C62_CookeryExtension } from './C/C62_CookeryExtension'
import { C63_CraftBrewery } from './C/C63_CraftBrewery'
import { C64_CornSchnappsDistillery } from './C/C64_CornSchnappsDistillery'
import { C65_Granary } from './C/C65_Granary'
import { C66_EternalRyeCultivation } from './C/C66_EternalRyeCultivation'
import { C67_MineralFeeder } from './C/C67_MineralFeeder'
import { C68_Bookcase } from './C/C68_Bookcase'
import { C69_LandConsolidation } from './C/C69_LandConsolidation'
import { C7_BladeShears } from './C/C7_BladeShears'
import { C70_LettucePatch } from './C/C70_LettucePatch'
import { C71_Slurry } from './C/C71_Slurry'
import { C72_FestivalPlanning } from './C/C72_FestivalPlanning'
import { C73_SeaweedFertilizer } from './C/C73_SeaweedFertilizer'
import { C74_PrivateForest } from './C/C74_PrivateForest'
import { C75_Firewood } from './C/C75_Firewood'
import { C76_WoodCart } from './C/C76_WoodCart'
import { C77_ClaySupply } from './C/C77_ClaySupply'
import { C78_ReedHattedToad } from './C/C78_ReedHattedToad'
import { C79_StoneCart } from './C/C79_StoneCart'
import { C8_PlantFertilizer } from './C/C8_PlantFertilizer'
import { C80_RockyTerrain } from './C/C80_RockyTerrain'
import { C81_MaterialHub } from './C/C81_MaterialHub'
import { C82_HardwareStore } from './C/C82_HardwareStore'
import { C83_EarlyCattle } from './C/C83_EarlyCattle'
import { C84_PerennialRye } from './C/C84_PerennialRye'
import { C85_DenBuilder } from './C/C85_DenBuilder'
import { C86_LivestockFeeder } from './C/C86_LivestockFeeder'
import { C87_Mason } from './C/C87_Mason'
import { C88_CarpentersApprentice } from './C/C88_CarpentersApprentice'
import { C89_StableMaster } from './C/C89_StableMaster'
import { C9_AutomaticWaterTrough } from './C/C9_AutomaticWaterTrough'
import { C90_FieldWatchman } from './C/C90_FieldWatchman'
import { C91_PlowHero } from './C/C91_PlowHero'
import { C92_AutumnMother } from './C/C92_AutumnMother'
import { C93_InnerDistrictsDirector } from './C/C93_InnerDistrictsDirector'
import { C94_StableCleaner } from './C/C94_StableCleaner'
import { C95_BasketWeaver } from './C/C95_BasketWeaver'
import { C96_Merchant } from './C/C96_Merchant'
import { C97_SeedResearcher } from './C/C97_SeedResearcher'
import { C98_CubeCutter } from './C/C98_CubeCutter'
import { C99_GardenDesigner } from './C/C99_GardenDesigner'
import { CUSTOM_FixtureHarvester } from './community/CUSTOM_FixtureHarvester'
import { D1_ZigzagHarrow } from './D/D1_ZigzagHarrow'
import { D10_StorksNest } from './D/D10_StorksNest'
import { D100_LordoftheManor } from './D/D100_LordoftheManor'
import { D101_SugarBaker } from './D/D101_SugarBaker'
import { D102_SampleStableMaker } from './D/D102_SampleStableMaker'
import { D103_CanalBoatman } from './D/D103_CanalBoatman'
import { D104_Cultivator } from './D/D104_Cultivator'
import { D105_Sculptor } from './D/D105_Sculptor'
import { D106_WhiskyDistiller } from './D/D106_WhiskyDistiller'
import { D107_Bellfounder } from './D/D107_Bellfounder'
import { D108_StoneCarver } from './D/D108_StoneCarver'
import { D109_SowingMaster } from './D/D109_SowingMaster'
import { D11_LawnFertilizer } from './D/D11_LawnFertilizer'
import { D110_FishFarmer } from './D/D110_FishFarmer'
import { D111_InteriorDecorator } from './D/D111_InteriorDecorator'
import { D112_YoungFarmer } from './D/D112_YoungFarmer'
import { D113_FoodMerchant } from './D/D113_FoodMerchant'
import { D114_SeedTrader } from './D/D114_SeedTrader'
import { D115_FodderPlanter } from './D/D115_FodderPlanter'
import { D116_TreeInspector } from './D/D116_TreeInspector'
import { D117_WoodExpert } from './D/D117_WoodExpert'
import { D118_Bonehead } from './D/D118_Bonehead'
import { D119_WoodBarterer } from './D/D119_WoodBarterer'
import { D12_MilkingPlace } from './D/D12_MilkingPlace'
import { D120_ClayDeliveryman } from './D/D120_ClayDeliveryman'
import { D121_ClayPlasterer } from './D/D121_ClayPlasterer'
import { D122_ClayCarrier } from './D/D122_ClayCarrier'
import { D123_RenovationPreparer } from './D/D123_RenovationPreparer'
import { D124_Emissary } from './D/D124_Emissary'
import { D125_ForestTrader } from './D/D125_ForestTrader'
import { D126_FieldCultivator } from './D/D126_FieldCultivator'
import { D127_HardworkingMan } from './D/D127_HardworkingMan'
import { D128_BuildingTycoon } from './D/D128_BuildingTycoon'
import { D129_LumberVirtuoso } from './D/D129_LumberVirtuoso'
import { D13_Trowel } from './D/D13_Trowel'
import { D130_RecreationalCarpenter } from './D/D130_RecreationalCarpenter'
import { D131_CraftsmanshipPromoter } from './D/D131_CraftsmanshipPromoter'
import { D132_HideFarmer } from './D/D132_HideFarmer'
import { D133_BeerTentOperator } from './D/D133_BeerTentOperator'
import { D134_OysterEater } from './D/D134_OysterEater'
import { D135_GardeningHeadOfficial } from './D/D135_GardeningHeadOfficial'
import { D136_AnimalActivist } from './D/D136_AnimalActivist'
import { D137_TradeTeacher } from './D/D137_TradeTeacher'
import { D138_PetLover } from './D/D138_PetLover'
import { D139_Chairman } from './D/D139_Chairman'
import { D14_HammerCrusher } from './D/D14_HammerCrusher'
import { D140_Loudmouth } from './D/D140_Loudmouth'
import { D141_SeedSeller } from './D/D141_SeedSeller'
import { D142_PotatoPlanter } from './D/D142_PotatoPlanter'
import { D143_TreeCutter } from './D/D143_TreeCutter'
import { D144_WaterWorker } from './D/D144_WaterWorker'
import { D145_RoofExaminer } from './D/D145_RoofExaminer'
import { D146_Porter } from './D/D146_Porter'
import { D147_TrapBuilder } from './D/D147_TrapBuilder'
import { D148_DomesticianExpert } from './D/D148_DomesticianExpert'
import { D149_CasualWorker } from './D/D149_CasualWorker'
import { D15_ClaySupports } from './D/D15_ClaySupports'
import { D150_GodlySpouse } from './D/D150_GodlySpouse'
import { D151_SpinDoctor } from './D/D151_SpinDoctor'
import { D152_Patron } from './D/D152_Patron'
import { D153_WealthyMan } from './D/D153_WealthyMan'
import { D154_ChimneySweep } from './D/D154_ChimneySweep'
import { D155_Ebonist } from './D/D155_Ebonist'
import { D156_RetailDealer } from './D/D156_RetailDealer'
import { D157_PartyOrganizer } from './D/D157_PartyOrganizer'
import { D158_BeanCounter } from './D/D158_BeanCounter'
import { D159_ReedSeller } from './D/D159_ReedSeller'
import { D16_WoodenWheyBucket } from './D/D16_WoodenWheyBucket'
import { D160_Midwife } from './D/D160_Midwife'
import { D161_CabbageBuyer } from './D/D161_CabbageBuyer'
import { D162_ClayFirer } from './D/D162_ClayFirer'
import { D163_JourneymanBricklayer } from './D/D163_JourneymanBricklayer'
import { D164_PetGrower } from './D/D164_PetGrower'
import { D165_PigStalker } from './D/D165_PigStalker'
import { D166_StableMilker } from './D/D166_StableMilker'
import { D167_PureBreeder } from './D/D167_PureBreeder'
import { D168_Stockman } from './D/D168_Stockman'
import { D169_Plowsmith } from './D/D169_Plowsmith'
import { D17_DrillHarrow } from './D/D17_DrillHarrow'
import { D170_FoldBuilder } from './D/D170_FoldBuilder'
import { D171_SeniorTeacher } from './D/D171_SeniorTeacher'
import { D172_PutcherMaker } from './D/D172_PutcherMaker'
import { D173_TownClerk } from './D/D173_TownClerk'
import { D174_LoessGardener } from './D/D174_LoessGardener'
import { D175_Countryman } from './D/D175_Countryman'
import { D176_Woodshacker } from './D/D176_Woodshacker'
import { D177_Graduate } from './D/D177_Graduate'
import { D178_SubstituteTeacher } from './D/D178_SubstituteTeacher'
import { D179_Bullcatcher } from './D/D179_Bullcatcher'
import { D18_SteamPlow } from './D/D18_SteamPlow'
import { D180_PartTimeWorker } from './D/D180_PartTimeWorker'
import { D19_PulverizerPlow } from './D/D19_PulverizerPlow'
import { D2_DwellingPlan } from './D/D2_DwellingPlan'
import { D20_TurnwrestPlow } from './D/D20_TurnwrestPlow'
import { D21_Recruitment } from './D/D21_Recruitment'
import { D22_WorkPermit } from './D/D22_WorkPermit'
import { D23_PioneeringSpirit } from './D/D23_PioneeringSpirit'
import { D24_BrotherlyLove } from './D/D24_BrotherlyLove'
import { D25_WitchesDanceFloor } from './D/D25_WitchesDanceFloor'
import { D26_CarpentersYard } from './D/D26_CarpentersYard'
import { D27_Retraining } from './D/D27_Retraining'
import { D28_WritingDesk } from './D/D28_WritingDesk'
import { D29_MuckRake } from './D/D29_MuckRake'
import { D3_Furrows } from './D/D3_Furrows'
import { D30_ArtisanDistrict } from './D/D30_ArtisanDistrict'
import { D31_Storeroom } from './D/D31_Storeroom'
import { D32_WoodRake } from './D/D32_WoodRake'
import { D33_SummerHouse } from './D/D33_SummerHouse'
import { D34_LuxuriousHostel } from './D/D34_LuxuriousHostel'
import { D35_FodderChamber } from './D/D35_FodderChamber'
import { D36_BreedRegistry } from './D/D36_BreedRegistry'
import { D37_Sculpture } from './D/D37_Sculpture'
import { D38_MilkingStool } from './D/D38_MilkingStool'
import { D39_TruffleSlicer } from './D/D39_TruffleSlicer'
import { D4_CrossCutWood } from './D/D4_CrossCutWood'
import { D40_Cesspit } from './D/D40_Cesspit'
import { D41_HorseDrawnBoat } from './D/D41_HorseDrawnBoat'
import { D42_EducationBonus } from './D/D42_EducationBonus'
import { D43_Hutch } from './D/D43_Hutch'
import { D44_ForestWell } from './D/D44_ForestWell'
import { D45_SheepWell } from './D/D45_SheepWell'
import { D46_PelletPress } from './D/D46_PelletPress'
import { D47_Churchyard } from './D/D47_Churchyard'
import { D48_CivicFacade } from './D/D48_CivicFacade'
import { D49_Bookshelf } from './D/D49_Bookshelf'
import { D5_FieldClay } from './D/D5_FieldClay'
import { D50_ForeignAid } from './D/D50_ForeignAid'
import { D51_Archway } from './D/D51_Archway'
import { D52_RollingPin } from './D/D52_RollingPin'
import { D53_TeaHouse } from './D/D53_TeaHouse'
import { D54_TroutPool } from './D/D54_TroutPool'
import { D55_NewMarket } from './D/D55_NewMarket'
import { D56_FatstockStretcher } from './D/D56_FatstockStretcher'
import { D57_WholesaleMarket } from './D/D57_WholesaleMarket'
import { D58_Gritter } from './D/D58_Gritter'
import { D59_EarthOven } from './D/D59_EarthOven'
import { D6_PetrifiedWood } from './D/D6_PetrifiedWood'
import { D60_LargePottery } from './D/D60_LargePottery'
import { D61_BaleofStraw } from './D/D61_BaleofStraw'
import { D62_BeerTap } from './D/D62_BeerTap'
import { D63_Lynchet } from './D/D63_Lynchet'
import { D64_BakingCourse } from './D/D64_BakingCourse'
import { D65_GrainSieve } from './D/D65_GrainSieve'
import { D66_PotterCeramics } from './D/D66_PotterCeramics'
import { D67_ReapHook } from './D/D67_ReapHook'
import { D68_SmallBasket } from './D/D68_SmallBasket'
import { D69_SmallGreenhouse } from './D/D69_SmallGreenhouse'
import { D7_Trident } from './D/D7_Trident'
import { D70_StrawManure } from './D/D70_StrawManure'
import { D71_Changeover } from './D/D71_Changeover'
import { D72_StableManure } from './D/D72_StableManure'
import { D73_SupplyBoat } from './D/D73_SupplyBoat'
import { D74_RoyalWood } from './D/D74_RoyalWood'
import { D75_WoodField } from './D/D75_WoodField'
import { D76_SocialBenefits } from './D/D76_SocialBenefits'
import { D77_RecycledBrick } from './D/D77_RecycledBrick'
import { D78_ReedPond } from './D/D78_ReedPond'
import { D79_CarrotMuseum } from './D/D79_CarrotMuseum'
import { D8_FernSeeds } from './D/D8_FernSeeds'
import { D80_BrickHammer } from './D/D80_BrickHammer'
import { D81_RoofLadder } from './D/D81_RoofLadder'
import { D82_HuntingTrophy } from './D/D82_HuntingTrophy'
import { D83_Pigswill } from './D/D83_Pigswill'
import { D84_FeedPellets } from './D/D84_FeedPellets'
import { D85_Reader } from './D/D85_Reader'
import { D86_SheepAgent } from './D/D86_SheepAgent'
import { D87_MasterBuilder } from './D/D87_MasterBuilder'
import { D88_Millwright } from './D/D88_Millwright'
import { D89_Stablehand } from './D/D89_Stablehand'
import { D9_GameTrade } from './D/D9_GameTrade'
import { D90_PlowMaker } from './D/D90_PlowMaker'
import { D91_Plowman } from './D/D91_Plowman'
import { D92_ChildOmbudsman } from './D/D92_ChildOmbudsman'
import { D93_SheepInspector } from './D/D93_SheepInspector'
import { D94_HenpeckedHusband } from './D/D94_HenpeckedHusband'
import { D95_SiteManager } from './D/D95_SiteManager'
import { D96_Furnisher } from './D/D96_Furnisher'
import { D97_BeggingStudent } from './D/D97_BeggingStudent'
import { D98_Transactor } from './D/D98_Transactor'
import { D99_EarthenwarePotter } from './D/D99_EarthenwarePotter'
import { E1_PoleBarns } from './E/E1_PoleBarns'
import { E10_StrawHat } from './E/E10_StrawHat'
import { E100_MuseumCaretaker } from './E/E100_MuseumCaretaker'
import { E101_Blighter } from './E/E101_Blighter'
import { E102_Acquirer } from './E/E102_Acquirer'
import { E103_Wolf } from './E/E103_Wolf'
import { E104_SpiceTrader } from './E/E104_SpiceTrader'
import { E105_Pioneer } from './E/E105_Pioneer'
import { E106_EmergencySeller } from './E/E106_EmergencySeller'
import { E107_LandSurveyor } from './E/E107_LandSurveyor'
import { E108_BlackberryFarmer } from './E/E108_BlackberryFarmer'
import { E109_BraidMaker } from './E/E109_BraidMaker'
import { E11_PettingZoo } from './E/E11_PettingZoo'
import { E110_Dentist } from './E/E110_Dentist'
import { E111_Recluse } from './E/E111_Recluse'
import { E112_GrainThief } from './E/E112_GrainThief'
import { E113_Godmother } from './E/E113_Godmother'
import { E114_ShedBuilder } from './E/E114_ShedBuilder'
import { E115_SeedServant } from './E/E115_SeedServant'
import { E116_FirCutter } from './E/E116_FirCutter'
import { E117_PipeSmoker } from './E/E117_PipeSmoker'
import { E118_KindlingGatherer } from './E/E118_KindlingGatherer'
import { E119_LandHeir } from './E/E119_LandHeir'
import { E12_AnimalBedding } from './E/E12_AnimalBedding'
import { E120_ScrapCollector } from './E/E120_ScrapCollector'
import { E121_HillCultivator } from './E/E121_HillCultivator'
import { E122_Cottar } from './E/E122_Cottar'
import { E123_ResourceHoarder } from './E/E123_ResourceHoarder'
import { E124_MayorCandidate } from './E/E124_MayorCandidate'
import { E125_DelayedWayfarer } from './E/E125_DelayedWayfarer'
import { E126_TaxCollector } from './E/E126_TaxCollector'
import { E127_DiligentFarmer } from './E/E127_DiligentFarmer'
import { E128_Saddler } from './E/E128_Saddler'
import { E129_Imitator } from './E/E129_Imitator'
import { E13_StoneHouseReconstruction } from './E/E13_StoneHouseReconstruction'
import { E130_Overachiever } from './E/E130_Overachiever'
import { E131_MarketMaster } from './E/E131_MarketMaster'
import { E132_VeggieLover } from './E/E132_VeggieLover'
import { E133_ChampionBreeder } from './E/E133_ChampionBreeder'
import { E134_Omnifarmer } from './E/E134_Omnifarmer'
import { E135_Pickler } from './E/E135_Pickler'
import { E136_AnimalHusbandryWorker } from './E/E136_AnimalHusbandryWorker'
import { E137_FlaxFarmer } from './E/E137_FlaxFarmer'
import { E138_LivestockExpert } from './E/E138_LivestockExpert'
import { E139_BunnyBreeder } from './E/E139_BunnyBreeder'
import { E14_WoodSaw } from './E/E14_WoodSaw'
import { E140_Carter } from './E/E140_Carter'
import { E141_VegetableVendor } from './E/E141_VegetableVendor'
import { E142_Smuggler } from './E/E142_Smuggler'
import { E143_Hewer } from './E/E143_Hewer'
import { E144_WaresSalesman } from './E/E144_WaresSalesman'
import { E145_Parvenu } from './E/E145_Parvenu'
import { E146_Reseller } from './E/E146_Reseller'
import { E147_AnimalDriver } from './E/E147_AnimalDriver'
import { E148_Lazybones } from './E/E148_Lazybones'
import { E149_MidnightFencer } from './E/E149_MidnightFencer'
import { E15_NailBasket } from './E/E15_NailBasket'
import { E150_RockBeater } from './E/E150_RockBeater'
import { E151_DeliveryNurse } from './E/E151_DeliveryNurse'
import { E152_BargainHunter } from './E/E152_BargainHunter'
import { E153_StoneSculptor } from './E/E153_StoneSculptor'
import { E154_Margrave } from './E/E154_Margrave'
import { E155_Visionary } from './E/E155_Visionary'
import { E156_ClaypitOwner } from './E/E156_ClaypitOwner'
import { E157_Usufructuary } from './E/E157_Usufructuary'
import { E158_StoneCustodian } from './E/E158_StoneCustodian'
import { E159_OldMiser } from './E/E159_OldMiser'
import { E16_BriarHedge } from './E/E16_BriarHedge'
import { E160_KelpGatherer } from './E/E160_KelpGatherer'
import { E161_ElderBaker } from './E/E161_ElderBaker'
import { E162_Entrepreneur } from './E/E162_Entrepreneur'
import { E163_Patroness } from './E/E163_Patroness'
import { E164_MountainPlowman } from './E/E164_MountainPlowman'
import { E165_MasterHuntsman } from './E/E165_MasterHuntsman'
import { E166_Roastmaster } from './E/E166_Roastmaster'
import { E167_DairyCrier } from './E/E167_DairyCrier'
import { E168_AnimalTamersApprentice } from './E/E168_AnimalTamersApprentice'
import { E17_SkimmerPlow } from './E/E17_SkimmerPlow'
import { E18_SeedAlmanac } from './E/E18_SeedAlmanac'
import { E19_OxGoad } from './E/E19_OxGoad'
import { E2_RenovationMaterials } from './E/E2_RenovationMaterials'
import { E20_IronHoe } from './E/E20_IronHoe'
import { E21_SheepRug } from './E/E21_SheepRug'
import { E22_GuestRoom } from './E/E22_GuestRoom'
import { E23_Apiary } from './E/E23_Apiary'
import { E24_Ambition } from './E/E24_Ambition'
import { E25_BumperCrop } from './E/E25_BumperCrop'
import { E26_Sundial } from './E/E26_Sundial'
import { E27_PiggyBank } from './E/E27_PiggyBank'
import { E28_Bookmark } from './E/E28_Bookmark'
import { E29_Heirloom } from './E/E29_Heirloom'
import { E3_TeaTime } from './E/E3_TeaTime'
import { E30_ChildsToy } from './E/E30_ChildsToy'
import { E31_Upholstery } from './E/E31_Upholstery'
import { E32_Nave } from './E/E32_Nave'
import { E33_BeaverColony } from './E/E33_BeaverColony'
import { E34_LandRegister } from './E/E34_LandRegister'
import { E35_Misanthropy } from './E/E35_Misanthropy'
import { E36_HerbalGarden } from './E/E36_HerbalGarden'
import { E37_OxSkull } from './E/E37_OxSkull'
import { E38_RodCollection } from './E/E38_RodCollection'
import { E39_Paintbrush } from './E/E39_Paintbrush'
import { E4_Thunderbolt } from './E/E4_Thunderbolt'
import { E40_BeeStatue } from './E/E40_BeeStatue'
import { E41_MuddyWaters } from './E/E41_MuddyWaters'
import { E42_WaterGully } from './E/E42_WaterGully'
import { E43_BarnCats } from './E/E43_BarnCats'
import { E44_FodderBeets } from './E/E44_FodderBeets'
import { E45_FruitLadder } from './E/E45_FruitLadder'
import { E46_WaterlilyPond } from './E/E46_WaterlilyPond'
import { E47_SyrupTap } from './E/E47_SyrupTap'
import { E48_TownHall } from './E/E48_TownHall'
import { E49_Twibil } from './E/E49_Twibil'
import { E5_NightLoot } from './E/E5_NightLoot'
import { E50_WildGreens } from './E/E50_WildGreens'
import { E51_WhaleOil } from './E/E51_WhaleOil'
import { E52_Cubbyhole } from './E/E52_Cubbyhole'
import { E53_BoarSpear } from './E/E53_BoarSpear'
import { E54_Contraband } from './E/E54_Contraband'
import { E55_StoneWeir } from './E/E55_StoneWeir'
import { E56_RomanPot } from './E/E56_RomanPot'
import { E57_CheeseFondue } from './E/E57_CheeseFondue'
import { E58_LunchtimeBeer } from './E/E58_LunchtimeBeer'
import { E59_CombandCutter } from './E/E59_CombandCutter'
import { E6_Recount } from './E/E6_Recount'
import { E60_WorkingGloves } from './E/E60_WorkingGloves'
import { E61_RaisedBed } from './E/E61_RaisedBed'
import { E62_SourDough } from './E/E62_SourDough'
import { E63_IronOven } from './E/E63_IronOven'
import { E64_SimpleOven } from './E/E64_SimpleOven'
import { E65_Almsbag } from './E/E65_Almsbag'
import { E66_BarnShed } from './E/E66_BarnShed'
import { E67_GrainBag } from './E/E67_GrainBag'
import { E68_CherryOrchard } from './E/E68_CherryOrchard'
import { E69_MelonPatch } from './E/E69_MelonPatch'
import { E7_Pumpernickel } from './E/E7_Pumpernickel'
import { E70_CropRotationField } from './E/E70_CropRotationField'
import { E71_CowPatty } from './E/E71_CowPatty'
import { E72_ArtichokeField } from './E/E72_ArtichokeField'
import { E73_Scythe } from './E/E73_Scythe'
import { E74_AshTrees } from './E/E74_AshTrees'
import { E75_StoneAxe } from './E/E75_StoneAxe'
import { E76_LumberPile } from './E/E76_LumberPile'
import { E77_Mattock } from './E/E77_Mattock'
import { E78_SleightofHand } from './E/E78_SleightofHand'
import { E79_FieldSpade } from './E/E79_FieldSpade'
import { E8_FarmersMarket } from './E/E8_FarmersMarket'
import { E80_RockGarden } from './E/E80_RockGarden'
import { E81_AlchemistsLab } from './E/E81_AlchemistsLab'
import { E82_Profiteering } from './E/E82_Profiteering'
import { E83_ShepherdsWhistle } from './E/E83_ShepherdsWhistle'
import { E84_DollysMother } from './E/E84_DollysMother'
import { E85_MasterTanner } from './E/E85_MasterTanner'
import { E86_PenBuilder } from './E/E86_PenBuilder'
import { E87_MasterRenovator } from './E/E87_MasterRenovator'
import { E88_MasterFencer } from './E/E88_MasterFencer'
import { E89_Stallwright } from './E/E89_Stallwright'
import { E9_BarteringHut } from './E/E9_BarteringHut'
import { E90_DungCollector } from './E/E90_DungCollector'
import { E91_PlowBuilder } from './E/E91_PlowBuilder'
import { E92_FieldDoctor } from './E/E92_FieldDoctor'
import { E93_Motivator } from './E/E93_Motivator'
import { E94_Prophet } from './E/E94_Prophet'
import { E95_Miller } from './E/E95_Miller'
import { E96_Elder } from './E/E96_Elder'
import { E97_Beneficiary } from './E/E97_Beneficiary'
import { E98_Prodigy } from './E/E98_Prodigy'
import { E99_UncaringParents } from './E/E99_UncaringParents'
import { STUB_BeforeBakeGainClay } from './__stubs__/STUB_BeforeBakeGainClay'

export const catalogCardSources = [
  A1_Shelter,
  A10_WoodenShed,
  A100_Curator,
  A101_CookeryOutfitter,
  A102_Grocer,
  A103_Portmonger,
  A104_WoodHarvester,
  A105_BarrowPusher,
  A106_SlurrySpreader,
  A107_Catcher,
  A108_MushroomCollector,
  A109_SmallTrader,
  A11_MudPatch,
  A110_Roughcaster,
  A111_WallBuilder,
  A112_ScytheWorker,
  A113_HeresyTeacher,
  A114_SeasonalWorker,
  A115_ChiefForester,
  A116_WoodCutter,
  A117_WoodCarrier,
  A118_Treegardener,
  A119_FirewoodCollector,
  A12_DrinkingTrough,
  A120_ClayHutBuilder,
  A121_ClayPuncher,
  A122_PanBaker,
  A123_FrameBuilder,
  A124_Knapper,
  A125_Priest,
  A126_MasterWorkman,
  A127_Lodger,
  A128_RiparianBuilder,
  A129_Swagman,
  A13_RenovationCompany,
  A130_MummysBoy,
  A131_CraftTeacher,
  A132_Publican,
  A133_Braggart,
  A134_FullFarmer,
  A135_AnimalReeve,
  A136_DrudgeryReeve,
  A137_RiverineShepherd,
  A138_Harpooner,
  A139_HollowWarden,
  A14_CarpentersHammer,
  A140_ShovelBearer,
  A141_TurnipFarmer,
  A142_Cordmaker,
  A143_Stonecutter,
  A144_Sequestrator,
  A145_Ropemaker,
  A146_StorehouseSteward,
  A147_AnimalDealer,
  A148_Woolgrower,
  A149_HouseArtist,
  A15_CarpentersAxe,
  A150_Stagehand,
  A151_Minstrel,
  A152_NightSchoolStudent,
  A153_PigOwner,
  A154_Paymaster,
  A155_Conjurer,
  A156_Buyer,
  A157_Bohemian,
  A158_CulinaryArtist,
  A159_JoineroftheSea,
  A16_RammedClay,
  A160_Lutenist,
  A161_PatchCaretaker,
  A162_ForestTallyman,
  A163_BuildingExpert,
  A164_WoodWorker,
  A165_PigBreeder,
  A166_Haydryer,
  A167_BreederBuyer,
  A168_AnimalTeacher,
  A169_OffSiter,
  A17_ReclamationPlow,
  A170_Hayward,
  A171_Sidekick,
  A172_BoatPainter,
  A173_ClayThief,
  A174_MasterHora,
  A175_HollowGardener,
  A176_Wheelmaker,
  A177_Middleman,
  A178_CarpentersBoy,
  A179_MountainShepherd,
  A18_WheelPlow,
  A180_AnimalBrander,
  A19_Handplow,
  A2_ShiftingCultivation,
  A20_DoubleTurnPlow,
  A21_FamilyFriendHome,
  A22_Telegram,
  A23_StoneCompany,
  A24_ThreshingBoard,
  A25_Bassinet,
  A26_SleepingCorner,
  A27_OvenSite,
  A28_ForestSchool,
  A29_AleBenches,
  A3_PaperKnife,
  A30_BakingSheet,
  A31_DebtSecurity,
  A32_Manger,
  A33_BigCountry,
  A34_Loppers,
  A35_SwimmingClass,
  A36_FacadesCarving,
  A37_Bucksaw,
  A38_WoolBlankets,
  A39_Chapel,
  A4_Baseboards,
  A40_PottersYard,
  A41_VegetableSlicer,
  A42_ForestLakeHut,
  A43_FarmyardManure,
  A44_PondHut,
  A45_FireProtectionPond,
  A46_ClawKnife,
  A47_Trellises,
  A48_ShavingHorse,
  A49_NestSite,
  A5_ClayEmbankment,
  A50_MilkJug,
  A51_DriftNetBoat,
  A52_ThrowingAxe,
  A53_Claypipe,
  A54_Credit,
  A55_JunkRoom,
  A56_Basket,
  A57_MilkingParlor,
  A58_AsparagusKnife,
  A59_PotatoRidger,
  A6_StorageBarn,
  A60_OrientalFireplace,
  A61_WinnowingFan,
  A62_BeerKeg,
  A63_DutchWindmill,
  A64_BarleyMill,
  A65_SeedPellets,
  A66_FeedingDish,
  A67_CornScoop,
  A68_AsparagusGift,
  A69_LargeGreenhouse,
  A7_GardenersKnife,
  A70_LiftingMachine,
  A71_ClearingSpade,
  A72_CalciumFertilizers,
  A73_AgriculturalFertilizers,
  A74_StableTree,
  A75_LumberMill,
  A76_Cob,
  A77_Hod,
  A78_Canoe,
  A79_GardenHoe,
  A8_FoodBasket,
  A80_StoneTongs,
  A81_InterimStorage,
  A82_WorkCertificate,
  A83_ShepherdsCrook,
  A84_Silage,
  A85_Homekeeper,
  A86_AnimalTamer,
  A87_Conservator,
  A88_HedgeKeeper,
  A89_StablePlanner,
  A9_YoungAnimalMarket,
  A90_PlowDriver,
  A91_ShiftingCultivator,
  A92_AdoptiveParents,
  A93_BedMaker,
  A94_LazySowman,
  A95_Angler,
  A96_TaskArtisan,
  A97_Freshman,
  A98_StableArchitect,
  A99_FellowGrazer,
  B1_UpscaleLifestyle,
  B10_Caravan,
  B100_Clutterer,
  B101_FurnitureCarpenter,
  B102_Consultant,
  B103_FieldMerchant,
  B104_SheepWalker,
  B105_CaseBuilder,
  B106_MoralCrusader,
  B107_Manservant,
  B108_OvenFiringBoy,
  B109_PaperMaker,
  B11_Feedyard,
  B110_Pavior,
  B111_Rustic,
  B112_Silokeeper,
  B113_PatchCaregiver,
  B114_Childless,
  B115_TinsmithMaster,
  B116_Shoreforester,
  B117_Informant,
  B118_SmallscaleFarmer,
  B119_Lumberjack,
  B12_Stockyard,
  B120_Sweep,
  B121_Geologist,
  B122_Mineralogist,
  B123_RoofBallaster,
  B124_Trimmer,
  B125_EstateWorker,
  B126_Carpenter,
  B127_Seducer,
  B128_Plumber,
  B129_Seatmate,
  B13_CarpentersParlor,
  B130_FullPeasant,
  B131_Equipper,
  B132_EstateMaster,
  B133_VillagePeasant,
  B134_HousebookMaster,
  B135_NutritionExpert,
  B136_HouseSteward,
  B137_Wholesaler,
  B138_ForestGuardian,
  B139_ForestScientist,
  B14_Hawktower,
  B140_FarmyardWorker,
  B141_FieldCaretaker,
  B142_Greengrocer,
  B143_ClayWarden,
  B144_Collier,
  B145_BrushwoodCollector,
  B146_Illusionist,
  B147_Huntsman,
  B148_PetBroker,
  B149_OpenAirFarmer,
  B15_CarpentersBench,
  B150_LargeScaleFarmer,
  B151_LittlePeasant,
  B152_JuniorArtist,
  B153_Housemaster,
  B154_SheepKeeper,
  B155_ArtTeacher,
  B156_StorehouseKeeper,
  B157_Salter,
  B158_DistrictManager,
  B159_LieutenantGeneral,
  B16_MiningHammer,
  B160_PubOwner,
  B161_Weakling,
  B162_ForestClearer,
  B163_Pastor,
  B164_SheepWhisperer,
  B165_GameProvider,
  B166_CattleFeeder,
  B167_StableSergeant,
  B168_PastureMaster,
  B169_LivestockSustainer,
  B17_ForestPlow,
  B170_CorralBuilder,
  B171_GreenhouseBuilder,
  B172_CattleCaregiver,
  B173_Sweeper,
  B174_RiverbankGardener,
  B175_FieldOverseer,
  B176_VillageIdiot,
  B177_StoneClawer,
  B178_TagAlong,
  B179_WildBoarHunter,
  B18_GrasslandHarrow,
  B180_GameTeaser,
  B19_MoldboardPlow,
  B2_MiniPasture,
  B20_ChainFloat,
  B21_HayloftBarn,
  B22_WalkingBoots,
  B23_FinalScenario,
  B24_Lasso,
  B25_BreadPaddle,
  B26_AgrarianFences,
  B27_Toolbox,
  B28_ForestryStudies,
  B29_CookeryLesson,
  B3_Moonshine,
  B30_WoodPalisades,
  B31_PotteryYard,
  B32_Kettle,
  B33_Mantlepiece,
  B34_SpecialFood,
  B35_HookKnife,
  B36_Bottles,
  B37_Grange,
  B38_FutureBuildingSite,
  B39_Loom,
  B4_WoodPile,
  B40_BreweryPond,
  B41_Hauberg,
  B42_ForestInn,
  B43_Chophouse,
  B44_ChickStable,
  B45_StrawberryPatch,
  B46_ClubHouse,
  B47_HerringPot,
  B48_ForestStone,
  B49_Scales,
  B5_StoreofExperience,
  B50_ButterChurn,
  B51_DiggingSpade,
  B52_GrowingFarm,
  B53_SculptureCourse,
  B54_Tumbrel,
  B55_MaintenancePremium,
  B56_Brook,
  B57_Scullery,
  B58_CrackWeeder,
  B59_FoodChest,
  B6_ExcursiontotheQuarry,
  B60_BrewingWater,
  B61_ThreeFieldRotation,
  B62_Pitchfork,
  B63_Tasting,
  B64_MillWheel,
  B65_GrainDepot,
  B66_SackCart,
  B67_HandTruck,
  B68_Beanfield,
  B69_PottersMarket,
  B7_Wage,
  B70_NewPurchase,
  B71_HarvestHouse,
  B72_LoveforAgriculture,
  B73_GiftBasket,
  B74_ThickForest,
  B75_WoodWorkshop,
  B76_Ceilings,
  B77_LoamPit,
  B78_ReedBelt,
  B79_Corf,
  B8_MarketStall,
  B80_HardPorcelain,
  B81_Handcart,
  B82_ValueAssets,
  B83_MuddyPuddles,
  B84_AcornsBasket,
  B85_FarmHand,
  B86_TruffleSearcher,
  B87_Cottager,
  B88_EstablishedPerson,
  B89_Groom,
  B9_BeatingRod,
  B90_CooperativePlower,
  B91_AssistantTiller,
  B92_LittleStickKnitter,
  B93_Confidant,
  B94_StockProtector,
  B95_MasterBricklayer,
  B96_TreeFarmJoiner,
  B97_Scholar,
  B98_OrganicFarmer,
  B99_Tutor,
  C1_Overhaul,
  C10_BunkBeds,
  C100_Butler,
  C101_StallHolder,
  C102_TreeGuard,
  C103_GreenGrocer,
  C104_Collector,
  C105_BasketCarrier,
  C106_PotatoHarvester,
  C107_Baker,
  C108_Layabout,
  C109_SchnappsDistiller,
  C11_WildlifeReserve,
  C110_HomeBrewer,
  C111_SmallAnimalBreeder,
  C112_Thresher,
  C113_WinterCaretaker,
  C114_SoilScientist,
  C115_Sower,
  C116_FurnitureMaker,
  C117_Legworker,
  C118_WoodCollector,
  C119_SkillfulRenovator,
  C12_CattleFarm,
  C120_AgriculturalLabourer,
  C121_ClayKneader,
  C122_Bricklayer,
  C123_Freemason,
  C124_StoneImporter,
  C125_Nightworker,
  C126_Excavator,
  C127_Lover,
  C128_WoodenHutExtender,
  C129_SecondSpouse,
  C13_WoodSlideHammer,
  C130_OutskirtsDirector,
  C131_PrivateTeacher,
  C132_TimberShingleMaker,
  C133_Soldier,
  C134_CowPrince,
  C135_Constable,
  C136_RanchProvost,
  C137_CharcoalBurner,
  C138_AnimalFeeder,
  C139_BasketmakersWife,
  C14_StrawThatchedRoof,
  C140_PackagingArtist,
  C141_SheepProvider,
  C142_MarketCrier,
  C143_StoneBuyer,
  C144_ReedRoofRenovator,
  C145_ForestReviewer,
  C146_WorkshopAssistant,
  C147_Cowherd,
  C148_MudWallower,
  C149_ResourceRecycler,
  C15_Trellis,
  C150_ParrotBreeder,
  C151_SowingDirector,
  C152_Puppeteer,
  C153_PatternMaker,
  C154_TwinResearcher,
  C155_FoodDistributor,
  C156_HoofCaregiver,
  C157_ResourceAnalyzer,
  C158_ForestCampaigner,
  C159_FishermansFriend,
  C16_FieldFences,
  C160_Outrider,
  C161_PotatoDigger,
  C162_ForestOwner,
  C163_MaterialDeliveryman,
  C164_GermanHeathKeeper,
  C165_GameCatcher,
  C166_CattleWhisperer,
  C167_CattleBuyer,
  C168_AnimalCatcher,
  C169_FastMason,
  C17_NewlyPlowedField,
  C170_AmateurFencer,
  C171_YoungArtist,
  C172_FieldCounter,
  C173_TopOuter,
  C174_StoneCustodian,
  C175_VillageTeacher,
  C176_Cleanacre,
  C177_MountainHiker,
  C178_OnSiteReverend,
  C179_BovinePioneer,
  C18_RollOverPlow,
  C180_Trapper,
  C19_SwingPlow,
  C2_Stable,
  C20_MolePlow,
  C21_HeartofStone,
  C22_BasketChair,
  C23_JobContract,
  C24_BedintheGrainField,
  C25_SteamMachine,
  C26_Flail,
  C27_Blueprint,
  C28_TeachersDesk,
  C29_BeerTable,
  C3_CarriageTrip,
  C30_HalfTimberedHouse,
  C31_WritingChamber,
  C32_AbortOriel,
  C33_GreeningPlan,
  C34_ElephantgrassPlant,
  C35_LanternHouse,
  C36_ClayDeposit,
  C37_DwellingMound,
  C38_Christianity,
  C39_StudioBoat,
  C4_WritingBoards,
  C40_CanvasSack,
  C41_FarmStore,
  C42_RavenousHunger,
  C43_FarmBuilding,
  C44_ChickenCoop,
  C45_Stew,
  C46_Mandoline,
  C47_GardenClaw,
  C48_Farmstead,
  C49_BeerStall,
  C5_Remodeling,
  C50_StableYard,
  C51_FishingNet,
  C52_HuntsmansHat,
  C53_GypsysCrock,
  C54_MarketBooth,
  C55_Studio,
  C56_FeedFence,
  C57_Crudite,
  C58_Woodcraft,
  C59_SchnappsDistillery,
  C6_StoneClearing,
  C60_SmallPottersOven,
  C61_BeerStein,
  C62_CookeryExtension,
  C63_CraftBrewery,
  C64_CornSchnappsDistillery,
  C65_Granary,
  C66_EternalRyeCultivation,
  C67_MineralFeeder,
  C68_Bookcase,
  C69_LandConsolidation,
  C7_BladeShears,
  C70_LettucePatch,
  C71_Slurry,
  C72_FestivalPlanning,
  C73_SeaweedFertilizer,
  C74_PrivateForest,
  C75_Firewood,
  C76_WoodCart,
  C77_ClaySupply,
  C78_ReedHattedToad,
  C79_StoneCart,
  C8_PlantFertilizer,
  C80_RockyTerrain,
  C81_MaterialHub,
  C82_HardwareStore,
  C83_EarlyCattle,
  C84_PerennialRye,
  C85_DenBuilder,
  C86_LivestockFeeder,
  C87_Mason,
  C88_CarpentersApprentice,
  C89_StableMaster,
  C9_AutomaticWaterTrough,
  C90_FieldWatchman,
  C91_PlowHero,
  C92_AutumnMother,
  C93_InnerDistrictsDirector,
  C94_StableCleaner,
  C95_BasketWeaver,
  C96_Merchant,
  C97_SeedResearcher,
  C98_CubeCutter,
  C99_GardenDesigner,
  CUSTOM_FixtureHarvester,
  D1_ZigzagHarrow,
  D10_StorksNest,
  D100_LordoftheManor,
  D101_SugarBaker,
  D102_SampleStableMaker,
  D103_CanalBoatman,
  D104_Cultivator,
  D105_Sculptor,
  D106_WhiskyDistiller,
  D107_Bellfounder,
  D108_StoneCarver,
  D109_SowingMaster,
  D11_LawnFertilizer,
  D110_FishFarmer,
  D111_InteriorDecorator,
  D112_YoungFarmer,
  D113_FoodMerchant,
  D114_SeedTrader,
  D115_FodderPlanter,
  D116_TreeInspector,
  D117_WoodExpert,
  D118_Bonehead,
  D119_WoodBarterer,
  D12_MilkingPlace,
  D120_ClayDeliveryman,
  D121_ClayPlasterer,
  D122_ClayCarrier,
  D123_RenovationPreparer,
  D124_Emissary,
  D125_ForestTrader,
  D126_FieldCultivator,
  D127_HardworkingMan,
  D128_BuildingTycoon,
  D129_LumberVirtuoso,
  D13_Trowel,
  D130_RecreationalCarpenter,
  D131_CraftsmanshipPromoter,
  D132_HideFarmer,
  D133_BeerTentOperator,
  D134_OysterEater,
  D135_GardeningHeadOfficial,
  D136_AnimalActivist,
  D137_TradeTeacher,
  D138_PetLover,
  D139_Chairman,
  D14_HammerCrusher,
  D140_Loudmouth,
  D141_SeedSeller,
  D142_PotatoPlanter,
  D143_TreeCutter,
  D144_WaterWorker,
  D145_RoofExaminer,
  D146_Porter,
  D147_TrapBuilder,
  D148_DomesticianExpert,
  D149_CasualWorker,
  D15_ClaySupports,
  D150_GodlySpouse,
  D151_SpinDoctor,
  D152_Patron,
  D153_WealthyMan,
  D154_ChimneySweep,
  D155_Ebonist,
  D156_RetailDealer,
  D157_PartyOrganizer,
  D158_BeanCounter,
  D159_ReedSeller,
  D16_WoodenWheyBucket,
  D160_Midwife,
  D161_CabbageBuyer,
  D162_ClayFirer,
  D163_JourneymanBricklayer,
  D164_PetGrower,
  D165_PigStalker,
  D166_StableMilker,
  D167_PureBreeder,
  D168_Stockman,
  D169_Plowsmith,
  D17_DrillHarrow,
  D170_FoldBuilder,
  D171_SeniorTeacher,
  D172_PutcherMaker,
  D173_TownClerk,
  D174_LoessGardener,
  D175_Countryman,
  D176_Woodshacker,
  D177_Graduate,
  D178_SubstituteTeacher,
  D179_Bullcatcher,
  D18_SteamPlow,
  D180_PartTimeWorker,
  D19_PulverizerPlow,
  D2_DwellingPlan,
  D20_TurnwrestPlow,
  D21_Recruitment,
  D22_WorkPermit,
  D23_PioneeringSpirit,
  D24_BrotherlyLove,
  D25_WitchesDanceFloor,
  D26_CarpentersYard,
  D27_Retraining,
  D28_WritingDesk,
  D29_MuckRake,
  D3_Furrows,
  D30_ArtisanDistrict,
  D31_Storeroom,
  D32_WoodRake,
  D33_SummerHouse,
  D34_LuxuriousHostel,
  D35_FodderChamber,
  D36_BreedRegistry,
  D37_Sculpture,
  D38_MilkingStool,
  D39_TruffleSlicer,
  D4_CrossCutWood,
  D40_Cesspit,
  D41_HorseDrawnBoat,
  D42_EducationBonus,
  D43_Hutch,
  D44_ForestWell,
  D45_SheepWell,
  D46_PelletPress,
  D47_Churchyard,
  D48_CivicFacade,
  D49_Bookshelf,
  D5_FieldClay,
  D50_ForeignAid,
  D51_Archway,
  D52_RollingPin,
  D53_TeaHouse,
  D54_TroutPool,
  D55_NewMarket,
  D56_FatstockStretcher,
  D57_WholesaleMarket,
  D58_Gritter,
  D59_EarthOven,
  D6_PetrifiedWood,
  D60_LargePottery,
  D61_BaleofStraw,
  D62_BeerTap,
  D63_Lynchet,
  D64_BakingCourse,
  D65_GrainSieve,
  D66_PotterCeramics,
  D67_ReapHook,
  D68_SmallBasket,
  D69_SmallGreenhouse,
  D7_Trident,
  D70_StrawManure,
  D71_Changeover,
  D72_StableManure,
  D73_SupplyBoat,
  D74_RoyalWood,
  D75_WoodField,
  D76_SocialBenefits,
  D77_RecycledBrick,
  D78_ReedPond,
  D79_CarrotMuseum,
  D8_FernSeeds,
  D80_BrickHammer,
  D81_RoofLadder,
  D82_HuntingTrophy,
  D83_Pigswill,
  D84_FeedPellets,
  D85_Reader,
  D86_SheepAgent,
  D87_MasterBuilder,
  D88_Millwright,
  D89_Stablehand,
  D9_GameTrade,
  D90_PlowMaker,
  D91_Plowman,
  D92_ChildOmbudsman,
  D93_SheepInspector,
  D94_HenpeckedHusband,
  D95_SiteManager,
  D96_Furnisher,
  D97_BeggingStudent,
  D98_Transactor,
  D99_EarthenwarePotter,
  E1_PoleBarns,
  E10_StrawHat,
  E100_MuseumCaretaker,
  E101_Blighter,
  E102_Acquirer,
  E103_Wolf,
  E104_SpiceTrader,
  E105_Pioneer,
  E106_EmergencySeller,
  E107_LandSurveyor,
  E108_BlackberryFarmer,
  E109_BraidMaker,
  E11_PettingZoo,
  E110_Dentist,
  E111_Recluse,
  E112_GrainThief,
  E113_Godmother,
  E114_ShedBuilder,
  E115_SeedServant,
  E116_FirCutter,
  E117_PipeSmoker,
  E118_KindlingGatherer,
  E119_LandHeir,
  E12_AnimalBedding,
  E120_ScrapCollector,
  E121_HillCultivator,
  E122_Cottar,
  E123_ResourceHoarder,
  E124_MayorCandidate,
  E125_DelayedWayfarer,
  E126_TaxCollector,
  E127_DiligentFarmer,
  E128_Saddler,
  E129_Imitator,
  E13_StoneHouseReconstruction,
  E130_Overachiever,
  E131_MarketMaster,
  E132_VeggieLover,
  E133_ChampionBreeder,
  E134_Omnifarmer,
  E135_Pickler,
  E136_AnimalHusbandryWorker,
  E137_FlaxFarmer,
  E138_LivestockExpert,
  E139_BunnyBreeder,
  E14_WoodSaw,
  E140_Carter,
  E141_VegetableVendor,
  E142_Smuggler,
  E143_Hewer,
  E144_WaresSalesman,
  E145_Parvenu,
  E146_Reseller,
  E147_AnimalDriver,
  E148_Lazybones,
  E149_MidnightFencer,
  E15_NailBasket,
  E150_RockBeater,
  E151_DeliveryNurse,
  E152_BargainHunter,
  E153_StoneSculptor,
  E154_Margrave,
  E155_Visionary,
  E156_ClaypitOwner,
  E157_Usufructuary,
  E158_StoneCustodian,
  E159_OldMiser,
  E16_BriarHedge,
  E160_KelpGatherer,
  E161_ElderBaker,
  E162_Entrepreneur,
  E163_Patroness,
  E164_MountainPlowman,
  E165_MasterHuntsman,
  E166_Roastmaster,
  E167_DairyCrier,
  E168_AnimalTamersApprentice,
  E17_SkimmerPlow,
  E18_SeedAlmanac,
  E19_OxGoad,
  E2_RenovationMaterials,
  E20_IronHoe,
  E21_SheepRug,
  E22_GuestRoom,
  E23_Apiary,
  E24_Ambition,
  E25_BumperCrop,
  E26_Sundial,
  E27_PiggyBank,
  E28_Bookmark,
  E29_Heirloom,
  E3_TeaTime,
  E30_ChildsToy,
  E31_Upholstery,
  E32_Nave,
  E33_BeaverColony,
  E34_LandRegister,
  E35_Misanthropy,
  E36_HerbalGarden,
  E37_OxSkull,
  E38_RodCollection,
  E39_Paintbrush,
  E4_Thunderbolt,
  E40_BeeStatue,
  E41_MuddyWaters,
  E42_WaterGully,
  E43_BarnCats,
  E44_FodderBeets,
  E45_FruitLadder,
  E46_WaterlilyPond,
  E47_SyrupTap,
  E48_TownHall,
  E49_Twibil,
  E5_NightLoot,
  E50_WildGreens,
  E51_WhaleOil,
  E52_Cubbyhole,
  E53_BoarSpear,
  E54_Contraband,
  E55_StoneWeir,
  E56_RomanPot,
  E57_CheeseFondue,
  E58_LunchtimeBeer,
  E59_CombandCutter,
  E6_Recount,
  E60_WorkingGloves,
  E61_RaisedBed,
  E62_SourDough,
  E63_IronOven,
  E64_SimpleOven,
  E65_Almsbag,
  E66_BarnShed,
  E67_GrainBag,
  E68_CherryOrchard,
  E69_MelonPatch,
  E7_Pumpernickel,
  E70_CropRotationField,
  E71_CowPatty,
  E72_ArtichokeField,
  E73_Scythe,
  E74_AshTrees,
  E75_StoneAxe,
  E76_LumberPile,
  E77_Mattock,
  E78_SleightofHand,
  E79_FieldSpade,
  E8_FarmersMarket,
  E80_RockGarden,
  E81_AlchemistsLab,
  E82_Profiteering,
  E83_ShepherdsWhistle,
  E84_DollysMother,
  E85_MasterTanner,
  E86_PenBuilder,
  E87_MasterRenovator,
  E88_MasterFencer,
  E89_Stallwright,
  E9_BarteringHut,
  E90_DungCollector,
  E91_PlowBuilder,
  E92_FieldDoctor,
  E93_Motivator,
  E94_Prophet,
  E95_Miller,
  E96_Elder,
  E97_Beneficiary,
  E98_Prodigy,
  E99_UncaringParents,
  STUB_BeforeBakeGainClay,
] as const satisfies readonly CardSource[]

const isMinorLike = (source: CardSource) =>
  source.meta.kind === 'minor' || source.meta.kind === 'playerAction'

const isOccupation = (source: CardSource) =>
  source.meta.kind === 'occupation'

const isImplemented = (card: CardSourceMeta) => card.implemented !== false

export const minorImprovementCardsList = catalogCardSources
  .filter(isMinorLike)
  .map((source) => source.meta)

export const occupationCardsList = catalogCardSources
  .filter(isOccupation)
  .map((source) => source.meta)

export const implementedMinorImprovementCardsList =
  minorImprovementCardsList.filter(isImplemented)

export const implementedOccupationCardsList =
  occupationCardsList.filter(isImplemented)

export const minorImprovementIdsList =
  implementedMinorImprovementCardsList.map((card) => card.id)

export const occupationIdsList =
  implementedOccupationCardsList.map((card) => card.id)
