// GENERATED by scripts/generate-register-all.ts. Do not edit by hand.
import type { CardImpl } from './registry'
import './catalog'

import { A1_Shelter } from './A/A1_Shelter'
import { A10_WoodenShed } from './A/A10_WoodenShed'
import { A100_Curator } from './A/A100_Curator'
import { A101_CookeryOutfitter } from './A/A101_CookeryOutfitter'
import { A102_Grocer } from './A/A102_Grocer'
import { A103_Portmonger } from './A/A103_Portmonger'
import { A104_WoodHarvester } from './A/A104_WoodHarvester'
import { A105_BarrowPusher } from './A/A105_BarrowPusher'
import { A106_SlurrySpreader } from './A/A106_SlurrySpreader'
import { A107_Catcher } from './A/A107_Catcher'
import { A108_MushroomCollector } from './A/A108_MushroomCollector'
import { A109_SmallTrader } from './A/A109_SmallTrader'
import { A11_MudPatch } from './A/A11_MudPatch'
import { A110_Roughcaster } from './A/A110_Roughcaster'
import { A111_WallBuilder } from './A/A111_WallBuilder'
import { A112_ScytheWorker } from './A/A112_ScytheWorker'
import { A113_HeresyTeacher } from './A/A113_HeresyTeacher'
import { A114_SeasonalWorker } from './A/A114_SeasonalWorker'
import { A115_ChiefForester } from './A/A115_ChiefForester'
import { A116_WoodCutter } from './A/A116_WoodCutter'
import { A117_WoodCarrier } from './A/A117_WoodCarrier'
import { A118_Treegardener } from './A/A118_Treegardener'
import { A119_FirewoodCollector } from './A/A119_FirewoodCollector'
import { A12_DrinkingTrough } from './A/A12_DrinkingTrough'
import { A120_ClayHutBuilder } from './A/A120_ClayHutBuilder'
import { A121_ClayPuncher } from './A/A121_ClayPuncher'
import { A122_PanBaker } from './A/A122_PanBaker'
import { A123_FrameBuilder } from './A/A123_FrameBuilder'
import { A124_Knapper } from './A/A124_Knapper'
import { A125_Priest } from './A/A125_Priest'
import { A126_MasterWorkman } from './A/A126_MasterWorkman'
import { A127_Lodger } from './A/A127_Lodger'
import { A128_RiparianBuilder } from './A/A128_RiparianBuilder'
import { A129_Swagman } from './A/A129_Swagman'
import { A13_RenovationCompany } from './A/A13_RenovationCompany'
import { A130_MummysBoy } from './A/A130_MummysBoy'
import { A131_CraftTeacher } from './A/A131_CraftTeacher'
import { A132_Publican } from './A/A132_Publican'
import { A133_Braggart } from './A/A133_Braggart'
import { A134_FullFarmer } from './A/A134_FullFarmer'
import { A135_AnimalReeve } from './A/A135_AnimalReeve'
import { A136_DrudgeryReeve } from './A/A136_DrudgeryReeve'
import { A137_RiverineShepherd } from './A/A137_RiverineShepherd'
import { A138_Harpooner } from './A/A138_Harpooner'
import { A139_HollowWarden } from './A/A139_HollowWarden'
import { A14_CarpentersHammer } from './A/A14_CarpentersHammer'
import { A140_ShovelBearer } from './A/A140_ShovelBearer'
import { A141_TurnipFarmer } from './A/A141_TurnipFarmer'
import { A142_Cordmaker } from './A/A142_Cordmaker'
import { A143_Stonecutter } from './A/A143_Stonecutter'
import { A144_Sequestrator } from './A/A144_Sequestrator'
import { A145_Ropemaker } from './A/A145_Ropemaker'
import { A146_StorehouseSteward } from './A/A146_StorehouseSteward'
import { A147_AnimalDealer } from './A/A147_AnimalDealer'
import { A148_Woolgrower } from './A/A148_Woolgrower'
import { A149_HouseArtist } from './A/A149_HouseArtist'
import { A15_CarpentersAxe } from './A/A15_CarpentersAxe'
import { A150_Stagehand } from './A/A150_Stagehand'
import { A151_Minstrel } from './A/A151_Minstrel'
import { A152_NightSchoolStudent } from './A/A152_NightSchoolStudent'
import { A153_PigOwner } from './A/A153_PigOwner'
import { A154_Paymaster } from './A/A154_Paymaster'
import { A155_Conjurer } from './A/A155_Conjurer'
import { A156_Buyer } from './A/A156_Buyer'
import { A157_Bohemian } from './A/A157_Bohemian'
import { A158_CulinaryArtist } from './A/A158_CulinaryArtist'
import { A159_JoineroftheSea } from './A/A159_JoineroftheSea'
import { A16_RammedClay } from './A/A16_RammedClay'
import { A160_Lutenist } from './A/A160_Lutenist'
import { A161_PatchCaretaker } from './A/A161_PatchCaretaker'
import { A162_ForestTallyman } from './A/A162_ForestTallyman'
import { A163_BuildingExpert } from './A/A163_BuildingExpert'
import { A164_WoodWorker } from './A/A164_WoodWorker'
import { A165_PigBreeder } from './A/A165_PigBreeder'
import { A166_Haydryer } from './A/A166_Haydryer'
import { A167_BreederBuyer } from './A/A167_BreederBuyer'
import { A168_AnimalTeacher } from './A/A168_AnimalTeacher'
import { A17_ReclamationPlow } from './A/A17_ReclamationPlow'
import { A176_Wheelmaker } from './A/A176_Wheelmaker'
import { A18_WheelPlow } from './A/A18_WheelPlow'
import { A19_Handplow } from './A/A19_Handplow'
import { A2_ShiftingCultivation } from './A/A2_ShiftingCultivation'
import { A20_DoubleTurnPlow } from './A/A20_DoubleTurnPlow'
import { A21_FamilyFriendHome } from './A/A21_FamilyFriendHome'
import { A22_Telegram } from './A/A22_Telegram'
import { A23_StoneCompany } from './A/A23_StoneCompany'
import { A24_ThreshingBoard } from './A/A24_ThreshingBoard'
import { A25_Bassinet } from './A/A25_Bassinet'
import { A26_SleepingCorner } from './A/A26_SleepingCorner'
import { A27_OvenSite } from './A/A27_OvenSite'
import { A28_ForestSchool } from './A/A28_ForestSchool'
import { A29_AleBenches } from './A/A29_AleBenches'
import { A3_PaperKnife } from './A/A3_PaperKnife'
import { A30_BakingSheet } from './A/A30_BakingSheet'
import { A31_DebtSecurity } from './A/A31_DebtSecurity'
import { A32_Manger } from './A/A32_Manger'
import { A33_BigCountry } from './A/A33_BigCountry'
import { A34_Loppers } from './A/A34_Loppers'
import { A35_SwimmingClass } from './A/A35_SwimmingClass'
import { A36_FacadesCarving } from './A/A36_FacadesCarving'
import { A37_Bucksaw } from './A/A37_Bucksaw'
import { A38_WoolBlankets } from './A/A38_WoolBlankets'
import { A39_Chapel } from './A/A39_Chapel'
import { A4_Baseboards } from './A/A4_Baseboards'
import { A40_PottersYard } from './A/A40_PottersYard'
import { A41_VegetableSlicer } from './A/A41_VegetableSlicer'
import { A42_ForestLakeHut } from './A/A42_ForestLakeHut'
import { A43_FarmyardManure } from './A/A43_FarmyardManure'
import { A44_PondHut } from './A/A44_PondHut'
import { A45_FireProtectionPond } from './A/A45_FireProtectionPond'
import { A46_ClawKnife } from './A/A46_ClawKnife'
import { A47_Trellises } from './A/A47_Trellises'
import { A48_ShavingHorse } from './A/A48_ShavingHorse'
import { A49_NestSite } from './A/A49_NestSite'
import { A5_ClayEmbankment } from './A/A5_ClayEmbankment'
import { A50_MilkJug } from './A/A50_MilkJug'
import { A51_DriftNetBoat } from './A/A51_DriftNetBoat'
import { A52_ThrowingAxe } from './A/A52_ThrowingAxe'
import { A53_Claypipe } from './A/A53_Claypipe'
import { A54_Credit } from './A/A54_Credit'
import { A55_JunkRoom } from './A/A55_JunkRoom'
import { A56_Basket } from './A/A56_Basket'
import { A57_MilkingParlor } from './A/A57_MilkingParlor'
import { A58_AsparagusKnife } from './A/A58_AsparagusKnife'
import { A59_PotatoRidger } from './A/A59_PotatoRidger'
import { A6_StorageBarn } from './A/A6_StorageBarn'
import { A61_WinnowingFan } from './A/A61_WinnowingFan'
import { A62_BeerKeg } from './A/A62_BeerKeg'
import { A63_DutchWindmill } from './A/A63_DutchWindmill'
import { A64_BarleyMill } from './A/A64_BarleyMill'
import { A65_SeedPellets } from './A/A65_SeedPellets'
import { A66_FeedingDish } from './A/A66_FeedingDish'
import { A67_CornScoop } from './A/A67_CornScoop'
import { A68_AsparagusGift } from './A/A68_AsparagusGift'
import { A69_LargeGreenhouse } from './A/A69_LargeGreenhouse'
import { A7_GardenersKnife } from './A/A7_GardenersKnife'
import { A70_LiftingMachine } from './A/A70_LiftingMachine'
import { A71_ClearingSpade } from './A/A71_ClearingSpade'
import { A72_CalciumFertilizers } from './A/A72_CalciumFertilizers'
import { A73_AgriculturalFertilizers } from './A/A73_AgriculturalFertilizers'
import { A74_StableTree } from './A/A74_StableTree'
import { A75_LumberMill } from './A/A75_LumberMill'
import { A76_Cob } from './A/A76_Cob'
import { A77_Hod } from './A/A77_Hod'
import { A78_Canoe } from './A/A78_Canoe'
import { A79_GardenHoe } from './A/A79_GardenHoe'
import { A8_FoodBasket } from './A/A8_FoodBasket'
import { A80_StoneTongs } from './A/A80_StoneTongs'
import { A81_InterimStorage } from './A/A81_InterimStorage'
import { A82_WorkCertificate } from './A/A82_WorkCertificate'
import { A83_ShepherdsCrook } from './A/A83_ShepherdsCrook'
import { A84_Silage } from './A/A84_Silage'
import { A85_Homekeeper } from './A/A85_Homekeeper'
import { A86_AnimalTamer } from './A/A86_AnimalTamer'
import { A87_Conservator } from './A/A87_Conservator'
import { A88_HedgeKeeper } from './A/A88_HedgeKeeper'
import { A89_StablePlanner } from './A/A89_StablePlanner'
import { A9_YoungAnimalMarket } from './A/A9_YoungAnimalMarket'
import { A90_PlowDriver } from './A/A90_PlowDriver'
import { A91_ShiftingCultivator } from './A/A91_ShiftingCultivator'
import { A92_AdoptiveParents } from './A/A92_AdoptiveParents'
import { A93_BedMaker } from './A/A93_BedMaker'
import { A94_LazySowman } from './A/A94_LazySowman'
import { A95_Angler } from './A/A95_Angler'
import { A96_TaskArtisan } from './A/A96_TaskArtisan'
import { A97_Freshman } from './A/A97_Freshman'
import { A98_StableArchitect } from './A/A98_StableArchitect'
import { A99_FellowGrazer } from './A/A99_FellowGrazer'
import { B1_UpscaleLifestyle } from './B/B1_UpscaleLifestyle'
import { B10_Caravan } from './B/B10_Caravan'
import { B100_Clutterer } from './B/B100_Clutterer'
import { B101_FurnitureCarpenter } from './B/B101_FurnitureCarpenter'
import { B102_Consultant } from './B/B102_Consultant'
import { B103_FieldMerchant } from './B/B103_FieldMerchant'
import { B104_SheepWalker } from './B/B104_SheepWalker'
import { B105_CaseBuilder } from './B/B105_CaseBuilder'
import { B106_MoralCrusader } from './B/B106_MoralCrusader'
import { B107_Manservant } from './B/B107_Manservant'
import { B108_OvenFiringBoy } from './B/B108_OvenFiringBoy'
import { B109_PaperMaker } from './B/B109_PaperMaker'
import { B11_Feedyard } from './B/B11_Feedyard'
import { B110_Pavior } from './B/B110_Pavior'
import { B111_Rustic } from './B/B111_Rustic'
import { B112_Silokeeper } from './B/B112_Silokeeper'
import { B113_PatchCaregiver } from './B/B113_PatchCaregiver'
import { B114_Childless } from './B/B114_Childless'
import { B115_TinsmithMaster } from './B/B115_TinsmithMaster'
import { B116_Shoreforester } from './B/B116_Shoreforester'
import { B117_Informant } from './B/B117_Informant'
import { B118_SmallscaleFarmer } from './B/B118_SmallscaleFarmer'
import { B119_Lumberjack } from './B/B119_Lumberjack'
import { B12_Stockyard } from './B/B12_Stockyard'
import { B120_Sweep } from './B/B120_Sweep'
import { B121_Geologist } from './B/B121_Geologist'
import { B122_Mineralogist } from './B/B122_Mineralogist'
import { B123_RoofBallaster } from './B/B123_RoofBallaster'
import { B124_Trimmer } from './B/B124_Trimmer'
import { B125_EstateWorker } from './B/B125_EstateWorker'
import { B126_Carpenter } from './B/B126_Carpenter'
import { B127_Seducer } from './B/B127_Seducer'
import { B128_Plumber } from './B/B128_Plumber'
import { B129_Seatmate } from './B/B129_Seatmate'
import { B13_CarpentersParlor } from './B/B13_CarpentersParlor'
import { B130_FullPeasant } from './B/B130_FullPeasant'
import { B131_Equipper } from './B/B131_Equipper'
import { B132_EstateMaster } from './B/B132_EstateMaster'
import { B133_VillagePeasant } from './B/B133_VillagePeasant'
import { B134_HousebookMaster } from './B/B134_HousebookMaster'
import { B135_NutritionExpert } from './B/B135_NutritionExpert'
import { B136_HouseSteward } from './B/B136_HouseSteward'
import { B137_Wholesaler } from './B/B137_Wholesaler'
import { B138_ForestGuardian } from './B/B138_ForestGuardian'
import { B139_ForestScientist } from './B/B139_ForestScientist'
import { B14_Hawktower } from './B/B14_Hawktower'
import { B140_FarmyardWorker } from './B/B140_FarmyardWorker'
import { B141_FieldCaretaker } from './B/B141_FieldCaretaker'
import { B142_Greengrocer } from './B/B142_Greengrocer'
import { B143_ClayWarden } from './B/B143_ClayWarden'
import { B144_Collier } from './B/B144_Collier'
import { B145_BrushwoodCollector } from './B/B145_BrushwoodCollector'
import { B146_Illusionist } from './B/B146_Illusionist'
import { B147_Huntsman } from './B/B147_Huntsman'
import { B148_PetBroker } from './B/B148_PetBroker'
import { B149_OpenAirFarmer } from './B/B149_OpenAirFarmer'
import { B15_CarpentersBench } from './B/B15_CarpentersBench'
import { B150_LargeScaleFarmer } from './B/B150_LargeScaleFarmer'
import { B151_LittlePeasant } from './B/B151_LittlePeasant'
import { B152_JuniorArtist } from './B/B152_JuniorArtist'
import { B153_Housemaster } from './B/B153_Housemaster'
import { B154_SheepKeeper } from './B/B154_SheepKeeper'
import { B155_ArtTeacher } from './B/B155_ArtTeacher'
import { B156_StorehouseKeeper } from './B/B156_StorehouseKeeper'
import { B157_Salter } from './B/B157_Salter'
import { B158_DistrictManager } from './B/B158_DistrictManager'
import { B159_LieutenantGeneral } from './B/B159_LieutenantGeneral'
import { B16_MiningHammer } from './B/B16_MiningHammer'
import { B160_PubOwner } from './B/B160_PubOwner'
import { B161_Weakling } from './B/B161_Weakling'
import { B162_ForestClearer } from './B/B162_ForestClearer'
import { B163_Pastor } from './B/B163_Pastor'
import { B164_SheepWhisperer } from './B/B164_SheepWhisperer'
import { B165_GameProvider } from './B/B165_GameProvider'
import { B166_CattleFeeder } from './B/B166_CattleFeeder'
import { B167_StableSergeant } from './B/B167_StableSergeant'
import { B168_PastureMaster } from './B/B168_PastureMaster'
import { B17_ForestPlow } from './B/B17_ForestPlow'
import { B18_GrasslandHarrow } from './B/B18_GrasslandHarrow'
import { B19_MoldboardPlow } from './B/B19_MoldboardPlow'
import { B2_MiniPasture } from './B/B2_MiniPasture'
import { B20_ChainFloat } from './B/B20_ChainFloat'
import { B21_HayloftBarn } from './B/B21_HayloftBarn'
import { B22_WalkingBoots } from './B/B22_WalkingBoots'
import { B23_FinalScenario } from './B/B23_FinalScenario'
import { B24_Lasso } from './B/B24_Lasso'
import { B25_BreadPaddle } from './B/B25_BreadPaddle'
import { B26_AgrarianFences } from './B/B26_AgrarianFences'
import { B27_Toolbox } from './B/B27_Toolbox'
import { B28_ForestryStudies } from './B/B28_ForestryStudies'
import { B29_CookeryLesson } from './B/B29_CookeryLesson'
import { B3_Moonshine } from './B/B3_Moonshine'
import { B30_WoodPalisades } from './B/B30_WoodPalisades'
import { B31_PotteryYard } from './B/B31_PotteryYard'
import { B32_Kettle } from './B/B32_Kettle'
import { B33_Mantlepiece } from './B/B33_Mantlepiece'
import { B34_SpecialFood } from './B/B34_SpecialFood'
import { B35_HookKnife } from './B/B35_HookKnife'
import { B36_Bottles } from './B/B36_Bottles'
import { B37_Grange } from './B/B37_Grange'
import { B38_FutureBuildingSite } from './B/B38_FutureBuildingSite'
import { B39_Loom } from './B/B39_Loom'
import { B4_WoodPile } from './B/B4_WoodPile'
import { B40_BreweryPond } from './B/B40_BreweryPond'
import { B41_Hauberg } from './B/B41_Hauberg'
import { B42_ForestInn } from './B/B42_ForestInn'
import { B43_Chophouse } from './B/B43_Chophouse'
import { B44_ChickStable } from './B/B44_ChickStable'
import { B45_StrawberryPatch } from './B/B45_StrawberryPatch'
import { B46_ClubHouse } from './B/B46_ClubHouse'
import { B47_HerringPot } from './B/B47_HerringPot'
import { B48_ForestStone } from './B/B48_ForestStone'
import { B49_Scales } from './B/B49_Scales'
import { B5_StoreofExperience } from './B/B5_StoreofExperience'
import { B50_ButterChurn } from './B/B50_ButterChurn'
import { B51_DiggingSpade } from './B/B51_DiggingSpade'
import { B52_GrowingFarm } from './B/B52_GrowingFarm'
import { B53_SculptureCourse } from './B/B53_SculptureCourse'
import { B54_Tumbrel } from './B/B54_Tumbrel'
import { B55_MaintenancePremium } from './B/B55_MaintenancePremium'
import { B56_Brook } from './B/B56_Brook'
import { B57_Scullery } from './B/B57_Scullery'
import { B58_CrackWeeder } from './B/B58_CrackWeeder'
import { B59_FoodChest } from './B/B59_FoodChest'
import { B6_ExcursiontotheQuarry } from './B/B6_ExcursiontotheQuarry'
import { B60_BrewingWater } from './B/B60_BrewingWater'
import { B61_ThreeFieldRotation } from './B/B61_ThreeFieldRotation'
import { B62_Pitchfork } from './B/B62_Pitchfork'
import { B63_Tasting } from './B/B63_Tasting'
import { B64_MillWheel } from './B/B64_MillWheel'
import { B65_GrainDepot } from './B/B65_GrainDepot'
import { B66_SackCart } from './B/B66_SackCart'
import { B67_HandTruck } from './B/B67_HandTruck'
import { B68_Beanfield } from './B/B68_Beanfield'
import { B69_PottersMarket } from './B/B69_PottersMarket'
import { B7_Wage } from './B/B7_Wage'
import { B70_NewPurchase } from './B/B70_NewPurchase'
import { B71_HarvestHouse } from './B/B71_HarvestHouse'
import { B72_LoveforAgriculture } from './B/B72_LoveforAgriculture'
import { B73_GiftBasket } from './B/B73_GiftBasket'
import { B74_ThickForest } from './B/B74_ThickForest'
import { B75_WoodWorkshop } from './B/B75_WoodWorkshop'
import { B76_Ceilings } from './B/B76_Ceilings'
import { B77_LoamPit } from './B/B77_LoamPit'
import { B78_ReedBelt } from './B/B78_ReedBelt'
import { B79_Corf } from './B/B79_Corf'
import { B8_MarketStall } from './B/B8_MarketStall'
import { B81_Handcart } from './B/B81_Handcart'
import { B82_ValueAssets } from './B/B82_ValueAssets'
import { B83_MuddyPuddles } from './B/B83_MuddyPuddles'
import { B84_AcornsBasket } from './B/B84_AcornsBasket'
import { B85_FarmHand } from './B/B85_FarmHand'
import { B86_TruffleSearcher } from './B/B86_TruffleSearcher'
import { B87_Cottager } from './B/B87_Cottager'
import { B88_EstablishedPerson } from './B/B88_EstablishedPerson'
import { B89_Groom } from './B/B89_Groom'
import { B9_BeatingRod } from './B/B9_BeatingRod'
import { B90_CooperativePlower } from './B/B90_CooperativePlower'
import { B91_AssistantTiller } from './B/B91_AssistantTiller'
import { B92_LittleStickKnitter } from './B/B92_LittleStickKnitter'
import { B93_Confidant } from './B/B93_Confidant'
import { B94_StockProtector } from './B/B94_StockProtector'
import { B95_MasterBricklayer } from './B/B95_MasterBricklayer'
import { B96_TreeFarmJoiner } from './B/B96_TreeFarmJoiner'
import { B97_Scholar } from './B/B97_Scholar'
import { B98_OrganicFarmer } from './B/B98_OrganicFarmer'
import { B99_Tutor } from './B/B99_Tutor'
import { C1_Overhaul } from './C/C1_Overhaul'
import { C10_BunkBeds } from './C/C10_BunkBeds'
import { C100_Butler } from './C/C100_Butler'
import { C101_StallHolder } from './C/C101_StallHolder'
import { C102_TreeGuard } from './C/C102_TreeGuard'
import { C103_GreenGrocer } from './C/C103_GreenGrocer'
import { C104_Collector } from './C/C104_Collector'
import { C106_PotatoHarvester } from './C/C106_PotatoHarvester'
import { C107_Baker } from './C/C107_Baker'
import { C108_Layabout } from './C/C108_Layabout'
import { C11_WildlifeReserve } from './C/C11_WildlifeReserve'
import { C110_HomeBrewer } from './C/C110_HomeBrewer'
import { C111_SmallAnimalBreeder } from './C/C111_SmallAnimalBreeder'
import { C112_Thresher } from './C/C112_Thresher'
import { C113_WinterCaretaker } from './C/C113_WinterCaretaker'
import { C114_SoilScientist } from './C/C114_SoilScientist'
import { C115_Sower } from './C/C115_Sower'
import { C116_FurnitureMaker } from './C/C116_FurnitureMaker'
import { C117_Legworker } from './C/C117_Legworker'
import { C118_WoodCollector } from './C/C118_WoodCollector'
import { C119_SkillfulRenovator } from './C/C119_SkillfulRenovator'
import { C12_CattleFarm } from './C/C12_CattleFarm'
import { C120_AgriculturalLabourer } from './C/C120_AgriculturalLabourer'
import { C121_ClayKneader } from './C/C121_ClayKneader'
import { C122_Bricklayer } from './C/C122_Bricklayer'
import { C123_Freemason } from './C/C123_Freemason'
import { C124_StoneImporter } from './C/C124_StoneImporter'
import { C125_Nightworker } from './C/C125_Nightworker'
import { C126_Excavator } from './C/C126_Excavator'
import { C127_Lover } from './C/C127_Lover'
import { C128_WoodenHutExtender } from './C/C128_WoodenHutExtender'
import { C129_SecondSpouse } from './C/C129_SecondSpouse'
import { C13_WoodSlideHammer } from './C/C13_WoodSlideHammer'
import { C130_OutskirtsDirector } from './C/C130_OutskirtsDirector'
import { C131_PrivateTeacher } from './C/C131_PrivateTeacher'
import { C132_TimberShingleMaker } from './C/C132_TimberShingleMaker'
import { C133_Soldier } from './C/C133_Soldier'
import { C134_CowPrince } from './C/C134_CowPrince'
import { C135_Constable } from './C/C135_Constable'
import { C136_RanchProvost } from './C/C136_RanchProvost'
import { C137_CharcoalBurner } from './C/C137_CharcoalBurner'
import { C138_AnimalFeeder } from './C/C138_AnimalFeeder'
import { C139_BasketmakersWife } from './C/C139_BasketmakersWife'
import { C14_StrawThatchedRoof } from './C/C14_StrawThatchedRoof'
import { C140_PackagingArtist } from './C/C140_PackagingArtist'
import { C141_SheepProvider } from './C/C141_SheepProvider'
import { C142_MarketCrier } from './C/C142_MarketCrier'
import { C143_StoneBuyer } from './C/C143_StoneBuyer'
import { C144_ReedRoofRenovator } from './C/C144_ReedRoofRenovator'
import { C145_ForestReviewer } from './C/C145_ForestReviewer'
import { C146_WorkshopAssistant } from './C/C146_WorkshopAssistant'
import { C147_Cowherd } from './C/C147_Cowherd'
import { C148_MudWallower } from './C/C148_MudWallower'
import { C149_ResourceRecycler } from './C/C149_ResourceRecycler'
import { C15_Trellis } from './C/C15_Trellis'
import { C150_ParrotBreeder } from './C/C150_ParrotBreeder'
import { C151_SowingDirector } from './C/C151_SowingDirector'
import { C152_Puppeteer } from './C/C152_Puppeteer'
import { C153_PatternMaker } from './C/C153_PatternMaker'
import { C154_TwinResearcher } from './C/C154_TwinResearcher'
import { C155_FoodDistributor } from './C/C155_FoodDistributor'
import { C156_HoofCaregiver } from './C/C156_HoofCaregiver'
import { C157_ResourceAnalyzer } from './C/C157_ResourceAnalyzer'
import { C158_ForestCampaigner } from './C/C158_ForestCampaigner'
import { C159_FishermansFriend } from './C/C159_FishermansFriend'
import { C16_FieldFences } from './C/C16_FieldFences'
import { C160_Outrider } from './C/C160_Outrider'
import { C161_PotatoDigger } from './C/C161_PotatoDigger'
import { C162_ForestOwner } from './C/C162_ForestOwner'
import { C163_MaterialDeliveryman } from './C/C163_MaterialDeliveryman'
import { C164_GermanHeathKeeper } from './C/C164_GermanHeathKeeper'
import { C165_GameCatcher } from './C/C165_GameCatcher'
import { C166_CattleWhisperer } from './C/C166_CattleWhisperer'
import { C167_CattleBuyer } from './C/C167_CattleBuyer'
import { C168_AnimalCatcher } from './C/C168_AnimalCatcher'
import { C17_NewlyPlowedField } from './C/C17_NewlyPlowedField'
import { C178_OnSiteReverend } from './C/C178_OnSiteReverend'
import { C18_RollOverPlow } from './C/C18_RollOverPlow'
import { C19_SwingPlow } from './C/C19_SwingPlow'
import { C2_Stable } from './C/C2_Stable'
import { C20_MolePlow } from './C/C20_MolePlow'
import { C21_HeartofStone } from './C/C21_HeartofStone'
import { C22_BasketChair } from './C/C22_BasketChair'
import { C23_JobContract } from './C/C23_JobContract'
import { C24_BedintheGrainField } from './C/C24_BedintheGrainField'
import { C25_SteamMachine } from './C/C25_SteamMachine'
import { C26_Flail } from './C/C26_Flail'
import { C27_Blueprint } from './C/C27_Blueprint'
import { C28_TeachersDesk } from './C/C28_TeachersDesk'
import { C29_BeerTable } from './C/C29_BeerTable'
import { C3_CarriageTrip } from './C/C3_CarriageTrip'
import { C30_HalfTimberedHouse } from './C/C30_HalfTimberedHouse'
import { C31_WritingChamber } from './C/C31_WritingChamber'
import { C32_AbortOriel } from './C/C32_AbortOriel'
import { C33_GreeningPlan } from './C/C33_GreeningPlan'
import { C34_ElephantgrassPlant } from './C/C34_ElephantgrassPlant'
import { C35_LanternHouse } from './C/C35_LanternHouse'
import { C36_ClayDeposit } from './C/C36_ClayDeposit'
import { C37_DwellingMound } from './C/C37_DwellingMound'
import { C38_Christianity } from './C/C38_Christianity'
import { C39_StudioBoat } from './C/C39_StudioBoat'
import { C4_WritingBoards } from './C/C4_WritingBoards'
import { C40_CanvasSack } from './C/C40_CanvasSack'
import { C41_FarmStore } from './C/C41_FarmStore'
import { C42_RavenousHunger } from './C/C42_RavenousHunger'
import { C43_FarmBuilding } from './C/C43_FarmBuilding'
import { C44_ChickenCoop } from './C/C44_ChickenCoop'
import { C45_Stew } from './C/C45_Stew'
import { C46_Mandoline } from './C/C46_Mandoline'
import { C47_GardenClaw } from './C/C47_GardenClaw'
import { C48_Farmstead } from './C/C48_Farmstead'
import { C49_BeerStall } from './C/C49_BeerStall'
import { C5_Remodeling } from './C/C5_Remodeling'
import { C50_StableYard } from './C/C50_StableYard'
import { C51_FishingNet } from './C/C51_FishingNet'
import { C52_HuntsmansHat } from './C/C52_HuntsmansHat'
import { C53_GypsysCrock } from './C/C53_GypsysCrock'
import { C54_MarketBooth } from './C/C54_MarketBooth'
import { C55_Studio } from './C/C55_Studio'
import { C56_FeedFence } from './C/C56_FeedFence'
import { C57_Crudite } from './C/C57_Crudite'
import { C58_Woodcraft } from './C/C58_Woodcraft'
import { C59_SchnappsDistillery } from './C/C59_SchnappsDistillery'
import { C6_StoneClearing } from './C/C6_StoneClearing'
import { C60_SmallPottersOven } from './C/C60_SmallPottersOven'
import { C61_BeerStein } from './C/C61_BeerStein'
import { C62_CookeryExtension } from './C/C62_CookeryExtension'
import { C63_CraftBrewery } from './C/C63_CraftBrewery'
import { C64_CornSchnappsDistillery } from './C/C64_CornSchnappsDistillery'
import { C65_Granary } from './C/C65_Granary'
import { C66_EternalRyeCultivation } from './C/C66_EternalRyeCultivation'
import { C67_MineralFeeder } from './C/C67_MineralFeeder'
import { C68_Bookcase } from './C/C68_Bookcase'
import { C69_LandConsolidation } from './C/C69_LandConsolidation'
import { C7_BladeShears } from './C/C7_BladeShears'
import { C70_LettucePatch } from './C/C70_LettucePatch'
import { C71_Slurry } from './C/C71_Slurry'
import { C72_FestivalPlanning } from './C/C72_FestivalPlanning'
import { C73_SeaweedFertilizer } from './C/C73_SeaweedFertilizer'
import { C74_PrivateForest } from './C/C74_PrivateForest'
import { C75_Firewood } from './C/C75_Firewood'
import { C76_WoodCart } from './C/C76_WoodCart'
import { C77_ClaySupply } from './C/C77_ClaySupply'
import { C78_ReedHattedToad } from './C/C78_ReedHattedToad'
import { C79_StoneCart } from './C/C79_StoneCart'
import { C8_PlantFertilizer } from './C/C8_PlantFertilizer'
import { C80_RockyTerrain } from './C/C80_RockyTerrain'
import { C81_MaterialHub } from './C/C81_MaterialHub'
import { C82_HardwareStore } from './C/C82_HardwareStore'
import { C83_EarlyCattle } from './C/C83_EarlyCattle'
import { C84_PerennialRye } from './C/C84_PerennialRye'
import { C85_DenBuilder } from './C/C85_DenBuilder'
import { C86_LivestockFeeder } from './C/C86_LivestockFeeder'
import { C87_Mason } from './C/C87_Mason'
import { C88_CarpentersApprentice } from './C/C88_CarpentersApprentice'
import { C89_StableMaster } from './C/C89_StableMaster'
import { C9_AutomaticWaterTrough } from './C/C9_AutomaticWaterTrough'
import { C90_FieldWatchman } from './C/C90_FieldWatchman'
import { C91_PlowHero } from './C/C91_PlowHero'
import { C92_AutumnMother } from './C/C92_AutumnMother'
import { C93_InnerDistrictsDirector } from './C/C93_InnerDistrictsDirector'
import { C94_StableCleaner } from './C/C94_StableCleaner'
import { C95_BasketWeaver } from './C/C95_BasketWeaver'
import { C96_Merchant } from './C/C96_Merchant'
import { C97_SeedResearcher } from './C/C97_SeedResearcher'
import { C98_CubeCutter } from './C/C98_CubeCutter'
import { C99_GardenDesigner } from './C/C99_GardenDesigner'
import { CUSTOM_FixtureHarvester } from './community/CUSTOM_FixtureHarvester'
import { D1_ZigzagHarrow } from './D/D1_ZigzagHarrow'
import { D10_StorksNest } from './D/D10_StorksNest'
import { D100_LordoftheManor } from './D/D100_LordoftheManor'
import { D101_SugarBaker } from './D/D101_SugarBaker'
import { D102_SampleStableMaker } from './D/D102_SampleStableMaker'
import { D103_CanalBoatman } from './D/D103_CanalBoatman'
import { D104_Cultivator } from './D/D104_Cultivator'
import { D105_Sculptor } from './D/D105_Sculptor'
import { D106_WhiskyDistiller } from './D/D106_WhiskyDistiller'
import { D107_Bellfounder } from './D/D107_Bellfounder'
import { D109_SowingMaster } from './D/D109_SowingMaster'
import { D11_LawnFertilizer } from './D/D11_LawnFertilizer'
import { D110_FishFarmer } from './D/D110_FishFarmer'
import { D111_InteriorDecorator } from './D/D111_InteriorDecorator'
import { D112_YoungFarmer } from './D/D112_YoungFarmer'
import { D113_FoodMerchant } from './D/D113_FoodMerchant'
import { D114_SeedTrader } from './D/D114_SeedTrader'
import { D115_FodderPlanter } from './D/D115_FodderPlanter'
import { D116_TreeInspector } from './D/D116_TreeInspector'
import { D117_WoodExpert } from './D/D117_WoodExpert'
import { D118_Bonehead } from './D/D118_Bonehead'
import { D119_WoodBarterer } from './D/D119_WoodBarterer'
import { D12_MilkingPlace } from './D/D12_MilkingPlace'
import { D120_ClayDeliveryman } from './D/D120_ClayDeliveryman'
import { D121_ClayPlasterer } from './D/D121_ClayPlasterer'
import { D122_ClayCarrier } from './D/D122_ClayCarrier'
import { D123_RenovationPreparer } from './D/D123_RenovationPreparer'
import { D124_Emissary } from './D/D124_Emissary'
import { D125_ForestTrader } from './D/D125_ForestTrader'
import { D126_FieldCultivator } from './D/D126_FieldCultivator'
import { D127_HardworkingMan } from './D/D127_HardworkingMan'
import { D128_BuildingTycoon } from './D/D128_BuildingTycoon'
import { D129_LumberVirtuoso } from './D/D129_LumberVirtuoso'
import { D13_Trowel } from './D/D13_Trowel'
import { D130_RecreationalCarpenter } from './D/D130_RecreationalCarpenter'
import { D131_CraftsmanshipPromoter } from './D/D131_CraftsmanshipPromoter'
import { D132_HideFarmer } from './D/D132_HideFarmer'
import { D133_BeerTentOperator } from './D/D133_BeerTentOperator'
import { D134_OysterEater } from './D/D134_OysterEater'
import { D135_GardeningHeadOfficial } from './D/D135_GardeningHeadOfficial'
import { D136_AnimalActivist } from './D/D136_AnimalActivist'
import { D137_TradeTeacher } from './D/D137_TradeTeacher'
import { D138_PetLover } from './D/D138_PetLover'
import { D139_Chairman } from './D/D139_Chairman'
import { D14_HammerCrusher } from './D/D14_HammerCrusher'
import { D140_Loudmouth } from './D/D140_Loudmouth'
import { D141_SeedSeller } from './D/D141_SeedSeller'
import { D142_PotatoPlanter } from './D/D142_PotatoPlanter'
import { D143_TreeCutter } from './D/D143_TreeCutter'
import { D144_WaterWorker } from './D/D144_WaterWorker'
import { D145_RoofExaminer } from './D/D145_RoofExaminer'
import { D146_Porter } from './D/D146_Porter'
import { D147_TrapBuilder } from './D/D147_TrapBuilder'
import { D148_DomesticianExpert } from './D/D148_DomesticianExpert'
import { D149_CasualWorker } from './D/D149_CasualWorker'
import { D15_ClaySupports } from './D/D15_ClaySupports'
import { D150_GodlySpouse } from './D/D150_GodlySpouse'
import { D151_SpinDoctor } from './D/D151_SpinDoctor'
import { D152_Patron } from './D/D152_Patron'
import { D153_WealthyMan } from './D/D153_WealthyMan'
import { D154_ChimneySweep } from './D/D154_ChimneySweep'
import { D156_RetailDealer } from './D/D156_RetailDealer'
import { D157_PartyOrganizer } from './D/D157_PartyOrganizer'
import { D158_BeanCounter } from './D/D158_BeanCounter'
import { D16_WoodenWheyBucket } from './D/D16_WoodenWheyBucket'
import { D160_Midwife } from './D/D160_Midwife'
import { D161_CabbageBuyer } from './D/D161_CabbageBuyer'
import { D162_ClayFirer } from './D/D162_ClayFirer'
import { D163_JourneymanBricklayer } from './D/D163_JourneymanBricklayer'
import { D164_PetGrower } from './D/D164_PetGrower'
import { D165_PigStalker } from './D/D165_PigStalker'
import { D166_StableMilker } from './D/D166_StableMilker'
import { D167_PureBreeder } from './D/D167_PureBreeder'
import { D168_Stockman } from './D/D168_Stockman'
import { D17_DrillHarrow } from './D/D17_DrillHarrow'
import { D177_Graduate } from './D/D177_Graduate'
import { D18_SteamPlow } from './D/D18_SteamPlow'
import { D19_PulverizerPlow } from './D/D19_PulverizerPlow'
import { D2_DwellingPlan } from './D/D2_DwellingPlan'
import { D20_TurnwrestPlow } from './D/D20_TurnwrestPlow'
import { D21_Recruitment } from './D/D21_Recruitment'
import { D22_WorkPermit } from './D/D22_WorkPermit'
import { D23_PioneeringSpirit } from './D/D23_PioneeringSpirit'
import { D24_BrotherlyLove } from './D/D24_BrotherlyLove'
import { D25_WitchesDanceFloor } from './D/D25_WitchesDanceFloor'
import { D26_CarpentersYard } from './D/D26_CarpentersYard'
import { D27_Retraining } from './D/D27_Retraining'
import { D28_WritingDesk } from './D/D28_WritingDesk'
import { D29_MuckRake } from './D/D29_MuckRake'
import { D3_Furrows } from './D/D3_Furrows'
import { D30_ArtisanDistrict } from './D/D30_ArtisanDistrict'
import { D31_Storeroom } from './D/D31_Storeroom'
import { D32_WoodRake } from './D/D32_WoodRake'
import { D33_SummerHouse } from './D/D33_SummerHouse'
import { D34_LuxuriousHostel } from './D/D34_LuxuriousHostel'
import { D35_FodderChamber } from './D/D35_FodderChamber'
import { D36_BreedRegistry } from './D/D36_BreedRegistry'
import { D37_Sculpture } from './D/D37_Sculpture'
import { D38_MilkingStool } from './D/D38_MilkingStool'
import { D39_TruffleSlicer } from './D/D39_TruffleSlicer'
import { D4_CrossCutWood } from './D/D4_CrossCutWood'
import { D40_Cesspit } from './D/D40_Cesspit'
import { D41_HorseDrawnBoat } from './D/D41_HorseDrawnBoat'
import { D42_EducationBonus } from './D/D42_EducationBonus'
import { D43_Hutch } from './D/D43_Hutch'
import { D44_ForestWell } from './D/D44_ForestWell'
import { D45_SheepWell } from './D/D45_SheepWell'
import { D46_PelletPress } from './D/D46_PelletPress'
import { D47_Churchyard } from './D/D47_Churchyard'
import { D48_CivicFacade } from './D/D48_CivicFacade'
import { D49_Bookshelf } from './D/D49_Bookshelf'
import { D5_FieldClay } from './D/D5_FieldClay'
import { D50_ForeignAid } from './D/D50_ForeignAid'
import { D51_Archway } from './D/D51_Archway'
import { D52_RollingPin } from './D/D52_RollingPin'
import { D53_TeaHouse } from './D/D53_TeaHouse'
import { D54_TroutPool } from './D/D54_TroutPool'
import { D55_NewMarket } from './D/D55_NewMarket'
import { D56_FatstockStretcher } from './D/D56_FatstockStretcher'
import { D57_WholesaleMarket } from './D/D57_WholesaleMarket'
import { D58_Gritter } from './D/D58_Gritter'
import { D6_PetrifiedWood } from './D/D6_PetrifiedWood'
import { D60_LargePottery } from './D/D60_LargePottery'
import { D61_BaleofStraw } from './D/D61_BaleofStraw'
import { D62_BeerTap } from './D/D62_BeerTap'
import { D63_Lynchet } from './D/D63_Lynchet'
import { D64_BakingCourse } from './D/D64_BakingCourse'
import { D65_GrainSieve } from './D/D65_GrainSieve'
import { D66_PotterCeramics } from './D/D66_PotterCeramics'
import { D67_ReapHook } from './D/D67_ReapHook'
import { D68_SmallBasket } from './D/D68_SmallBasket'
import { D69_SmallGreenhouse } from './D/D69_SmallGreenhouse'
import { D7_Trident } from './D/D7_Trident'
import { D70_StrawManure } from './D/D70_StrawManure'
import { D71_Changeover } from './D/D71_Changeover'
import { D72_StableManure } from './D/D72_StableManure'
import { D73_SupplyBoat } from './D/D73_SupplyBoat'
import { D74_RoyalWood } from './D/D74_RoyalWood'
import { D75_WoodField } from './D/D75_WoodField'
import { D76_SocialBenefits } from './D/D76_SocialBenefits'
import { D77_RecycledBrick } from './D/D77_RecycledBrick'
import { D78_ReedPond } from './D/D78_ReedPond'
import { D79_CarrotMuseum } from './D/D79_CarrotMuseum'
import { D8_FernSeeds } from './D/D8_FernSeeds'
import { D80_BrickHammer } from './D/D80_BrickHammer'
import { D81_RoofLadder } from './D/D81_RoofLadder'
import { D82_HuntingTrophy } from './D/D82_HuntingTrophy'
import { D83_Pigswill } from './D/D83_Pigswill'
import { D84_FeedPellets } from './D/D84_FeedPellets'
import { D85_Reader } from './D/D85_Reader'
import { D86_SheepAgent } from './D/D86_SheepAgent'
import { D87_MasterBuilder } from './D/D87_MasterBuilder'
import { D88_Millwright } from './D/D88_Millwright'
import { D89_Stablehand } from './D/D89_Stablehand'
import { D9_GameTrade } from './D/D9_GameTrade'
import { D90_PlowMaker } from './D/D90_PlowMaker'
import { D91_Plowman } from './D/D91_Plowman'
import { D92_ChildOmbudsman } from './D/D92_ChildOmbudsman'
import { D93_SheepInspector } from './D/D93_SheepInspector'
import { D94_HenpeckedHusband } from './D/D94_HenpeckedHusband'
import { D95_SiteManager } from './D/D95_SiteManager'
import { D96_Furnisher } from './D/D96_Furnisher'
import { D97_BeggingStudent } from './D/D97_BeggingStudent'
import { D98_Transactor } from './D/D98_Transactor'
import { D99_EarthenwarePotter } from './D/D99_EarthenwarePotter'
import { E1_PoleBarns } from './E/E1_PoleBarns'
import { E10_StrawHat } from './E/E10_StrawHat'
import { E100_MuseumCaretaker } from './E/E100_MuseumCaretaker'
import { E101_Blighter } from './E/E101_Blighter'
import { E102_Acquirer } from './E/E102_Acquirer'
import { E103_Wolf } from './E/E103_Wolf'
import { E104_SpiceTrader } from './E/E104_SpiceTrader'
import { E105_Pioneer } from './E/E105_Pioneer'
import { E106_EmergencySeller } from './E/E106_EmergencySeller'
import { E107_LandSurveyor } from './E/E107_LandSurveyor'
import { E108_BlackberryFarmer } from './E/E108_BlackberryFarmer'
import { E109_BraidMaker } from './E/E109_BraidMaker'
import { E11_PettingZoo } from './E/E11_PettingZoo'
import { E110_Dentist } from './E/E110_Dentist'
import { E111_Recluse } from './E/E111_Recluse'
import { E112_GrainThief } from './E/E112_GrainThief'
import { E113_Godmother } from './E/E113_Godmother'
import { E114_ShedBuilder } from './E/E114_ShedBuilder'
import { E115_SeedServant } from './E/E115_SeedServant'
import { E116_FirCutter } from './E/E116_FirCutter'
import { E117_PipeSmoker } from './E/E117_PipeSmoker'
import { E118_KindlingGatherer } from './E/E118_KindlingGatherer'
import { E119_LandHeir } from './E/E119_LandHeir'
import { E12_AnimalBedding } from './E/E12_AnimalBedding'
import { E120_ScrapCollector } from './E/E120_ScrapCollector'
import { E121_HillCultivator } from './E/E121_HillCultivator'
import { E122_Cottar } from './E/E122_Cottar'
import { E123_ResourceHoarder } from './E/E123_ResourceHoarder'
import { E124_MayorCandidate } from './E/E124_MayorCandidate'
import { E125_DelayedWayfarer } from './E/E125_DelayedWayfarer'
import { E126_TaxCollector } from './E/E126_TaxCollector'
import { E127_DiligentFarmer } from './E/E127_DiligentFarmer'
import { E128_Saddler } from './E/E128_Saddler'
import { E129_Imitator } from './E/E129_Imitator'
import { E13_StoneHouseReconstruction } from './E/E13_StoneHouseReconstruction'
import { E130_Overachiever } from './E/E130_Overachiever'
import { E131_MarketMaster } from './E/E131_MarketMaster'
import { E132_VeggieLover } from './E/E132_VeggieLover'
import { E133_ChampionBreeder } from './E/E133_ChampionBreeder'
import { E134_Omnifarmer } from './E/E134_Omnifarmer'
import { E135_Pickler } from './E/E135_Pickler'
import { E136_AnimalHusbandryWorker } from './E/E136_AnimalHusbandryWorker'
import { E137_FlaxFarmer } from './E/E137_FlaxFarmer'
import { E138_LivestockExpert } from './E/E138_LivestockExpert'
import { E139_BunnyBreeder } from './E/E139_BunnyBreeder'
import { E14_WoodSaw } from './E/E14_WoodSaw'
import { E140_Carter } from './E/E140_Carter'
import { E141_VegetableVendor } from './E/E141_VegetableVendor'
import { E142_Smuggler } from './E/E142_Smuggler'
import { E143_Hewer } from './E/E143_Hewer'
import { E144_WaresSalesman } from './E/E144_WaresSalesman'
import { E145_Parvenu } from './E/E145_Parvenu'
import { E146_Reseller } from './E/E146_Reseller'
import { E147_AnimalDriver } from './E/E147_AnimalDriver'
import { E148_Lazybones } from './E/E148_Lazybones'
import { E149_MidnightFencer } from './E/E149_MidnightFencer'
import { E15_NailBasket } from './E/E15_NailBasket'
import { E150_RockBeater } from './E/E150_RockBeater'
import { E151_DeliveryNurse } from './E/E151_DeliveryNurse'
import { E152_BargainHunter } from './E/E152_BargainHunter'
import { E153_StoneSculptor } from './E/E153_StoneSculptor'
import { E154_Margrave } from './E/E154_Margrave'
import { E155_Visionary } from './E/E155_Visionary'
import { E156_ClaypitOwner } from './E/E156_ClaypitOwner'
import { E157_Usufructuary } from './E/E157_Usufructuary'
import { E158_StoneCustodian } from './E/E158_StoneCustodian'
import { E159_OldMiser } from './E/E159_OldMiser'
import { E16_BriarHedge } from './E/E16_BriarHedge'
import { E160_KelpGatherer } from './E/E160_KelpGatherer'
import { E161_ElderBaker } from './E/E161_ElderBaker'
import { E162_Entrepreneur } from './E/E162_Entrepreneur'
import { E163_Patroness } from './E/E163_Patroness'
import { E164_MountainPlowman } from './E/E164_MountainPlowman'
import { E165_MasterHuntsman } from './E/E165_MasterHuntsman'
import { E166_Roastmaster } from './E/E166_Roastmaster'
import { E167_DairyCrier } from './E/E167_DairyCrier'
import { E168_AnimalTamersApprentice } from './E/E168_AnimalTamersApprentice'
import { E17_SkimmerPlow } from './E/E17_SkimmerPlow'
import { E18_SeedAlmanac } from './E/E18_SeedAlmanac'
import { E19_OxGoad } from './E/E19_OxGoad'
import { E2_RenovationMaterials } from './E/E2_RenovationMaterials'
import { E20_IronHoe } from './E/E20_IronHoe'
import { E21_SheepRug } from './E/E21_SheepRug'
import { E22_GuestRoom } from './E/E22_GuestRoom'
import { E23_Apiary } from './E/E23_Apiary'
import { E24_Ambition } from './E/E24_Ambition'
import { E25_BumperCrop } from './E/E25_BumperCrop'
import { E26_Sundial } from './E/E26_Sundial'
import { E27_PiggyBank } from './E/E27_PiggyBank'
import { E28_Bookmark } from './E/E28_Bookmark'
import { E29_Heirloom } from './E/E29_Heirloom'
import { E3_TeaTime } from './E/E3_TeaTime'
import { E30_ChildsToy } from './E/E30_ChildsToy'
import { E31_Upholstery } from './E/E31_Upholstery'
import { E32_Nave } from './E/E32_Nave'
import { E33_BeaverColony } from './E/E33_BeaverColony'
import { E34_LandRegister } from './E/E34_LandRegister'
import { E35_Misanthropy } from './E/E35_Misanthropy'
import { E36_HerbalGarden } from './E/E36_HerbalGarden'
import { E37_OxSkull } from './E/E37_OxSkull'
import { E38_RodCollection } from './E/E38_RodCollection'
import { E39_Paintbrush } from './E/E39_Paintbrush'
import { E4_Thunderbolt } from './E/E4_Thunderbolt'
import { E40_BeeStatue } from './E/E40_BeeStatue'
import { E41_MuddyWaters } from './E/E41_MuddyWaters'
import { E42_WaterGully } from './E/E42_WaterGully'
import { E43_BarnCats } from './E/E43_BarnCats'
import { E44_FodderBeets } from './E/E44_FodderBeets'
import { E45_FruitLadder } from './E/E45_FruitLadder'
import { E46_WaterlilyPond } from './E/E46_WaterlilyPond'
import { E47_SyrupTap } from './E/E47_SyrupTap'
import { E48_TownHall } from './E/E48_TownHall'
import { E49_Twibil } from './E/E49_Twibil'
import { E5_NightLoot } from './E/E5_NightLoot'
import { E50_WildGreens } from './E/E50_WildGreens'
import { E51_WhaleOil } from './E/E51_WhaleOil'
import { E52_Cubbyhole } from './E/E52_Cubbyhole'
import { E53_BoarSpear } from './E/E53_BoarSpear'
import { E54_Contraband } from './E/E54_Contraband'
import { E55_StoneWeir } from './E/E55_StoneWeir'
import { E56_RomanPot } from './E/E56_RomanPot'
import { E57_CheeseFondue } from './E/E57_CheeseFondue'
import { E58_LunchtimeBeer } from './E/E58_LunchtimeBeer'
import { E59_CombandCutter } from './E/E59_CombandCutter'
import { E6_Recount } from './E/E6_Recount'
import { E60_WorkingGloves } from './E/E60_WorkingGloves'
import { E61_RaisedBed } from './E/E61_RaisedBed'
import { E62_SourDough } from './E/E62_SourDough'
import { E63_IronOven } from './E/E63_IronOven'
import { E64_SimpleOven } from './E/E64_SimpleOven'
import { E65_Almsbag } from './E/E65_Almsbag'
import { E66_BarnShed } from './E/E66_BarnShed'
import { E67_GrainBag } from './E/E67_GrainBag'
import { E68_CherryOrchard } from './E/E68_CherryOrchard'
import { E69_MelonPatch } from './E/E69_MelonPatch'
import { E7_Pumpernickel } from './E/E7_Pumpernickel'
import { E70_CropRotationField } from './E/E70_CropRotationField'
import { E71_CowPatty } from './E/E71_CowPatty'
import { E72_ArtichokeField } from './E/E72_ArtichokeField'
import { E73_Scythe } from './E/E73_Scythe'
import { E74_AshTrees } from './E/E74_AshTrees'
import { E75_StoneAxe } from './E/E75_StoneAxe'
import { E76_LumberPile } from './E/E76_LumberPile'
import { E77_Mattock } from './E/E77_Mattock'
import { E78_SleightofHand } from './E/E78_SleightofHand'
import { E79_FieldSpade } from './E/E79_FieldSpade'
import { E8_FarmersMarket } from './E/E8_FarmersMarket'
import { E80_RockGarden } from './E/E80_RockGarden'
import { E81_AlchemistsLab } from './E/E81_AlchemistsLab'
import { E82_Profiteering } from './E/E82_Profiteering'
import { E83_ShepherdsWhistle } from './E/E83_ShepherdsWhistle'
import { E84_DollysMother } from './E/E84_DollysMother'
import { E85_MasterTanner } from './E/E85_MasterTanner'
import { E86_PenBuilder } from './E/E86_PenBuilder'
import { E87_MasterRenovator } from './E/E87_MasterRenovator'
import { E88_MasterFencer } from './E/E88_MasterFencer'
import { E89_Stallwright } from './E/E89_Stallwright'
import { E9_BarteringHut } from './E/E9_BarteringHut'
import { E90_DungCollector } from './E/E90_DungCollector'
import { E91_PlowBuilder } from './E/E91_PlowBuilder'
import { E92_FieldDoctor } from './E/E92_FieldDoctor'
import { E93_Motivator } from './E/E93_Motivator'
import { E94_Prophet } from './E/E94_Prophet'
import { E95_Miller } from './E/E95_Miller'
import { E96_Elder } from './E/E96_Elder'
import { E97_Beneficiary } from './E/E97_Beneficiary'
import { E98_Prodigy } from './E/E98_Prodigy'
import { E99_UncaringParents } from './E/E99_UncaringParents'
import { STUB_BeforeBakeGainClay } from './__stubs__/STUB_BeforeBakeGainClay'
import { Major_ClayOven } from './major/clay-oven'
import { Major_StoneOven } from './major/stone-oven'
import { Major_Well } from './major/well'
import { Major_Joinery } from './major/joinery'
import { Major_Pottery } from './major/pottery'
import { Major_Basket } from './major/basketmaker'
import { Major_Well2 } from './major/well'
import { Major_ClayOven2 } from './major/clay-oven'
import { Major_StoneOven2 } from './major/stone-oven'
import { Major_Joinery2 } from './major/joinery'
import { Major_Pottery2 } from './major/pottery'
import { Major_Basket2 } from './major/basketmaker'

export const ALL_CARD_IMPLS: Readonly<Record<string, CardImpl>> = {
  'A1_Shelter': A1_Shelter.impl,
  'A10_WoodenShed': A10_WoodenShed.impl,
  'A100_Curator': A100_Curator.impl,
  'A101_CookeryOutfitter': A101_CookeryOutfitter.impl,
  'A102_Grocer': A102_Grocer.impl,
  'A103_Portmonger': A103_Portmonger.impl,
  'A104_WoodHarvester': A104_WoodHarvester.impl,
  'A105_BarrowPusher': A105_BarrowPusher.impl,
  'A106_SlurrySpreader': A106_SlurrySpreader.impl,
  'A107_Catcher': A107_Catcher.impl,
  'A108_MushroomCollector': A108_MushroomCollector.impl,
  'A109_SmallTrader': A109_SmallTrader.impl,
  'A11_MudPatch': A11_MudPatch.impl,
  'A110_Roughcaster': A110_Roughcaster.impl,
  'A111_WallBuilder': A111_WallBuilder.impl,
  'A112_ScytheWorker': A112_ScytheWorker.impl,
  'A113_HeresyTeacher': A113_HeresyTeacher.impl,
  'A114_SeasonalWorker': A114_SeasonalWorker.impl,
  'A115_ChiefForester': A115_ChiefForester.impl,
  'A116_WoodCutter': A116_WoodCutter.impl,
  'A117_WoodCarrier': A117_WoodCarrier.impl,
  'A118_Treegardener': A118_Treegardener.impl,
  'A119_FirewoodCollector': A119_FirewoodCollector.impl,
  'A12_DrinkingTrough': A12_DrinkingTrough.impl,
  'A120_ClayHutBuilder': A120_ClayHutBuilder.impl,
  'A121_ClayPuncher': A121_ClayPuncher.impl,
  'A122_PanBaker': A122_PanBaker.impl,
  'A123_FrameBuilder': A123_FrameBuilder.impl,
  'A124_Knapper': A124_Knapper.impl,
  'A125_Priest': A125_Priest.impl,
  'A126_MasterWorkman': A126_MasterWorkman.impl,
  'A127_Lodger': A127_Lodger.impl,
  'A128_RiparianBuilder': A128_RiparianBuilder.impl,
  'A129_Swagman': A129_Swagman.impl,
  'A13_RenovationCompany': A13_RenovationCompany.impl,
  'A130_MummysBoy': A130_MummysBoy.impl,
  'A131_CraftTeacher': A131_CraftTeacher.impl,
  'A132_Publican': A132_Publican.impl,
  'A133_Braggart': A133_Braggart.impl,
  'A134_FullFarmer': A134_FullFarmer.impl,
  'A135_AnimalReeve': A135_AnimalReeve.impl,
  'A136_DrudgeryReeve': A136_DrudgeryReeve.impl,
  'A137_RiverineShepherd': A137_RiverineShepherd.impl,
  'A138_Harpooner': A138_Harpooner.impl,
  'A139_HollowWarden': A139_HollowWarden.impl,
  'A14_CarpentersHammer': A14_CarpentersHammer.impl,
  'A140_ShovelBearer': A140_ShovelBearer.impl,
  'A141_TurnipFarmer': A141_TurnipFarmer.impl,
  'A142_Cordmaker': A142_Cordmaker.impl,
  'A143_Stonecutter': A143_Stonecutter.impl,
  'A144_Sequestrator': A144_Sequestrator.impl,
  'A145_Ropemaker': A145_Ropemaker.impl,
  'A146_StorehouseSteward': A146_StorehouseSteward.impl,
  'A147_AnimalDealer': A147_AnimalDealer.impl,
  'A148_Woolgrower': A148_Woolgrower.impl,
  'A149_HouseArtist': A149_HouseArtist.impl,
  'A15_CarpentersAxe': A15_CarpentersAxe.impl,
  'A150_Stagehand': A150_Stagehand.impl,
  'A151_Minstrel': A151_Minstrel.impl,
  'A152_NightSchoolStudent': A152_NightSchoolStudent.impl,
  'A153_PigOwner': A153_PigOwner.impl,
  'A154_Paymaster': A154_Paymaster.impl,
  'A155_Conjurer': A155_Conjurer.impl,
  'A156_Buyer': A156_Buyer.impl,
  'A157_Bohemian': A157_Bohemian.impl,
  'A158_CulinaryArtist': A158_CulinaryArtist.impl,
  'A159_JoineroftheSea': A159_JoineroftheSea.impl,
  'A16_RammedClay': A16_RammedClay.impl,
  'A160_Lutenist': A160_Lutenist.impl,
  'A161_PatchCaretaker': A161_PatchCaretaker.impl,
  'A162_ForestTallyman': A162_ForestTallyman.impl,
  'A163_BuildingExpert': A163_BuildingExpert.impl,
  'A164_WoodWorker': A164_WoodWorker.impl,
  'A165_PigBreeder': A165_PigBreeder.impl,
  'A166_Haydryer': A166_Haydryer.impl,
  'A167_BreederBuyer': A167_BreederBuyer.impl,
  'A168_AnimalTeacher': A168_AnimalTeacher.impl,
  'A17_ReclamationPlow': A17_ReclamationPlow.impl,
  'A176_Wheelmaker': A176_Wheelmaker.impl,
  'A18_WheelPlow': A18_WheelPlow.impl,
  'A19_Handplow': A19_Handplow.impl,
  'A2_ShiftingCultivation': A2_ShiftingCultivation.impl,
  'A20_DoubleTurnPlow': A20_DoubleTurnPlow.impl,
  'A21_FamilyFriendHome': A21_FamilyFriendHome.impl,
  'A22_Telegram': A22_Telegram.impl,
  'A23_StoneCompany': A23_StoneCompany.impl,
  'A24_ThreshingBoard': A24_ThreshingBoard.impl,
  'A25_Bassinet': A25_Bassinet.impl,
  'A26_SleepingCorner': A26_SleepingCorner.impl,
  'A27_OvenSite': A27_OvenSite.impl,
  'A28_ForestSchool': A28_ForestSchool.impl,
  'A29_AleBenches': A29_AleBenches.impl,
  'A3_PaperKnife': A3_PaperKnife.impl,
  'A30_BakingSheet': A30_BakingSheet.impl,
  'A31_DebtSecurity': A31_DebtSecurity.impl,
  'A32_Manger': A32_Manger.impl,
  'A33_BigCountry': A33_BigCountry.impl,
  'A34_Loppers': A34_Loppers.impl,
  'A35_SwimmingClass': A35_SwimmingClass.impl,
  'A36_FacadesCarving': A36_FacadesCarving.impl,
  'A37_Bucksaw': A37_Bucksaw.impl,
  'A38_WoolBlankets': A38_WoolBlankets.impl,
  'A39_Chapel': A39_Chapel.impl,
  'A4_Baseboards': A4_Baseboards.impl,
  'A40_PottersYard': A40_PottersYard.impl,
  'A41_VegetableSlicer': A41_VegetableSlicer.impl,
  'A42_ForestLakeHut': A42_ForestLakeHut.impl,
  'A43_FarmyardManure': A43_FarmyardManure.impl,
  'A44_PondHut': A44_PondHut.impl,
  'A45_FireProtectionPond': A45_FireProtectionPond.impl,
  'A46_ClawKnife': A46_ClawKnife.impl,
  'A47_Trellises': A47_Trellises.impl,
  'A48_ShavingHorse': A48_ShavingHorse.impl,
  'A49_NestSite': A49_NestSite.impl,
  'A5_ClayEmbankment': A5_ClayEmbankment.impl,
  'A50_MilkJug': A50_MilkJug.impl,
  'A51_DriftNetBoat': A51_DriftNetBoat.impl,
  'A52_ThrowingAxe': A52_ThrowingAxe.impl,
  'A53_Claypipe': A53_Claypipe.impl,
  'A54_Credit': A54_Credit.impl,
  'A55_JunkRoom': A55_JunkRoom.impl,
  'A56_Basket': A56_Basket.impl,
  'A57_MilkingParlor': A57_MilkingParlor.impl,
  'A58_AsparagusKnife': A58_AsparagusKnife.impl,
  'A59_PotatoRidger': A59_PotatoRidger.impl,
  'A6_StorageBarn': A6_StorageBarn.impl,
  'A61_WinnowingFan': A61_WinnowingFan.impl,
  'A62_BeerKeg': A62_BeerKeg.impl,
  'A63_DutchWindmill': A63_DutchWindmill.impl,
  'A64_BarleyMill': A64_BarleyMill.impl,
  'A65_SeedPellets': A65_SeedPellets.impl,
  'A66_FeedingDish': A66_FeedingDish.impl,
  'A67_CornScoop': A67_CornScoop.impl,
  'A68_AsparagusGift': A68_AsparagusGift.impl,
  'A69_LargeGreenhouse': A69_LargeGreenhouse.impl,
  'A7_GardenersKnife': A7_GardenersKnife.impl,
  'A70_LiftingMachine': A70_LiftingMachine.impl,
  'A71_ClearingSpade': A71_ClearingSpade.impl,
  'A72_CalciumFertilizers': A72_CalciumFertilizers.impl,
  'A73_AgriculturalFertilizers': A73_AgriculturalFertilizers.impl,
  'A74_StableTree': A74_StableTree.impl,
  'A75_LumberMill': A75_LumberMill.impl,
  'A76_Cob': A76_Cob.impl,
  'A77_Hod': A77_Hod.impl,
  'A78_Canoe': A78_Canoe.impl,
  'A79_GardenHoe': A79_GardenHoe.impl,
  'A8_FoodBasket': A8_FoodBasket.impl,
  'A80_StoneTongs': A80_StoneTongs.impl,
  'A81_InterimStorage': A81_InterimStorage.impl,
  'A82_WorkCertificate': A82_WorkCertificate.impl,
  'A83_ShepherdsCrook': A83_ShepherdsCrook.impl,
  'A84_Silage': A84_Silage.impl,
  'A85_Homekeeper': A85_Homekeeper.impl,
  'A86_AnimalTamer': A86_AnimalTamer.impl,
  'A87_Conservator': A87_Conservator.impl,
  'A88_HedgeKeeper': A88_HedgeKeeper.impl,
  'A89_StablePlanner': A89_StablePlanner.impl,
  'A9_YoungAnimalMarket': A9_YoungAnimalMarket.impl,
  'A90_PlowDriver': A90_PlowDriver.impl,
  'A91_ShiftingCultivator': A91_ShiftingCultivator.impl,
  'A92_AdoptiveParents': A92_AdoptiveParents.impl,
  'A93_BedMaker': A93_BedMaker.impl,
  'A94_LazySowman': A94_LazySowman.impl,
  'A95_Angler': A95_Angler.impl,
  'A96_TaskArtisan': A96_TaskArtisan.impl,
  'A97_Freshman': A97_Freshman.impl,
  'A98_StableArchitect': A98_StableArchitect.impl,
  'A99_FellowGrazer': A99_FellowGrazer.impl,
  'B1_UpscaleLifestyle': B1_UpscaleLifestyle.impl,
  'B10_Caravan': B10_Caravan.impl,
  'B100_Clutterer': B100_Clutterer.impl,
  'B101_FurnitureCarpenter': B101_FurnitureCarpenter.impl,
  'B102_Consultant': B102_Consultant.impl,
  'B103_FieldMerchant': B103_FieldMerchant.impl,
  'B104_SheepWalker': B104_SheepWalker.impl,
  'B105_CaseBuilder': B105_CaseBuilder.impl,
  'B106_MoralCrusader': B106_MoralCrusader.impl,
  'B107_Manservant': B107_Manservant.impl,
  'B108_OvenFiringBoy': B108_OvenFiringBoy.impl,
  'B109_PaperMaker': B109_PaperMaker.impl,
  'B11_Feedyard': B11_Feedyard.impl,
  'B110_Pavior': B110_Pavior.impl,
  'B111_Rustic': B111_Rustic.impl,
  'B112_Silokeeper': B112_Silokeeper.impl,
  'B113_PatchCaregiver': B113_PatchCaregiver.impl,
  'B114_Childless': B114_Childless.impl,
  'B115_TinsmithMaster': B115_TinsmithMaster.impl,
  'B116_Shoreforester': B116_Shoreforester.impl,
  'B117_Informant': B117_Informant.impl,
  'B118_SmallscaleFarmer': B118_SmallscaleFarmer.impl,
  'B119_Lumberjack': B119_Lumberjack.impl,
  'B12_Stockyard': B12_Stockyard.impl,
  'B120_Sweep': B120_Sweep.impl,
  'B121_Geologist': B121_Geologist.impl,
  'B122_Mineralogist': B122_Mineralogist.impl,
  'B123_RoofBallaster': B123_RoofBallaster.impl,
  'B124_Trimmer': B124_Trimmer.impl,
  'B125_EstateWorker': B125_EstateWorker.impl,
  'B126_Carpenter': B126_Carpenter.impl,
  'B127_Seducer': B127_Seducer.impl,
  'B128_Plumber': B128_Plumber.impl,
  'B129_Seatmate': B129_Seatmate.impl,
  'B13_CarpentersParlor': B13_CarpentersParlor.impl,
  'B130_FullPeasant': B130_FullPeasant.impl,
  'B131_Equipper': B131_Equipper.impl,
  'B132_EstateMaster': B132_EstateMaster.impl,
  'B133_VillagePeasant': B133_VillagePeasant.impl,
  'B134_HousebookMaster': B134_HousebookMaster.impl,
  'B135_NutritionExpert': B135_NutritionExpert.impl,
  'B136_HouseSteward': B136_HouseSteward.impl,
  'B137_Wholesaler': B137_Wholesaler.impl,
  'B138_ForestGuardian': B138_ForestGuardian.impl,
  'B139_ForestScientist': B139_ForestScientist.impl,
  'B14_Hawktower': B14_Hawktower.impl,
  'B140_FarmyardWorker': B140_FarmyardWorker.impl,
  'B141_FieldCaretaker': B141_FieldCaretaker.impl,
  'B142_Greengrocer': B142_Greengrocer.impl,
  'B143_ClayWarden': B143_ClayWarden.impl,
  'B144_Collier': B144_Collier.impl,
  'B145_BrushwoodCollector': B145_BrushwoodCollector.impl,
  'B146_Illusionist': B146_Illusionist.impl,
  'B147_Huntsman': B147_Huntsman.impl,
  'B148_PetBroker': B148_PetBroker.impl,
  'B149_OpenAirFarmer': B149_OpenAirFarmer.impl,
  'B15_CarpentersBench': B15_CarpentersBench.impl,
  'B150_LargeScaleFarmer': B150_LargeScaleFarmer.impl,
  'B151_LittlePeasant': B151_LittlePeasant.impl,
  'B152_JuniorArtist': B152_JuniorArtist.impl,
  'B153_Housemaster': B153_Housemaster.impl,
  'B154_SheepKeeper': B154_SheepKeeper.impl,
  'B155_ArtTeacher': B155_ArtTeacher.impl,
  'B156_StorehouseKeeper': B156_StorehouseKeeper.impl,
  'B157_Salter': B157_Salter.impl,
  'B158_DistrictManager': B158_DistrictManager.impl,
  'B159_LieutenantGeneral': B159_LieutenantGeneral.impl,
  'B16_MiningHammer': B16_MiningHammer.impl,
  'B160_PubOwner': B160_PubOwner.impl,
  'B161_Weakling': B161_Weakling.impl,
  'B162_ForestClearer': B162_ForestClearer.impl,
  'B163_Pastor': B163_Pastor.impl,
  'B164_SheepWhisperer': B164_SheepWhisperer.impl,
  'B165_GameProvider': B165_GameProvider.impl,
  'B166_CattleFeeder': B166_CattleFeeder.impl,
  'B167_StableSergeant': B167_StableSergeant.impl,
  'B168_PastureMaster': B168_PastureMaster.impl,
  'B17_ForestPlow': B17_ForestPlow.impl,
  'B18_GrasslandHarrow': B18_GrasslandHarrow.impl,
  'B19_MoldboardPlow': B19_MoldboardPlow.impl,
  'B2_MiniPasture': B2_MiniPasture.impl,
  'B20_ChainFloat': B20_ChainFloat.impl,
  'B21_HayloftBarn': B21_HayloftBarn.impl,
  'B22_WalkingBoots': B22_WalkingBoots.impl,
  'B23_FinalScenario': B23_FinalScenario.impl,
  'B24_Lasso': B24_Lasso.impl,
  'B25_BreadPaddle': B25_BreadPaddle.impl,
  'B26_AgrarianFences': B26_AgrarianFences.impl,
  'B27_Toolbox': B27_Toolbox.impl,
  'B28_ForestryStudies': B28_ForestryStudies.impl,
  'B29_CookeryLesson': B29_CookeryLesson.impl,
  'B3_Moonshine': B3_Moonshine.impl,
  'B30_WoodPalisades': B30_WoodPalisades.impl,
  'B31_PotteryYard': B31_PotteryYard.impl,
  'B32_Kettle': B32_Kettle.impl,
  'B33_Mantlepiece': B33_Mantlepiece.impl,
  'B34_SpecialFood': B34_SpecialFood.impl,
  'B35_HookKnife': B35_HookKnife.impl,
  'B36_Bottles': B36_Bottles.impl,
  'B37_Grange': B37_Grange.impl,
  'B38_FutureBuildingSite': B38_FutureBuildingSite.impl,
  'B39_Loom': B39_Loom.impl,
  'B4_WoodPile': B4_WoodPile.impl,
  'B40_BreweryPond': B40_BreweryPond.impl,
  'B41_Hauberg': B41_Hauberg.impl,
  'B42_ForestInn': B42_ForestInn.impl,
  'B43_Chophouse': B43_Chophouse.impl,
  'B44_ChickStable': B44_ChickStable.impl,
  'B45_StrawberryPatch': B45_StrawberryPatch.impl,
  'B46_ClubHouse': B46_ClubHouse.impl,
  'B47_HerringPot': B47_HerringPot.impl,
  'B48_ForestStone': B48_ForestStone.impl,
  'B49_Scales': B49_Scales.impl,
  'B5_StoreofExperience': B5_StoreofExperience.impl,
  'B50_ButterChurn': B50_ButterChurn.impl,
  'B51_DiggingSpade': B51_DiggingSpade.impl,
  'B52_GrowingFarm': B52_GrowingFarm.impl,
  'B53_SculptureCourse': B53_SculptureCourse.impl,
  'B54_Tumbrel': B54_Tumbrel.impl,
  'B55_MaintenancePremium': B55_MaintenancePremium.impl,
  'B56_Brook': B56_Brook.impl,
  'B57_Scullery': B57_Scullery.impl,
  'B58_CrackWeeder': B58_CrackWeeder.impl,
  'B59_FoodChest': B59_FoodChest.impl,
  'B6_ExcursiontotheQuarry': B6_ExcursiontotheQuarry.impl,
  'B60_BrewingWater': B60_BrewingWater.impl,
  'B61_ThreeFieldRotation': B61_ThreeFieldRotation.impl,
  'B62_Pitchfork': B62_Pitchfork.impl,
  'B63_Tasting': B63_Tasting.impl,
  'B64_MillWheel': B64_MillWheel.impl,
  'B65_GrainDepot': B65_GrainDepot.impl,
  'B66_SackCart': B66_SackCart.impl,
  'B67_HandTruck': B67_HandTruck.impl,
  'B68_Beanfield': B68_Beanfield.impl,
  'B69_PottersMarket': B69_PottersMarket.impl,
  'B7_Wage': B7_Wage.impl,
  'B70_NewPurchase': B70_NewPurchase.impl,
  'B71_HarvestHouse': B71_HarvestHouse.impl,
  'B72_LoveforAgriculture': B72_LoveforAgriculture.impl,
  'B73_GiftBasket': B73_GiftBasket.impl,
  'B74_ThickForest': B74_ThickForest.impl,
  'B75_WoodWorkshop': B75_WoodWorkshop.impl,
  'B76_Ceilings': B76_Ceilings.impl,
  'B77_LoamPit': B77_LoamPit.impl,
  'B78_ReedBelt': B78_ReedBelt.impl,
  'B79_Corf': B79_Corf.impl,
  'B8_MarketStall': B8_MarketStall.impl,
  'B81_Handcart': B81_Handcart.impl,
  'B82_ValueAssets': B82_ValueAssets.impl,
  'B83_MuddyPuddles': B83_MuddyPuddles.impl,
  'B84_AcornsBasket': B84_AcornsBasket.impl,
  'B85_FarmHand': B85_FarmHand.impl,
  'B86_TruffleSearcher': B86_TruffleSearcher.impl,
  'B87_Cottager': B87_Cottager.impl,
  'B88_EstablishedPerson': B88_EstablishedPerson.impl,
  'B89_Groom': B89_Groom.impl,
  'B9_BeatingRod': B9_BeatingRod.impl,
  'B90_CooperativePlower': B90_CooperativePlower.impl,
  'B91_AssistantTiller': B91_AssistantTiller.impl,
  'B92_LittleStickKnitter': B92_LittleStickKnitter.impl,
  'B93_Confidant': B93_Confidant.impl,
  'B94_StockProtector': B94_StockProtector.impl,
  'B95_MasterBricklayer': B95_MasterBricklayer.impl,
  'B96_TreeFarmJoiner': B96_TreeFarmJoiner.impl,
  'B97_Scholar': B97_Scholar.impl,
  'B98_OrganicFarmer': B98_OrganicFarmer.impl,
  'B99_Tutor': B99_Tutor.impl,
  'C1_Overhaul': C1_Overhaul.impl,
  'C10_BunkBeds': C10_BunkBeds.impl,
  'C100_Butler': C100_Butler.impl,
  'C101_StallHolder': C101_StallHolder.impl,
  'C102_TreeGuard': C102_TreeGuard.impl,
  'C103_GreenGrocer': C103_GreenGrocer.impl,
  'C104_Collector': C104_Collector.impl,
  'C106_PotatoHarvester': C106_PotatoHarvester.impl,
  'C107_Baker': C107_Baker.impl,
  'C108_Layabout': C108_Layabout.impl,
  'C11_WildlifeReserve': C11_WildlifeReserve.impl,
  'C110_HomeBrewer': C110_HomeBrewer.impl,
  'C111_SmallAnimalBreeder': C111_SmallAnimalBreeder.impl,
  'C112_Thresher': C112_Thresher.impl,
  'C113_WinterCaretaker': C113_WinterCaretaker.impl,
  'C114_SoilScientist': C114_SoilScientist.impl,
  'C115_Sower': C115_Sower.impl,
  'C116_FurnitureMaker': C116_FurnitureMaker.impl,
  'C117_Legworker': C117_Legworker.impl,
  'C118_WoodCollector': C118_WoodCollector.impl,
  'C119_SkillfulRenovator': C119_SkillfulRenovator.impl,
  'C12_CattleFarm': C12_CattleFarm.impl,
  'C120_AgriculturalLabourer': C120_AgriculturalLabourer.impl,
  'C121_ClayKneader': C121_ClayKneader.impl,
  'C122_Bricklayer': C122_Bricklayer.impl,
  'C123_Freemason': C123_Freemason.impl,
  'C124_StoneImporter': C124_StoneImporter.impl,
  'C125_Nightworker': C125_Nightworker.impl,
  'C126_Excavator': C126_Excavator.impl,
  'C127_Lover': C127_Lover.impl,
  'C128_WoodenHutExtender': C128_WoodenHutExtender.impl,
  'C129_SecondSpouse': C129_SecondSpouse.impl,
  'C13_WoodSlideHammer': C13_WoodSlideHammer.impl,
  'C130_OutskirtsDirector': C130_OutskirtsDirector.impl,
  'C131_PrivateTeacher': C131_PrivateTeacher.impl,
  'C132_TimberShingleMaker': C132_TimberShingleMaker.impl,
  'C133_Soldier': C133_Soldier.impl,
  'C134_CowPrince': C134_CowPrince.impl,
  'C135_Constable': C135_Constable.impl,
  'C136_RanchProvost': C136_RanchProvost.impl,
  'C137_CharcoalBurner': C137_CharcoalBurner.impl,
  'C138_AnimalFeeder': C138_AnimalFeeder.impl,
  'C139_BasketmakersWife': C139_BasketmakersWife.impl,
  'C14_StrawThatchedRoof': C14_StrawThatchedRoof.impl,
  'C140_PackagingArtist': C140_PackagingArtist.impl,
  'C141_SheepProvider': C141_SheepProvider.impl,
  'C142_MarketCrier': C142_MarketCrier.impl,
  'C143_StoneBuyer': C143_StoneBuyer.impl,
  'C144_ReedRoofRenovator': C144_ReedRoofRenovator.impl,
  'C145_ForestReviewer': C145_ForestReviewer.impl,
  'C146_WorkshopAssistant': C146_WorkshopAssistant.impl,
  'C147_Cowherd': C147_Cowherd.impl,
  'C148_MudWallower': C148_MudWallower.impl,
  'C149_ResourceRecycler': C149_ResourceRecycler.impl,
  'C15_Trellis': C15_Trellis.impl,
  'C150_ParrotBreeder': C150_ParrotBreeder.impl,
  'C151_SowingDirector': C151_SowingDirector.impl,
  'C152_Puppeteer': C152_Puppeteer.impl,
  'C153_PatternMaker': C153_PatternMaker.impl,
  'C154_TwinResearcher': C154_TwinResearcher.impl,
  'C155_FoodDistributor': C155_FoodDistributor.impl,
  'C156_HoofCaregiver': C156_HoofCaregiver.impl,
  'C157_ResourceAnalyzer': C157_ResourceAnalyzer.impl,
  'C158_ForestCampaigner': C158_ForestCampaigner.impl,
  'C159_FishermansFriend': C159_FishermansFriend.impl,
  'C16_FieldFences': C16_FieldFences.impl,
  'C160_Outrider': C160_Outrider.impl,
  'C161_PotatoDigger': C161_PotatoDigger.impl,
  'C162_ForestOwner': C162_ForestOwner.impl,
  'C163_MaterialDeliveryman': C163_MaterialDeliveryman.impl,
  'C164_GermanHeathKeeper': C164_GermanHeathKeeper.impl,
  'C165_GameCatcher': C165_GameCatcher.impl,
  'C166_CattleWhisperer': C166_CattleWhisperer.impl,
  'C167_CattleBuyer': C167_CattleBuyer.impl,
  'C168_AnimalCatcher': C168_AnimalCatcher.impl,
  'C17_NewlyPlowedField': C17_NewlyPlowedField.impl,
  'C178_OnSiteReverend': C178_OnSiteReverend.impl,
  'C18_RollOverPlow': C18_RollOverPlow.impl,
  'C19_SwingPlow': C19_SwingPlow.impl,
  'C2_Stable': C2_Stable.impl,
  'C20_MolePlow': C20_MolePlow.impl,
  'C21_HeartofStone': C21_HeartofStone.impl,
  'C22_BasketChair': C22_BasketChair.impl,
  'C23_JobContract': C23_JobContract.impl,
  'C24_BedintheGrainField': C24_BedintheGrainField.impl,
  'C25_SteamMachine': C25_SteamMachine.impl,
  'C26_Flail': C26_Flail.impl,
  'C27_Blueprint': C27_Blueprint.impl,
  'C28_TeachersDesk': C28_TeachersDesk.impl,
  'C29_BeerTable': C29_BeerTable.impl,
  'C3_CarriageTrip': C3_CarriageTrip.impl,
  'C30_HalfTimberedHouse': C30_HalfTimberedHouse.impl,
  'C31_WritingChamber': C31_WritingChamber.impl,
  'C32_AbortOriel': C32_AbortOriel.impl,
  'C33_GreeningPlan': C33_GreeningPlan.impl,
  'C34_ElephantgrassPlant': C34_ElephantgrassPlant.impl,
  'C35_LanternHouse': C35_LanternHouse.impl,
  'C36_ClayDeposit': C36_ClayDeposit.impl,
  'C37_DwellingMound': C37_DwellingMound.impl,
  'C38_Christianity': C38_Christianity.impl,
  'C39_StudioBoat': C39_StudioBoat.impl,
  'C4_WritingBoards': C4_WritingBoards.impl,
  'C40_CanvasSack': C40_CanvasSack.impl,
  'C41_FarmStore': C41_FarmStore.impl,
  'C42_RavenousHunger': C42_RavenousHunger.impl,
  'C43_FarmBuilding': C43_FarmBuilding.impl,
  'C44_ChickenCoop': C44_ChickenCoop.impl,
  'C45_Stew': C45_Stew.impl,
  'C46_Mandoline': C46_Mandoline.impl,
  'C47_GardenClaw': C47_GardenClaw.impl,
  'C48_Farmstead': C48_Farmstead.impl,
  'C49_BeerStall': C49_BeerStall.impl,
  'C5_Remodeling': C5_Remodeling.impl,
  'C50_StableYard': C50_StableYard.impl,
  'C51_FishingNet': C51_FishingNet.impl,
  'C52_HuntsmansHat': C52_HuntsmansHat.impl,
  'C53_GypsysCrock': C53_GypsysCrock.impl,
  'C54_MarketBooth': C54_MarketBooth.impl,
  'C55_Studio': C55_Studio.impl,
  'C56_FeedFence': C56_FeedFence.impl,
  'C57_Crudite': C57_Crudite.impl,
  'C58_Woodcraft': C58_Woodcraft.impl,
  'C59_SchnappsDistillery': C59_SchnappsDistillery.impl,
  'C6_StoneClearing': C6_StoneClearing.impl,
  'C60_SmallPottersOven': C60_SmallPottersOven.impl,
  'C61_BeerStein': C61_BeerStein.impl,
  'C62_CookeryExtension': C62_CookeryExtension.impl,
  'C63_CraftBrewery': C63_CraftBrewery.impl,
  'C64_CornSchnappsDistillery': C64_CornSchnappsDistillery.impl,
  'C65_Granary': C65_Granary.impl,
  'C66_EternalRyeCultivation': C66_EternalRyeCultivation.impl,
  'C67_MineralFeeder': C67_MineralFeeder.impl,
  'C68_Bookcase': C68_Bookcase.impl,
  'C69_LandConsolidation': C69_LandConsolidation.impl,
  'C7_BladeShears': C7_BladeShears.impl,
  'C70_LettucePatch': C70_LettucePatch.impl,
  'C71_Slurry': C71_Slurry.impl,
  'C72_FestivalPlanning': C72_FestivalPlanning.impl,
  'C73_SeaweedFertilizer': C73_SeaweedFertilizer.impl,
  'C74_PrivateForest': C74_PrivateForest.impl,
  'C75_Firewood': C75_Firewood.impl,
  'C76_WoodCart': C76_WoodCart.impl,
  'C77_ClaySupply': C77_ClaySupply.impl,
  'C78_ReedHattedToad': C78_ReedHattedToad.impl,
  'C79_StoneCart': C79_StoneCart.impl,
  'C8_PlantFertilizer': C8_PlantFertilizer.impl,
  'C80_RockyTerrain': C80_RockyTerrain.impl,
  'C81_MaterialHub': C81_MaterialHub.impl,
  'C82_HardwareStore': C82_HardwareStore.impl,
  'C83_EarlyCattle': C83_EarlyCattle.impl,
  'C84_PerennialRye': C84_PerennialRye.impl,
  'C85_DenBuilder': C85_DenBuilder.impl,
  'C86_LivestockFeeder': C86_LivestockFeeder.impl,
  'C87_Mason': C87_Mason.impl,
  'C88_CarpentersApprentice': C88_CarpentersApprentice.impl,
  'C89_StableMaster': C89_StableMaster.impl,
  'C9_AutomaticWaterTrough': C9_AutomaticWaterTrough.impl,
  'C90_FieldWatchman': C90_FieldWatchman.impl,
  'C91_PlowHero': C91_PlowHero.impl,
  'C92_AutumnMother': C92_AutumnMother.impl,
  'C93_InnerDistrictsDirector': C93_InnerDistrictsDirector.impl,
  'C94_StableCleaner': C94_StableCleaner.impl,
  'C95_BasketWeaver': C95_BasketWeaver.impl,
  'C96_Merchant': C96_Merchant.impl,
  'C97_SeedResearcher': C97_SeedResearcher.impl,
  'C98_CubeCutter': C98_CubeCutter.impl,
  'C99_GardenDesigner': C99_GardenDesigner.impl,
  'CUSTOM_FixtureHarvester': CUSTOM_FixtureHarvester.impl,
  'D1_ZigzagHarrow': D1_ZigzagHarrow.impl,
  'D10_StorksNest': D10_StorksNest.impl,
  'D100_LordoftheManor': D100_LordoftheManor.impl,
  'D101_SugarBaker': D101_SugarBaker.impl,
  'D102_SampleStableMaker': D102_SampleStableMaker.impl,
  'D103_CanalBoatman': D103_CanalBoatman.impl,
  'D104_Cultivator': D104_Cultivator.impl,
  'D105_Sculptor': D105_Sculptor.impl,
  'D106_WhiskyDistiller': D106_WhiskyDistiller.impl,
  'D107_Bellfounder': D107_Bellfounder.impl,
  'D109_SowingMaster': D109_SowingMaster.impl,
  'D11_LawnFertilizer': D11_LawnFertilizer.impl,
  'D110_FishFarmer': D110_FishFarmer.impl,
  'D111_InteriorDecorator': D111_InteriorDecorator.impl,
  'D112_YoungFarmer': D112_YoungFarmer.impl,
  'D113_FoodMerchant': D113_FoodMerchant.impl,
  'D114_SeedTrader': D114_SeedTrader.impl,
  'D115_FodderPlanter': D115_FodderPlanter.impl,
  'D116_TreeInspector': D116_TreeInspector.impl,
  'D117_WoodExpert': D117_WoodExpert.impl,
  'D118_Bonehead': D118_Bonehead.impl,
  'D119_WoodBarterer': D119_WoodBarterer.impl,
  'D12_MilkingPlace': D12_MilkingPlace.impl,
  'D120_ClayDeliveryman': D120_ClayDeliveryman.impl,
  'D121_ClayPlasterer': D121_ClayPlasterer.impl,
  'D122_ClayCarrier': D122_ClayCarrier.impl,
  'D123_RenovationPreparer': D123_RenovationPreparer.impl,
  'D124_Emissary': D124_Emissary.impl,
  'D125_ForestTrader': D125_ForestTrader.impl,
  'D126_FieldCultivator': D126_FieldCultivator.impl,
  'D127_HardworkingMan': D127_HardworkingMan.impl,
  'D128_BuildingTycoon': D128_BuildingTycoon.impl,
  'D129_LumberVirtuoso': D129_LumberVirtuoso.impl,
  'D13_Trowel': D13_Trowel.impl,
  'D130_RecreationalCarpenter': D130_RecreationalCarpenter.impl,
  'D131_CraftsmanshipPromoter': D131_CraftsmanshipPromoter.impl,
  'D132_HideFarmer': D132_HideFarmer.impl,
  'D133_BeerTentOperator': D133_BeerTentOperator.impl,
  'D134_OysterEater': D134_OysterEater.impl,
  'D135_GardeningHeadOfficial': D135_GardeningHeadOfficial.impl,
  'D136_AnimalActivist': D136_AnimalActivist.impl,
  'D137_TradeTeacher': D137_TradeTeacher.impl,
  'D138_PetLover': D138_PetLover.impl,
  'D139_Chairman': D139_Chairman.impl,
  'D14_HammerCrusher': D14_HammerCrusher.impl,
  'D140_Loudmouth': D140_Loudmouth.impl,
  'D141_SeedSeller': D141_SeedSeller.impl,
  'D142_PotatoPlanter': D142_PotatoPlanter.impl,
  'D143_TreeCutter': D143_TreeCutter.impl,
  'D144_WaterWorker': D144_WaterWorker.impl,
  'D145_RoofExaminer': D145_RoofExaminer.impl,
  'D146_Porter': D146_Porter.impl,
  'D147_TrapBuilder': D147_TrapBuilder.impl,
  'D148_DomesticianExpert': D148_DomesticianExpert.impl,
  'D149_CasualWorker': D149_CasualWorker.impl,
  'D15_ClaySupports': D15_ClaySupports.impl,
  'D150_GodlySpouse': D150_GodlySpouse.impl,
  'D151_SpinDoctor': D151_SpinDoctor.impl,
  'D152_Patron': D152_Patron.impl,
  'D153_WealthyMan': D153_WealthyMan.impl,
  'D154_ChimneySweep': D154_ChimneySweep.impl,
  'D156_RetailDealer': D156_RetailDealer.impl,
  'D157_PartyOrganizer': D157_PartyOrganizer.impl,
  'D158_BeanCounter': D158_BeanCounter.impl,
  'D16_WoodenWheyBucket': D16_WoodenWheyBucket.impl,
  'D160_Midwife': D160_Midwife.impl,
  'D161_CabbageBuyer': D161_CabbageBuyer.impl,
  'D162_ClayFirer': D162_ClayFirer.impl,
  'D163_JourneymanBricklayer': D163_JourneymanBricklayer.impl,
  'D164_PetGrower': D164_PetGrower.impl,
  'D165_PigStalker': D165_PigStalker.impl,
  'D166_StableMilker': D166_StableMilker.impl,
  'D167_PureBreeder': D167_PureBreeder.impl,
  'D168_Stockman': D168_Stockman.impl,
  'D17_DrillHarrow': D17_DrillHarrow.impl,
  'D177_Graduate': D177_Graduate.impl,
  'D18_SteamPlow': D18_SteamPlow.impl,
  'D19_PulverizerPlow': D19_PulverizerPlow.impl,
  'D2_DwellingPlan': D2_DwellingPlan.impl,
  'D20_TurnwrestPlow': D20_TurnwrestPlow.impl,
  'D21_Recruitment': D21_Recruitment.impl,
  'D22_WorkPermit': D22_WorkPermit.impl,
  'D23_PioneeringSpirit': D23_PioneeringSpirit.impl,
  'D24_BrotherlyLove': D24_BrotherlyLove.impl,
  'D25_WitchesDanceFloor': D25_WitchesDanceFloor.impl,
  'D26_CarpentersYard': D26_CarpentersYard.impl,
  'D27_Retraining': D27_Retraining.impl,
  'D28_WritingDesk': D28_WritingDesk.impl,
  'D29_MuckRake': D29_MuckRake.impl,
  'D3_Furrows': D3_Furrows.impl,
  'D30_ArtisanDistrict': D30_ArtisanDistrict.impl,
  'D31_Storeroom': D31_Storeroom.impl,
  'D32_WoodRake': D32_WoodRake.impl,
  'D33_SummerHouse': D33_SummerHouse.impl,
  'D34_LuxuriousHostel': D34_LuxuriousHostel.impl,
  'D35_FodderChamber': D35_FodderChamber.impl,
  'D36_BreedRegistry': D36_BreedRegistry.impl,
  'D37_Sculpture': D37_Sculpture.impl,
  'D38_MilkingStool': D38_MilkingStool.impl,
  'D39_TruffleSlicer': D39_TruffleSlicer.impl,
  'D4_CrossCutWood': D4_CrossCutWood.impl,
  'D40_Cesspit': D40_Cesspit.impl,
  'D41_HorseDrawnBoat': D41_HorseDrawnBoat.impl,
  'D42_EducationBonus': D42_EducationBonus.impl,
  'D43_Hutch': D43_Hutch.impl,
  'D44_ForestWell': D44_ForestWell.impl,
  'D45_SheepWell': D45_SheepWell.impl,
  'D46_PelletPress': D46_PelletPress.impl,
  'D47_Churchyard': D47_Churchyard.impl,
  'D48_CivicFacade': D48_CivicFacade.impl,
  'D49_Bookshelf': D49_Bookshelf.impl,
  'D5_FieldClay': D5_FieldClay.impl,
  'D50_ForeignAid': D50_ForeignAid.impl,
  'D51_Archway': D51_Archway.impl,
  'D52_RollingPin': D52_RollingPin.impl,
  'D53_TeaHouse': D53_TeaHouse.impl,
  'D54_TroutPool': D54_TroutPool.impl,
  'D55_NewMarket': D55_NewMarket.impl,
  'D56_FatstockStretcher': D56_FatstockStretcher.impl,
  'D57_WholesaleMarket': D57_WholesaleMarket.impl,
  'D58_Gritter': D58_Gritter.impl,
  'D6_PetrifiedWood': D6_PetrifiedWood.impl,
  'D60_LargePottery': D60_LargePottery.impl,
  'D61_BaleofStraw': D61_BaleofStraw.impl,
  'D62_BeerTap': D62_BeerTap.impl,
  'D63_Lynchet': D63_Lynchet.impl,
  'D64_BakingCourse': D64_BakingCourse.impl,
  'D65_GrainSieve': D65_GrainSieve.impl,
  'D66_PotterCeramics': D66_PotterCeramics.impl,
  'D67_ReapHook': D67_ReapHook.impl,
  'D68_SmallBasket': D68_SmallBasket.impl,
  'D69_SmallGreenhouse': D69_SmallGreenhouse.impl,
  'D7_Trident': D7_Trident.impl,
  'D70_StrawManure': D70_StrawManure.impl,
  'D71_Changeover': D71_Changeover.impl,
  'D72_StableManure': D72_StableManure.impl,
  'D73_SupplyBoat': D73_SupplyBoat.impl,
  'D74_RoyalWood': D74_RoyalWood.impl,
  'D75_WoodField': D75_WoodField.impl,
  'D76_SocialBenefits': D76_SocialBenefits.impl,
  'D77_RecycledBrick': D77_RecycledBrick.impl,
  'D78_ReedPond': D78_ReedPond.impl,
  'D79_CarrotMuseum': D79_CarrotMuseum.impl,
  'D8_FernSeeds': D8_FernSeeds.impl,
  'D80_BrickHammer': D80_BrickHammer.impl,
  'D81_RoofLadder': D81_RoofLadder.impl,
  'D82_HuntingTrophy': D82_HuntingTrophy.impl,
  'D83_Pigswill': D83_Pigswill.impl,
  'D84_FeedPellets': D84_FeedPellets.impl,
  'D85_Reader': D85_Reader.impl,
  'D86_SheepAgent': D86_SheepAgent.impl,
  'D87_MasterBuilder': D87_MasterBuilder.impl,
  'D88_Millwright': D88_Millwright.impl,
  'D89_Stablehand': D89_Stablehand.impl,
  'D9_GameTrade': D9_GameTrade.impl,
  'D90_PlowMaker': D90_PlowMaker.impl,
  'D91_Plowman': D91_Plowman.impl,
  'D92_ChildOmbudsman': D92_ChildOmbudsman.impl,
  'D93_SheepInspector': D93_SheepInspector.impl,
  'D94_HenpeckedHusband': D94_HenpeckedHusband.impl,
  'D95_SiteManager': D95_SiteManager.impl,
  'D96_Furnisher': D96_Furnisher.impl,
  'D97_BeggingStudent': D97_BeggingStudent.impl,
  'D98_Transactor': D98_Transactor.impl,
  'D99_EarthenwarePotter': D99_EarthenwarePotter.impl,
  'E1_PoleBarns': E1_PoleBarns.impl,
  'E10_StrawHat': E10_StrawHat.impl,
  'E100_MuseumCaretaker': E100_MuseumCaretaker.impl,
  'E101_Blighter': E101_Blighter.impl,
  'E102_Acquirer': E102_Acquirer.impl,
  'E103_Wolf': E103_Wolf.impl,
  'E104_SpiceTrader': E104_SpiceTrader.impl,
  'E105_Pioneer': E105_Pioneer.impl,
  'E106_EmergencySeller': E106_EmergencySeller.impl,
  'E107_LandSurveyor': E107_LandSurveyor.impl,
  'E108_BlackberryFarmer': E108_BlackberryFarmer.impl,
  'E109_BraidMaker': E109_BraidMaker.impl,
  'E11_PettingZoo': E11_PettingZoo.impl,
  'E110_Dentist': E110_Dentist.impl,
  'E111_Recluse': E111_Recluse.impl,
  'E112_GrainThief': E112_GrainThief.impl,
  'E113_Godmother': E113_Godmother.impl,
  'E114_ShedBuilder': E114_ShedBuilder.impl,
  'E115_SeedServant': E115_SeedServant.impl,
  'E116_FirCutter': E116_FirCutter.impl,
  'E117_PipeSmoker': E117_PipeSmoker.impl,
  'E118_KindlingGatherer': E118_KindlingGatherer.impl,
  'E119_LandHeir': E119_LandHeir.impl,
  'E12_AnimalBedding': E12_AnimalBedding.impl,
  'E120_ScrapCollector': E120_ScrapCollector.impl,
  'E121_HillCultivator': E121_HillCultivator.impl,
  'E122_Cottar': E122_Cottar.impl,
  'E123_ResourceHoarder': E123_ResourceHoarder.impl,
  'E124_MayorCandidate': E124_MayorCandidate.impl,
  'E125_DelayedWayfarer': E125_DelayedWayfarer.impl,
  'E126_TaxCollector': E126_TaxCollector.impl,
  'E127_DiligentFarmer': E127_DiligentFarmer.impl,
  'E128_Saddler': E128_Saddler.impl,
  'E129_Imitator': E129_Imitator.impl,
  'E13_StoneHouseReconstruction': E13_StoneHouseReconstruction.impl,
  'E130_Overachiever': E130_Overachiever.impl,
  'E131_MarketMaster': E131_MarketMaster.impl,
  'E132_VeggieLover': E132_VeggieLover.impl,
  'E133_ChampionBreeder': E133_ChampionBreeder.impl,
  'E134_Omnifarmer': E134_Omnifarmer.impl,
  'E135_Pickler': E135_Pickler.impl,
  'E136_AnimalHusbandryWorker': E136_AnimalHusbandryWorker.impl,
  'E137_FlaxFarmer': E137_FlaxFarmer.impl,
  'E138_LivestockExpert': E138_LivestockExpert.impl,
  'E139_BunnyBreeder': E139_BunnyBreeder.impl,
  'E14_WoodSaw': E14_WoodSaw.impl,
  'E140_Carter': E140_Carter.impl,
  'E141_VegetableVendor': E141_VegetableVendor.impl,
  'E142_Smuggler': E142_Smuggler.impl,
  'E143_Hewer': E143_Hewer.impl,
  'E144_WaresSalesman': E144_WaresSalesman.impl,
  'E145_Parvenu': E145_Parvenu.impl,
  'E146_Reseller': E146_Reseller.impl,
  'E147_AnimalDriver': E147_AnimalDriver.impl,
  'E148_Lazybones': E148_Lazybones.impl,
  'E149_MidnightFencer': E149_MidnightFencer.impl,
  'E15_NailBasket': E15_NailBasket.impl,
  'E150_RockBeater': E150_RockBeater.impl,
  'E151_DeliveryNurse': E151_DeliveryNurse.impl,
  'E152_BargainHunter': E152_BargainHunter.impl,
  'E153_StoneSculptor': E153_StoneSculptor.impl,
  'E154_Margrave': E154_Margrave.impl,
  'E155_Visionary': E155_Visionary.impl,
  'E156_ClaypitOwner': E156_ClaypitOwner.impl,
  'E157_Usufructuary': E157_Usufructuary.impl,
  'E158_StoneCustodian': E158_StoneCustodian.impl,
  'E159_OldMiser': E159_OldMiser.impl,
  'E16_BriarHedge': E16_BriarHedge.impl,
  'E160_KelpGatherer': E160_KelpGatherer.impl,
  'E161_ElderBaker': E161_ElderBaker.impl,
  'E162_Entrepreneur': E162_Entrepreneur.impl,
  'E163_Patroness': E163_Patroness.impl,
  'E164_MountainPlowman': E164_MountainPlowman.impl,
  'E165_MasterHuntsman': E165_MasterHuntsman.impl,
  'E166_Roastmaster': E166_Roastmaster.impl,
  'E167_DairyCrier': E167_DairyCrier.impl,
  'E168_AnimalTamersApprentice': E168_AnimalTamersApprentice.impl,
  'E17_SkimmerPlow': E17_SkimmerPlow.impl,
  'E18_SeedAlmanac': E18_SeedAlmanac.impl,
  'E19_OxGoad': E19_OxGoad.impl,
  'E2_RenovationMaterials': E2_RenovationMaterials.impl,
  'E20_IronHoe': E20_IronHoe.impl,
  'E21_SheepRug': E21_SheepRug.impl,
  'E22_GuestRoom': E22_GuestRoom.impl,
  'E23_Apiary': E23_Apiary.impl,
  'E24_Ambition': E24_Ambition.impl,
  'E25_BumperCrop': E25_BumperCrop.impl,
  'E26_Sundial': E26_Sundial.impl,
  'E27_PiggyBank': E27_PiggyBank.impl,
  'E28_Bookmark': E28_Bookmark.impl,
  'E29_Heirloom': E29_Heirloom.impl,
  'E3_TeaTime': E3_TeaTime.impl,
  'E30_ChildsToy': E30_ChildsToy.impl,
  'E31_Upholstery': E31_Upholstery.impl,
  'E32_Nave': E32_Nave.impl,
  'E33_BeaverColony': E33_BeaverColony.impl,
  'E34_LandRegister': E34_LandRegister.impl,
  'E35_Misanthropy': E35_Misanthropy.impl,
  'E36_HerbalGarden': E36_HerbalGarden.impl,
  'E37_OxSkull': E37_OxSkull.impl,
  'E38_RodCollection': E38_RodCollection.impl,
  'E39_Paintbrush': E39_Paintbrush.impl,
  'E4_Thunderbolt': E4_Thunderbolt.impl,
  'E40_BeeStatue': E40_BeeStatue.impl,
  'E41_MuddyWaters': E41_MuddyWaters.impl,
  'E42_WaterGully': E42_WaterGully.impl,
  'E43_BarnCats': E43_BarnCats.impl,
  'E44_FodderBeets': E44_FodderBeets.impl,
  'E45_FruitLadder': E45_FruitLadder.impl,
  'E46_WaterlilyPond': E46_WaterlilyPond.impl,
  'E47_SyrupTap': E47_SyrupTap.impl,
  'E48_TownHall': E48_TownHall.impl,
  'E49_Twibil': E49_Twibil.impl,
  'E5_NightLoot': E5_NightLoot.impl,
  'E50_WildGreens': E50_WildGreens.impl,
  'E51_WhaleOil': E51_WhaleOil.impl,
  'E52_Cubbyhole': E52_Cubbyhole.impl,
  'E53_BoarSpear': E53_BoarSpear.impl,
  'E54_Contraband': E54_Contraband.impl,
  'E55_StoneWeir': E55_StoneWeir.impl,
  'E56_RomanPot': E56_RomanPot.impl,
  'E57_CheeseFondue': E57_CheeseFondue.impl,
  'E58_LunchtimeBeer': E58_LunchtimeBeer.impl,
  'E59_CombandCutter': E59_CombandCutter.impl,
  'E6_Recount': E6_Recount.impl,
  'E60_WorkingGloves': E60_WorkingGloves.impl,
  'E61_RaisedBed': E61_RaisedBed.impl,
  'E62_SourDough': E62_SourDough.impl,
  'E63_IronOven': E63_IronOven.impl,
  'E64_SimpleOven': E64_SimpleOven.impl,
  'E65_Almsbag': E65_Almsbag.impl,
  'E66_BarnShed': E66_BarnShed.impl,
  'E67_GrainBag': E67_GrainBag.impl,
  'E68_CherryOrchard': E68_CherryOrchard.impl,
  'E69_MelonPatch': E69_MelonPatch.impl,
  'E7_Pumpernickel': E7_Pumpernickel.impl,
  'E70_CropRotationField': E70_CropRotationField.impl,
  'E71_CowPatty': E71_CowPatty.impl,
  'E72_ArtichokeField': E72_ArtichokeField.impl,
  'E73_Scythe': E73_Scythe.impl,
  'E74_AshTrees': E74_AshTrees.impl,
  'E75_StoneAxe': E75_StoneAxe.impl,
  'E76_LumberPile': E76_LumberPile.impl,
  'E77_Mattock': E77_Mattock.impl,
  'E78_SleightofHand': E78_SleightofHand.impl,
  'E79_FieldSpade': E79_FieldSpade.impl,
  'E8_FarmersMarket': E8_FarmersMarket.impl,
  'E80_RockGarden': E80_RockGarden.impl,
  'E81_AlchemistsLab': E81_AlchemistsLab.impl,
  'E82_Profiteering': E82_Profiteering.impl,
  'E83_ShepherdsWhistle': E83_ShepherdsWhistle.impl,
  'E84_DollysMother': E84_DollysMother.impl,
  'E85_MasterTanner': E85_MasterTanner.impl,
  'E86_PenBuilder': E86_PenBuilder.impl,
  'E87_MasterRenovator': E87_MasterRenovator.impl,
  'E88_MasterFencer': E88_MasterFencer.impl,
  'E89_Stallwright': E89_Stallwright.impl,
  'E9_BarteringHut': E9_BarteringHut.impl,
  'E90_DungCollector': E90_DungCollector.impl,
  'E91_PlowBuilder': E91_PlowBuilder.impl,
  'E92_FieldDoctor': E92_FieldDoctor.impl,
  'E93_Motivator': E93_Motivator.impl,
  'E94_Prophet': E94_Prophet.impl,
  'E95_Miller': E95_Miller.impl,
  'E96_Elder': E96_Elder.impl,
  'E97_Beneficiary': E97_Beneficiary.impl,
  'E98_Prodigy': E98_Prodigy.impl,
  'E99_UncaringParents': E99_UncaringParents.impl,
  'STUB_BeforeBakeGainClay': STUB_BeforeBakeGainClay.impl,
  'Major_ClayOven': Major_ClayOven.impl,
  'Major_StoneOven': Major_StoneOven.impl,
  'Major_Well': Major_Well.impl,
  'Major_Joinery': Major_Joinery.impl,
  'Major_Pottery': Major_Pottery.impl,
  'Major_Basket': Major_Basket.impl,
  'Major_Well2': Major_Well2.impl,
  'Major_ClayOven2': Major_ClayOven2.impl,
  'Major_StoneOven2': Major_StoneOven2.impl,
  'Major_Joinery2': Major_Joinery2.impl,
  'Major_Pottery2': Major_Pottery2.impl,
  'Major_Basket2': Major_Basket2.impl,
}

export type AllCardImpls = typeof ALL_CARD_IMPLS
