// GENERATED by scripts/generate-register-all.ts — do not edit by hand.
// Run `pnpm run generate:register-all` after adding or removing card _impl exports.
import type { CardImpl } from './registry'
// Load the catalog BEFORE pulling in card `_impl` modules. Catalog imports every
// card-definition file (e.g. `A93_BedMaker`) and builds global arrays at module
// scope; some card files (e.g. D117) circle back to catalog for helpers. If
// register-all is the first entry into this subgraph, the `_impl` imports below
// can reach catalog before its arrays are populated, surfacing undefined entries
// (pre-existing cycle). Importing catalog first forces the whole card-definition
// graph to finish initialising before we start harvesting `_impl` exports.
import './catalog'

import { A100_Curator_impl } from './A/A100_Curator'
import { A101_CookeryOutfitter_impl } from './A/A101_CookeryOutfitter'
import { A102_Grocer_impl } from './A/A102_Grocer'
import { A103_Portmonger_impl } from './A/A103_Portmonger'
import { A104_WoodHarvester_impl } from './A/A104_WoodHarvester'
import { A105_BarrowPusher_impl } from './A/A105_BarrowPusher'
import { A106_SlurrySpreader_impl } from './A/A106_SlurrySpreader'
import { A107_Catcher_impl } from './A/A107_Catcher'
import { A108_MushroomCollector_impl } from './A/A108_MushroomCollector'
import { A109_SmallTrader_impl } from './A/A109_SmallTrader'
import { A10_WoodenShed_impl } from './A/A10_WoodenShed'
import { A110_Roughcaster_impl } from './A/A110_Roughcaster'
import { A111_WallBuilder_impl } from './A/A111_WallBuilder'
import { A112_ScytheWorker_impl } from './A/A112_ScytheWorker'
import { A113_HeresyTeacher_impl } from './A/A113_HeresyTeacher'
import { A114_SeasonalWorker_impl } from './A/A114_SeasonalWorker'
import { A115_ChiefForester_impl } from './A/A115_ChiefForester'
import { A116_WoodCutter_impl } from './A/A116_WoodCutter'
import { A117_WoodCarrier_impl } from './A/A117_WoodCarrier'
import { A118_Treegardener_impl } from './A/A118_Treegardener'
import { A119_FirewoodCollector_impl } from './A/A119_FirewoodCollector'
import { A11_MudPatch_impl } from './A/A11_MudPatch'
import { A120_ClayHutBuilder_impl } from './A/A120_ClayHutBuilder'
import { A121_ClayPuncher_impl } from './A/A121_ClayPuncher'
import { A122_PanBaker_impl } from './A/A122_PanBaker'
import { A124_Knapper_impl } from './A/A124_Knapper'
import { A125_Priest_impl } from './A/A125_Priest'
import { A126_MasterWorkman_impl } from './A/A126_MasterWorkman'
import { A127_Lodger_impl } from './A/A127_Lodger'
import { A128_RiparianBuilder_impl } from './A/A128_RiparianBuilder'
import { A129_Swagman_impl } from './A/A129_Swagman'
import { A12_DrinkingTrough_impl } from './A/A12_DrinkingTrough'
import { A130_MummysBoy_impl } from './A/A130_MummysBoy'
import { A131_CraftTeacher_impl } from './A/A131_CraftTeacher'
import { A132_Publican_impl } from './A/A132_Publican'
import { A133_Braggart_impl } from './A/A133_Braggart'
import { A134_FullFarmer_impl } from './A/A134_FullFarmer'
import { A135_AnimalReeve_impl } from './A/A135_AnimalReeve'
import { A136_DrudgeryReeve_impl } from './A/A136_DrudgeryReeve'
import { A137_RiverineShepherd_impl } from './A/A137_RiverineShepherd'
import { A138_Harpooner_impl } from './A/A138_Harpooner'
import { A139_HollowWarden_impl } from './A/A139_HollowWarden'
import { A13_RenovationCompany_impl } from './A/A13_RenovationCompany'
import { A140_ShovelBearer_impl } from './A/A140_ShovelBearer'
import { A141_TurnipFarmer_impl } from './A/A141_TurnipFarmer'
import { A142_Cordmaker_impl } from './A/A142_Cordmaker'
import { A143_Stonecutter_impl } from './A/A143_Stonecutter'
import { A144_Sequestrator_impl } from './A/A144_Sequestrator'
import { A145_Ropemaker_impl } from './A/A145_Ropemaker'
import { A146_StorehouseSteward_impl } from './A/A146_StorehouseSteward'
import { A147_AnimalDealer_impl } from './A/A147_AnimalDealer'
import { A148_Woolgrower_impl } from './A/A148_Woolgrower'
import { A149_HouseArtist_impl } from './A/A149_HouseArtist'
import { A150_Stagehand_impl } from './A/A150_Stagehand'
import { A151_Minstrel_impl } from './A/A151_Minstrel'
import { A152_NightSchoolStudent_impl } from './A/A152_NightSchoolStudent'
import { A153_PigOwner_impl } from './A/A153_PigOwner'
import { A154_Paymaster_impl } from './A/A154_Paymaster'
import { A155_Conjurer_impl } from './A/A155_Conjurer'
import { A156_Buyer_impl } from './A/A156_Buyer'
import { A157_Bohemian_impl } from './A/A157_Bohemian'
import { A158_CulinaryArtist_impl } from './A/A158_CulinaryArtist'
import { A159_JoineroftheSea_impl } from './A/A159_JoineroftheSea'
import { A15_CarpentersAxe_impl } from './A/A15_CarpentersAxe'
import { A160_Lutenist_impl } from './A/A160_Lutenist'
import { A161_PatchCaretaker_impl } from './A/A161_PatchCaretaker'
import { A162_ForestTallyman_impl } from './A/A162_ForestTallyman'
import { A163_BuildingExpert_impl } from './A/A163_BuildingExpert'
import { A164_WoodWorker_impl } from './A/A164_WoodWorker'
import { A165_PigBreeder_impl } from './A/A165_PigBreeder'
import { A166_Haydryer_impl } from './A/A166_Haydryer'
import { A167_BreederBuyer_impl } from './A/A167_BreederBuyer'
import { A168_AnimalTeacher_impl } from './A/A168_AnimalTeacher'
import { A16_RammedClay_impl } from './A/A16_RammedClay'
import { A17_ReclamationPlow_impl } from './A/A17_ReclamationPlow'
import { A18_WheelPlow_impl } from './A/A18_WheelPlow'
import { A19_Handplow_impl } from './A/A19_Handplow'
import { A1_Shelter_impl } from './A/A1_Shelter'
import { A20_DoubleTurnPlow_impl } from './A/A20_DoubleTurnPlow'
import { A21_FamilyFriendHome_impl } from './A/A21_FamilyFriendHome'
import { A22_Telegram_impl } from './A/A22_Telegram'
import { A23_StoneCompany_impl } from './A/A23_StoneCompany'
import { A24_ThreshingBoard_impl } from './A/A24_ThreshingBoard'
import { A25_Bassinet_impl } from './A/A25_Bassinet'
import { A26_SleepingCorner_impl } from './A/A26_SleepingCorner'
import { A27_OvenSite_impl } from './A/A27_OvenSite'
import { A28_ForestSchool_impl } from './A/A28_ForestSchool'
import { A29_AleBenches_impl } from './A/A29_AleBenches'
import { A2_ShiftingCultivation_impl } from './A/A2_ShiftingCultivation'
import { A30_BakingSheet_impl } from './A/A30_BakingSheet'
import { A31_DebtSecurity_impl } from './A/A31_DebtSecurity'
import { A32_Manger_impl } from './A/A32_Manger'
import { A33_BigCountry_impl } from './A/A33_BigCountry'
import { A34_Loppers_impl } from './A/A34_Loppers'
import { A35_SwimmingClass_impl } from './A/A35_SwimmingClass'
import { A36_FacadesCarving_impl } from './A/A36_FacadesCarving'
import { A37_Bucksaw_impl } from './A/A37_Bucksaw'
import { A38_WoolBlankets_impl } from './A/A38_WoolBlankets'
import { A39_Chapel_impl } from './A/A39_Chapel'
import { A3_PaperKnife_impl } from './A/A3_PaperKnife'
import { A40_PottersYard_impl } from './A/A40_PottersYard'
import { A41_VegetableSlicer_impl } from './A/A41_VegetableSlicer'
import { A42_ForestLakeHut_impl } from './A/A42_ForestLakeHut'
import { A43_FarmyardManure_impl } from './A/A43_FarmyardManure'
import { A44_PondHut_impl } from './A/A44_PondHut'
import { A45_FireProtectionPond_impl } from './A/A45_FireProtectionPond'
import { A46_ClawKnife_impl } from './A/A46_ClawKnife'
import { A47_Trellises_impl } from './A/A47_Trellises'
import { A48_ShavingHorse_impl } from './A/A48_ShavingHorse'
import { A49_NestSite_impl } from './A/A49_NestSite'
import { A4_Baseboards_impl } from './A/A4_Baseboards'
import { A50_MilkJug_impl } from './A/A50_MilkJug'
import { A51_DriftNetBoat_impl } from './A/A51_DriftNetBoat'
import { A52_ThrowingAxe_impl } from './A/A52_ThrowingAxe'
import { A53_Claypipe_impl } from './A/A53_Claypipe'
import { A54_Credit_impl } from './A/A54_Credit'
import { A55_JunkRoom_impl } from './A/A55_JunkRoom'
import { A56_Basket_impl } from './A/A56_Basket'
import { A57_MilkingParlor_impl } from './A/A57_MilkingParlor'
import { A58_AsparagusKnife_impl } from './A/A58_AsparagusKnife'
import { A59_PotatoRidger_impl } from './A/A59_PotatoRidger'
import { A5_ClayEmbankment_impl } from './A/A5_ClayEmbankment'
import { A61_WinnowingFan_impl } from './A/A61_WinnowingFan'
import { A62_BeerKeg_impl } from './A/A62_BeerKeg'
import { A63_DutchWindmill_impl } from './A/A63_DutchWindmill'
import { A64_BarleyMill_impl } from './A/A64_BarleyMill'
import { A65_SeedPellets_impl } from './A/A65_SeedPellets'
import { A66_FeedingDish_impl } from './A/A66_FeedingDish'
import { A67_CornScoop_impl } from './A/A67_CornScoop'
import { A68_AsparagusGift_impl } from './A/A68_AsparagusGift'
import { A69_LargeGreenhouse_impl } from './A/A69_LargeGreenhouse'
import { A6_StorageBarn_impl } from './A/A6_StorageBarn'
import { A70_LiftingMachine_impl } from './A/A70_LiftingMachine'
import { A71_ClearingSpade_impl } from './A/A71_ClearingSpade'
import { A72_CalciumFertilizers_impl } from './A/A72_CalciumFertilizers'
import { A73_AgriculturalFertilizers_impl } from './A/A73_AgriculturalFertilizers'
import { A74_StableTree_impl } from './A/A74_StableTree'
import { A75_LumberMill_impl } from './A/A75_LumberMill'
import { A76_Cob_impl } from './A/A76_Cob'
import { A77_Hod_impl } from './A/A77_Hod'
import { A78_Canoe_impl } from './A/A78_Canoe'
import { A79_GardenHoe_impl } from './A/A79_GardenHoe'
import { A7_GardenersKnife_impl } from './A/A7_GardenersKnife'
import { A80_StoneTongs_impl } from './A/A80_StoneTongs'
import { A81_InterimStorage_impl } from './A/A81_InterimStorage'
import { A82_WorkCertificate_impl } from './A/A82_WorkCertificate'
import { A83_ShepherdsCrook_impl } from './A/A83_ShepherdsCrook'
import { A84_Silage_impl } from './A/A84_Silage'
import { A85_Homekeeper_impl } from './A/A85_Homekeeper'
import { A86_AnimalTamer_impl } from './A/A86_AnimalTamer'
import { A87_Conservator_impl } from './A/A87_Conservator'
import { A89_StablePlanner_impl } from './A/A89_StablePlanner'
import { A8_FoodBasket_impl } from './A/A8_FoodBasket'
import { A90_PlowDriver_impl } from './A/A90_PlowDriver'
import { A91_ShiftingCultivator_impl } from './A/A91_ShiftingCultivator'
import { A92_AdoptiveParents_impl } from './A/A92_AdoptiveParents'
import { A93_BedMaker_impl } from './A/A93_BedMaker'
import { A94_LazySowman_impl } from './A/A94_LazySowman'
import { A95_Angler_impl } from './A/A95_Angler'
import { A96_TaskArtisan_impl } from './A/A96_TaskArtisan'
import { A97_Freshman_impl } from './A/A97_Freshman'
import { A98_StableArchitect_impl } from './A/A98_StableArchitect'
import { A99_FellowGrazer_impl } from './A/A99_FellowGrazer'
import { A9_YoungAnimalMarket_impl } from './A/A9_YoungAnimalMarket'
import { B100_Clutterer_impl } from './B/B100_Clutterer'
import { B101_FurnitureCarpenter_impl } from './B/B101_FurnitureCarpenter'
import { B102_Consultant_impl } from './B/B102_Consultant'
import { B103_FieldMerchant_impl } from './B/B103_FieldMerchant'
import { B105_CaseBuilder_impl } from './B/B105_CaseBuilder'
import { B106_MoralCrusader_impl } from './B/B106_MoralCrusader'
import { B107_Manservant_impl } from './B/B107_Manservant'
import { B108_OvenFiringBoy_impl } from './B/B108_OvenFiringBoy'
import { B109_PaperMaker_impl } from './B/B109_PaperMaker'
import { B110_Pavior_impl } from './B/B110_Pavior'
import { B111_Rustic_impl } from './B/B111_Rustic'
import { B112_Silokeeper_impl } from './B/B112_Silokeeper'
import { B113_PatchCaregiver_impl } from './B/B113_PatchCaregiver'
import { B114_Childless_impl } from './B/B114_Childless'
import { B115_TinsmithMaster_impl } from './B/B115_TinsmithMaster'
import { B116_Shoreforester_impl } from './B/B116_Shoreforester'
import { B117_Informant_impl } from './B/B117_Informant'
import { B118_SmallscaleFarmer_impl } from './B/B118_SmallscaleFarmer'
import { B119_Lumberjack_impl } from './B/B119_Lumberjack'
import { B11_Feedyard_impl } from './B/B11_Feedyard'
import { B120_Sweep_impl } from './B/B120_Sweep'
import { B121_Geologist_impl } from './B/B121_Geologist'
import { B122_Mineralogist_impl } from './B/B122_Mineralogist'
import { B123_RoofBallaster_impl } from './B/B123_RoofBallaster'
import { B124_Trimmer_impl } from './B/B124_Trimmer'
import { B125_EstateWorker_impl } from './B/B125_EstateWorker'
import { B126_Carpenter_impl } from './B/B126_Carpenter'
import { B127_Seducer_impl } from './B/B127_Seducer'
import { B128_Plumber_impl } from './B/B128_Plumber'
import { B129_Seatmate_impl } from './B/B129_Seatmate'
import { B12_Stockyard_impl } from './B/B12_Stockyard'
import { B130_FullPeasant_impl } from './B/B130_FullPeasant'
import { B131_Equipper_impl } from './B/B131_Equipper'
import { B132_EstateMaster_impl } from './B/B132_EstateMaster'
import { B133_VillagePeasant_impl } from './B/B133_VillagePeasant'
import { B134_HousebookMaster_impl } from './B/B134_HousebookMaster'
import { B135_NutritionExpert_impl } from './B/B135_NutritionExpert'
import { B136_HouseSteward_impl } from './B/B136_HouseSteward'
import { B137_Wholesaler_impl } from './B/B137_Wholesaler'
import { B138_ForestGuardian_impl } from './B/B138_ForestGuardian'
import { B139_ForestScientist_impl } from './B/B139_ForestScientist'
import { B13_CarpentersParlor_impl } from './B/B13_CarpentersParlor'
import { B140_FarmyardWorker_impl } from './B/B140_FarmyardWorker'
import { B141_FieldCaretaker_impl } from './B/B141_FieldCaretaker'
import { B142_Greengrocer_impl } from './B/B142_Greengrocer'
import { B143_ClayWarden_impl } from './B/B143_ClayWarden'
import { B144_Collier_impl } from './B/B144_Collier'
import { B146_Illusionist_impl } from './B/B146_Illusionist'
import { B147_Huntsman_impl } from './B/B147_Huntsman'
import { B148_PetBroker_impl } from './B/B148_PetBroker'
import { B149_OpenAirFarmer_impl } from './B/B149_OpenAirFarmer'
import { B14_Hawktower_impl } from './B/B14_Hawktower'
import { B150_LargeScaleFarmer_impl } from './B/B150_LargeScaleFarmer'
import { B151_LittlePeasant_impl } from './B/B151_LittlePeasant'
import { B152_JuniorArtist_impl } from './B/B152_JuniorArtist'
import { B153_Housemaster_impl } from './B/B153_Housemaster'
import { B154_SheepKeeper_impl } from './B/B154_SheepKeeper'
import { B155_ArtTeacher_impl } from './B/B155_ArtTeacher'
import { B156_StorehouseKeeper_impl } from './B/B156_StorehouseKeeper'
import { B157_Salter_impl } from './B/B157_Salter'
import { B158_DistrictManager_impl } from './B/B158_DistrictManager'
import { B159_LieutenantGeneral_impl } from './B/B159_LieutenantGeneral'
import { B15_CarpentersBench_impl } from './B/B15_CarpentersBench'
import { B160_PubOwner_impl } from './B/B160_PubOwner'
import { B161_Weakling_impl } from './B/B161_Weakling'
import { B162_ForestClearer_impl } from './B/B162_ForestClearer'
import { B163_Pastor_impl } from './B/B163_Pastor'
import { B164_SheepWhisperer_impl } from './B/B164_SheepWhisperer'
import { B165_GameProvider_impl } from './B/B165_GameProvider'
import { B166_CattleFeeder_impl } from './B/B166_CattleFeeder'
import { B167_StableSergeant_impl } from './B/B167_StableSergeant'
import { B168_PastureMaster_impl } from './B/B168_PastureMaster'
import { B16_MiningHammer_impl } from './B/B16_MiningHammer'
import { B17_ForestPlow_impl } from './B/B17_ForestPlow'
import { B18_GrasslandHarrow_impl } from './B/B18_GrasslandHarrow'
import { B19_MoldboardPlow_impl } from './B/B19_MoldboardPlow'
import { B1_UpscaleLifestyle_impl } from './B/B1_UpscaleLifestyle'
import { B20_ChainFloat_impl } from './B/B20_ChainFloat'
import { B21_HayloftBarn_impl } from './B/B21_HayloftBarn'
import { B22_WalkingBoots_impl } from './B/B22_WalkingBoots'
import { B23_FinalScenario_impl } from './B/B23_FinalScenario'
import { B24_Lasso_impl } from './B/B24_Lasso'
import { B25_BreadPaddle_impl } from './B/B25_BreadPaddle'
import { B26_AgrarianFences_impl } from './B/B26_AgrarianFences'
import { B27_Toolbox_impl } from './B/B27_Toolbox'
import { B28_ForestryStudies_impl } from './B/B28_ForestryStudies'
import { B29_CookeryLesson_impl } from './B/B29_CookeryLesson'
import { B2_MiniPasture_impl } from './B/B2_MiniPasture'
import { B30_WoodPalisades_impl } from './B/B30_WoodPalisades'
import { B31_PotteryYard_impl } from './B/B31_PotteryYard'
import { B33_Mantlepiece_impl } from './B/B33_Mantlepiece'
import { B34_SpecialFood_impl } from './B/B34_SpecialFood'
import { B35_HookKnife_impl } from './B/B35_HookKnife'
import { B36_Bottles_impl } from './B/B36_Bottles'
import { B37_Grange_impl } from './B/B37_Grange'
import { B38_FutureBuildingSite_impl } from './B/B38_FutureBuildingSite'
import { B39_Loom_impl } from './B/B39_Loom'
import { B3_Moonshine_impl } from './B/B3_Moonshine'
import { B40_BreweryPond_impl } from './B/B40_BreweryPond'
import { B41_Hauberg_impl } from './B/B41_Hauberg'
import { B42_ForestInn_impl } from './B/B42_ForestInn'
import { B43_Chophouse_impl } from './B/B43_Chophouse'
import { B44_ChickStable_impl } from './B/B44_ChickStable'
import { B45_StrawberryPatch_impl } from './B/B45_StrawberryPatch'
import { B46_ClubHouse_impl } from './B/B46_ClubHouse'
import { B47_HerringPot_impl } from './B/B47_HerringPot'
import { B48_ForestStone_impl } from './B/B48_ForestStone'
import { B49_Scales_impl } from './B/B49_Scales'
import { B4_WoodPile_impl } from './B/B4_WoodPile'
import { B50_ButterChurn_impl } from './B/B50_ButterChurn'
import { B51_DiggingSpade_impl } from './B/B51_DiggingSpade'
import { B52_GrowingFarm_impl } from './B/B52_GrowingFarm'
import { B53_SculptureCourse_impl } from './B/B53_SculptureCourse'
import { B54_Tumbrel_impl } from './B/B54_Tumbrel'
import { B55_MaintenancePremium_impl } from './B/B55_MaintenancePremium'
import { B56_Brook_impl } from './B/B56_Brook'
import { B57_Scullery_impl } from './B/B57_Scullery'
import { B58_CrackWeeder_impl } from './B/B58_CrackWeeder'
import { B59_FoodChest_impl } from './B/B59_FoodChest'
import { B5_StoreofExperience_impl } from './B/B5_StoreofExperience'
import { B60_BrewingWater_impl } from './B/B60_BrewingWater'
import { B61_ThreeFieldRotation_impl } from './B/B61_ThreeFieldRotation'
import { B62_Pitchfork_impl } from './B/B62_Pitchfork'
import { B63_Tasting_impl } from './B/B63_Tasting'
import { B64_MillWheel_impl } from './B/B64_MillWheel'
import { B65_GrainDepot_impl } from './B/B65_GrainDepot'
import { B66_SackCart_impl } from './B/B66_SackCart'
import { B67_HandTruck_impl } from './B/B67_HandTruck'
import { B68_Beanfield_impl } from './B/B68_Beanfield'
import { B69_PottersMarket_impl } from './B/B69_PottersMarket'
import { B6_ExcursiontotheQuarry_impl } from './B/B6_ExcursiontotheQuarry'
import { B70_NewPurchase_impl } from './B/B70_NewPurchase'
import { B71_HarvestHouse_impl } from './B/B71_HarvestHouse'
import { B72_LoveforAgriculture_impl } from './B/B72_LoveforAgriculture'
import { B73_GiftBasket_impl } from './B/B73_GiftBasket'
import { B74_ThickForest_impl } from './B/B74_ThickForest'
import { B75_WoodWorkshop_impl } from './B/B75_WoodWorkshop'
import { B76_Ceilings_impl } from './B/B76_Ceilings'
import { B77_LoamPit_impl } from './B/B77_LoamPit'
import { B78_ReedBelt_impl } from './B/B78_ReedBelt'
import { B79_Corf_impl } from './B/B79_Corf'
import { B7_Wage_impl } from './B/B7_Wage'
import { B81_Handcart_impl } from './B/B81_Handcart'
import { B82_ValueAssets_impl } from './B/B82_ValueAssets'
import { B83_MuddyPuddles_impl } from './B/B83_MuddyPuddles'
import { B84_AcornsBasket_impl } from './B/B84_AcornsBasket'
import { B85_FarmHand_impl } from './B/B85_FarmHand'
import { B86_TruffleSearcher_impl } from './B/B86_TruffleSearcher'
import { B87_Cottager_impl } from './B/B87_Cottager'
import { B88_EstablishedPerson_impl } from './B/B88_EstablishedPerson'
import { B89_Groom_impl } from './B/B89_Groom'
import { B8_MarketStall_impl } from './B/B8_MarketStall'
import { B90_CooperativePlower_impl } from './B/B90_CooperativePlower'
import { B91_AssistantTiller_impl } from './B/B91_AssistantTiller'
import { B92_LittleStickKnitter_impl } from './B/B92_LittleStickKnitter'
import { B93_Confidant_impl } from './B/B93_Confidant'
import { B94_StockProtector_impl } from './B/B94_StockProtector'
import { B95_MasterBricklayer_impl } from './B/B95_MasterBricklayer'
import { B96_TreeFarmJoiner_impl } from './B/B96_TreeFarmJoiner'
import { B97_Scholar_impl } from './B/B97_Scholar'
import { B98_OrganicFarmer_impl } from './B/B98_OrganicFarmer'
import { B99_Tutor_impl } from './B/B99_Tutor'
import { B9_BeatingRod_impl } from './B/B9_BeatingRod'
import { C100_Butler_impl } from './C/C100_Butler'
import { C101_StallHolder_impl } from './C/C101_StallHolder'
import { C102_TreeGuard_impl } from './C/C102_TreeGuard'
import { C103_GreenGrocer_impl } from './C/C103_GreenGrocer'
import { C104_Collector_impl } from './C/C104_Collector'
import { C106_PotatoHarvester_impl } from './C/C106_PotatoHarvester'
import { C107_Baker_impl } from './C/C107_Baker'
import { C108_Layabout_impl } from './C/C108_Layabout'
import { C10_BunkBeds_impl } from './C/C10_BunkBeds'
import { C110_HomeBrewer_impl } from './C/C110_HomeBrewer'
import { C111_SmallAnimalBreeder_impl } from './C/C111_SmallAnimalBreeder'
import { C112_Thresher_impl } from './C/C112_Thresher'
import { C113_WinterCaretaker_impl } from './C/C113_WinterCaretaker'
import { C114_SoilScientist_impl } from './C/C114_SoilScientist'
import { C115_Sower_impl } from './C/C115_Sower'
import { C116_FurnitureMaker_impl } from './C/C116_FurnitureMaker'
import { C117_Legworker_impl } from './C/C117_Legworker'
import { C118_WoodCollector_impl } from './C/C118_WoodCollector'
import { C119_SkillfulRenovator_impl } from './C/C119_SkillfulRenovator'
import { C11_WildlifeReserve_impl } from './C/C11_WildlifeReserve'
import { C120_AgriculturalLabourer_impl } from './C/C120_AgriculturalLabourer'
import { C121_ClayKneader_impl } from './C/C121_ClayKneader'
import { C122_Bricklayer_impl } from './C/C122_Bricklayer'
import { C123_Freemason_impl } from './C/C123_Freemason'
import { C124_StoneImporter_impl } from './C/C124_StoneImporter'
import { C125_Nightworker_impl } from './C/C125_Nightworker'
import { C126_Excavator_impl } from './C/C126_Excavator'
import { C127_Lover_impl } from './C/C127_Lover'
import { C128_WoodenHutExtender_impl } from './C/C128_WoodenHutExtender'
import { C129_SecondSpouse_impl } from './C/C129_SecondSpouse'
import { C12_CattleFarm_impl } from './C/C12_CattleFarm'
import { C130_OutskirtsDirector_impl } from './C/C130_OutskirtsDirector'
import { C131_PrivateTeacher_impl } from './C/C131_PrivateTeacher'
import { C132_TimberShingleMaker_impl } from './C/C132_TimberShingleMaker'
import { C133_Soldier_impl } from './C/C133_Soldier'
import { C134_CowPrince_impl } from './C/C134_CowPrince'
import { C135_Constable_impl } from './C/C135_Constable'
import { C136_RanchProvost_impl } from './C/C136_RanchProvost'
import { C137_CharcoalBurner_impl } from './C/C137_CharcoalBurner'
import { C138_AnimalFeeder_impl } from './C/C138_AnimalFeeder'
import { C139_BasketmakersWife_impl } from './C/C139_BasketmakersWife'
import { C140_PackagingArtist_impl } from './C/C140_PackagingArtist'
import { C141_SheepProvider_impl } from './C/C141_SheepProvider'
import { C142_MarketCrier_impl } from './C/C142_MarketCrier'
import { C143_StoneBuyer_impl } from './C/C143_StoneBuyer'
import { C144_ReedRoofRenovator_impl } from './C/C144_ReedRoofRenovator'
import { C145_ForestReviewer_impl } from './C/C145_ForestReviewer'
import { C146_WorkshopAssistant_impl } from './C/C146_WorkshopAssistant'
import { C147_Cowherd_impl } from './C/C147_Cowherd'
import { C148_MudWallower_impl } from './C/C148_MudWallower'
import { C149_ResourceRecycler_impl } from './C/C149_ResourceRecycler'
import { C150_ParrotBreeder_impl } from './C/C150_ParrotBreeder'
import { C151_SowingDirector_impl } from './C/C151_SowingDirector'
import { C152_Puppeteer_impl } from './C/C152_Puppeteer'
import { C153_PatternMaker_impl } from './C/C153_PatternMaker'
import { C154_TwinResearcher_impl } from './C/C154_TwinResearcher'
import { C155_FoodDistributor_impl } from './C/C155_FoodDistributor'
import { C156_HoofCaregiver_impl } from './C/C156_HoofCaregiver'
import { C157_ResourceAnalyzer_impl } from './C/C157_ResourceAnalyzer'
import { C158_ForestCampaigner_impl } from './C/C158_ForestCampaigner'
import { C159_FishermansFriend_impl } from './C/C159_FishermansFriend'
import { C15_Trellis_impl } from './C/C15_Trellis'
import { C160_Outrider_impl } from './C/C160_Outrider'
import { C161_PotatoDigger_impl } from './C/C161_PotatoDigger'
import { C162_ForestOwner_impl } from './C/C162_ForestOwner'
import { C163_MaterialDeliveryman_impl } from './C/C163_MaterialDeliveryman'
import { C164_GermanHeathKeeper_impl } from './C/C164_GermanHeathKeeper'
import { C165_GameCatcher_impl } from './C/C165_GameCatcher'
import { C166_CattleWhisperer_impl } from './C/C166_CattleWhisperer'
import { C167_CattleBuyer_impl } from './C/C167_CattleBuyer'
import { C168_AnimalCatcher_impl } from './C/C168_AnimalCatcher'
import { C16_FieldFences_impl } from './C/C16_FieldFences'
import { C17_NewlyPlowedField_impl } from './C/C17_NewlyPlowedField'
import { C18_RollOverPlow_impl } from './C/C18_RollOverPlow'
import { C19_SwingPlow_impl } from './C/C19_SwingPlow'
import { C1_Overhaul_impl } from './C/C1_Overhaul'
import { C20_MolePlow_impl } from './C/C20_MolePlow'
import { C21_HeartofStone_impl } from './C/C21_HeartofStone'
import { C22_BasketChair_impl } from './C/C22_BasketChair'
import { C23_JobContract_impl } from './C/C23_JobContract'
import { C24_BedintheGrainField_impl } from './C/C24_BedintheGrainField'
import { C25_SteamMachine_impl } from './C/C25_SteamMachine'
import { C26_Flail_impl } from './C/C26_Flail'
import { C27_Blueprint_impl } from './C/C27_Blueprint'
import { C28_TeachersDesk_impl } from './C/C28_TeachersDesk'
import { C29_BeerTable_impl } from './C/C29_BeerTable'
import { C2_Stable_impl } from './C/C2_Stable'
import { C30_HalfTimberedHouse_impl } from './C/C30_HalfTimberedHouse'
import { C31_WritingChamber_impl } from './C/C31_WritingChamber'
import { C33_GreeningPlan_impl } from './C/C33_GreeningPlan'
import { C34_ElephantgrassPlant_impl } from './C/C34_ElephantgrassPlant'
import { C35_LanternHouse_impl } from './C/C35_LanternHouse'
import { C36_ClayDeposit_impl } from './C/C36_ClayDeposit'
import { C37_DwellingMound_impl } from './C/C37_DwellingMound'
import { C38_Christianity_impl } from './C/C38_Christianity'
import { C39_StudioBoat_impl } from './C/C39_StudioBoat'
import { C3_CarriageTrip_impl } from './C/C3_CarriageTrip'
import { C40_CanvasSack_impl } from './C/C40_CanvasSack'
import { C41_FarmStore_impl } from './C/C41_FarmStore'
import { C42_RavenousHunger_impl } from './C/C42_RavenousHunger'
import { C43_FarmBuilding_impl } from './C/C43_FarmBuilding'
import { C44_ChickenCoop_impl } from './C/C44_ChickenCoop'
import { C45_Stew_impl } from './C/C45_Stew'
import { C46_Mandoline_impl } from './C/C46_Mandoline'
import { C47_GardenClaw_impl } from './C/C47_GardenClaw'
import { C48_Farmstead_impl } from './C/C48_Farmstead'
import { C49_BeerStall_impl } from './C/C49_BeerStall'
import { C4_WritingBoards_impl } from './C/C4_WritingBoards'
import { C50_StableYard_impl } from './C/C50_StableYard'
import { C51_FishingNet_impl } from './C/C51_FishingNet'
import { C52_HuntsmansHat_impl } from './C/C52_HuntsmansHat'
import { C53_GypsysCrock_impl } from './C/C53_GypsysCrock'
import { C54_MarketBooth_impl } from './C/C54_MarketBooth'
import { C55_Studio_impl } from './C/C55_Studio'
import { C56_FeedFence_impl } from './C/C56_FeedFence'
import { C57_Crudite_impl } from './C/C57_Crudite'
import { C58_Woodcraft_impl } from './C/C58_Woodcraft'
import { C59_SchnappsDistillery_impl } from './C/C59_SchnappsDistillery'
import { C5_Remodeling_impl } from './C/C5_Remodeling'
import { C60_SmallPottersOven_impl } from './C/C60_SmallPottersOven'
import { C61_BeerStein_impl } from './C/C61_BeerStein'
import { C63_CraftBrewery_impl } from './C/C63_CraftBrewery'
import { C64_CornSchnappsDistillery_impl } from './C/C64_CornSchnappsDistillery'
import { C65_Granary_impl } from './C/C65_Granary'
import { C66_EternalRyeCultivation_impl } from './C/C66_EternalRyeCultivation'
import { C67_MineralFeeder_impl } from './C/C67_MineralFeeder'
import { C68_Bookcase_impl } from './C/C68_Bookcase'
import { C69_LandConsolidation_impl } from './C/C69_LandConsolidation'
import { C6_StoneClearing_impl } from './C/C6_StoneClearing'
import { C70_LettucePatch_impl } from './C/C70_LettucePatch'
import { C71_Slurry_impl } from './C/C71_Slurry'
import { C71_SlurrySpreader_impl } from './C/C71_SlurrySpreader'
import { C72_FestivalPlanning_impl } from './C/C72_FestivalPlanning'
import { C73_SeaweedFertilizer_impl } from './C/C73_SeaweedFertilizer'
import { C74_PrivateForest_impl } from './C/C74_PrivateForest'
import { C75_Firewood_impl } from './C/C75_Firewood'
import { C76_WoodCart_impl } from './C/C76_WoodCart'
import { C77_ClaySupply_impl } from './C/C77_ClaySupply'
import { C78_ReedHattedToad_impl } from './C/C78_ReedHattedToad'
import { C79_StoneCart_impl } from './C/C79_StoneCart'
import { C7_BladeShears_impl } from './C/C7_BladeShears'
import { C80_RockyTerrain_impl } from './C/C80_RockyTerrain'
import { C81_MaterialHub_impl } from './C/C81_MaterialHub'
import { C82_HardwareStore_impl } from './C/C82_HardwareStore'
import { C83_EarlyCattle_impl } from './C/C83_EarlyCattle'
import { C84_PerennialRye_impl } from './C/C84_PerennialRye'
import { C85_DenBuilder_impl } from './C/C85_DenBuilder'
import { C86_LivestockFeeder_impl } from './C/C86_LivestockFeeder'
import { C87_Mason_impl } from './C/C87_Mason'
import { C88_CarpentersApprentice_impl } from './C/C88_CarpentersApprentice'
import { C89_StableMaster_impl } from './C/C89_StableMaster'
import { C8_PlantFertilizer_impl } from './C/C8_PlantFertilizer'
import { C90_FieldWatchman_impl } from './C/C90_FieldWatchman'
import { C91_PlowHero_impl } from './C/C91_PlowHero'
import { C92_AutumnMother_impl } from './C/C92_AutumnMother'
import { C93_InnerDistrictsDirector_impl } from './C/C93_InnerDistrictsDirector'
import { C94_StableCleaner_impl } from './C/C94_StableCleaner'
import { C95_BasketWeaver_impl } from './C/C95_BasketWeaver'
import { C96_Merchant_impl } from './C/C96_Merchant'
import { C97_SeedResearcher_impl } from './C/C97_SeedResearcher'
import { C98_CubeCutter_impl } from './C/C98_CubeCutter'
import { C99_GardenDesigner_impl } from './C/C99_GardenDesigner'
import { C9_AutomaticWaterTrough_impl } from './C/C9_AutomaticWaterTrough'
import { D100_LordoftheManor_impl } from './D/D100_LordoftheManor'
import { D101_SugarBaker_impl } from './D/D101_SugarBaker'
import { D102_SampleStableMaker_impl } from './D/D102_SampleStableMaker'
import { D103_CanalBoatman_impl } from './D/D103_CanalBoatman'
import { D104_Cultivator_impl } from './D/D104_Cultivator'
import { D105_Sculptor_impl } from './D/D105_Sculptor'
import { D106_WhiskyDistiller_impl } from './D/D106_WhiskyDistiller'
import { D107_Bellfounder_impl } from './D/D107_Bellfounder'
import { D109_SowingMaster_impl } from './D/D109_SowingMaster'
import { D10_StorksNest_impl } from './D/D10_StorksNest'
import { D110_FishFarmer_impl } from './D/D110_FishFarmer'
import { D111_InteriorDecorator_impl } from './D/D111_InteriorDecorator'
import { D112_YoungFarmer_impl } from './D/D112_YoungFarmer'
import { D113_FoodMerchant_impl } from './D/D113_FoodMerchant'
import { D114_SeedTrader_impl } from './D/D114_SeedTrader'
import { D115_FodderPlanter_impl } from './D/D115_FodderPlanter'
import { D116_TreeInspector_impl } from './D/D116_TreeInspector'
import { D117_WoodExpert_impl } from './D/D117_WoodExpert'
import { D118_Bonehead_impl } from './D/D118_Bonehead'
import { D119_WoodBarterer_impl } from './D/D119_WoodBarterer'
import { D11_LawnFertilizer_impl } from './D/D11_LawnFertilizer'
import { D120_ClayDeliveryman_impl } from './D/D120_ClayDeliveryman'
import { D121_ClayPlasterer_impl } from './D/D121_ClayPlasterer'
import { D122_ClayCarrier_impl } from './D/D122_ClayCarrier'
import { D123_RenovationPreparer_impl } from './D/D123_RenovationPreparer'
import { D124_Emissary_impl } from './D/D124_Emissary'
import { D125_ForestTrader_impl } from './D/D125_ForestTrader'
import { D126_FieldCultivator_impl } from './D/D126_FieldCultivator'
import { D127_HardworkingMan_impl } from './D/D127_HardworkingMan'
import { D128_BuildingTycoon_impl } from './D/D128_BuildingTycoon'
import { D129_LumberVirtuoso_impl } from './D/D129_LumberVirtuoso'
import { D12_MilkingPlace_impl } from './D/D12_MilkingPlace'
import { D130_RecreationalCarpenter_impl } from './D/D130_RecreationalCarpenter'
import { D131_CraftsmanshipPromoter_impl } from './D/D131_CraftsmanshipPromoter'
import { D132_HideFarmer_impl } from './D/D132_HideFarmer'
import { D133_BeerTentOperator_impl } from './D/D133_BeerTentOperator'
import { D134_OysterEater_impl } from './D/D134_OysterEater'
import { D135_GardeningHeadOfficial_impl } from './D/D135_GardeningHeadOfficial'
import { D136_AnimalActivist_impl } from './D/D136_AnimalActivist'
import { D137_TradeTeacher_impl } from './D/D137_TradeTeacher'
import { D138_PetLover_impl } from './D/D138_PetLover'
import { D139_Chairman_impl } from './D/D139_Chairman'
import { D13_Trowel_impl } from './D/D13_Trowel'
import { D140_Loudmouth_impl } from './D/D140_Loudmouth'
import { D141_SeedSeller_impl } from './D/D141_SeedSeller'
import { D142_PotatoPlanter_impl } from './D/D142_PotatoPlanter'
import { D143_TreeCutter_impl } from './D/D143_TreeCutter'
import { D144_WaterWorker_impl } from './D/D144_WaterWorker'
import { D145_RoofExaminer_impl } from './D/D145_RoofExaminer'
import { D146_Porter_impl } from './D/D146_Porter'
import { D147_TrapBuilder_impl } from './D/D147_TrapBuilder'
import { D148_DomesticianExpert_impl } from './D/D148_DomesticianExpert'
import { D149_CasualWorker_impl } from './D/D149_CasualWorker'
import { D14_HammerCrusher_impl } from './D/D14_HammerCrusher'
import { D150_GodlySpouse_impl } from './D/D150_GodlySpouse'
import { D151_SpinDoctor_impl } from './D/D151_SpinDoctor'
import { D152_Patron_impl } from './D/D152_Patron'
import { D153_WealthyMan_impl } from './D/D153_WealthyMan'
import { D154_ChimneySweep_impl } from './D/D154_ChimneySweep'
import { D156_RetailDealer_impl } from './D/D156_RetailDealer'
import { D157_PartyOrganizer_impl } from './D/D157_PartyOrganizer'
import { D158_BeanCounter_impl } from './D/D158_BeanCounter'
import { D15_ClaySupports_impl } from './D/D15_ClaySupports'
import { D160_Midwife_impl } from './D/D160_Midwife'
import { D161_CabbageBuyer_impl } from './D/D161_CabbageBuyer'
import { D162_ClayFirer_impl } from './D/D162_ClayFirer'
import { D163_JourneymanBricklayer_impl } from './D/D163_JourneymanBricklayer'
import { D164_PetGrower_impl } from './D/D164_PetGrower'
import { D165_PigStalker_impl } from './D/D165_PigStalker'
import { D166_StableMilker_impl } from './D/D166_StableMilker'
import { D167_PureBreeder_impl } from './D/D167_PureBreeder'
import { D168_Stockman_impl } from './D/D168_Stockman'
import { D16_WoodenWheyBucket_impl } from './D/D16_WoodenWheyBucket'
import { D17_DrillHarrow_impl } from './D/D17_DrillHarrow'
import { D18_SteamPlow_impl } from './D/D18_SteamPlow'
import { D19_PulverizerPlow_impl } from './D/D19_PulverizerPlow'
import { D1_ZigzagHarrow_impl } from './D/D1_ZigzagHarrow'
import { D20_TurnwrestPlow_impl } from './D/D20_TurnwrestPlow'
import { D21_Recruitment_impl } from './D/D21_Recruitment'
import { D22_WorkPermit_impl } from './D/D22_WorkPermit'
import { D23_PioneeringSpirit_impl } from './D/D23_PioneeringSpirit'
import { D24_BrotherlyLove_impl } from './D/D24_BrotherlyLove'
import { D25_WitchesDanceFloor_impl } from './D/D25_WitchesDanceFloor'
import { D26_CarpentersYard_impl } from './D/D26_CarpentersYard'
import { D27_Retraining_impl } from './D/D27_Retraining'
import { D28_WritingDesk_impl } from './D/D28_WritingDesk'
import { D29_MuckRake_impl } from './D/D29_MuckRake'
import { D2_DwellingPlan_impl } from './D/D2_DwellingPlan'
import { D30_ArtisanDistrict_impl } from './D/D30_ArtisanDistrict'
import { D31_Storeroom_impl } from './D/D31_Storeroom'
import { D32_WoodRake_impl } from './D/D32_WoodRake'
import { D33_SummerHouse_impl } from './D/D33_SummerHouse'
import { D34_LuxuriousHostel_impl } from './D/D34_LuxuriousHostel'
import { D35_FodderChamber_impl } from './D/D35_FodderChamber'
import { D36_BreedRegistry_impl } from './D/D36_BreedRegistry'
import { D38_MilkingStool_impl } from './D/D38_MilkingStool'
import { D39_TruffleSlicer_impl } from './D/D39_TruffleSlicer'
import { D3_Furrows_impl } from './D/D3_Furrows'
import { D40_Cesspit_impl } from './D/D40_Cesspit'
import { D41_HorseDrawnBoat_impl } from './D/D41_HorseDrawnBoat'
import { D42_EducationBonus_impl } from './D/D42_EducationBonus'
import { D43_Hutch_impl } from './D/D43_Hutch'
import { D44_ForestWell_impl } from './D/D44_ForestWell'
import { D45_SheepWell_impl } from './D/D45_SheepWell'
import { D46_PelletPress_impl } from './D/D46_PelletPress'
import { D47_Churchyard_impl } from './D/D47_Churchyard'
import { D48_CivicFacade_impl } from './D/D48_CivicFacade'
import { D49_Bookshelf_impl } from './D/D49_Bookshelf'
import { D4_CrossCutWood_impl } from './D/D4_CrossCutWood'
import { D50_ForeignAid_impl } from './D/D50_ForeignAid'
import { D51_Archway_impl } from './D/D51_Archway'
import { D52_RollingPin_impl } from './D/D52_RollingPin'
import { D53_TeaHouse_impl } from './D/D53_TeaHouse'
import { D54_TroutPool_impl } from './D/D54_TroutPool'
import { D55_NewMarket_impl } from './D/D55_NewMarket'
import { D56_FatstockStretcher_impl } from './D/D56_FatstockStretcher'
import { D57_WholesaleMarket_impl } from './D/D57_WholesaleMarket'
import { D58_Gritter_impl } from './D/D58_Gritter'
import { D5_FieldClay_impl } from './D/D5_FieldClay'
import { D60_LargePottery_impl } from './D/D60_LargePottery'
import { D61_BaleofStraw_impl } from './D/D61_BaleofStraw'
import { D62_BeerTap_impl } from './D/D62_BeerTap'
import { D63_Lynchet_impl } from './D/D63_Lynchet'
import { D64_BakingCourse_impl } from './D/D64_BakingCourse'
import { D65_GrainSieve_impl } from './D/D65_GrainSieve'
import { D66_PotterCeramics_impl } from './D/D66_PotterCeramics'
import { D67_ReapHook_impl } from './D/D67_ReapHook'
import { D68_SmallBasket_impl } from './D/D68_SmallBasket'
import { D69_SmallGreenhouse_impl } from './D/D69_SmallGreenhouse'
import { D6_PetrifiedWood_impl } from './D/D6_PetrifiedWood'
import { D70_StrawManure_impl } from './D/D70_StrawManure'
import { D71_Changeover_impl } from './D/D71_Changeover'
import { D72_StableManure_impl } from './D/D72_StableManure'
import { D73_SupplyBoat_impl } from './D/D73_SupplyBoat'
import { D74_RoyalWood_impl } from './D/D74_RoyalWood'
import { D76_SocialBenefits_impl } from './D/D76_SocialBenefits'
import { D77_RecycledBrick_impl } from './D/D77_RecycledBrick'
import { D78_ReedPond_impl } from './D/D78_ReedPond'
import { D79_CarrotMuseum_impl } from './D/D79_CarrotMuseum'
import { D7_Trident_impl } from './D/D7_Trident'
import { D80_BrickHammer_impl } from './D/D80_BrickHammer'
import { D81_RoofLadder_impl } from './D/D81_RoofLadder'
import { D82_HuntingTrophy_impl } from './D/D82_HuntingTrophy'
import { D83_Pigswill_impl } from './D/D83_Pigswill'
import { D84_FeedPellets_impl } from './D/D84_FeedPellets'
import { D85_Reader_impl } from './D/D85_Reader'
import { D86_SheepAgent_impl } from './D/D86_SheepAgent'
import { D87_MasterBuilder_impl } from './D/D87_MasterBuilder'
import { D88_Millwright_impl } from './D/D88_Millwright'
import { D89_Stablehand_impl } from './D/D89_Stablehand'
import { D8_FernSeeds_impl } from './D/D8_FernSeeds'
import { D90_PlowMaker_impl } from './D/D90_PlowMaker'
import { D91_Plowman_impl } from './D/D91_Plowman'
import { D92_ChildOmbudsman_impl } from './D/D92_ChildOmbudsman'
import { D93_SheepInspector_impl } from './D/D93_SheepInspector'
import { D94_HenpeckedHusband_impl } from './D/D94_HenpeckedHusband'
import { D95_SiteManager_impl } from './D/D95_SiteManager'
import { D96_Furnisher_impl } from './D/D96_Furnisher'
import { D97_BeggingStudent_impl } from './D/D97_BeggingStudent'
import { D98_Transactor_impl } from './D/D98_Transactor'
import { D99_EarthenwarePotter_impl } from './D/D99_EarthenwarePotter'
import { D9_GameTrade_impl } from './D/D9_GameTrade'
import { E100_MuseumCaretaker_impl } from './E/E100_MuseumCaretaker'
import { E101_Blighter_impl } from './E/E101_Blighter'
import { E102_Acquirer_impl } from './E/E102_Acquirer'
import { E103_Wolf_impl } from './E/E103_Wolf'
import { E104_SpiceTrader_impl } from './E/E104_SpiceTrader'
import { E105_Pioneer_impl } from './E/E105_Pioneer'
import { E106_EmergencySeller_impl } from './E/E106_EmergencySeller'
import { E107_LandSurveyor_impl } from './E/E107_LandSurveyor'
import { E108_BlackberryFarmer_impl } from './E/E108_BlackberryFarmer'
import { E109_BraidMaker_impl } from './E/E109_BraidMaker'
import { E10_StrawHat_impl } from './E/E10_StrawHat'
import { E110_Dentist_impl } from './E/E110_Dentist'
import { E111_Recluse_impl } from './E/E111_Recluse'
import { E112_GrainThief_impl } from './E/E112_GrainThief'
import { E113_Godmother_impl } from './E/E113_Godmother'
import { E114_ShedBuilder_impl } from './E/E114_ShedBuilder'
import { E115_SeedServant_impl } from './E/E115_SeedServant'
import { E116_FirCutter_impl } from './E/E116_FirCutter'
import { E117_PipeSmoker_impl } from './E/E117_PipeSmoker'
import { E118_KindlingGatherer_impl } from './E/E118_KindlingGatherer'
import { E119_LandHeir_impl } from './E/E119_LandHeir'
import { E11_PettingZoo_impl } from './E/E11_PettingZoo'
import { E120_ScrapCollector_impl } from './E/E120_ScrapCollector'
import { E121_HillCultivator_impl } from './E/E121_HillCultivator'
import { E122_Cottar_impl } from './E/E122_Cottar'
import { E123_ResourceHoarder_impl } from './E/E123_ResourceHoarder'
import { E124_MayorCandidate_impl } from './E/E124_MayorCandidate'
import { E125_DelayedWayfarer_impl } from './E/E125_DelayedWayfarer'
import { E126_TaxCollector_impl } from './E/E126_TaxCollector'
import { E127_DiligentFarmer_impl } from './E/E127_DiligentFarmer'
import { E128_Saddler_impl } from './E/E128_Saddler'
import { E129_Imitator_impl } from './E/E129_Imitator'
import { E12_AnimalBedding_impl } from './E/E12_AnimalBedding'
import { E130_Overachiever_impl } from './E/E130_Overachiever'
import { E131_MarketMaster_impl } from './E/E131_MarketMaster'
import { E132_VeggieLover_impl } from './E/E132_VeggieLover'
import { E133_ChampionBreeder_impl } from './E/E133_ChampionBreeder'
import { E134_Omnifarmer_impl } from './E/E134_Omnifarmer'
import { E135_Pickler_impl } from './E/E135_Pickler'
import { E136_AnimalHusbandryWorker_impl } from './E/E136_AnimalHusbandryWorker'
import { E137_FlaxFarmer_impl } from './E/E137_FlaxFarmer'
import { E138_LivestockExpert_impl } from './E/E138_LivestockExpert'
import { E139_BunnyBreeder_impl } from './E/E139_BunnyBreeder'
import { E13_StoneHouseReconstruction_impl } from './E/E13_StoneHouseReconstruction'
import { E140_Carter_impl } from './E/E140_Carter'
import { E141_VegetableVendor_impl } from './E/E141_VegetableVendor'
import { E142_Smuggler_impl } from './E/E142_Smuggler'
import { E143_Hewer_impl } from './E/E143_Hewer'
import { E144_WaresSalesman_impl } from './E/E144_WaresSalesman'
import { E145_Parvenu_impl } from './E/E145_Parvenu'
import { E146_Reseller_impl } from './E/E146_Reseller'
import { E147_AnimalDriver_impl } from './E/E147_AnimalDriver'
import { E148_Lazybones_impl } from './E/E148_Lazybones'
import { E14_WoodSaw_impl } from './E/E14_WoodSaw'
import { E150_RockBeater_impl } from './E/E150_RockBeater'
import { E151_DeliveryNurse_impl } from './E/E151_DeliveryNurse'
import { E152_BargainHunter_impl } from './E/E152_BargainHunter'
import { E154_Margrave_impl } from './E/E154_Margrave'
import { E155_Visionary_impl } from './E/E155_Visionary'
import { E156_ClaypitOwner_impl } from './E/E156_ClaypitOwner'
import { E157_Usufructuary_impl } from './E/E157_Usufructuary'
import { E158_StoneCustodian_impl } from './E/E158_StoneCustodian'
import { E159_OldMiser_impl } from './E/E159_OldMiser'
import { E15_NailBasket_impl } from './E/E15_NailBasket'
import { E160_KelpGatherer_impl } from './E/E160_KelpGatherer'
import { E161_ElderBaker_impl } from './E/E161_ElderBaker'
import { E162_Entrepreneur_impl } from './E/E162_Entrepreneur'
import { E163_Patroness_impl } from './E/E163_Patroness'
import { E164_MountainPlowman_impl } from './E/E164_MountainPlowman'
import { E165_MasterHuntsman_impl } from './E/E165_MasterHuntsman'
import { E166_Roastmaster_impl } from './E/E166_Roastmaster'
import { E167_DairyCrier_impl } from './E/E167_DairyCrier'
import { E168_AnimalTamersApprentice_impl } from './E/E168_AnimalTamersApprentice'
import { E16_BriarHedge_impl } from './E/E16_BriarHedge'
import { E17_SkimmerPlow_impl } from './E/E17_SkimmerPlow'
import { E18_SeedAlmanac_impl } from './E/E18_SeedAlmanac'
import { E19_OxGoad_impl } from './E/E19_OxGoad'
import { E1_PoleBarns_impl } from './E/E1_PoleBarns'
import { E20_IronHoe_impl } from './E/E20_IronHoe'
import { E21_SheepRug_impl } from './E/E21_SheepRug'
import { E22_GuestRoom_impl } from './E/E22_GuestRoom'
import { E23_Apiary_impl } from './E/E23_Apiary'
import { E24_Ambition_impl } from './E/E24_Ambition'
import { E25_BumperCrop_impl } from './E/E25_BumperCrop'
import { E26_Sundial_impl } from './E/E26_Sundial'
import { E27_PiggyBank_impl } from './E/E27_PiggyBank'
import { E28_Bookmark_impl } from './E/E28_Bookmark'
import { E2_RenovationMaterials_impl } from './E/E2_RenovationMaterials'
import { E30_ChildsToy_impl } from './E/E30_ChildsToy'
import { E31_Upholstery_impl } from './E/E31_Upholstery'
import { E32_Nave_impl } from './E/E32_Nave'
import { E33_BeaverColony_impl } from './E/E33_BeaverColony'
import { E34_LandRegister_impl } from './E/E34_LandRegister'
import { E35_Misanthropy_impl } from './E/E35_Misanthropy'
import { E36_HerbalGarden_impl } from './E/E36_HerbalGarden'
import { E37_OxSkull_impl } from './E/E37_OxSkull'
import { E38_RodCollection_impl } from './E/E38_RodCollection'
import { E39_Paintbrush_impl } from './E/E39_Paintbrush'
import { E3_TeaTime_impl } from './E/E3_TeaTime'
import { E40_BeeStatue_impl } from './E/E40_BeeStatue'
import { E41_MuddyWaters_impl } from './E/E41_MuddyWaters'
import { E42_WaterGully_impl } from './E/E42_WaterGully'
import { E43_BarnCats_impl } from './E/E43_BarnCats'
import { E44_FodderBeets_impl } from './E/E44_FodderBeets'
import { E45_FruitLadder_impl } from './E/E45_FruitLadder'
import { E46_WaterlilyPond_impl } from './E/E46_WaterlilyPond'
import { E47_SyrupTap_impl } from './E/E47_SyrupTap'
import { E48_TownHall_impl } from './E/E48_TownHall'
import { E49_Twibil_impl } from './E/E49_Twibil'
import { E4_Thunderbolt_impl } from './E/E4_Thunderbolt'
import { E50_WildGreens_impl } from './E/E50_WildGreens'
import { E51_WhaleOil_impl } from './E/E51_WhaleOil'
import { E52_Cubbyhole_impl } from './E/E52_Cubbyhole'
import { E53_BoarSpear_impl } from './E/E53_BoarSpear'
import { E54_Contraband_impl } from './E/E54_Contraband'
import { E55_StoneWeir_impl } from './E/E55_StoneWeir'
import { E56_RomanPot_impl } from './E/E56_RomanPot'
import { E57_CheeseFondue_impl } from './E/E57_CheeseFondue'
import { E58_LunchtimeBeer_impl } from './E/E58_LunchtimeBeer'
import { E59_CombandCutter_impl } from './E/E59_CombandCutter'
import { E5_NightLoot_impl } from './E/E5_NightLoot'
import { E60_WorkingGloves_impl } from './E/E60_WorkingGloves'
import { E61_RaisedBed_impl } from './E/E61_RaisedBed'
import { E62_SourDough_impl } from './E/E62_SourDough'
import { E63_IronOven_impl } from './E/E63_IronOven'
import { E64_SimpleOven_impl } from './E/E64_SimpleOven'
import { E65_Almsbag_impl } from './E/E65_Almsbag'
import { E66_BarnShed_impl } from './E/E66_BarnShed'
import { E67_GrainBag_impl } from './E/E67_GrainBag'
import { E68_CherryOrchard_impl } from './E/E68_CherryOrchard'
import { E69_MelonPatch_impl } from './E/E69_MelonPatch'
import { E6_Recount_impl } from './E/E6_Recount'
import { E70_CropRotationField_impl } from './E/E70_CropRotationField'
import { E71_CowPatty_impl } from './E/E71_CowPatty'
import { E72_ArtichokeField_impl } from './E/E72_ArtichokeField'
import { E73_Scythe_impl } from './E/E73_Scythe'
import { E74_AshTrees_impl } from './E/E74_AshTrees'
import { E75_StoneAxe_impl } from './E/E75_StoneAxe'
import { E76_LumberPile_impl } from './E/E76_LumberPile'
import { E77_Mattock_impl } from './E/E77_Mattock'
import { E78_SleightofHand_impl } from './E/E78_SleightofHand'
import { E79_FieldSpade_impl } from './E/E79_FieldSpade'
import { E7_Pumpernickel_impl } from './E/E7_Pumpernickel'
import { E81_AlchemistsLab_impl } from './E/E81_AlchemistsLab'
import { E82_Profiteering_impl } from './E/E82_Profiteering'
import { E83_ShepherdsWhistle_impl } from './E/E83_ShepherdsWhistle'
import { E84_DollysMother_impl } from './E/E84_DollysMother'
import { E85_MasterTanner_impl } from './E/E85_MasterTanner'
import { E86_PenBuilder_impl } from './E/E86_PenBuilder'
import { E87_MasterRenovator_impl } from './E/E87_MasterRenovator'
import { E88_MasterFencer_impl } from './E/E88_MasterFencer'
import { E89_Stallwright_impl } from './E/E89_Stallwright'
import { E8_FarmersMarket_impl } from './E/E8_FarmersMarket'
import { E90_DungCollector_impl } from './E/E90_DungCollector'
import { E91_PlowBuilder_impl } from './E/E91_PlowBuilder'
import { E92_FieldDoctor_impl } from './E/E92_FieldDoctor'
import { E93_Motivator_impl } from './E/E93_Motivator'
import { E94_Prophet_impl } from './E/E94_Prophet'
import { E95_Miller_impl } from './E/E95_Miller'
import { E96_Elder_impl } from './E/E96_Elder'
import { E97_Beneficiary_impl } from './E/E97_Beneficiary'
import { E98_Prodigy_impl } from './E/E98_Prodigy'
import { E99_UncaringParents_impl } from './E/E99_UncaringParents'
import { E9_BarteringHut_impl } from './E/E9_BarteringHut'
import { CUSTOM_FixtureHarvester_impl } from './community/CUSTOM_FixtureHarvester'

export const ALL_CARD_IMPLS: Readonly<Record<string, CardImpl>> = {
  'A100_Curator': A100_Curator_impl,
  'A101_CookeryOutfitter': A101_CookeryOutfitter_impl,
  'A102_Grocer': A102_Grocer_impl,
  'A103_Portmonger': A103_Portmonger_impl,
  'A104_WoodHarvester': A104_WoodHarvester_impl,
  'A105_BarrowPusher': A105_BarrowPusher_impl,
  'A106_SlurrySpreader': A106_SlurrySpreader_impl,
  'A107_Catcher': A107_Catcher_impl,
  'A108_MushroomCollector': A108_MushroomCollector_impl,
  'A109_SmallTrader': A109_SmallTrader_impl,
  'A10_WoodenShed': A10_WoodenShed_impl,
  'A110_Roughcaster': A110_Roughcaster_impl,
  'A111_WallBuilder': A111_WallBuilder_impl,
  'A112_ScytheWorker': A112_ScytheWorker_impl,
  'A113_HeresyTeacher': A113_HeresyTeacher_impl,
  'A114_SeasonalWorker': A114_SeasonalWorker_impl,
  'A115_ChiefForester': A115_ChiefForester_impl,
  'A116_WoodCutter': A116_WoodCutter_impl,
  'A117_WoodCarrier': A117_WoodCarrier_impl,
  'A118_Treegardener': A118_Treegardener_impl,
  'A119_FirewoodCollector': A119_FirewoodCollector_impl,
  'A11_MudPatch': A11_MudPatch_impl,
  'A120_ClayHutBuilder': A120_ClayHutBuilder_impl,
  'A121_ClayPuncher': A121_ClayPuncher_impl,
  'A122_PanBaker': A122_PanBaker_impl,
  'A124_Knapper': A124_Knapper_impl,
  'A125_Priest': A125_Priest_impl,
  'A126_MasterWorkman': A126_MasterWorkman_impl,
  'A127_Lodger': A127_Lodger_impl,
  'A128_RiparianBuilder': A128_RiparianBuilder_impl,
  'A129_Swagman': A129_Swagman_impl,
  'A12_DrinkingTrough': A12_DrinkingTrough_impl,
  'A130_MummysBoy': A130_MummysBoy_impl,
  'A131_CraftTeacher': A131_CraftTeacher_impl,
  'A132_Publican': A132_Publican_impl,
  'A133_Braggart': A133_Braggart_impl,
  'A134_FullFarmer': A134_FullFarmer_impl,
  'A135_AnimalReeve': A135_AnimalReeve_impl,
  'A136_DrudgeryReeve': A136_DrudgeryReeve_impl,
  'A137_RiverineShepherd': A137_RiverineShepherd_impl,
  'A138_Harpooner': A138_Harpooner_impl,
  'A139_HollowWarden': A139_HollowWarden_impl,
  'A13_RenovationCompany': A13_RenovationCompany_impl,
  'A140_ShovelBearer': A140_ShovelBearer_impl,
  'A141_TurnipFarmer': A141_TurnipFarmer_impl,
  'A142_Cordmaker': A142_Cordmaker_impl,
  'A143_Stonecutter': A143_Stonecutter_impl,
  'A144_Sequestrator': A144_Sequestrator_impl,
  'A145_Ropemaker': A145_Ropemaker_impl,
  'A146_StorehouseSteward': A146_StorehouseSteward_impl,
  'A147_AnimalDealer': A147_AnimalDealer_impl,
  'A148_Woolgrower': A148_Woolgrower_impl,
  'A149_HouseArtist': A149_HouseArtist_impl,
  'A150_Stagehand': A150_Stagehand_impl,
  'A151_Minstrel': A151_Minstrel_impl,
  'A152_NightSchoolStudent': A152_NightSchoolStudent_impl,
  'A153_PigOwner': A153_PigOwner_impl,
  'A154_Paymaster': A154_Paymaster_impl,
  'A155_Conjurer': A155_Conjurer_impl,
  'A156_Buyer': A156_Buyer_impl,
  'A157_Bohemian': A157_Bohemian_impl,
  'A158_CulinaryArtist': A158_CulinaryArtist_impl,
  'A159_JoineroftheSea': A159_JoineroftheSea_impl,
  'A15_CarpentersAxe': A15_CarpentersAxe_impl,
  'A160_Lutenist': A160_Lutenist_impl,
  'A161_PatchCaretaker': A161_PatchCaretaker_impl,
  'A162_ForestTallyman': A162_ForestTallyman_impl,
  'A163_BuildingExpert': A163_BuildingExpert_impl,
  'A164_WoodWorker': A164_WoodWorker_impl,
  'A165_PigBreeder': A165_PigBreeder_impl,
  'A166_Haydryer': A166_Haydryer_impl,
  'A167_BreederBuyer': A167_BreederBuyer_impl,
  'A168_AnimalTeacher': A168_AnimalTeacher_impl,
  'A16_RammedClay': A16_RammedClay_impl,
  'A17_ReclamationPlow': A17_ReclamationPlow_impl,
  'A18_WheelPlow': A18_WheelPlow_impl,
  'A19_Handplow': A19_Handplow_impl,
  'A1_Shelter': A1_Shelter_impl,
  'A20_DoubleTurnPlow': A20_DoubleTurnPlow_impl,
  'A21_FamilyFriendHome': A21_FamilyFriendHome_impl,
  'A22_Telegram': A22_Telegram_impl,
  'A23_StoneCompany': A23_StoneCompany_impl,
  'A24_ThreshingBoard': A24_ThreshingBoard_impl,
  'A25_Bassinet': A25_Bassinet_impl,
  'A26_SleepingCorner': A26_SleepingCorner_impl,
  'A27_OvenSite': A27_OvenSite_impl,
  'A28_ForestSchool': A28_ForestSchool_impl,
  'A29_AleBenches': A29_AleBenches_impl,
  'A2_ShiftingCultivation': A2_ShiftingCultivation_impl,
  'A30_BakingSheet': A30_BakingSheet_impl,
  'A31_DebtSecurity': A31_DebtSecurity_impl,
  'A32_Manger': A32_Manger_impl,
  'A33_BigCountry': A33_BigCountry_impl,
  'A34_Loppers': A34_Loppers_impl,
  'A35_SwimmingClass': A35_SwimmingClass_impl,
  'A36_FacadesCarving': A36_FacadesCarving_impl,
  'A37_Bucksaw': A37_Bucksaw_impl,
  'A38_WoolBlankets': A38_WoolBlankets_impl,
  'A39_Chapel': A39_Chapel_impl,
  'A3_PaperKnife': A3_PaperKnife_impl,
  'A40_PottersYard': A40_PottersYard_impl,
  'A41_VegetableSlicer': A41_VegetableSlicer_impl,
  'A42_ForestLakeHut': A42_ForestLakeHut_impl,
  'A43_FarmyardManure': A43_FarmyardManure_impl,
  'A44_PondHut': A44_PondHut_impl,
  'A45_FireProtectionPond': A45_FireProtectionPond_impl,
  'A46_ClawKnife': A46_ClawKnife_impl,
  'A47_Trellises': A47_Trellises_impl,
  'A48_ShavingHorse': A48_ShavingHorse_impl,
  'A49_NestSite': A49_NestSite_impl,
  'A4_Baseboards': A4_Baseboards_impl,
  'A50_MilkJug': A50_MilkJug_impl,
  'A51_DriftNetBoat': A51_DriftNetBoat_impl,
  'A52_ThrowingAxe': A52_ThrowingAxe_impl,
  'A53_Claypipe': A53_Claypipe_impl,
  'A54_Credit': A54_Credit_impl,
  'A55_JunkRoom': A55_JunkRoom_impl,
  'A56_Basket': A56_Basket_impl,
  'A57_MilkingParlor': A57_MilkingParlor_impl,
  'A58_AsparagusKnife': A58_AsparagusKnife_impl,
  'A59_PotatoRidger': A59_PotatoRidger_impl,
  'A5_ClayEmbankment': A5_ClayEmbankment_impl,
  'A61_WinnowingFan': A61_WinnowingFan_impl,
  'A62_BeerKeg': A62_BeerKeg_impl,
  'A63_DutchWindmill': A63_DutchWindmill_impl,
  'A64_BarleyMill': A64_BarleyMill_impl,
  'A65_SeedPellets': A65_SeedPellets_impl,
  'A66_FeedingDish': A66_FeedingDish_impl,
  'A67_CornScoop': A67_CornScoop_impl,
  'A68_AsparagusGift': A68_AsparagusGift_impl,
  'A69_LargeGreenhouse': A69_LargeGreenhouse_impl,
  'A6_StorageBarn': A6_StorageBarn_impl,
  'A70_LiftingMachine': A70_LiftingMachine_impl,
  'A71_ClearingSpade': A71_ClearingSpade_impl,
  'A72_CalciumFertilizers': A72_CalciumFertilizers_impl,
  'A73_AgriculturalFertilizers': A73_AgriculturalFertilizers_impl,
  'A74_StableTree': A74_StableTree_impl,
  'A75_LumberMill': A75_LumberMill_impl,
  'A76_Cob': A76_Cob_impl,
  'A77_Hod': A77_Hod_impl,
  'A78_Canoe': A78_Canoe_impl,
  'A79_GardenHoe': A79_GardenHoe_impl,
  'A7_GardenersKnife': A7_GardenersKnife_impl,
  'A80_StoneTongs': A80_StoneTongs_impl,
  'A81_InterimStorage': A81_InterimStorage_impl,
  'A82_WorkCertificate': A82_WorkCertificate_impl,
  'A83_ShepherdsCrook': A83_ShepherdsCrook_impl,
  'A84_Silage': A84_Silage_impl,
  'A85_Homekeeper': A85_Homekeeper_impl,
  'A86_AnimalTamer': A86_AnimalTamer_impl,
  'A87_Conservator': A87_Conservator_impl,
  'A89_StablePlanner': A89_StablePlanner_impl,
  'A8_FoodBasket': A8_FoodBasket_impl,
  'A90_PlowDriver': A90_PlowDriver_impl,
  'A91_ShiftingCultivator': A91_ShiftingCultivator_impl,
  'A92_AdoptiveParents': A92_AdoptiveParents_impl,
  'A93_BedMaker': A93_BedMaker_impl,
  'A94_LazySowman': A94_LazySowman_impl,
  'A95_Angler': A95_Angler_impl,
  'A96_TaskArtisan': A96_TaskArtisan_impl,
  'A97_Freshman': A97_Freshman_impl,
  'A98_StableArchitect': A98_StableArchitect_impl,
  'A99_FellowGrazer': A99_FellowGrazer_impl,
  'A9_YoungAnimalMarket': A9_YoungAnimalMarket_impl,
  'B100_Clutterer': B100_Clutterer_impl,
  'B101_FurnitureCarpenter': B101_FurnitureCarpenter_impl,
  'B102_Consultant': B102_Consultant_impl,
  'B103_FieldMerchant': B103_FieldMerchant_impl,
  'B105_CaseBuilder': B105_CaseBuilder_impl,
  'B106_MoralCrusader': B106_MoralCrusader_impl,
  'B107_Manservant': B107_Manservant_impl,
  'B108_OvenFiringBoy': B108_OvenFiringBoy_impl,
  'B109_PaperMaker': B109_PaperMaker_impl,
  'B110_Pavior': B110_Pavior_impl,
  'B111_Rustic': B111_Rustic_impl,
  'B112_Silokeeper': B112_Silokeeper_impl,
  'B113_PatchCaregiver': B113_PatchCaregiver_impl,
  'B114_Childless': B114_Childless_impl,
  'B115_TinsmithMaster': B115_TinsmithMaster_impl,
  'B116_Shoreforester': B116_Shoreforester_impl,
  'B117_Informant': B117_Informant_impl,
  'B118_SmallscaleFarmer': B118_SmallscaleFarmer_impl,
  'B119_Lumberjack': B119_Lumberjack_impl,
  'B11_Feedyard': B11_Feedyard_impl,
  'B120_Sweep': B120_Sweep_impl,
  'B121_Geologist': B121_Geologist_impl,
  'B122_Mineralogist': B122_Mineralogist_impl,
  'B123_RoofBallaster': B123_RoofBallaster_impl,
  'B124_Trimmer': B124_Trimmer_impl,
  'B125_EstateWorker': B125_EstateWorker_impl,
  'B126_Carpenter': B126_Carpenter_impl,
  'B127_Seducer': B127_Seducer_impl,
  'B128_Plumber': B128_Plumber_impl,
  'B129_Seatmate': B129_Seatmate_impl,
  'B12_Stockyard': B12_Stockyard_impl,
  'B130_FullPeasant': B130_FullPeasant_impl,
  'B131_Equipper': B131_Equipper_impl,
  'B132_EstateMaster': B132_EstateMaster_impl,
  'B133_VillagePeasant': B133_VillagePeasant_impl,
  'B134_HousebookMaster': B134_HousebookMaster_impl,
  'B135_NutritionExpert': B135_NutritionExpert_impl,
  'B136_HouseSteward': B136_HouseSteward_impl,
  'B137_Wholesaler': B137_Wholesaler_impl,
  'B138_ForestGuardian': B138_ForestGuardian_impl,
  'B139_ForestScientist': B139_ForestScientist_impl,
  'B13_CarpentersParlor': B13_CarpentersParlor_impl,
  'B140_FarmyardWorker': B140_FarmyardWorker_impl,
  'B141_FieldCaretaker': B141_FieldCaretaker_impl,
  'B142_Greengrocer': B142_Greengrocer_impl,
  'B143_ClayWarden': B143_ClayWarden_impl,
  'B144_Collier': B144_Collier_impl,
  'B146_Illusionist': B146_Illusionist_impl,
  'B147_Huntsman': B147_Huntsman_impl,
  'B148_PetBroker': B148_PetBroker_impl,
  'B149_OpenAirFarmer': B149_OpenAirFarmer_impl,
  'B14_Hawktower': B14_Hawktower_impl,
  'B150_LargeScaleFarmer': B150_LargeScaleFarmer_impl,
  'B151_LittlePeasant': B151_LittlePeasant_impl,
  'B152_JuniorArtist': B152_JuniorArtist_impl,
  'B153_Housemaster': B153_Housemaster_impl,
  'B154_SheepKeeper': B154_SheepKeeper_impl,
  'B155_ArtTeacher': B155_ArtTeacher_impl,
  'B156_StorehouseKeeper': B156_StorehouseKeeper_impl,
  'B157_Salter': B157_Salter_impl,
  'B158_DistrictManager': B158_DistrictManager_impl,
  'B159_LieutenantGeneral': B159_LieutenantGeneral_impl,
  'B15_CarpentersBench': B15_CarpentersBench_impl,
  'B160_PubOwner': B160_PubOwner_impl,
  'B161_Weakling': B161_Weakling_impl,
  'B162_ForestClearer': B162_ForestClearer_impl,
  'B163_Pastor': B163_Pastor_impl,
  'B164_SheepWhisperer': B164_SheepWhisperer_impl,
  'B165_GameProvider': B165_GameProvider_impl,
  'B166_CattleFeeder': B166_CattleFeeder_impl,
  'B167_StableSergeant': B167_StableSergeant_impl,
  'B168_PastureMaster': B168_PastureMaster_impl,
  'B16_MiningHammer': B16_MiningHammer_impl,
  'B17_ForestPlow': B17_ForestPlow_impl,
  'B18_GrasslandHarrow': B18_GrasslandHarrow_impl,
  'B19_MoldboardPlow': B19_MoldboardPlow_impl,
  'B1_UpscaleLifestyle': B1_UpscaleLifestyle_impl,
  'B20_ChainFloat': B20_ChainFloat_impl,
  'B21_HayloftBarn': B21_HayloftBarn_impl,
  'B22_WalkingBoots': B22_WalkingBoots_impl,
  'B23_FinalScenario': B23_FinalScenario_impl,
  'B24_Lasso': B24_Lasso_impl,
  'B25_BreadPaddle': B25_BreadPaddle_impl,
  'B26_AgrarianFences': B26_AgrarianFences_impl,
  'B27_Toolbox': B27_Toolbox_impl,
  'B28_ForestryStudies': B28_ForestryStudies_impl,
  'B29_CookeryLesson': B29_CookeryLesson_impl,
  'B2_MiniPasture': B2_MiniPasture_impl,
  'B30_WoodPalisades': B30_WoodPalisades_impl,
  'B31_PotteryYard': B31_PotteryYard_impl,
  'B33_Mantlepiece': B33_Mantlepiece_impl,
  'B34_SpecialFood': B34_SpecialFood_impl,
  'B35_HookKnife': B35_HookKnife_impl,
  'B36_Bottles': B36_Bottles_impl,
  'B37_Grange': B37_Grange_impl,
  'B38_FutureBuildingSite': B38_FutureBuildingSite_impl,
  'B39_Loom': B39_Loom_impl,
  'B3_Moonshine': B3_Moonshine_impl,
  'B40_BreweryPond': B40_BreweryPond_impl,
  'B41_Hauberg': B41_Hauberg_impl,
  'B42_ForestInn': B42_ForestInn_impl,
  'B43_Chophouse': B43_Chophouse_impl,
  'B44_ChickStable': B44_ChickStable_impl,
  'B45_StrawberryPatch': B45_StrawberryPatch_impl,
  'B46_ClubHouse': B46_ClubHouse_impl,
  'B47_HerringPot': B47_HerringPot_impl,
  'B48_ForestStone': B48_ForestStone_impl,
  'B49_Scales': B49_Scales_impl,
  'B4_WoodPile': B4_WoodPile_impl,
  'B50_ButterChurn': B50_ButterChurn_impl,
  'B51_DiggingSpade': B51_DiggingSpade_impl,
  'B52_GrowingFarm': B52_GrowingFarm_impl,
  'B53_SculptureCourse': B53_SculptureCourse_impl,
  'B54_Tumbrel': B54_Tumbrel_impl,
  'B55_MaintenancePremium': B55_MaintenancePremium_impl,
  'B56_Brook': B56_Brook_impl,
  'B57_Scullery': B57_Scullery_impl,
  'B58_CrackWeeder': B58_CrackWeeder_impl,
  'B59_FoodChest': B59_FoodChest_impl,
  'B5_StoreofExperience': B5_StoreofExperience_impl,
  'B60_BrewingWater': B60_BrewingWater_impl,
  'B61_ThreeFieldRotation': B61_ThreeFieldRotation_impl,
  'B62_Pitchfork': B62_Pitchfork_impl,
  'B63_Tasting': B63_Tasting_impl,
  'B64_MillWheel': B64_MillWheel_impl,
  'B65_GrainDepot': B65_GrainDepot_impl,
  'B66_SackCart': B66_SackCart_impl,
  'B67_HandTruck': B67_HandTruck_impl,
  'B68_Beanfield': B68_Beanfield_impl,
  'B69_PottersMarket': B69_PottersMarket_impl,
  'B6_ExcursiontotheQuarry': B6_ExcursiontotheQuarry_impl,
  'B70_NewPurchase': B70_NewPurchase_impl,
  'B71_HarvestHouse': B71_HarvestHouse_impl,
  'B72_LoveforAgriculture': B72_LoveforAgriculture_impl,
  'B73_GiftBasket': B73_GiftBasket_impl,
  'B74_ThickForest': B74_ThickForest_impl,
  'B75_WoodWorkshop': B75_WoodWorkshop_impl,
  'B76_Ceilings': B76_Ceilings_impl,
  'B77_LoamPit': B77_LoamPit_impl,
  'B78_ReedBelt': B78_ReedBelt_impl,
  'B79_Corf': B79_Corf_impl,
  'B7_Wage': B7_Wage_impl,
  'B81_Handcart': B81_Handcart_impl,
  'B82_ValueAssets': B82_ValueAssets_impl,
  'B83_MuddyPuddles': B83_MuddyPuddles_impl,
  'B84_AcornsBasket': B84_AcornsBasket_impl,
  'B85_FarmHand': B85_FarmHand_impl,
  'B86_TruffleSearcher': B86_TruffleSearcher_impl,
  'B87_Cottager': B87_Cottager_impl,
  'B88_EstablishedPerson': B88_EstablishedPerson_impl,
  'B89_Groom': B89_Groom_impl,
  'B8_MarketStall': B8_MarketStall_impl,
  'B90_CooperativePlower': B90_CooperativePlower_impl,
  'B91_AssistantTiller': B91_AssistantTiller_impl,
  'B92_LittleStickKnitter': B92_LittleStickKnitter_impl,
  'B93_Confidant': B93_Confidant_impl,
  'B94_StockProtector': B94_StockProtector_impl,
  'B95_MasterBricklayer': B95_MasterBricklayer_impl,
  'B96_TreeFarmJoiner': B96_TreeFarmJoiner_impl,
  'B97_Scholar': B97_Scholar_impl,
  'B98_OrganicFarmer': B98_OrganicFarmer_impl,
  'B99_Tutor': B99_Tutor_impl,
  'B9_BeatingRod': B9_BeatingRod_impl,
  'C100_Butler': C100_Butler_impl,
  'C101_StallHolder': C101_StallHolder_impl,
  'C102_TreeGuard': C102_TreeGuard_impl,
  'C103_GreenGrocer': C103_GreenGrocer_impl,
  'C104_Collector': C104_Collector_impl,
  'C106_PotatoHarvester': C106_PotatoHarvester_impl,
  'C107_Baker': C107_Baker_impl,
  'C108_Layabout': C108_Layabout_impl,
  'C10_BunkBeds': C10_BunkBeds_impl,
  'C110_HomeBrewer': C110_HomeBrewer_impl,
  'C111_SmallAnimalBreeder': C111_SmallAnimalBreeder_impl,
  'C112_Thresher': C112_Thresher_impl,
  'C113_WinterCaretaker': C113_WinterCaretaker_impl,
  'C114_SoilScientist': C114_SoilScientist_impl,
  'C115_Sower': C115_Sower_impl,
  'C116_FurnitureMaker': C116_FurnitureMaker_impl,
  'C117_Legworker': C117_Legworker_impl,
  'C118_WoodCollector': C118_WoodCollector_impl,
  'C119_SkillfulRenovator': C119_SkillfulRenovator_impl,
  'C11_WildlifeReserve': C11_WildlifeReserve_impl,
  'C120_AgriculturalLabourer': C120_AgriculturalLabourer_impl,
  'C121_ClayKneader': C121_ClayKneader_impl,
  'C122_Bricklayer': C122_Bricklayer_impl,
  'C123_Freemason': C123_Freemason_impl,
  'C124_StoneImporter': C124_StoneImporter_impl,
  'C125_Nightworker': C125_Nightworker_impl,
  'C126_Excavator': C126_Excavator_impl,
  'C127_Lover': C127_Lover_impl,
  'C128_WoodenHutExtender': C128_WoodenHutExtender_impl,
  'C129_SecondSpouse': C129_SecondSpouse_impl,
  'C12_CattleFarm': C12_CattleFarm_impl,
  'C130_OutskirtsDirector': C130_OutskirtsDirector_impl,
  'C131_PrivateTeacher': C131_PrivateTeacher_impl,
  'C132_TimberShingleMaker': C132_TimberShingleMaker_impl,
  'C133_Soldier': C133_Soldier_impl,
  'C134_CowPrince': C134_CowPrince_impl,
  'C135_Constable': C135_Constable_impl,
  'C136_RanchProvost': C136_RanchProvost_impl,
  'C137_CharcoalBurner': C137_CharcoalBurner_impl,
  'C138_AnimalFeeder': C138_AnimalFeeder_impl,
  'C139_BasketmakersWife': C139_BasketmakersWife_impl,
  'C140_PackagingArtist': C140_PackagingArtist_impl,
  'C141_SheepProvider': C141_SheepProvider_impl,
  'C142_MarketCrier': C142_MarketCrier_impl,
  'C143_StoneBuyer': C143_StoneBuyer_impl,
  'C144_ReedRoofRenovator': C144_ReedRoofRenovator_impl,
  'C145_ForestReviewer': C145_ForestReviewer_impl,
  'C146_WorkshopAssistant': C146_WorkshopAssistant_impl,
  'C147_Cowherd': C147_Cowherd_impl,
  'C148_MudWallower': C148_MudWallower_impl,
  'C149_ResourceRecycler': C149_ResourceRecycler_impl,
  'C150_ParrotBreeder': C150_ParrotBreeder_impl,
  'C151_SowingDirector': C151_SowingDirector_impl,
  'C152_Puppeteer': C152_Puppeteer_impl,
  'C153_PatternMaker': C153_PatternMaker_impl,
  'C154_TwinResearcher': C154_TwinResearcher_impl,
  'C155_FoodDistributor': C155_FoodDistributor_impl,
  'C156_HoofCaregiver': C156_HoofCaregiver_impl,
  'C157_ResourceAnalyzer': C157_ResourceAnalyzer_impl,
  'C158_ForestCampaigner': C158_ForestCampaigner_impl,
  'C159_FishermansFriend': C159_FishermansFriend_impl,
  'C15_Trellis': C15_Trellis_impl,
  'C160_Outrider': C160_Outrider_impl,
  'C161_PotatoDigger': C161_PotatoDigger_impl,
  'C162_ForestOwner': C162_ForestOwner_impl,
  'C163_MaterialDeliveryman': C163_MaterialDeliveryman_impl,
  'C164_GermanHeathKeeper': C164_GermanHeathKeeper_impl,
  'C165_GameCatcher': C165_GameCatcher_impl,
  'C166_CattleWhisperer': C166_CattleWhisperer_impl,
  'C167_CattleBuyer': C167_CattleBuyer_impl,
  'C168_AnimalCatcher': C168_AnimalCatcher_impl,
  'C16_FieldFences': C16_FieldFences_impl,
  'C17_NewlyPlowedField': C17_NewlyPlowedField_impl,
  'C18_RollOverPlow': C18_RollOverPlow_impl,
  'C19_SwingPlow': C19_SwingPlow_impl,
  'C1_Overhaul': C1_Overhaul_impl,
  'C20_MolePlow': C20_MolePlow_impl,
  'C21_HeartofStone': C21_HeartofStone_impl,
  'C22_BasketChair': C22_BasketChair_impl,
  'C23_JobContract': C23_JobContract_impl,
  'C24_BedintheGrainField': C24_BedintheGrainField_impl,
  'C25_SteamMachine': C25_SteamMachine_impl,
  'C26_Flail': C26_Flail_impl,
  'C27_Blueprint': C27_Blueprint_impl,
  'C28_TeachersDesk': C28_TeachersDesk_impl,
  'C29_BeerTable': C29_BeerTable_impl,
  'C2_Stable': C2_Stable_impl,
  'C30_HalfTimberedHouse': C30_HalfTimberedHouse_impl,
  'C31_WritingChamber': C31_WritingChamber_impl,
  'C33_GreeningPlan': C33_GreeningPlan_impl,
  'C34_ElephantgrassPlant': C34_ElephantgrassPlant_impl,
  'C35_LanternHouse': C35_LanternHouse_impl,
  'C36_ClayDeposit': C36_ClayDeposit_impl,
  'C37_DwellingMound': C37_DwellingMound_impl,
  'C38_Christianity': C38_Christianity_impl,
  'C39_StudioBoat': C39_StudioBoat_impl,
  'C3_CarriageTrip': C3_CarriageTrip_impl,
  'C40_CanvasSack': C40_CanvasSack_impl,
  'C41_FarmStore': C41_FarmStore_impl,
  'C42_RavenousHunger': C42_RavenousHunger_impl,
  'C43_FarmBuilding': C43_FarmBuilding_impl,
  'C44_ChickenCoop': C44_ChickenCoop_impl,
  'C45_Stew': C45_Stew_impl,
  'C46_Mandoline': C46_Mandoline_impl,
  'C47_GardenClaw': C47_GardenClaw_impl,
  'C48_Farmstead': C48_Farmstead_impl,
  'C49_BeerStall': C49_BeerStall_impl,
  'C4_WritingBoards': C4_WritingBoards_impl,
  'C50_StableYard': C50_StableYard_impl,
  'C51_FishingNet': C51_FishingNet_impl,
  'C52_HuntsmansHat': C52_HuntsmansHat_impl,
  'C53_GypsysCrock': C53_GypsysCrock_impl,
  'C54_MarketBooth': C54_MarketBooth_impl,
  'C55_Studio': C55_Studio_impl,
  'C56_FeedFence': C56_FeedFence_impl,
  'C57_Crudite': C57_Crudite_impl,
  'C58_Woodcraft': C58_Woodcraft_impl,
  'C59_SchnappsDistillery': C59_SchnappsDistillery_impl,
  'C5_Remodeling': C5_Remodeling_impl,
  'C60_SmallPottersOven': C60_SmallPottersOven_impl,
  'C61_BeerStein': C61_BeerStein_impl,
  'C63_CraftBrewery': C63_CraftBrewery_impl,
  'C64_CornSchnappsDistillery': C64_CornSchnappsDistillery_impl,
  'C65_Granary': C65_Granary_impl,
  'C66_EternalRyeCultivation': C66_EternalRyeCultivation_impl,
  'C67_MineralFeeder': C67_MineralFeeder_impl,
  'C68_Bookcase': C68_Bookcase_impl,
  'C69_LandConsolidation': C69_LandConsolidation_impl,
  'C6_StoneClearing': C6_StoneClearing_impl,
  'C70_LettucePatch': C70_LettucePatch_impl,
  'C71_Slurry': C71_Slurry_impl,
  'C71_SlurrySpreader': C71_SlurrySpreader_impl,
  'C72_FestivalPlanning': C72_FestivalPlanning_impl,
  'C73_SeaweedFertilizer': C73_SeaweedFertilizer_impl,
  'C74_PrivateForest': C74_PrivateForest_impl,
  'C75_Firewood': C75_Firewood_impl,
  'C76_WoodCart': C76_WoodCart_impl,
  'C77_ClaySupply': C77_ClaySupply_impl,
  'C78_ReedHattedToad': C78_ReedHattedToad_impl,
  'C79_StoneCart': C79_StoneCart_impl,
  'C7_BladeShears': C7_BladeShears_impl,
  'C80_RockyTerrain': C80_RockyTerrain_impl,
  'C81_MaterialHub': C81_MaterialHub_impl,
  'C82_HardwareStore': C82_HardwareStore_impl,
  'C83_EarlyCattle': C83_EarlyCattle_impl,
  'C84_PerennialRye': C84_PerennialRye_impl,
  'C85_DenBuilder': C85_DenBuilder_impl,
  'C86_LivestockFeeder': C86_LivestockFeeder_impl,
  'C87_Mason': C87_Mason_impl,
  'C88_CarpentersApprentice': C88_CarpentersApprentice_impl,
  'C89_StableMaster': C89_StableMaster_impl,
  'C8_PlantFertilizer': C8_PlantFertilizer_impl,
  'C90_FieldWatchman': C90_FieldWatchman_impl,
  'C91_PlowHero': C91_PlowHero_impl,
  'C92_AutumnMother': C92_AutumnMother_impl,
  'C93_InnerDistrictsDirector': C93_InnerDistrictsDirector_impl,
  'C94_StableCleaner': C94_StableCleaner_impl,
  'C95_BasketWeaver': C95_BasketWeaver_impl,
  'C96_Merchant': C96_Merchant_impl,
  'C97_SeedResearcher': C97_SeedResearcher_impl,
  'C98_CubeCutter': C98_CubeCutter_impl,
  'C99_GardenDesigner': C99_GardenDesigner_impl,
  'C9_AutomaticWaterTrough': C9_AutomaticWaterTrough_impl,
  'D100_LordoftheManor': D100_LordoftheManor_impl,
  'D101_SugarBaker': D101_SugarBaker_impl,
  'D102_SampleStableMaker': D102_SampleStableMaker_impl,
  'D103_CanalBoatman': D103_CanalBoatman_impl,
  'D104_Cultivator': D104_Cultivator_impl,
  'D105_Sculptor': D105_Sculptor_impl,
  'D106_WhiskyDistiller': D106_WhiskyDistiller_impl,
  'D107_Bellfounder': D107_Bellfounder_impl,
  'D109_SowingMaster': D109_SowingMaster_impl,
  'D10_StorksNest': D10_StorksNest_impl,
  'D110_FishFarmer': D110_FishFarmer_impl,
  'D111_InteriorDecorator': D111_InteriorDecorator_impl,
  'D112_YoungFarmer': D112_YoungFarmer_impl,
  'D113_FoodMerchant': D113_FoodMerchant_impl,
  'D114_SeedTrader': D114_SeedTrader_impl,
  'D115_FodderPlanter': D115_FodderPlanter_impl,
  'D116_TreeInspector': D116_TreeInspector_impl,
  'D117_WoodExpert': D117_WoodExpert_impl,
  'D118_Bonehead': D118_Bonehead_impl,
  'D119_WoodBarterer': D119_WoodBarterer_impl,
  'D11_LawnFertilizer': D11_LawnFertilizer_impl,
  'D120_ClayDeliveryman': D120_ClayDeliveryman_impl,
  'D121_ClayPlasterer': D121_ClayPlasterer_impl,
  'D122_ClayCarrier': D122_ClayCarrier_impl,
  'D123_RenovationPreparer': D123_RenovationPreparer_impl,
  'D124_Emissary': D124_Emissary_impl,
  'D125_ForestTrader': D125_ForestTrader_impl,
  'D126_FieldCultivator': D126_FieldCultivator_impl,
  'D127_HardworkingMan': D127_HardworkingMan_impl,
  'D128_BuildingTycoon': D128_BuildingTycoon_impl,
  'D129_LumberVirtuoso': D129_LumberVirtuoso_impl,
  'D12_MilkingPlace': D12_MilkingPlace_impl,
  'D130_RecreationalCarpenter': D130_RecreationalCarpenter_impl,
  'D131_CraftsmanshipPromoter': D131_CraftsmanshipPromoter_impl,
  'D132_HideFarmer': D132_HideFarmer_impl,
  'D133_BeerTentOperator': D133_BeerTentOperator_impl,
  'D134_OysterEater': D134_OysterEater_impl,
  'D135_GardeningHeadOfficial': D135_GardeningHeadOfficial_impl,
  'D136_AnimalActivist': D136_AnimalActivist_impl,
  'D137_TradeTeacher': D137_TradeTeacher_impl,
  'D138_PetLover': D138_PetLover_impl,
  'D139_Chairman': D139_Chairman_impl,
  'D13_Trowel': D13_Trowel_impl,
  'D140_Loudmouth': D140_Loudmouth_impl,
  'D141_SeedSeller': D141_SeedSeller_impl,
  'D142_PotatoPlanter': D142_PotatoPlanter_impl,
  'D143_TreeCutter': D143_TreeCutter_impl,
  'D144_WaterWorker': D144_WaterWorker_impl,
  'D145_RoofExaminer': D145_RoofExaminer_impl,
  'D146_Porter': D146_Porter_impl,
  'D147_TrapBuilder': D147_TrapBuilder_impl,
  'D148_DomesticianExpert': D148_DomesticianExpert_impl,
  'D149_CasualWorker': D149_CasualWorker_impl,
  'D14_HammerCrusher': D14_HammerCrusher_impl,
  'D150_GodlySpouse': D150_GodlySpouse_impl,
  'D151_SpinDoctor': D151_SpinDoctor_impl,
  'D152_Patron': D152_Patron_impl,
  'D153_WealthyMan': D153_WealthyMan_impl,
  'D154_ChimneySweep': D154_ChimneySweep_impl,
  'D156_RetailDealer': D156_RetailDealer_impl,
  'D157_PartyOrganizer': D157_PartyOrganizer_impl,
  'D158_BeanCounter': D158_BeanCounter_impl,
  'D15_ClaySupports': D15_ClaySupports_impl,
  'D160_Midwife': D160_Midwife_impl,
  'D161_CabbageBuyer': D161_CabbageBuyer_impl,
  'D162_ClayFirer': D162_ClayFirer_impl,
  'D163_JourneymanBricklayer': D163_JourneymanBricklayer_impl,
  'D164_PetGrower': D164_PetGrower_impl,
  'D165_PigStalker': D165_PigStalker_impl,
  'D166_StableMilker': D166_StableMilker_impl,
  'D167_PureBreeder': D167_PureBreeder_impl,
  'D168_Stockman': D168_Stockman_impl,
  'D16_WoodenWheyBucket': D16_WoodenWheyBucket_impl,
  'D17_DrillHarrow': D17_DrillHarrow_impl,
  'D18_SteamPlow': D18_SteamPlow_impl,
  'D19_PulverizerPlow': D19_PulverizerPlow_impl,
  'D1_ZigzagHarrow': D1_ZigzagHarrow_impl,
  'D20_TurnwrestPlow': D20_TurnwrestPlow_impl,
  'D21_Recruitment': D21_Recruitment_impl,
  'D22_WorkPermit': D22_WorkPermit_impl,
  'D23_PioneeringSpirit': D23_PioneeringSpirit_impl,
  'D24_BrotherlyLove': D24_BrotherlyLove_impl,
  'D25_WitchesDanceFloor': D25_WitchesDanceFloor_impl,
  'D26_CarpentersYard': D26_CarpentersYard_impl,
  'D27_Retraining': D27_Retraining_impl,
  'D28_WritingDesk': D28_WritingDesk_impl,
  'D29_MuckRake': D29_MuckRake_impl,
  'D2_DwellingPlan': D2_DwellingPlan_impl,
  'D30_ArtisanDistrict': D30_ArtisanDistrict_impl,
  'D31_Storeroom': D31_Storeroom_impl,
  'D32_WoodRake': D32_WoodRake_impl,
  'D33_SummerHouse': D33_SummerHouse_impl,
  'D34_LuxuriousHostel': D34_LuxuriousHostel_impl,
  'D35_FodderChamber': D35_FodderChamber_impl,
  'D36_BreedRegistry': D36_BreedRegistry_impl,
  'D38_MilkingStool': D38_MilkingStool_impl,
  'D39_TruffleSlicer': D39_TruffleSlicer_impl,
  'D3_Furrows': D3_Furrows_impl,
  'D40_Cesspit': D40_Cesspit_impl,
  'D41_HorseDrawnBoat': D41_HorseDrawnBoat_impl,
  'D42_EducationBonus': D42_EducationBonus_impl,
  'D43_Hutch': D43_Hutch_impl,
  'D44_ForestWell': D44_ForestWell_impl,
  'D45_SheepWell': D45_SheepWell_impl,
  'D46_PelletPress': D46_PelletPress_impl,
  'D47_Churchyard': D47_Churchyard_impl,
  'D48_CivicFacade': D48_CivicFacade_impl,
  'D49_Bookshelf': D49_Bookshelf_impl,
  'D4_CrossCutWood': D4_CrossCutWood_impl,
  'D50_ForeignAid': D50_ForeignAid_impl,
  'D51_Archway': D51_Archway_impl,
  'D52_RollingPin': D52_RollingPin_impl,
  'D53_TeaHouse': D53_TeaHouse_impl,
  'D54_TroutPool': D54_TroutPool_impl,
  'D55_NewMarket': D55_NewMarket_impl,
  'D56_FatstockStretcher': D56_FatstockStretcher_impl,
  'D57_WholesaleMarket': D57_WholesaleMarket_impl,
  'D58_Gritter': D58_Gritter_impl,
  'D5_FieldClay': D5_FieldClay_impl,
  'D60_LargePottery': D60_LargePottery_impl,
  'D61_BaleofStraw': D61_BaleofStraw_impl,
  'D62_BeerTap': D62_BeerTap_impl,
  'D63_Lynchet': D63_Lynchet_impl,
  'D64_BakingCourse': D64_BakingCourse_impl,
  'D65_GrainSieve': D65_GrainSieve_impl,
  'D66_PotterCeramics': D66_PotterCeramics_impl,
  'D67_ReapHook': D67_ReapHook_impl,
  'D68_SmallBasket': D68_SmallBasket_impl,
  'D69_SmallGreenhouse': D69_SmallGreenhouse_impl,
  'D6_PetrifiedWood': D6_PetrifiedWood_impl,
  'D70_StrawManure': D70_StrawManure_impl,
  'D71_Changeover': D71_Changeover_impl,
  'D72_StableManure': D72_StableManure_impl,
  'D73_SupplyBoat': D73_SupplyBoat_impl,
  'D74_RoyalWood': D74_RoyalWood_impl,
  'D76_SocialBenefits': D76_SocialBenefits_impl,
  'D77_RecycledBrick': D77_RecycledBrick_impl,
  'D78_ReedPond': D78_ReedPond_impl,
  'D79_CarrotMuseum': D79_CarrotMuseum_impl,
  'D7_Trident': D7_Trident_impl,
  'D80_BrickHammer': D80_BrickHammer_impl,
  'D81_RoofLadder': D81_RoofLadder_impl,
  'D82_HuntingTrophy': D82_HuntingTrophy_impl,
  'D83_Pigswill': D83_Pigswill_impl,
  'D84_FeedPellets': D84_FeedPellets_impl,
  'D85_Reader': D85_Reader_impl,
  'D86_SheepAgent': D86_SheepAgent_impl,
  'D87_MasterBuilder': D87_MasterBuilder_impl,
  'D88_Millwright': D88_Millwright_impl,
  'D89_Stablehand': D89_Stablehand_impl,
  'D8_FernSeeds': D8_FernSeeds_impl,
  'D90_PlowMaker': D90_PlowMaker_impl,
  'D91_Plowman': D91_Plowman_impl,
  'D92_ChildOmbudsman': D92_ChildOmbudsman_impl,
  'D93_SheepInspector': D93_SheepInspector_impl,
  'D94_HenpeckedHusband': D94_HenpeckedHusband_impl,
  'D95_SiteManager': D95_SiteManager_impl,
  'D96_Furnisher': D96_Furnisher_impl,
  'D97_BeggingStudent': D97_BeggingStudent_impl,
  'D98_Transactor': D98_Transactor_impl,
  'D99_EarthenwarePotter': D99_EarthenwarePotter_impl,
  'D9_GameTrade': D9_GameTrade_impl,
  'E100_MuseumCaretaker': E100_MuseumCaretaker_impl,
  'E101_Blighter': E101_Blighter_impl,
  'E102_Acquirer': E102_Acquirer_impl,
  'E103_Wolf': E103_Wolf_impl,
  'E104_SpiceTrader': E104_SpiceTrader_impl,
  'E105_Pioneer': E105_Pioneer_impl,
  'E106_EmergencySeller': E106_EmergencySeller_impl,
  'E107_LandSurveyor': E107_LandSurveyor_impl,
  'E108_BlackberryFarmer': E108_BlackberryFarmer_impl,
  'E109_BraidMaker': E109_BraidMaker_impl,
  'E10_StrawHat': E10_StrawHat_impl,
  'E110_Dentist': E110_Dentist_impl,
  'E111_Recluse': E111_Recluse_impl,
  'E112_GrainThief': E112_GrainThief_impl,
  'E113_Godmother': E113_Godmother_impl,
  'E114_ShedBuilder': E114_ShedBuilder_impl,
  'E115_SeedServant': E115_SeedServant_impl,
  'E116_FirCutter': E116_FirCutter_impl,
  'E117_PipeSmoker': E117_PipeSmoker_impl,
  'E118_KindlingGatherer': E118_KindlingGatherer_impl,
  'E119_LandHeir': E119_LandHeir_impl,
  'E11_PettingZoo': E11_PettingZoo_impl,
  'E120_ScrapCollector': E120_ScrapCollector_impl,
  'E121_HillCultivator': E121_HillCultivator_impl,
  'E122_Cottar': E122_Cottar_impl,
  'E123_ResourceHoarder': E123_ResourceHoarder_impl,
  'E124_MayorCandidate': E124_MayorCandidate_impl,
  'E125_DelayedWayfarer': E125_DelayedWayfarer_impl,
  'E126_TaxCollector': E126_TaxCollector_impl,
  'E127_DiligentFarmer': E127_DiligentFarmer_impl,
  'E128_Saddler': E128_Saddler_impl,
  'E129_Imitator': E129_Imitator_impl,
  'E12_AnimalBedding': E12_AnimalBedding_impl,
  'E130_Overachiever': E130_Overachiever_impl,
  'E131_MarketMaster': E131_MarketMaster_impl,
  'E132_VeggieLover': E132_VeggieLover_impl,
  'E133_ChampionBreeder': E133_ChampionBreeder_impl,
  'E134_Omnifarmer': E134_Omnifarmer_impl,
  'E135_Pickler': E135_Pickler_impl,
  'E136_AnimalHusbandryWorker': E136_AnimalHusbandryWorker_impl,
  'E137_FlaxFarmer': E137_FlaxFarmer_impl,
  'E138_LivestockExpert': E138_LivestockExpert_impl,
  'E139_BunnyBreeder': E139_BunnyBreeder_impl,
  'E13_StoneHouseReconstruction': E13_StoneHouseReconstruction_impl,
  'E140_Carter': E140_Carter_impl,
  'E141_VegetableVendor': E141_VegetableVendor_impl,
  'E142_Smuggler': E142_Smuggler_impl,
  'E143_Hewer': E143_Hewer_impl,
  'E144_WaresSalesman': E144_WaresSalesman_impl,
  'E145_Parvenu': E145_Parvenu_impl,
  'E146_Reseller': E146_Reseller_impl,
  'E147_AnimalDriver': E147_AnimalDriver_impl,
  'E148_Lazybones': E148_Lazybones_impl,
  'E14_WoodSaw': E14_WoodSaw_impl,
  'E150_RockBeater': E150_RockBeater_impl,
  'E151_DeliveryNurse': E151_DeliveryNurse_impl,
  'E152_BargainHunter': E152_BargainHunter_impl,
  'E154_Margrave': E154_Margrave_impl,
  'E155_Visionary': E155_Visionary_impl,
  'E156_ClaypitOwner': E156_ClaypitOwner_impl,
  'E157_Usufructuary': E157_Usufructuary_impl,
  'E158_StoneCustodian': E158_StoneCustodian_impl,
  'E159_OldMiser': E159_OldMiser_impl,
  'E15_NailBasket': E15_NailBasket_impl,
  'E160_KelpGatherer': E160_KelpGatherer_impl,
  'E161_ElderBaker': E161_ElderBaker_impl,
  'E162_Entrepreneur': E162_Entrepreneur_impl,
  'E163_Patroness': E163_Patroness_impl,
  'E164_MountainPlowman': E164_MountainPlowman_impl,
  'E165_MasterHuntsman': E165_MasterHuntsman_impl,
  'E166_Roastmaster': E166_Roastmaster_impl,
  'E167_DairyCrier': E167_DairyCrier_impl,
  'E168_AnimalTamersApprentice': E168_AnimalTamersApprentice_impl,
  'E16_BriarHedge': E16_BriarHedge_impl,
  'E17_SkimmerPlow': E17_SkimmerPlow_impl,
  'E18_SeedAlmanac': E18_SeedAlmanac_impl,
  'E19_OxGoad': E19_OxGoad_impl,
  'E1_PoleBarns': E1_PoleBarns_impl,
  'E20_IronHoe': E20_IronHoe_impl,
  'E21_SheepRug': E21_SheepRug_impl,
  'E22_GuestRoom': E22_GuestRoom_impl,
  'E23_Apiary': E23_Apiary_impl,
  'E24_Ambition': E24_Ambition_impl,
  'E25_BumperCrop': E25_BumperCrop_impl,
  'E26_Sundial': E26_Sundial_impl,
  'E27_PiggyBank': E27_PiggyBank_impl,
  'E28_Bookmark': E28_Bookmark_impl,
  'E2_RenovationMaterials': E2_RenovationMaterials_impl,
  'E30_ChildsToy': E30_ChildsToy_impl,
  'E31_Upholstery': E31_Upholstery_impl,
  'E32_Nave': E32_Nave_impl,
  'E33_BeaverColony': E33_BeaverColony_impl,
  'E34_LandRegister': E34_LandRegister_impl,
  'E35_Misanthropy': E35_Misanthropy_impl,
  'E36_HerbalGarden': E36_HerbalGarden_impl,
  'E37_OxSkull': E37_OxSkull_impl,
  'E38_RodCollection': E38_RodCollection_impl,
  'E39_Paintbrush': E39_Paintbrush_impl,
  'E3_TeaTime': E3_TeaTime_impl,
  'E40_BeeStatue': E40_BeeStatue_impl,
  'E41_MuddyWaters': E41_MuddyWaters_impl,
  'E42_WaterGully': E42_WaterGully_impl,
  'E43_BarnCats': E43_BarnCats_impl,
  'E44_FodderBeets': E44_FodderBeets_impl,
  'E45_FruitLadder': E45_FruitLadder_impl,
  'E46_WaterlilyPond': E46_WaterlilyPond_impl,
  'E47_SyrupTap': E47_SyrupTap_impl,
  'E48_TownHall': E48_TownHall_impl,
  'E49_Twibil': E49_Twibil_impl,
  'E4_Thunderbolt': E4_Thunderbolt_impl,
  'E50_WildGreens': E50_WildGreens_impl,
  'E51_WhaleOil': E51_WhaleOil_impl,
  'E52_Cubbyhole': E52_Cubbyhole_impl,
  'E53_BoarSpear': E53_BoarSpear_impl,
  'E54_Contraband': E54_Contraband_impl,
  'E55_StoneWeir': E55_StoneWeir_impl,
  'E56_RomanPot': E56_RomanPot_impl,
  'E57_CheeseFondue': E57_CheeseFondue_impl,
  'E58_LunchtimeBeer': E58_LunchtimeBeer_impl,
  'E59_CombandCutter': E59_CombandCutter_impl,
  'E5_NightLoot': E5_NightLoot_impl,
  'E60_WorkingGloves': E60_WorkingGloves_impl,
  'E61_RaisedBed': E61_RaisedBed_impl,
  'E62_SourDough': E62_SourDough_impl,
  'E63_IronOven': E63_IronOven_impl,
  'E64_SimpleOven': E64_SimpleOven_impl,
  'E65_Almsbag': E65_Almsbag_impl,
  'E66_BarnShed': E66_BarnShed_impl,
  'E67_GrainBag': E67_GrainBag_impl,
  'E68_CherryOrchard': E68_CherryOrchard_impl,
  'E69_MelonPatch': E69_MelonPatch_impl,
  'E6_Recount': E6_Recount_impl,
  'E70_CropRotationField': E70_CropRotationField_impl,
  'E71_CowPatty': E71_CowPatty_impl,
  'E72_ArtichokeField': E72_ArtichokeField_impl,
  'E73_Scythe': E73_Scythe_impl,
  'E74_AshTrees': E74_AshTrees_impl,
  'E75_StoneAxe': E75_StoneAxe_impl,
  'E76_LumberPile': E76_LumberPile_impl,
  'E77_Mattock': E77_Mattock_impl,
  'E78_SleightofHand': E78_SleightofHand_impl,
  'E79_FieldSpade': E79_FieldSpade_impl,
  'E7_Pumpernickel': E7_Pumpernickel_impl,
  'E81_AlchemistsLab': E81_AlchemistsLab_impl,
  'E82_Profiteering': E82_Profiteering_impl,
  'E83_ShepherdsWhistle': E83_ShepherdsWhistle_impl,
  'E84_DollysMother': E84_DollysMother_impl,
  'E85_MasterTanner': E85_MasterTanner_impl,
  'E86_PenBuilder': E86_PenBuilder_impl,
  'E87_MasterRenovator': E87_MasterRenovator_impl,
  'E88_MasterFencer': E88_MasterFencer_impl,
  'E89_Stallwright': E89_Stallwright_impl,
  'E8_FarmersMarket': E8_FarmersMarket_impl,
  'E90_DungCollector': E90_DungCollector_impl,
  'E91_PlowBuilder': E91_PlowBuilder_impl,
  'E92_FieldDoctor': E92_FieldDoctor_impl,
  'E93_Motivator': E93_Motivator_impl,
  'E94_Prophet': E94_Prophet_impl,
  'E95_Miller': E95_Miller_impl,
  'E96_Elder': E96_Elder_impl,
  'E97_Beneficiary': E97_Beneficiary_impl,
  'E98_Prodigy': E98_Prodigy_impl,
  'E99_UncaringParents': E99_UncaringParents_impl,
  'E9_BarteringHut': E9_BarteringHut_impl,
  'CUSTOM_FixtureHarvester': CUSTOM_FixtureHarvester_impl,
}

export type AllCardImpls = typeof ALL_CARD_IMPLS
