import { describe, expect, it } from 'vitest'
import { allMinorImprovementCards, allOccupationCards } from '../catalog'
import { C039_StudioBoat } from '../../cards/C/C039_StudioBoat'

const expectedCategories: Record<string, string> = {
  'A011_MudPatch': 'FARM_PLANNER',
  'A132_Publican': 'POINTS_PROVIDER',
  'A150_Stagehand': 'ACTIONS_BOOSTER',
  'A154_Paymaster': 'POINTS_PROVIDER',
  'A160_Lutenist': 'CROP_PROVIDER',
  'A025_Bassinet': 'ACTIONS_BOOSTER',
  'A086_AnimalTamer': 'FARM_PLANNER',
  'A087_Conservator': 'FARM_PLANNER',
  'B102_Consultant': 'GOODS_PROVIDER',
  'B105_CaseBuilder': 'GOODS_PROVIDER',
  'B119_Lumberjack': 'BUILDING_RESOURCE_PROVIDER',
  'B011_Feedyard': 'FARM_PLANNER',
  'B123_RoofBallaster': 'BUILDING_RESOURCE_PROVIDER',
  'B138_ForestGuardian': 'GOODS_PROVIDER',
  'B164_SheepWhisperer': 'LIVESTOCK_PROVIDER',
  'B167_StableSergeant': 'LIVESTOCK_PROVIDER',
  'B022_WalkingBoots': 'ACTIONS_BOOSTER',
  'B041_Hauberg': 'GOODS_PROVIDER',
  'B044_ChickStable': 'FOOD_PROVIDER',
  'B045_StrawberryPatch': 'FOOD_PROVIDER',
  'B046_ClubHouse': 'FOOD_PROVIDER',
  'B052_GrowingFarm': 'FOOD_PROVIDER',
  'B059_FoodChest': 'FOOD_PROVIDER',
  'B074_ThickForest': 'BUILDING_RESOURCE_PROVIDER',
  'B078_ReedBelt': 'BUILDING_RESOURCE_PROVIDER',
  'B007_Wage': 'FOOD_PROVIDER',
  'B084_AcornsBasket': 'LIVESTOCK_PROVIDER',
  'B093_Confidant': 'ACTIONS_BOOSTER',
  'B096_TreeFarmJoiner': 'ACTIONS_BOOSTER',
  'B009_BeatingRod': 'GOODS_PROVIDER',
  'C112_Thresher': 'CROP_PROVIDER',
  'C118_WoodCollector': 'BUILDING_RESOURCE_PROVIDER',
  'C011_WildlifeReserve': 'FARM_PLANNER',
  'C129_SecondSpouse': 'ACTIONS_BOOSTER',
  'C012_CattleFarm': 'FARM_PLANNER',
  'C145_ForestReviewer': 'ACTIONS_BOOSTER',
  'C149_ResourceRecycler': 'FARM_PLANNER',
  'C151_SowingDirector': 'ACTIONS_BOOSTER',
  'C153_PatternMaker': 'POINTS_PROVIDER',
  'C163_MaterialDeliveryman': 'ACTIONS_BOOSTER',
  'C165_GameCatcher': 'LIVESTOCK_PROVIDER',
  'C166_CattleWhisperer': 'LIVESTOCK_PROVIDER',
  'C167_CattleBuyer': 'LIVESTOCK_PROVIDER',
  'C039_StudioBoat': 'POINTS_PROVIDER',
  'C004_WritingBoards': 'BUILDING_RESOURCE_PROVIDER',
  'C059_SchnappsDistillery': 'FOOD_PROVIDER',
  'C074_PrivateForest': 'BUILDING_RESOURCE_PROVIDER',
  'C077_ClaySupply': 'BUILDING_RESOURCE_PROVIDER',
  'C078_ReedHattedToad': 'BUILDING_RESOURCE_PROVIDER',
  'C079_StoneCart': 'BUILDING_RESOURCE_PROVIDER',
  'C007_BladeShears': 'FOOD_PROVIDER',
  'C083_EarlyCattle': 'LIVESTOCK_PROVIDER',
  'C089_StableMaster': 'FARM_PLANNER',
  'C009_AutomaticWaterTrough': 'LIVESTOCK_PROVIDER',
  'D113_FoodMerchant': 'CROP_PROVIDER',
  'D118_Bonehead': 'BUILDING_RESOURCE_PROVIDER',
  'D128_BuildingTycoon': 'FARM_PLANNER',
  'D012_MilkingPlace': 'FARM_PLANNER',
  'D149_CasualWorker': 'FARM_PLANNER',
  'D152_Patron': 'ACTIONS_BOOSTER',
  'D163_JourneymanBricklayer': 'BUILDING_RESOURCE_PROVIDER',
  'D039_TruffleSlicer': 'POINTS_PROVIDER',
  'D003_Furrows': 'ACTIONS_BOOSTER',
  'D084_FeedPellets': 'LIVESTOCK_PROVIDER',
  'D009_GameTrade': 'LIVESTOCK_PROVIDER',
  'E100_MuseumCaretaker': 'BONUS_POINTS_-_GET',
  'E101_Blighter': 'BONUS_POINTS_-_GET',
  'E102_Acquirer': 'GOODS_-_GET',
  'E104_SpiceTrader': 'GOODS_-_GET',
  'E105_Pioneer': 'GOODS_-_GET',
  'E106_EmergencySeller': 'FOOD',
  'E107_LandSurveyor': 'FOOD',
  'E108_BlackberryFarmer': 'FOOD',
  'E109_BraidMaker': 'FOOD',
  'E110_Dentist': 'FOOD',
  'E113_Godmother': 'CROPS_-_VEGETABLE',
  'E114_ShedBuilder': 'CROPS_-_GRAIN_AND_VEGETABLE',
  'E115_SeedServant': 'CROPS_-_SOWING',
  'E117_PipeSmoker': 'BUILDING_RESOURCES_-_WOOD',
  'E118_KindlingGatherer': 'BUILDING_RESOURCES_-_WOOD',
  'E119_LandHeir': 'BUILDING_RESOURCES_-_WOOD_(AND_CLAY)',
  'E120_ScrapCollector': 'BUILDING_RESOURCES_-_CLAY_(AND_WOOD)',
  'E121_HillCultivator': 'BUILDING_RESOURCES_-_CLAY',
  'E122_Cottar': 'BUILDING_RESOURCES_-_CLAY',
  'E126_TaxCollector': 'BUILDING_RESOURCES_-_ALL',
  'E127_DiligentFarmer': 'FARMYARD_-_PLACE_FOR_PERSON',
  'E128_Saddler': 'FARMYARD',
  'E129_Imitator': 'ACTION',
  'E130_Overachiever': 'ACTION_-_IMPROVEMENTS_OR_OCCUPATIONS',
  'E131_MarketMaster': 'ACTION_-_IMPROVEMENTS_OR_OCCUPATIONS',
  'E132_VeggieLover': 'BONUS_POINTS',
  'E134_Omnifarmer': 'BONUS_POINTS',
  'E135_Pickler': 'BONUS_POINTS_-_4_WOOD_CARD_COMPETITION',
  'E136_AnimalHusbandryWorker': 'BONUS_POINTS_-_4_WOOD_CARD_COMPETITION',
  'E137_FlaxFarmer': 'GOODS_-_GET',
  'E138_LivestockExpert': 'GOODS_-_GET',
  'E139_BunnyBreeder': 'FOOD',
  'E141_VegetableVendor': 'CROPS',
  'E142_Smuggler': 'CROPS',
  'E143_Hewer': 'BUILDING_RESOURCES_-_CLAY_OR_STONE',
  'E144_WaresSalesman': 'BUILDING_RESOURCES_-_REED',
  'E145_Parvenu': 'BUILDING_RESOURCES_-_REED',
  'E146_Reseller': 'BUILDING_RESOURCES_-_ALL',
  'E147_AnimalDriver': 'ANIMALS_-_ALL',
  'E152_BargainHunter': 'ACTION_-_IMPROVEMENTS_OR_OCCUPATIONS',
  'E154_Margrave': 'BONUS_POINTS',
  'E155_Visionary': 'GOODS_-_GET',
  'E156_ClaypitOwner': 'GOODS_-_GET',
  'E157_Usufructuary': 'FOOD',
  'E158_StoneCustodian': 'FOOD',
  'E159_OldMiser': 'FOOD',
  'E015_NailBasket': 'FARMYARD_-__FENCING_OR_STABLE_BUILDING',
  'E160_KelpGatherer': 'CROPS',
  'E164_MountainPlowman': 'ANIMALS_-_SHEEP',
  'E166_Roastmaster': 'ANIMALS_-_CATTLE',
  'E168_AnimalTamersApprentice': 'ANIMALS_-_ALL',
  'E017_SkimmerPlow': 'FARMYARD_-_PLOWING',
  'E018_SeedAlmanac': 'FARMYARD_-_PLOWING',
  'E019_OxGoad': 'FARMYARD_-_PLOWING',
  'E001_PoleBarns': 'PASSING_-_FARMYARD',
  'E020_IronHoe': 'FARMYARD_-_PLOWING',
  'E021_SheepRug': 'ACTION_-_FAMILY_GROWTH',
  'E024_Ambition': 'ACTION',
  'E025_BumperCrop': 'ACTION',
  'E029_Heirloom': 'BONUS_POINTS_-_GET',
  'E002_RenovationMaterials': 'PASSING_-_ACTION_-_FARMYARD',
  'E030_ChildsToy': 'BONUS_POINTS_-_GET',
  'E031_Upholstery': 'BONUS_POINTS_-_GET',
  'E032_Nave': 'BONUS_POINTS_-_GET',
  'E033_BeaverColony': 'BONUS_POINTS_-_GET',
  'E034_LandRegister': 'BONUS_POINTS_-_GET',
  'E035_Misanthropy': 'BONUS_POINTS_-_GET',
  'E036_HerbalGarden': 'BONUS_POINTS_-_GET',
  'E037_OxSkull': 'BONUS_POINTS_-_GET',
  'E038_RodCollection': 'BONUS_POINTS_-_GET',
  'E039_Paintbrush': 'BONUS_POINTS_-_GET',
  'E003_TeaTime': 'PASSING_-_ACTION_-_FARMYARD',
  'E040_BeeStatue': 'GOODS_-_GET',
  'E041_MuddyWaters': 'GOODS_-_GET',
  'E042_WaterGully': 'GOODS_-_GET',
  'E043_BarnCats': 'FOOD_-_FUTURE_ROUND_SPACES',
  'E044_FodderBeets': 'FOOD_-_FUTURE_ROUND_SPACES',
  'E045_FruitLadder': 'FOOD',
  'E046_WaterlilyPond': 'FOOD_-_FUTURE_ROUND_SPACES',
  'E048_TownHall': 'FOOD',
  'E049_Twibil': 'FOOD',
  'E050_WildGreens': 'FOOD',
  'E054_Contraband': 'FOOD',
  'E055_StoneWeir': 'FOOD',
  'E056_RomanPot': 'FOOD_-_FUTURE_ROUND_SPACES',
  'E057_CheeseFondue': 'FOOD',
  'E058_LunchtimeBeer': 'FOOD',
  'E059_CombandCutter': 'FOOD',
  'E005_NightLoot': 'PASSING_-_BUILDING_RESOURCES_',
  'E061_RaisedBed': 'FOOD_-_GRAIN',
  'E063_IronOven': 'FOOD_-_GRAIN',
  'E064_SimpleOven': 'FOOD_-_GRAIN',
  'E065_Almsbag': 'CROPS_-_GRAIN',
  'E067_GrainBag': 'CROPS_-_GRAIN',
  'E068_CherryOrchard': 'CROPS_-_VEGETABLE',
  'E069_MelonPatch': 'CROPS_-_VEGETABLE',
  'E006_Recount': 'PASSING_-_BUILDING_RESOURCES_',
  'E070_CropRotationField': 'CROPS_-_VEGETABLE',
  'E072_ArtichokeField': 'CROPS_-_GRAIN_AND_VEGETABLE',
  'E076_LumberPile': 'BUILDING_RESOURCES_-_WOOD_OR_CLAY',
  'E077_Mattock': 'BUILDING_RESOURCES_-_CLAY',
  'E078_SleightofHand': 'BUILDING_RESOURCES_-_REED',
  'E079_FieldSpade': 'BUILDING_RESOURCES_-_STONE',
  'E007_Pumpernickel': 'PASSING_-_FOOD',
  'E088_MasterFencer': 'FARMYARD_-_FENCING',
  'E089_Stallwright': 'FARMYARD_-_STABLE_BUILDING',
  'E008_FarmersMarket': 'PASSING_-_CROP',
  'E094_Prophet': 'ACTION',
  'E096_Elder': 'ACTION_-_IMPROVEMENT',
  'E097_Beneficiary': 'ACTION_-_OCCUPATION',
  'E098_Prodigy': 'BONUS_POINTS_-_GET',
  'E099_UncaringParents': 'BONUS_POINTS_-_GET',
  'E009_BarteringHut': 'PASSING_-_ANIMAL',
  // Auto-fix 2026-05-12: 33 cards with missing category
  'B148_PetBroker': 'FARM_PLANNER',
  'D148_DomesticianExpert': 'FARM_PLANNER',
  'E103_Wolf': 'GOODS_-_GET',
  'E010_StrawHat': 'ACTION_-_GUEST',
  'E112_GrainThief': 'CROPS_-_GRAIN',
  'E123_ResourceHoarder': 'BUILDING_RESOURCES_-_CLAY_AND/OR_STONE',
  'E124_MayorCandidate': 'BUILDING_RESOURCES_-_STONE',
  'E133_ChampionBreeder': 'BONUS_POINTS',
  'E140_Carter': 'FOOD',
  'E148_Lazybones': 'FARMYARD_-_PLACE_FOR_ANIMALS',
  'E149_MidnightFencer': 'FARMYARD',
  'E151_DeliveryNurse': 'ACTION',
  'E161_ElderBaker': 'CROPS',
  'E162_Entrepreneur': 'BUILDING_RESOURCES',
  'E167_DairyCrier': 'ANIMALS_-_ALL',
  'E016_BriarHedge': 'FARMYARD_-__FENCING_OR_STABLE_BUILDING',
  'E027_PiggyBank': 'ACTION_-_IMPROVEMENT',
  'E028_Bookmark': 'ACTION_-_OCCUPATION',
  'E047_SyrupTap': 'FOOD',
  'E004_Thunderbolt': 'PASSING_-_IMPROVEMENT/OCC_-_WOOD',
  'E062_SourDough': 'FOOD_-_GRAIN',
  'E071_CowPatty': 'CROPS_-_GRAIN_AND_VEGETABLE',
  'E073_Scythe': 'CROPS_-_GRAIN_AND_VEGETABLE',
  'E074_AshTrees': 'BUILDING_RESOURCES_-_WOOD',
  'E075_StoneAxe': 'BUILDING_RESOURCES_-_WOOD',
  'E081_AlchemistsLab': 'BUILDING_RESOURCES_-_ALL',
  'E082_Profiteering': 'BUILDING_RESOURCES_-_ALL',
  'E084_DollysMother': 'ANIMALS_',
  'E085_MasterTanner': 'FARMYARD_-_PLACE_FOR_PERSON',
  'E090_DungCollector': 'FARMYARD_-_PLOWING',
  'E091_PlowBuilder': 'FARMYARD_-_PLOWING',
  'E092_FieldDoctor': 'ACTION_-_FAMILY_GROWTH',
  'E093_Motivator': 'ACTION_-_GUEST',
  'E022_GuestRoom': 'FARMYARD_-_PLACE_FOR_PERSON',
}

describe('Sprint 4 PR-4B — category BGA alignment', () => {
  // C039_StudioBoat is a PlayerActionCard registered via side-effect import in
  // catalog.ts; it does not appear in the minor/occupation arrays, so include
  // it explicitly to keep this test's coverage exhaustive.
  const allCards = [...allMinorImprovementCards, ...allOccupationCards, C039_StudioBoat]
  const cardsById = new Map(allCards.map((c) => [c.id, c]))

  for (const [cardId, expected] of Object.entries(expectedCategories)) {
    it(`${cardId} category equals ${expected}`, () => {
      const card = cardsById.get(cardId)
      expect(card, `card not found: ${cardId}`).toBeDefined()
      expect(card!.category).toBe(expected)
    })
  }
})
