import { describe, expect, it } from 'vitest'
import { allMinorImprovementCards, allOccupationCards } from '../catalog'
import { C39_StudioBoat } from '../../cards-display/C/C39_StudioBoat'

const expectedCategories: Record<string, string> = {
  'A11_MudPatch': 'FARM_PLANNER',
  'A132_Publican': 'POINTS_PROVIDER',
  'A150_Stagehand': 'ACTIONS_BOOSTER',
  'A154_Paymaster': 'POINTS_PROVIDER',
  'A160_Lutenist': 'CROP_PROVIDER',
  'A25_Bassinet': 'ACTIONS_BOOSTER',
  'A86_AnimalTamer': 'FARM_PLANNER',
  'A87_Conservator': 'FARM_PLANNER',
  'B102_Consultant': 'GOODS_PROVIDER',
  'B105_CaseBuilder': 'GOODS_PROVIDER',
  'B119_Lumberjack': 'BUILDING_RESOURCE_PROVIDER',
  'B11_Feedyard': 'FARM_PLANNER',
  'B123_RoofBallaster': 'BUILDING_RESOURCE_PROVIDER',
  'B138_ForestGuardian': 'GOODS_PROVIDER',
  'B164_SheepWhisperer': 'LIVESTOCK_PROVIDER',
  'B167_StableSergeant': 'LIVESTOCK_PROVIDER',
  'B22_WalkingBoots': 'ACTIONS_BOOSTER',
  'B41_Hauberg': 'GOODS_PROVIDER',
  'B44_ChickStable': 'FOOD_PROVIDER',
  'B45_StrawberryPatch': 'FOOD_PROVIDER',
  'B46_ClubHouse': 'FOOD_PROVIDER',
  'B52_GrowingFarm': 'FOOD_PROVIDER',
  'B59_FoodChest': 'FOOD_PROVIDER',
  'B74_ThickForest': 'BUILDING_RESOURCE_PROVIDER',
  'B78_ReedBelt': 'BUILDING_RESOURCE_PROVIDER',
  'B7_Wage': 'FOOD_PROVIDER',
  'B84_AcornsBasket': 'LIVESTOCK_PROVIDER',
  'B93_Confidant': 'ACTIONS_BOOSTER',
  'B96_TreeFarmJoiner': 'ACTIONS_BOOSTER',
  'B9_BeatingRod': 'GOODS_PROVIDER',
  'C112_Thresher': 'CROP_PROVIDER',
  'C118_WoodCollector': 'BUILDING_RESOURCE_PROVIDER',
  'C11_WildlifeReserve': 'FARM_PLANNER',
  'C129_SecondSpouse': 'ACTIONS_BOOSTER',
  'C12_CattleFarm': 'FARM_PLANNER',
  'C145_ForestReviewer': 'ACTIONS_BOOSTER',
  'C149_ResourceRecycler': 'FARM_PLANNER',
  'C151_SowingDirector': 'ACTIONS_BOOSTER',
  'C153_PatternMaker': 'POINTS_PROVIDER',
  'C163_MaterialDeliveryman': 'ACTIONS_BOOSTER',
  'C165_GameCatcher': 'LIVESTOCK_PROVIDER',
  'C166_CattleWhisperer': 'LIVESTOCK_PROVIDER',
  'C167_CattleBuyer': 'LIVESTOCK_PROVIDER',
  'C39_StudioBoat': 'POINTS_PROVIDER',
  'C4_WritingBoards': 'BUILDING_RESOURCE_PROVIDER',
  'C59_SchnappsDistillery': 'FOOD_PROVIDER',
  'C74_PrivateForest': 'BUILDING_RESOURCE_PROVIDER',
  'C77_ClaySupply': 'BUILDING_RESOURCE_PROVIDER',
  'C78_ReedHattedToad': 'BUILDING_RESOURCE_PROVIDER',
  'C79_StoneCart': 'BUILDING_RESOURCE_PROVIDER',
  'C7_BladeShears': 'FOOD_PROVIDER',
  'C83_EarlyCattle': 'LIVESTOCK_PROVIDER',
  'C89_StableMaster': 'FARM_PLANNER',
  'C9_AutomaticWaterTrough': 'LIVESTOCK_PROVIDER',
  'D113_FoodMerchant': 'CROP_PROVIDER',
  'D118_Bonehead': 'BUILDING_RESOURCE_PROVIDER',
  'D128_BuildingTycoon': 'FARM_PLANNER',
  'D12_MilkingPlace': 'FARM_PLANNER',
  'D149_CasualWorker': 'FARM_PLANNER',
  'D152_Patron': 'ACTIONS_BOOSTER',
  'D163_JourneymanBricklayer': 'BUILDING_RESOURCE_PROVIDER',
  'D39_TruffleSlicer': 'POINTS_PROVIDER',
  'D3_Furrows': 'ACTIONS_BOOSTER',
  'D84_FeedPellets': 'LIVESTOCK_PROVIDER',
  'D9_GameTrade': 'LIVESTOCK_PROVIDER',
  'E100_MuseumCaretaker': 'BONUS_POINTS_-_GET',
  'E101_Blighter': 'BONUS_POINTS_-_GET',
  'E102_Acquirer': 'GOODS_-_GET',
  'E104_SpiceTrader': 'GOODS_-_GET',
  'E105_Pioneer': 'GOODS_-_GET',
  'E106_EmergencySeller': 'FOOD',
  'E107_LandSurveyor': 'FOOD',
  'E108_BlackberryFarmer': 'FOOD',
  'E109_BraidMaker': 'FOOD',
  'E110_Dentist': 'FOOD',
  'E113_Godmother': 'CROPS_-_VEGETABLE',
  'E114_ShedBuilder': 'CROPS_-_GRAIN_AND_VEGETABLE',
  'E115_SeedServant': 'CROPS_-_SOWING',
  'E117_PipeSmoker': 'BUILDING_RESOURCES_-_WOOD',
  'E118_KindlingGatherer': 'BUILDING_RESOURCES_-_WOOD',
  'E119_LandHeir': 'BUILDING_RESOURCES_-_WOOD_(AND_CLAY)',
  'E120_ScrapCollector': 'BUILDING_RESOURCES_-_CLAY_(AND_WOOD)',
  'E121_HillCultivator': 'BUILDING_RESOURCES_-_CLAY',
  'E122_Cottar': 'BUILDING_RESOURCES_-_CLAY',
  'E126_TaxCollector': 'BUILDING_RESOURCES_-_ALL',
  'E127_DiligentFarmer': 'FARMYARD_-_PLACE_FOR_PERSON',
  'E128_Saddler': 'FARMYARD',
  'E129_Imitator': 'ACTION',
  'E130_Overachiever': 'ACTION_-_IMPROVEMENTS_OR_OCCUPATIONS',
  'E131_MarketMaster': 'ACTION_-_IMPROVEMENTS_OR_OCCUPATIONS',
  'E132_VeggieLover': 'BONUS_POINTS',
  'E134_Omnifarmer': 'BONUS_POINTS',
  'E135_Pickler': 'BONUS_POINTS_-_4_WOOD_CARD_COMPETITION',
  'E136_AnimalHusbandryWorker': 'BONUS_POINTS_-_4_WOOD_CARD_COMPETITION',
  'E137_FlaxFarmer': 'GOODS_-_GET',
  'E138_LivestockExpert': 'GOODS_-_GET',
  'E139_BunnyBreeder': 'FOOD',
  'E141_VegetableVendor': 'CROPS',
  'E142_Smuggler': 'CROPS',
  'E143_Hewer': 'BUILDING_RESOURCES_-_CLAY_OR_STONE',
  'E144_WaresSalesman': 'BUILDING_RESOURCES_-_REED',
  'E145_Parvenu': 'BUILDING_RESOURCES_-_REED',
  'E146_Reseller': 'BUILDING_RESOURCES_-_ALL',
  'E147_AnimalDriver': 'ANIMALS_-_ALL',
  'E152_BargainHunter': 'ACTION_-_IMPROVEMENTS_OR_OCCUPATIONS',
  'E154_Margrave': 'BONUS_POINTS',
  'E155_Visionary': 'GOODS_-_GET',
  'E156_ClaypitOwner': 'GOODS_-_GET',
  'E157_Usufructuary': 'FOOD',
  'E158_StoneCustodian': 'FOOD',
  'E159_OldMiser': 'FOOD',
  'E15_NailBasket': 'FARMYARD_-__FENCING_OR_STABLE_BUILDING',
  'E160_KelpGatherer': 'CROPS',
  'E164_MountainPlowman': 'ANIMALS_-_SHEEP',
  'E166_Roastmaster': 'ANIMALS_-_CATTLE',
  'E168_AnimalTamersApprentice': 'ANIMALS_-_ALL',
  'E17_SkimmerPlow': 'FARMYARD_-_PLOWING',
  'E18_SeedAlmanac': 'FARMYARD_-_PLOWING',
  'E19_OxGoad': 'FARMYARD_-_PLOWING',
  'E1_PoleBarns': 'PASSING_-_FARMYARD',
  'E20_IronHoe': 'FARMYARD_-_PLOWING',
  'E21_SheepRug': 'ACTION_-_FAMILY_GROWTH',
  'E24_Ambition': 'ACTION',
  'E25_BumperCrop': 'ACTION',
  'E29_Heirloom': 'BONUS_POINTS_-_GET',
  'E2_RenovationMaterials': 'PASSING_-_ACTION_-_FARMYARD',
  'E30_ChildsToy': 'BONUS_POINTS_-_GET',
  'E31_Upholstery': 'BONUS_POINTS_-_GET',
  'E32_Nave': 'BONUS_POINTS_-_GET',
  'E33_BeaverColony': 'BONUS_POINTS_-_GET',
  'E34_LandRegister': 'BONUS_POINTS_-_GET',
  'E35_Misanthropy': 'BONUS_POINTS_-_GET',
  'E36_HerbalGarden': 'BONUS_POINTS_-_GET',
  'E37_OxSkull': 'BONUS_POINTS_-_GET',
  'E38_RodCollection': 'BONUS_POINTS_-_GET',
  'E39_Paintbrush': 'BONUS_POINTS_-_GET',
  'E3_TeaTime': 'PASSING_-_ACTION_-_FARMYARD',
  'E40_BeeStatue': 'GOODS_-_GET',
  'E41_MuddyWaters': 'GOODS_-_GET',
  'E42_WaterGully': 'GOODS_-_GET',
  'E43_BarnCats': 'FOOD_-_FUTURE_ROUND_SPACES',
  'E44_FodderBeets': 'FOOD_-_FUTURE_ROUND_SPACES',
  'E45_FruitLadder': 'FOOD',
  'E46_WaterlilyPond': 'FOOD_-_FUTURE_ROUND_SPACES',
  'E48_TownHall': 'FOOD',
  'E49_Twibil': 'FOOD',
  'E50_WildGreens': 'FOOD',
  'E54_Contraband': 'FOOD',
  'E55_StoneWeir': 'FOOD',
  'E56_RomanPot': 'FOOD_-_FUTURE_ROUND_SPACES',
  'E57_CheeseFondue': 'FOOD',
  'E58_LunchtimeBeer': 'FOOD',
  'E59_CombandCutter': 'FOOD',
  'E5_NightLoot': 'PASSING_-_BUILDING_RESOURCES_',
  'E61_RaisedBed': 'FOOD_-_GRAIN',
  'E63_IronOven': 'FOOD_-_GRAIN',
  'E64_SimpleOven': 'FOOD_-_GRAIN',
  'E65_Almsbag': 'CROPS_-_GRAIN',
  'E67_GrainBag': 'CROPS_-_GRAIN',
  'E68_CherryOrchard': 'CROPS_-_VEGETABLE',
  'E69_MelonPatch': 'CROPS_-_VEGETABLE',
  'E6_Recount': 'PASSING_-_BUILDING_RESOURCES_',
  'E70_CropRotationField': 'CROPS_-_VEGETABLE',
  'E72_ArtichokeField': 'CROPS_-_GRAIN_AND_VEGETABLE',
  'E76_LumberPile': 'BUILDING_RESOURCES_-_WOOD_OR_CLAY',
  'E77_Mattock': 'BUILDING_RESOURCES_-_CLAY',
  'E78_SleightofHand': 'BUILDING_RESOURCES_-_REED',
  'E79_FieldSpade': 'BUILDING_RESOURCES_-_STONE',
  'E7_Pumpernickel': 'PASSING_-_FOOD',
  'E88_MasterFencer': 'FARMYARD_-_FENCING',
  'E89_Stallwright': 'FARMYARD_-_STABLE_BUILDING',
  'E8_FarmersMarket': 'PASSING_-_CROP',
  'E94_Prophet': 'ACTION',
  'E96_Elder': 'ACTION_-_IMPROVEMENT',
  'E97_Beneficiary': 'ACTION_-_OCCUPATION',
  'E98_Prodigy': 'BONUS_POINTS_-_GET',
  'E99_UncaringParents': 'BONUS_POINTS_-_GET',
  'E9_BarteringHut': 'PASSING_-_ANIMAL',
}

describe('Sprint 4 PR-4B — category BGA alignment', () => {
  // C39_StudioBoat is a PlayerActionCard registered via side-effect import in
  // catalog.ts; it does not appear in the minor/occupation arrays, so include
  // it explicitly to keep this test's coverage exhaustive.
  const allCards = [...allMinorImprovementCards, ...allOccupationCards, C39_StudioBoat]
  const cardsById = new Map(allCards.map((c) => [c.id, c]))

  for (const [cardId, expected] of Object.entries(expectedCategories)) {
    it(`${cardId} category equals ${expected}`, () => {
      const card = cardsById.get(cardId)
      expect(card, `card not found: ${cardId}`).toBeDefined()
      expect(card!.category).toBe(expected)
    })
  }
})
