import { describe, expect, it } from 'vitest'
import { getMinorImprovementCard, getOccupationCard } from '../catalog'

// BGA reference: bga-agricola/modules/php/Cards/<deck>/<id>.php $this->extraVp = true
// Locked in by 2026-05-12 auto-fix run.
const cases: Array<{ id: string; kind: 'minor' | 'occupation' }> = [
  { id: 'B100_Clutterer', kind: 'occupation' },
  { id: 'B101_FurnitureCarpenter', kind: 'occupation' },
  { id: 'B111_Rustic', kind: 'occupation' },
  { id: 'B134_HousebookMaster', kind: 'occupation' },
  { id: 'B135_NutritionExpert', kind: 'occupation' },
  { id: 'B153_Housemaster', kind: 'occupation' },
  { id: 'B154_SheepKeeper', kind: 'occupation' },
  { id: 'B30_WoodPalisades', kind: 'minor' },
  { id: 'B31_PotteryYard', kind: 'minor' },
  { id: 'B33_Mantlepiece', kind: 'minor' },
  { id: 'B34_SpecialFood', kind: 'minor' },
  { id: 'B35_HookKnife', kind: 'minor' },
  { id: 'B39_Loom', kind: 'minor' },
  { id: 'B98_OrganicFarmer', kind: 'occupation' },
  { id: 'B99_Tutor', kind: 'occupation' },
  { id: 'C100_Butler', kind: 'occupation' },
  { id: 'C101_StallHolder', kind: 'occupation' },
  { id: 'C110_HomeBrewer', kind: 'occupation' },
  { id: 'C133_Soldier', kind: 'occupation' },
  { id: 'C134_CowPrince', kind: 'occupation' },
  { id: 'C135_Constable', kind: 'occupation' },
  { id: 'C136_RanchProvost', kind: 'occupation' },
  { id: 'C153_PatternMaker', kind: 'occupation' },
  { id: 'C154_TwinResearcher', kind: 'occupation' },
  { id: 'C29_BeerTable', kind: 'minor' },
  { id: 'C30_HalfTimberedHouse', kind: 'minor' },
  { id: 'C33_GreeningPlan', kind: 'minor' },
  { id: 'C34_ElephantgrassPlant', kind: 'minor' },
  { id: 'C35_LanternHouse', kind: 'minor' },
  { id: 'C36_ClayDeposit', kind: 'minor' },
  { id: 'C46_Mandoline', kind: 'minor' },
  { id: 'C59_SchnappsDistillery', kind: 'minor' },
  { id: 'C61_BeerStein', kind: 'minor' },
  { id: 'C98_CubeCutter', kind: 'occupation' },
  { id: 'D101_SugarBaker', kind: 'occupation' },
  { id: 'D107_Bellfounder', kind: 'occupation' },
  { id: 'D133_BeerTentOperator', kind: 'occupation' },
  { id: 'D134_OysterEater', kind: 'occupation' },
  { id: 'D135_GardeningHeadOfficial', kind: 'occupation' },
  { id: 'D136_AnimalActivist', kind: 'occupation' },
  { id: 'D153_WealthyMan', kind: 'occupation' },
  { id: 'D154_ChimneySweep', kind: 'occupation' },
  { id: 'D157_PartyOrganizer', kind: 'occupation' },
  { id: 'D29_MuckRake', kind: 'minor' },
  { id: 'D30_ArtisanDistrict', kind: 'minor' },
  { id: 'D31_Storeroom', kind: 'minor' },
  { id: 'D32_WoodRake', kind: 'minor' },
  { id: 'D35_FodderChamber', kind: 'minor' },
  { id: 'D36_BreedRegistry', kind: 'minor' },
  { id: 'D38_MilkingStool', kind: 'minor' },
  { id: 'D39_TruffleSlicer', kind: 'minor' },
  { id: 'D99_EarthenwarePotter', kind: 'occupation' },
  { id: 'E100_MuseumCaretaker', kind: 'occupation' },
  { id: 'E101_Blighter', kind: 'occupation' },
  { id: 'E124_MayorCandidate', kind: 'occupation' },
  { id: 'E132_VeggieLover', kind: 'occupation' },
  { id: 'E133_ChampionBreeder', kind: 'occupation' },
  { id: 'E134_Omnifarmer', kind: 'occupation' },
  { id: 'E135_Pickler', kind: 'occupation' },
  { id: 'E136_AnimalHusbandryWorker', kind: 'occupation' },
  { id: 'E154_Margrave', kind: 'occupation' },
  { id: 'E31_Upholstery', kind: 'minor' },
  { id: 'E32_Nave', kind: 'minor' },
  { id: 'E33_BeaverColony', kind: 'minor' },
  { id: 'E34_LandRegister', kind: 'minor' },
  { id: 'E35_Misanthropy', kind: 'minor' },
  { id: 'E37_OxSkull', kind: 'minor' },
  { id: 'E38_RodCollection', kind: 'minor' },
  { id: 'E39_Paintbrush', kind: 'minor' },
  { id: 'E98_Prodigy', kind: 'occupation' },
  { id: 'E99_UncaringParents', kind: 'occupation' },
  { id: 'B132_EstateMaster', kind: 'occupation' },
  { id: 'C31_WritingChamber', kind: 'minor' },
  { id: 'C63_CraftBrewery', kind: 'minor' },
  { id: 'C99_GardenDesigner', kind: 'occupation' },
  { id: 'D33_SummerHouse', kind: 'minor' },
  { id: 'D92_ChildOmbudsman', kind: 'occupation' },
]

describe('extraVp BGA alignment (auto-fix lock-in)', () => {
  it.each(cases)(
    '$id has extraVp:true matching BGA',
    ({ id, kind }) => {
      const card = kind === 'occupation' ? getOccupationCard(id) : getMinorImprovementCard(id)
      expect(card, `card not found in catalog: ${id}`).toBeDefined()
      expect(card!.extraVp).toBe(true)
    },
  )
})
