import { describe, expect, it } from 'vitest'
import { getMinorImprovementCard, getOccupationCard } from '../catalog'

// Reference: the reference $this->extraVp = true
// Locked in by 2026-05-12 auto-fix run.
const cases: Array<{ id: string; kind: 'minor' | 'occupation' }> = [
  { id: 'B100_Clutterer', kind: 'occupation' },
  { id: 'B101_FurnitureCarpenter', kind: 'occupation' },
  { id: 'B111_Rustic', kind: 'occupation' },
  { id: 'B134_HousebookMaster', kind: 'occupation' },
  { id: 'B135_NutritionExpert', kind: 'occupation' },
  { id: 'B153_Housemaster', kind: 'occupation' },
  { id: 'B154_SheepKeeper', kind: 'occupation' },
  { id: 'B030_WoodPalisades', kind: 'minor' },
  { id: 'B031_PotteryYard', kind: 'minor' },
  { id: 'B033_Mantlepiece', kind: 'minor' },
  { id: 'B034_SpecialFood', kind: 'minor' },
  { id: 'B035_HookKnife', kind: 'minor' },
  { id: 'B039_Loom', kind: 'minor' },
  { id: 'B098_OrganicFarmer', kind: 'occupation' },
  { id: 'B099_Tutor', kind: 'occupation' },
  { id: 'C100_Butler', kind: 'occupation' },
  { id: 'C101_StallHolder', kind: 'occupation' },
  { id: 'C110_HomeBrewer', kind: 'occupation' },
  { id: 'C133_Soldier', kind: 'occupation' },
  { id: 'C134_CowPrince', kind: 'occupation' },
  { id: 'C135_Constable', kind: 'occupation' },
  { id: 'C136_RanchProvost', kind: 'occupation' },
  { id: 'C153_PatternMaker', kind: 'occupation' },
  { id: 'C154_TwinResearcher', kind: 'occupation' },
  { id: 'C029_BeerTable', kind: 'minor' },
  { id: 'C030_HalfTimberedHouse', kind: 'minor' },
  { id: 'C033_GreeningPlan', kind: 'minor' },
  { id: 'C034_ElephantgrassPlant', kind: 'minor' },
  { id: 'C035_LanternHouse', kind: 'minor' },
  { id: 'C036_ClayDeposit', kind: 'minor' },
  { id: 'C046_Mandoline', kind: 'minor' },
  { id: 'C059_SchnappsDistillery', kind: 'minor' },
  { id: 'C061_BeerStein', kind: 'minor' },
  { id: 'C098_CubeCutter', kind: 'occupation' },
  { id: 'D101_SugarBaker', kind: 'occupation' },
  { id: 'D107_Bellfounder', kind: 'occupation' },
  { id: 'D133_BeerTentOperator', kind: 'occupation' },
  { id: 'D134_OysterEater', kind: 'occupation' },
  { id: 'D135_GardeningHeadOfficial', kind: 'occupation' },
  { id: 'D136_AnimalActivist', kind: 'occupation' },
  { id: 'D153_WealthyMan', kind: 'occupation' },
  { id: 'D154_ChimneySweep', kind: 'occupation' },
  { id: 'D157_PartyOrganizer', kind: 'occupation' },
  { id: 'D029_MuckRake', kind: 'minor' },
  { id: 'D030_ArtisanDistrict', kind: 'minor' },
  { id: 'D031_Storeroom', kind: 'minor' },
  { id: 'D032_WoodRake', kind: 'minor' },
  { id: 'D035_FodderChamber', kind: 'minor' },
  { id: 'D036_BreedRegistry', kind: 'minor' },
  { id: 'D038_MilkingStool', kind: 'minor' },
  { id: 'D039_TruffleSlicer', kind: 'minor' },
  { id: 'D099_EarthenwarePotter', kind: 'occupation' },
  { id: 'E100_MuseumCaretaker', kind: 'occupation' },
  { id: 'E101_Blighter', kind: 'occupation' },
  { id: 'E124_MayorCandidate', kind: 'occupation' },
  { id: 'E132_VeggieLover', kind: 'occupation' },
  { id: 'E133_ChampionBreeder', kind: 'occupation' },
  { id: 'E134_Omnifarmer', kind: 'occupation' },
  { id: 'E135_Pickler', kind: 'occupation' },
  { id: 'E136_AnimalHusbandryWorker', kind: 'occupation' },
  { id: 'E154_Margrave', kind: 'occupation' },
  { id: 'E031_Upholstery', kind: 'minor' },
  { id: 'E032_Nave', kind: 'minor' },
  { id: 'E033_BeaverColony', kind: 'minor' },
  { id: 'E034_LandRegister', kind: 'minor' },
  { id: 'E035_Misanthropy', kind: 'minor' },
  { id: 'E037_OxSkull', kind: 'minor' },
  { id: 'E038_RodCollection', kind: 'minor' },
  { id: 'E039_Paintbrush', kind: 'minor' },
  { id: 'E098_Prodigy', kind: 'occupation' },
  { id: 'E099_UncaringParents', kind: 'occupation' },
  { id: 'B132_EstateMaster', kind: 'occupation' },
  { id: 'C031_WritingChamber', kind: 'minor' },
  { id: 'C063_CraftBrewery', kind: 'minor' },
  { id: 'C099_GardenDesigner', kind: 'occupation' },
  { id: 'D033_SummerHouse', kind: 'minor' },
  { id: 'D092_ChildOmbudsman', kind: 'occupation' },
]

describe('extraVp reference alignment (auto-fix lock-in)', () => {
  it.each(cases)(
    '$id has extraVp:true matching the reference',
    ({ id, kind }) => {
      const card = kind === 'occupation' ? getOccupationCard(id) : getMinorImprovementCard(id)
      expect(card, `card not found in catalog: ${id}`).toBeDefined()
      expect(card!.extraVp).toBe(true)
    },
  )
})
