// GENERATED by scripts/generate-register-all.ts — do not edit by hand.
// Run `pnpm run generate:register-all` after adding or removing community card definitions.
import type { MinorImprovement, Occupation } from '../../cards-display/types'

import { CUSTOM_FixtureHarvester } from '../../cards-display/community/CUSTOM_FixtureHarvester'

export const allCommunityCards: Array<MinorImprovement | Occupation> = [
  CUSTOM_FixtureHarvester,
]
