// GENERATED by scripts/generate-register-all.ts — do not edit by hand.
// Run `pnpm run generate:register-all` after adding or removing community card definitions.
import type { MinorImprovement, Occupation } from '../types'

export const allCommunityCards: Array<MinorImprovement | Occupation> = []
