// GENERATED by scripts/generate-register-all.ts — do not edit by hand.
// Run `pnpm run generate:register-all` after adding or removing community card definitions.
import type { MinorImprovement, Occupation } from '../types'

import { CUSTOM_FixtureHarvester } from './CUSTOM_FixtureHarvester'
import { CUSTOM_MedievalMallet } from './CUSTOM_MedievalMallet'

export const allCommunityCards: Array<MinorImprovement | Occupation> = [
  CUSTOM_FixtureHarvester,
  CUSTOM_MedievalMallet,
]
