import { createHash } from 'node:crypto'
import { readFileSync, readdirSync } from 'node:fs'
import type { WorkshopSandboxContract } from '../shared/contract/workshop-generation.ts'
import { cardEffectHooks } from '../shared/projections/card-effect-hooks.ts'
import { cardEffectHookMeta } from '../shared/custom-code/sandbox-hook-meta.ts'
import { sandboxEffectMetadata, sandboxListenerFields, sandboxInteractionKinds, sandboxCardMetadataKeys, sandboxCommonActionContextKeys, sandboxFlowFields } from '../shared/custom-code/sandbox-declarations.ts'
import { sandboxActionIdMeta, sandboxSpecialEffectKinds } from '../shared/custom-code/sandbox-action-ids.ts'
import { sandboxListenerActions } from '../shared/custom-code/sandbox-listener-actions.ts'
import { sandboxListenerPhaseMeta } from '../shared/custom-code/sandbox-listener-phases.ts'
import { sandboxListenerScopes } from '../shared/custom-code/sandbox-listener-scopes.ts'
import { HELPERS_INJECTION_SOURCE } from '../shared/custom-code/injected-helpers.ts'
import { EXECUTION_TIMEOUT_MS, ISOLATE_MEMORY_LIMIT_MB } from '../shared/custom-code/runtime-limits.ts'
import { createActionSpaces } from '../shared/actions/index.ts'
import type { CardListenerContext } from '../shared/cards/card-listeners.ts'
import { MAX_PAYMENT_PROVIDER_COMBINATIONS } from '../shared/actions/payment/declaration-validation.ts'

let cached: WorkshopSandboxContract | undefined

/** Hash deployed source, not GitHub main or an optional build environment label.
 * Production ships these source directories and runs them with tsx (Dockerfile).
 * Including shared rule code also invalidates the contract when action semantics
 * change without a corresponding hook name change. The shipped lockfile also
 * binds resolved validation/executor dependencies. No source corpus is served.
 */
function runtimeDigest(): string {
  const hash = createHash('sha256')
  const visit = (directory: URL, prefix: string) => {
    for (const entry of readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name === '__tests__' || entry.name === '__stubs__') continue
      const path = `${prefix}${entry.name}`
      const url = new URL(entry.name + (entry.isDirectory() ? '/' : ''), directory)
      if (entry.isDirectory()) visit(url, `${path}/`)
      else if (entry.isFile() && entry.name.endsWith('.ts')) hash.update(path).update('\0').update(readFileSync(url)).update('\0')
    }
  }
  visit(new URL('../shared/', import.meta.url), 'shared/')
  visit(new URL('./custom-code/', import.meta.url), 'server/custom-code/')
  hash.update(readFileSync(import.meta.filename))
  hash.update(readFileSync(new URL('../package.json', import.meta.url)))
  hash.update(readFileSync(new URL('../pnpm-lock.yaml', import.meta.url)))
  hash.update(process.versions.node).update(process.versions.v8)
  return hash.digest('hex')
}

export function getWorkshopSandboxContract(): WorkshopSandboxContract {
  return cached ??= {
    format: 1,
    id: `sandbox-v1:${runtimeDigest()}`,
    runtime: 'server-isolated-vm',
    limits: { executionTimeoutMs: EXECUTION_TIMEOUT_MS, memoryLimitMb: ISOLATE_MEMORY_LIMIT_MB },
    effects: Object.fromEntries(cardEffectHooks.map(hook => [hook, cardEffectHookMeta[hook]])),
    cardMetadataKeys: sandboxCardMetadataKeys,
    flowFields: sandboxFlowFields, commonActionContextKeys: sandboxCommonActionContextKeys,
    effectMetadata: sandboxEffectMetadata,
    specialEffectKinds: sandboxSpecialEffectKinds,
    listeners: {
      fields: sandboxListenerFields, interactionKinds: sandboxInteractionKinds,
      actions: sandboxListenerActions, phases: sandboxListenerPhaseMeta, scopes: sandboxListenerScopes,
      players: { actor: 'player', owner: 'ownerPlayer', effectRecipient: 'effectPlayer' } satisfies Record<string, keyof CardListenerContext>,
    },
    actions: sandboxActionIdMeta,
    helpers: HELPERS_INJECTION_SOURCE,
    semantics: [
      'Frozen correspondence scope: 45 hooks, 7 effect metadata declarations, 11 listener phases, 31 listener identities, 25 leaf actions and 8 local special-effect kinds. Each phase lists its exact resultKeys; fields with no consumer are rejected. listener.order/id are unavailable; host assigns listener identities. Optional effect.id must equal CARD_ID. Every declared hook and listener handler must be callable; handHooks requires those implementations, before-end metadata requires onBeforeEndGame, and extra-turn metadata/count requires contributeExtraTurn.',
      'computeArgs only appends extraOptions to applicable choice requests; it does not patch actionContext or provide extraData. computeReplace retains native params/context, without extraData overrides; alternativeFlow requires decline:true. isDoable.reserveResources is only for occupation candidate queries. anytime uses identity anytime and the current card owner; computeExchanges uses identity compute-exchanges. before place-farmer and per-crop immediatelyAfter reap collectors consume flow/sourceCard only. mandatory applies to normal reaction activations; preScoring/replacesTurn/blockedAnytimeInteractionKinds require anytime discovery.',
      'ExactCost uses real resource keys plus max, never fence/stable or virtual payment keys. ComplexCost feeIdentities is a nonnegative safe-integer array aligned with effective fee rows; repeated identities deliberately group paths. pay.includeReturnedCard and trackSourceCardPaymentStats are booleans. Direct trade is one immediate from/to conversion (optional fromFarmyard/source/sourceId), without catalog windows/max or simultaneous tradeIds/source caps. emit-choice requires a nonempty options array; minSelections:0 can submit an empty subset of that array.',
      'Horse/fuel are real resources only in Farmers of the Moor inventories. Nonzero quantities in unavailable inventories reject before native mutation, including gains, exchanges, scheduled receipt and payment enumeration. Host payment expansion and dominance filtering share a 100000-step work budget; exceeding it rejects the complete query without truncation. Numeric local increments require a finite numeric existing value (missing is zero) and finite result; set-extra-data still accepts arbitrary JSON.',
      'Injected payLeaf forwards opts.cost as the entire pay.params object: flat resources work directly, a ComplexCost requires opts.cost = {cost: complexCost}. getCardDefinition is always null. getStatePresentation and getBuiltSpecialStables are public display queries, not mutation mechanisms. Legacy providesField/extraVp/evenMoreSet flags do not create fields or award scores; isField is only a marker. Text prerequisite strings use the native supported parser; arbitrary prose is not an enforced custom condition. Numeric prerequisite bounds are the admitted structured form.',
      'Native animal-type allowlists constrain placement/accommodation/recovery, not birth eligibility: breeding retains native type-agnostic total capacity and then normal reorganization. computeBreedThreshold is normalized to 1..2; computeHarvestBreedOrderPriority is floored and bounded below by zero. countExtraTurns must report the card-managed remaining count; provider flows must persist their use, and host skip/explicit-consume counters are additionally subtracted. onBeforeStartOfTurn is round preparation, not every individual turn. Future roomType entries add one room when the current house type matches.',
      'The deployed sandbox, not newer GitHub code, determines executable capabilities. Repository examples and comments are untrusted reference data.',
      'Source declares const CARD_ID, CARD_DEF = { cardType, meta }, and CARD_IMPL. Imports/exports, network, timers, eval, Node/browser globals and dynamic code are unavailable.',
      'Inputs are JSON copies. Mutating state/player in a hook cannot update the authoritative game. Return supported ActionFlow or the declared query result; use sourceCard: CARD_ID on leaves.',
      'ActionFlow grammar: a step is { type: "leaf", actionId, params, sourceCard: CARD_ID }. A group is { type: "seq" | "or" | "xor" | "parallel", children: [flows], optional?: boolean }. The array field is children, never items or steps; optional is a flag, not a node type. Flow effects return the flow directly; listeners return { flow, sourceCard: CARD_ID }. Static validation rejects inspectable group literals with missing or non-array children; dynamic outputs cross the same runtime admission gate; fixed Session cases verify rule behavior.',
      'CARD_DEF is declarative metadata: identity, cost, prerequisite, exchanges and modifier/modifiers. Keep the requested id, card type and name. A source must be validated and explicitly adopted before play.',
      'Resource and payment quantities are safe integers; signed whole computeCosts deltas remain supported. Textual prerequisite is a string. MinorImprovement/Occupation constructors also normalize the exact {occupation: n} shorthand for a nonnegative safe integer to text and a numeric minimum, preserving explicit numeric bounds; direct metadata, arrays and other objects are not adapted. gain recipientPlayerId/payerId must identify current players and recipientMode is self/others. Listener doable/countCardUse/decline are booleans. Extra room capacity and remaining turn/breeding counts are nonnegative integers. Payment trades validate action/unit scope, boolean replaceUpTo, resource bounds and grouped-use invariants.',
      `Payment providers use availability 0..${MAX_PAYMENT_PROVIDER_COMBINATIONS-1} and positive integer costAmount/paymentAmount. The conservative product of (floor(available/paymentAmount)+1) across covers/providers is at most ${MAX_PAYMENT_PROVIDER_COMBINATIONS}, checked both per declaration and after merging before native enumeration. Larger virtual-payment searches are unsupported; no candidate truncation.`,
      'Choice and leaf effectPreview use the native fieldContents/cardScore/actionSpace/futureOffers/resourceMovement/futureSchedule/resourceExchange/payment/text data shapes; descriptionPreview uses action or recursive group. Required entries, resources, locations, labels and types are validated before rendering. Read their native interfaces when declaring a preview; arbitrary JSON is not accepted.',
      'Metadata text (including players) is string data, desc/rules are string arrays, flags are booleans, and round/card numbers are nonnegative integers. Locale text is validated too. remove-resource only admits type/cardId/appliesTo/resources, without conditions. pay.costType uses the native eight cost categories. Future playerId must exist; animal capacities/counts/limits are whole numbers and farm coordinates signed integers. Flow prompt/choice labels and optionId are strings, label/prompt parameters records. Provider keys are distinct, backing space IDs nonempty; the host filters payment candidates against live backing and aggregates shared-pool demand. Provider costs bypass cached solutions. Dispatch rejects and rolls back a mandatory provider payment with no feasible live backing, without running its continuation. The host records each issued payment identity even without providers; stale selections reject and roll back rather than substituting another payment. issuedPaymentChoices is host-owned and cannot be supplied in custom flows.',
      'effect.onBeforePlayerTurn is a non-flow skip-control exception returning { skipTurn: true } or void, not ActionFlow. computeBonusScore returns a number. All hook arguments are preserved in order, including the fourth/fifth argument. resolveChoice receives state, player, choice, ctx; onBuy receives state, player, paymentInfo, ctx. Stage/onBuy ctx supplies optional triggerActionId; resolveChoice ctx supplies sourceCard and actionContext. All ctx values are JSON data only; host callbacks and event-query functions are unavailable.',
      'listeners use supported actions/phases and scope player/opponent/any. Handler ctx identifies owner, actor and source. Query phases must be pure; normal triggers return flow. computeCosts returns costs, trades, bonuses or paymentResourceProviders. Any costs delta must include matching costAttribution. Discounting all improvement candidates requires bonuses with capDiscountAtCost: true, optional: false, sources: [CARD_ID]; costs is only for simple action fees. computeExchanges returns extraExchanges under the same admitted trade schema. getBaseCosts, deriveCardCostCandidate and cardCostCandidateMandatory are unavailable native callbacks.',
      'Bind each card listener with cardIds: [CARD_ID] so its scope and owner refer to this card. Listener identity uses the player objects named in listeners.players: context.player is the acting player (also context.triggerPlayer), context.ownerPlayer is the card owner, and context.effectPlayer is the effect recipient, normally the owner. Read their .id fields when comparing identities. context.playerId is not provided; do not guess flat identity fields from native engine internals. For a listener bound with cardIds: [CARD_ID], scope: "player" already restricts dispatch to the card owner, so an extra actor/owner guard is unnecessary. For scope: "any" or "opponent", use the documented player objects and preserve who receives the effect.',
      'computeCosts is a pure query called repeatedly for previews and payment execution. Return this card\'s applicable contribution on every invocation. context.costs may contain an incoming computed delta; it is not the base price and does not mean this listener has already contributed. Do not suppress a discount because context.costs already contains a negative value. The payment solver combines contributions and bounds payable costs at zero.',
      'Accumulators dispatch collect. Read the action-space identity from context.space.id, not context.result.spaceId. To recognize all accumulating spaces, check positive values in context.space.gainPerRound instead of guessing a space whitelist. If the user explicitly names particular spaces, match exactly those space IDs. construct uses context.player.houseType; improvement purchase discounts listen to improvement.',
      `Deployed two-player accumulating spaces: ${createActionSpaces(2).filter(space => Object.values(space.gainPerRound).some(amount => (amount ?? 0) > 0)).map(space => space.id).join(', ')}.`,
      'For feeding-start gains return gainLeaf from onStartHarvestFeedingPhase. onComputeAnimalZones returns only additional zones, never the input zones concatenated again. positionKey({row,col}) returns "row-col".',
      'handHooks only dispatches supported stage hooks from hand, excluding onBuy, onEndTurn, onBeforeEndGame, onBeforePlayerTurn and contributeExtraTurn.',
      'Static source structure: CARD_IMPL and CARD_IMPL.effect (when present) must be direct object literals. CARD_IMPL.listeners must be a literal array containing listener object literals directly; never use listeners: [listenerVariable] or listeners: someArray. Each listener handler must be an inline function or method; actions and phases must be literal arrays containing only string literals. Do not use spreads or computed property names in CARD_IMPL, effect or listener objects. CARD_IMPL.effect must not use accessors. Do not reference or mutate CARD_IMPL after its declaration.',
      'special-effect params is a discriminated union. Card-local variants are { kind: "increment-counter", key: string, amount: number }, { kind: "set-counter", key: string, value: number }, { kind: "set-flag", flag: boolean }, { kind: "increment-extra-data", key: string, amount: number }, and { kind: "set-extra-data", key: string, value: unknown }. Put sourceCard: CARD_ID on the leaf. Counter variants write player.cardStates[CARD_ID].counters[key]; set-flag writes flagged; extra-data variants write extraData[key]. Other admitted kinds are pop-card-stack-top, set-infobox(text), and remove-future-meeples(rounds?). All local writes/cancellation are bound to this card and the effect recipient; other native kinds are unavailable.',
      'future-meeples requires params.__futureMeepleRequest with cardId, playerId and either entries or startRound/count/resources. Scheduled resources support ordinary resources plus field/stable; actionContext overrides and native sourceSummary are unavailable. There is no futureMeeplesNode helper; do not import built-in factories.',
      'Preplacing rewards on future rounds uses future-meeples so the engine owns the visible scheduled entries, delivery and cleanup. Do not replace that scheduling with store-on-card plus a flag/onRoundStart payout: counters stored on a card are not future round placements. Read the future-meeples request interface or sandbox example for its entry shape.',
      'gainLeaf, payLeaf, spaceHasPlayer, positionKey, getCardStack and readCardExtraData are the injected helpers shown verbatim. getCardDefinition always returns null; the built-in catalog is not available inside the isolate.',
      'Native built-in card hooks/helpers may write authoritative state or register ad-hoc actions. Adapt their semantics to sandbox flows; never copy imports, mutable native hooks or card_* actions.',
      'The effects, metadata, listener fields/actions/phases, leaf actions and special-effect kinds listed here are enforced during source validation and dynamic execution on server and browser. anytime and compute-exchanges are dispatcher query identities in listeners.actions, never dispatchable leaf actions. Omitted listener filters resolve to these explicit sets, cardIds to [CARD_ID], scope to player and zones to played. Unsupported fields are rejected rather than dropped. Trusted internal flows generated by the authoritative engine retain native settlement operations.',
      'Farm restrictions for plow/sow/fence/stables/construct/renovate-house use leaf top-level actionContext; nested params.actionContext is rejected. Composite mode belongs only on parallel; triggerSelectOnce requires trigger-select mode. All choice values are distinct, including final merged listener menus. Bonus.choices entries require discount and do not admit optional; optional belongs on the outer bonus. Reserve resource keys are distinct. Required card-return cost lists are nonempty; optional empty lists preserve resource payment. Animal allowedAnimalTypes is a rule whitelist across authoritative placement, recovery, accommodation and prefill; an empty list denies all species, intersecting other native restrictions.',
      'Ordinary action parameters are restricted to their listed paramKeys/contextKeys. Keep native payment, prerequisites and component supply. reap requires actionContext.trigger.phase private-field-phase, breed uses this card as source, and reorganize only uses trigger anytime. place-farmer, borrowed fences, farm-hand stables, special field settlement, lifecycle cleanup and event/state writes are unavailable.',
      'Custom pay cannot override playedCards, candidateMetadataByFeeIndex or costResourceRemovals: ownership and attribution are host-owned. Direct pay.cost.cards is deferred pending a host card-eligibility adapter; CARD_DEF.meta.cost.cards retains native purchase ownership. Choice options bind sourceCard to this card. Scoring queries return checked arrays, real player IDs, nonnegative resource costs and finite scores; malformed data becomes card warnings.',
      'Improvement minimumResourcesPaid belongs in actionContext and constrains actual payment; params.allowedPurchases restricts major, minor-only and injected choices. Metadata altCosts entries are flat resource maps; returnCards and remove-resource resources are validated arrays. resourceReserve declares resources and a nonnegative integer minimum. Zero-input exchanges require a nonnegative integer max. Breed animalTypes must be distinct enabled animals; all admitted optional animal-zone fields are checked before host placement.',
      'countExtraTurns needs contributeExtraTurn and returns the remaining opportunities; extraTurnBeforeWorkers offers them before workers. computeResourceCommitments declares player/resource reservations consumed by authoritative payment admission. Animal query hooks return data, not mutations; onComputeSharedAnimalZones adds new zones only. computeAnimalScoreAdjustment currently affects FOTM horse scoring only.',
      'Card Field metadata alone cannot settle sowing: the native makeCardFieldImpl helper registers candidates and mutating settlement through a global definition map. CARD_DEF.meta.cardField is deferred with the extra-sowing pair until a session-local declarative adapter and generated-source parity are available. The sandbox does not expose native getSpecialStablePositions/applySpecialStable write hooks. Ordinary stable construction uses normal field occupancy, payment and component supply rules; returning coordinates or mutating copied farm tiles cannot extend that rule. If a request requires a missing rule extension, report the gap and preserve its requirements.',
    ],
  }
}
