import { describe, expect, it } from 'vitest'
import { GameSession, type SessionResponse } from '../game/authoritative-session'
import { markAllWorkersUsed, setActiveWorkerCount, setWorkersAtHome, workersAvailable } from '../../shared/domain/player'
import { getStoredResource, setStoredResource } from '../../shared/cards/helpers/card-storage'
import { stabilizeRandomHands } from './_helpers/stabilize-random-hands'
import { resolveTriggerIfPresent } from './_helpers/trigger-select'
import { autoAdvanceRoundEnd } from '../../tests/llm-card-gen/session-helpers'

import '../../shared/cards/E/E049_Twibil'
import '../../shared/cards/E/E050_WildGreens'
import '../../shared/cards/E/E052_Cubbyhole'
import '../../shared/cards/E/E054_Contraband'
import '../../shared/cards/E/E055_StoneWeir'
import '../../shared/cards/E/E057_CheeseFondue'
import '../../shared/cards/E/E058_LunchtimeBeer'
import '../../shared/cards/E/E059_CombandCutter'
import '../../shared/cards/E/E061_RaisedBed'
import '../../shared/cards/E/E062_SourDough'
import '../../shared/cards/E/E064_SimpleOven'
import '../../shared/cards/E/E073_Scythe'

const FILLER = '__test_placeholder__'
const OCCUPATIONS = ['A125_Priest', 'B121_Geologist', 'C123_Freemason']
const options = (r: SessionResponse) => r.interaction.stateId === 'wait' ? r.interaction.request.options ?? [] : []
const setup = ({ cardId, played = true, round = 5, occupations = 0, resources = {} }: { cardId: string; played?: boolean; round?: number; occupations?: number; resources?: Record<string, number> }) => {
  const s = new GameSession(8700 + round, undefined, { playerCount: 2 }); stabilizeRandomHands(s.state.players); const st = s.state; st.currentPlayerIndex = 0; st.round = round; st.roundPhase = 'work'; st.actionSpaces.forEach((x) => { x.takenBy = [] }); st.players.forEach((p, i) => { setWorkersAtHome(st, p, i === 0 ? 2 : 0); p.minorHand = [FILLER]; p.occupationHand = [FILLER]; p.minorPlayed = []; p.occupationPlayed = []; p.improvements = []; p.cardStates = {}; p.fields = []; p.pastures = []; p.stableTiles = []; p.fenceSegments = []; p.houseAnimalType = null; p.houseAnimalCount = 0; p.stableAnimals = {}; p.resources = { ...p.resources, wood: 0, clay: 0, reed: 0, stone: 0, food: i === 0 ? 0 : 20, grain: 0, vegetable: 0, sheep: 0, boar: 0, cattle: 0, begging: 0 } }); const p = st.players[0]!; p.minorHand = played ? [FILLER] : [cardId]; p.minorPlayed = played ? [cardId] : []; p.occupationPlayed = OCCUPATIONS.slice(0, occupations); Object.assign(p.resources, resources); s.loadState(st); return s
}
const choose = (s: GameSession, r: SessionResponse, f: (o: ReturnType<typeof options>[number]) => boolean) => { expect(r.interaction.stateId, JSON.stringify(r.interaction)).toBe('wait'); if (r.interaction.stateId !== 'wait') return r; const o = options(r).find(f); expect(o, JSON.stringify(r.interaction)).toBeDefined(); return s.resolveChoice(r.interaction.playerIndex, o!.value) }
const playMinor = (s: GameSession, id: string) => { let r = s.takeAction(0, 'meeting-place'); if (r.interaction.stateId === 'wait') { const b = options(r).find((o) => o.value.startsWith('action-improvement-')); if (b) r = s.resolveChoice(0, b.value) } if (r.state.players[0]!.minorHand.includes(id) && r.interaction.stateId === 'wait') { const c = options(r).find((o) => o.value === id || o.value === `minor:${id}`); if (c) r = s.resolveChoice(0, c.value) } return r }
const accept = (s: GameSession, r: SessionResponse, id: string) => { r = resolveTriggerIfPresent(s, r, id); return r.interaction.stateId === 'wait' ? choose(s, r, (o) => o.value !== '__skip__') : r }
const decline = (s: GameSession, r: SessionResponse, id: string) => { r = resolveTriggerIfPresent(s, r, id); return r.interaction.stateId === 'wait' && options(r).some((o) => o.value === '__skip__') ? s.resolveChoice(r.interaction.playerIndex, '__skip__') : r }
const prepareRoundEnd = (s: GameSession) => { s.state.players.forEach((p) => { p.resources.food = Math.max(p.resources.food, 20); markAllWorkersUsed(s.state, p) }); s.loadState(s.state) }
const bonus = (r: SessionResponse, id: string) => r.scores[0]!.categories.find((c) => c.key === 'cardBonusVp')?.entries.find((e) => e.type === 'bonus' && e.cardId === id)?.score ?? 0
const buildRoom = (s: GameSession) => { let r = s.takeAction(0, 'farm-expansion'); if (r.interaction.stateId === 'wait') { const c = options(r).find((o) => o.labelKey === 'actions.construct.name'); if (c) r = s.resolveChoice(0, c.value) } if (r.interaction.stateId !== 'wait' || r.interaction.request.kind !== 'farm-select') return r; return s.commitSelectionChoice(0, { rooms: [r.interaction.request.farm.selectableTiles[0]!] }) }
const sow = (s: GameSession, crops: Array<{ row: number; col: number; crop: 'grain' | 'vegetable' }>) => { s.state.roundActionOrder[0] = 'grain-utilization'; s.state.actionSpaces.find((x) => x.id === 'grain-utilization')!.roundAvailable = 1; s.loadState(s.state); let r = s.takeAction(0, 'grain-utilization'); if (r.interaction.stateId === 'wait' && r.interaction.request.kind !== 'farm-select') r = choose(s, r, (o) => o.value === 'sow' || o.labelKey === 'actions.sow.name'); return s.commitSelectionChoice(0, { crops }) }
const setupSourDough = () => { const s = new GameSession(62062, undefined, { playerCount: 2 }); stabilizeRandomHands(s.state.players); const st = s.getState().state; st.currentPlayerIndex = 0; st.round = 1; st.roundPhase = 'work'; st.actionSpaces.forEach((space) => { space.takenBy = [] }); st.players.forEach((player) => { setActiveWorkerCount(player, 1); setWorkersAtHome(st, player, 1) }); const owner = st.players[0]!; owner.minorPlayed = ['E062_SourDough']; owner.improvements = ['Major_Fireplace1', 'Major_ClayOven']; owner.resources.grain = 1; owner.resources.food = 0; s.loadState(st); return s }

describe('E049-E052 parity', () => {
  it('E049 S1: paying one stone plays Twibil', () => expect(playMinor(setup({ cardId: 'E049_Twibil', played: false, resources: { stone: 1 } }), 'E049_Twibil').state.players[0]!.minorPlayed).toContain('E049_Twibil'))
  it('E049 S2: building a wooden room gives the owner one food', () => expect(buildRoom(setup({ cardId: 'E049_Twibil', resources: { wood: 5, reed: 2 } })).state.players[0]!.resources.food).toBe(1))
  it('E049 S3: building a clay room gives the owner no food', () => { const s = setup({ cardId: 'E049_Twibil', resources: { clay: 5, reed: 2 } }); s.state.players[0]!.houseType = 'clay'; s.loadState(s.state); expect(buildRoom(s).state.players[0]!.resources.food).toBe(0) })
  it('E050 S1: Wild Greens plays for free', () => expect(playMinor(setup({ cardId: 'E050_WildGreens', played: false }), 'E050_WildGreens').state.players[0]!.minorPlayed).toContain('E050_WildGreens'))
  it('E050 S2: sowing grain and vegetables gains one food per crop type', () => { const s = setup({ cardId: 'E050_WildGreens', round: 10, resources: { grain: 1, vegetable: 1 } }); s.state.players[0]!.fields = [{ row: 0, col: 2, stacks: [] }, { row: 1, col: 2, stacks: [] }]; const r = sow(s, [{ row: 0, col: 2, crop: 'grain' }, { row: 1, col: 2, crop: 'vegetable' }]); expect(r.state.players[0]!.resources.food).toBe(2) })
  it('E050 S3: sowing two grain fields gains only one food', () => { const s = setup({ cardId: 'E050_WildGreens', round: 10, resources: { grain: 2 } }); s.state.players[0]!.fields = [{ row: 0, col: 2, stacks: [] }, { row: 1, col: 2, stacks: [] }]; expect(sow(s, [{ row: 0, col: 2, crop: 'grain' }, { row: 1, col: 2, crop: 'grain' }]).state.players[0]!.resources.food).toBe(1) })
  it.each([{ resource: 'wood' as const }, { resource: 'clay' as const }])('E052 alternate $resource cost plays Cubbyhole', ({ resource }) => expect(playMinor(setup({ cardId: 'E052_Cubbyhole', played: false, resources: { [resource]: 1, reed: 1 } }), 'E052_Cubbyhole').state.players[0]!.minorPlayed).toContain('E052_Cubbyhole'))
  it('E052 S3: each new room stores one food on Cubbyhole', () => { const s = setup({ cardId: 'E052_Cubbyhole', resources: { wood: 5, reed: 2 } }); let r = buildRoom(s); r = resolveTriggerIfPresent(s, r, 'E052_Cubbyhole'); expect(getStoredResource(r.state.players[0]!, 'E052_Cubbyhole', 'food')).toBe(1) })
  it('E052 S4: feeding gains the stored amount from supply and preserves Cubbyhole food', () => { const s = setup({ cardId: 'E052_Cubbyhole', round: 4 }); setStoredResource(s.state.players[0]!, 'E052_Cubbyhole', 'food', 2); prepareRoundEnd(s); const r = autoAdvanceRoundEnd(s, { onChoice: (interaction, current) => { const o = interaction.request.options?.find((x) => x.value === 'E052_Cubbyhole' || x.sourceCard === 'E052_Cubbyhole'); return o ? current.resolveChoice(interaction.playerIndex, o.value) : undefined } }); expect(r.state.players[0]!.resources.food).toBe(18); expect(getStoredResource(r.state.players[0]!, 'E052_Cubbyhole', 'food')).toBe(2) })
})

describe('E054-E059 parity', () => {
  it('E054 S1: paying one food plays Contraband without triggering itself', () => { const r = playMinor(setup({ cardId: 'E054_Contraband', played: false, resources: { food: 1 } }), 'E054_Contraband'); expect(r.state.players[0]!.minorPlayed).toContain('E054_Contraband'); expect(r.state.players[0]!.resources.food).toBe(0) })
  const contraband = (take: boolean) => { const s = setup({ cardId: 'E054_Contraband', resources: { clay: 3 } }); s.state.availableMajorImprovements = ['Major_Fireplace1']; s.loadState(s.state); let r = s.takeAction(0, 'major-improvement'); if (r.interaction.stateId === 'wait' && r.interaction.request.kind !== 'select-trigger') { const major = options(r).find((o) => o.value === 'Major_Fireplace1'); const branch = options(r).find((o) => o.value.startsWith('action-improvement-')); if (major) r = s.resolveChoice(r.interaction.playerIndex, major.value); else if (branch) { r = s.resolveChoice(r.interaction.playerIndex, branch.value); if (r.interaction.stateId === 'wait') r = choose(s, r, (o) => o.value === 'Major_Fireplace1') } } r = resolveTriggerIfPresent(s, r, 'E054_Contraband'); if (r.interaction.stateId === 'wait') r = s.resolveChoice(r.interaction.playerIndex, take ? options(r).find((o) => o.value !== '__skip__')!.value : '__skip__'); if (take && r.interaction.stateId === 'wait' && r.interaction.sourceCard === 'E054_Contraband') r = choose(s, r, (o) => o.value !== '__skip__'); return r }
  it('E054 S2: after a clay-cost improvement one extra clay may buy three food', () => expect(contraband(true).state.players[0]!.resources).toMatchObject({ clay: 0, food: 3 }))
  it('E054 S3: the Contraband exchange may be declined', () => expect(contraband(false).state.players[0]!.resources).toMatchObject({ clay: 1, food: 0 }))
  it('E055 S1: two occupations and one stone play Stone Weir', () => expect(playMinor(setup({ cardId: 'E055_StoneWeir', played: false, occupations: 2, resources: { stone: 1 } }), 'E055_StoneWeir').state.players[0]!.minorPlayed).toContain('E055_StoneWeir'))
  it.each([0, 1, 3, 4])('E055 Fishing with %i food leaves four food total', (food) => { const s = setup({ cardId: 'E055_StoneWeir', occupations: 2 }); s.state.actionSpaces.find((x) => x.id === 'fishing')!.resources.food = food; s.loadState(s.state); expect(s.takeAction(0, 'fishing').state.players[0]!.resources.food).toBe(4) })
  it('E057 S1: paying one clay plays Cheese Fondue', () => expect(playMinor(setup({ cardId: 'E057_CheeseFondue', played: false, resources: { clay: 1 } }), 'E057_CheeseFondue').state.players[0]!.minorPlayed).toContain('E057_CheeseFondue'))
  const bake = (animals: boolean) => { const s = setup({ cardId: 'E057_CheeseFondue', resources: { grain: 1, sheep: animals ? 1 : 0, cattle: animals ? 1 : 0 } }); s.state.players[0]!.improvements = ['Major_Fireplace1']; if (animals) { s.state.players[0]!.houseAnimalType = 'sheep'; s.state.players[0]!.houseAnimalCount = 1; s.state.players[0]!.pastures = [{ id: 'cattle-pasture', size: 1, tiles: [{ row: 2, col: 2 }], stables: 0, animalType: 'cattle', animalCount: 1 }] } s.state.roundActionOrder[0] = 'grain-utilization'; s.state.actionSpaces.find((x) => x.id === 'grain-utilization')!.roundAvailable = 1; s.loadState(s.state); let r = s.takeAction(0, 'grain-utilization'); if (r.interaction.stateId === 'wait' && options(r).some((o) => o.value === 'bake-bread' || o.labelKey === 'actions.bakeBread.name')) r = choose(s, r, (o) => o.value === 'bake-bread' || o.labelKey === 'actions.bakeBread.name'); if (r.interaction.stateId === 'wait' && r.interaction.promptKey === 'ui.interactionBakeBreadChoice') r = choose(s, r, (o) => o.value === 'Major_Fireplace1'); return r }
  it('E057 S2: baking with sheep and cattle gains two additional food', () => expect(bake(true).state.players[0]!.resources.food).toBe(4))
  it('E057 S3: baking without sheep or cattle gains no extra food', () => expect(bake(false).state.players[0]!.resources.food).toBe(2))
  it('E058 S1: Lunchtime Beer plays for free', () => expect(playMinor(setup({ cardId: 'E058_LunchtimeBeer', played: false }), 'E058_LunchtimeBeer').state.players[0]!.minorPlayed).toContain('E058_LunchtimeBeer'))
  const lunchtime = (take: boolean) => { const s = setup({ cardId: 'E058_LunchtimeBeer', round: 4 }); s.state.players[0]!.fields = [{ row: 0, col: 2, stacks: [{ kind: 'grain', remaining: 2 }] }]; prepareRoundEnd(s); return autoAdvanceRoundEnd(s, { onChoice: (interaction, current) => { if (interaction.sourceCard !== 'E058_LunchtimeBeer' && !interaction.request.options?.some((o) => o.sourceCard === 'E058_LunchtimeBeer')) return undefined; const o = interaction.request.options?.find((x) => take ? x.value !== '__skip__' : x.value === '__skip__'); return o ? current.resolveChoice(interaction.playerIndex, o.value) : undefined } }) }
  it('E058 S2: accepting gains one food and skips field harvest', () => { const r = lunchtime(true); expect(r.state.players[0]!.fields[0]!.stacks[0]!.remaining).toBe(2); expect(r.state.players[0]!.resources.food).toBe(17) })
  it('E058 S3: declining allows the normal field harvest', () => { const r = lunchtime(false); expect(r.state.players[0]!.fields[0]!.stacks[0]!.remaining).toBe(1); expect(r.state.players[0]!.resources.grain).toBe(1) })
  it('E059 S1: paying one wood plays Comb and Cutter', () => expect(playMinor(setup({ cardId: 'E059_CombandCutter', played: false, resources: { wood: 1 } }), 'E059_CombandCutter').state.players[0]!.minorPlayed).toContain('E059_CombandCutter'))
  it.each([{ sheep: 2, food: 4 }, { sheep: 5, food: 6 }])('E059 Day Laborer with $sheep sheep on market gives $food food', ({ sheep, food }) => { const s = setup({ cardId: 'E059_CombandCutter' }); s.state.actionSpaces.find((x) => x.id === 'sheep-market')!.resources.sheep = sheep; s.loadState(s.state); expect(s.takeAction(0, 'day-laborer').state.players[0]!.resources.food).toBe(food) })
})

describe('E061-E073 parity', () => {
  const grainFields = [{ row: 0, col: 2, stacks: [{ kind: 'grain' as const, remaining: 1 }] }, { row: 1, col: 2, stacks: [{ kind: 'grain' as const, remaining: 1 }] }]
  it('E061 S1/S2: exactly two grain fields satisfy Raised Bed prerequisite', () => { const ok = setup({ cardId: 'E061_RaisedBed', played: false, resources: { clay: 2, stone: 2 } }); ok.state.players[0]!.fields = grainFields; ok.loadState(ok.state); expect(playMinor(ok, 'E061_RaisedBed').state.players[0]!.minorPlayed).toContain('E061_RaisedBed'); const no = setup({ cardId: 'E061_RaisedBed', played: false, resources: { clay: 2, stone: 2 } }); no.state.players[0]!.fields = grainFields.slice(0, 1); no.loadState(no.state); expect(playMinor(no, 'E061_RaisedBed').state.players[0]!.minorPlayed).not.toContain('E061_RaisedBed') })
  it('E061 S3: harvest start gains four food', () => { const s = setup({ cardId: 'E061_RaisedBed', round: 4 }); prepareRoundEnd(s); expect(autoAdvanceRoundEnd(s).state.players[0]!.resources.food).toBe(20) })
  it('E062 S1: three occupations and a baking improvement allow Sour Dough', () => { const s = setup({ cardId: 'E062_SourDough', played: false, occupations: 3 }); s.state.players[0]!.improvements = ['Major_Fireplace1']; s.loadState(s.state); expect(playMinor(s, 'E062_SourDough').state.players[0]!.minorPlayed).toContain('E062_SourDough') })
  it('E062 S2: Sour Dough replaces placement with baking and passes the turn', () => { const s = setupSourDough(); const before = s.getState(); expect(before.interaction.stateId).toBe('idle'); expect(before.interaction.anytimeActions.map((a) => a.id)).toContain('E62-sour-dough-anytime'); let r = s.takeAnytimeAction(0, 'E62-sour-dough-anytime'); expect(r.interaction).toMatchObject({ stateId: 'wait', playerIndex: 0, promptKey: 'ui.interactionBakeBreadChoice' }); r = s.resolveChoice(0, 'Major_Fireplace1'); expect(r.ok, r.error).toBe(true); expect(r.state.players[0]!.resources).toMatchObject({ grain: 0, food: 2 }); expect(workersAvailable(r.state, r.state.players[0]!)).toBe(1); expect(r.state.actionSpaces.every((space) => space.takenBy.every((worker) => worker.playerId !== r.state.players[0]!.id))).toBe(true); expect(r.state.players[0]!.cardStates.E062_SourDough?.flagged).toBe(true); expect(r.interaction).toMatchObject({ stateId: 'wait', request: { kind: 'confirm-next-player', nextPlayerIndex: 1 } }) })
  it('E062 S3: a used Sour Dough flag suppresses a second use in the same round', () => { const s = setup({ cardId: 'E062_SourDough', occupations: 3, resources: { grain: 1 } }); s.state.players[0]!.improvements = ['Major_Fireplace1']; s.state.players[0]!.cardStates.E062_SourDough = { flagged: true }; setWorkersAtHome(s.state, s.state.players[1]!, 1); s.loadState(s.state); expect(s.getState().interaction.anytimeActions.map((a) => a.id)).not.toContain('E62-sour-dough-anytime') })
  it('E064 S1: two clay play Simple Oven', () => expect(playMinor(setup({ cardId: 'E064_SimpleOven', played: false, resources: { clay: 2 } }), 'E064_SimpleOven').state.players[0]!.minorPlayed).toContain('E064_SimpleOven'))
  it.each([true, false])('E064 immediate bake take=%s', (take) => { const s = setup({ cardId: 'E064_SimpleOven', played: false, resources: { clay: 2, grain: 1 } }); let r = playMinor(s, 'E064_SimpleOven'); if (r.interaction.stateId === 'wait' && r.interaction.sourceCard === 'E064_SimpleOven') r = take ? choose(s, r, (o) => o.value !== '__skip__') : s.resolveChoice(r.interaction.playerIndex, '__skip__'); if (take && r.interaction.stateId === 'wait' && r.interaction.promptKey === 'ui.interactionBakeBreadChoice') r = choose(s, r, (o) => o.value === 'E064_SimpleOven'); expect(r.state.players[0]!.resources).toMatchObject({ grain: take ? 0 : 1, food: take ? 3 : 0 }) })
  it('E073 S1: paying one wood plays Scythe', () => expect(playMinor(setup({ cardId: 'E073_Scythe', played: false, resources: { wood: 1 } }), 'E073_Scythe').state.players[0]!.minorPlayed).toContain('E073_Scythe'))
  const scythe = (take: boolean) => { const s = setup({ cardId: 'E073_Scythe', round: 4 }); s.state.players[0]!.fields = [{ row: 0, col: 2, stacks: [{ kind: 'grain', remaining: 3 }] }, { row: 1, col: 2, stacks: [{ kind: 'vegetable', remaining: 2 }] }]; prepareRoundEnd(s); return autoAdvanceRoundEnd(s, { onChoice: (interaction, current) => { if (interaction.sourceCard !== 'E073_Scythe' && !interaction.request.options?.some((o) => o.sourceCard === 'E073_Scythe')) return undefined; const o = interaction.request.options?.find((x) => take ? x.value !== '__skip__' && JSON.stringify(x).includes('grain') : x.value === '__skip__'); return o ? current.resolveChoice(interaction.playerIndex, o.value) : undefined } }) }
  it('E073 S2: Scythe harvests all crops from one selected field', () => { const r = scythe(true); expect(r.state.players[0]!.fields.map((f) => f.stacks[0]?.remaining ?? 0)).toEqual([0, 1]); expect(r.state.players[0]!.resources).toMatchObject({ grain: 3, vegetable: 1 }) })
  it('E073 S3: declining harvests one crop from each field normally', () => { const r = scythe(false); expect(r.state.players[0]!.fields.map((f) => f.stacks[0]?.remaining ?? 0)).toEqual([2, 1]); expect(r.state.players[0]!.resources).toMatchObject({ grain: 1, vegetable: 1 }) })
})
