import { describe, expect, it } from 'vitest'
import { GameSession, type SessionResponse } from '../game/authoritative-session'
import { markAllWorkersUsed, setWorkersAtHome } from '../../shared/domain/player'
import { getCardStack } from '../../shared/cards/helpers/card-state'
import { stabilizeRandomHands } from './_helpers/stabilize-random-hands'
import { resolveTriggerIfPresent } from './_helpers/trigger-select'
import { autoAdvanceRoundEnd } from '../../tests/llm-card-gen/session-helpers'

import '../../shared/cards/E/E090_DungCollector'
import '../../shared/cards/E/E101_Blighter'
import '../../shared/cards/E/E102_Acquirer'
import '../../shared/cards/E/E105_Pioneer'
import '../../shared/cards/E/E106_EmergencySeller'
import '../../shared/cards/E/E107_LandSurveyor'
import '../../shared/cards/E/E110_Dentist'
import '../../shared/cards/E/E111_Recluse'
import '../../shared/cards/E/E118_KindlingGatherer'
import '../../shared/cards/E/E122_Cottar'
import '../../shared/cards/E/E126_TaxCollector'
import '../../shared/cards/E/E127_DiligentFarmer'

const FILLER = '__test_placeholder__'
const options = (r: SessionResponse) => r.interaction.stateId === 'wait' ? r.interaction.request.options ?? [] : []
const setup = ({ cardId, played = true, playerCount = 2, round = 5, resources = {} }: { cardId: string; played?: boolean; playerCount?: number; round?: number; resources?: Record<string, number> }) => { const s = new GameSession(8800 + round, undefined, { playerCount }); stabilizeRandomHands(s.state.players); const st = s.state; st.currentPlayerIndex = 0; st.round = round; st.roundPhase = 'work'; st.actionSpaces.forEach((x) => { x.takenBy = [] }); st.players.forEach((p, i) => { setWorkersAtHome(st, p, i === 0 ? 2 : 0); p.minorHand = [FILLER]; p.occupationHand = [FILLER]; p.minorPlayed = []; p.occupationPlayed = []; p.improvements = []; p.cardStates = {}; p.fields = []; p.pastures = []; p.stableTiles = []; p.fenceSegments = []; p.houseAnimalType = null; p.houseAnimalCount = 0; p.stableAnimals = {}; p.resources = { ...p.resources, wood: 0, clay: 0, reed: 0, stone: 0, food: i === 0 ? 0 : 20, grain: 0, vegetable: 0, sheep: 0, boar: 0, cattle: 0, begging: 0 } }); const p = st.players[0]!; p.occupationHand = played ? [FILLER] : [cardId]; p.occupationPlayed = played ? [cardId] : []; Object.assign(p.resources, resources); s.loadState(st); return s }
const choose = (s: GameSession, r: SessionResponse, f: (o: ReturnType<typeof options>[number]) => boolean) => { expect(r.interaction.stateId, JSON.stringify(r.interaction)).toBe('wait'); if (r.interaction.stateId !== 'wait') return r; const o = options(r).find(f); expect(o, JSON.stringify(r.interaction)).toBeDefined(); return s.resolveChoice(r.interaction.playerIndex, o!.value) }
const playOccupation = (s: GameSession, id: string) => { let r = s.takeAction(0, 'lessons'); if (r.state.players[0]!.occupationHand.includes(id) && r.interaction.stateId === 'wait') { const c = options(r).find((o) => o.value === id); if (c) r = s.resolveChoice(0, c.value) } return r }
const prepareRoundEnd = (s: GameSession) => { s.state.players.forEach((p) => { p.resources.food = Math.max(p.resources.food, 20); markAllWorkersUsed(s.state, p) }); s.loadState(s.state) }
const bonus = (r: SessionResponse, id: string) => r.state.players[0]!.cardStates[id]?.counters?.bonusVp ?? r.scores[0]!.categories.find((c) => c.key === 'cardBonusVp')?.entries.find((e) => e.type === 'bonus' && e.cardId === id)?.score ?? 0

describe('E090-E107 parity', () => {
  it('E090 S1: Dung Collector can be played as the first occupation', () => expect(playOccupation(setup({ cardId: 'E090_DungCollector', played: false }), 'E090_DungCollector').state.players[0]!.occupationPlayed).toContain('E090_DungCollector'))
  const dung = (sheep: number) => { const s = setup({ cardId: 'E090_DungCollector', round: 4, resources: { sheep } }); s.state.players[0]!.fields = []; s.state.players[0]!.pastures = [{ id: 'sheep', size: 2, tiles: [{ row: 1, col: 0 }, { row: 1, col: 1 }], stables: 1, animalType: 'sheep', animalCount: sheep }]; prepareRoundEnd(s); let r = s.performRoundEnd(); if (r.interaction.stateId === 'wait' && r.interaction.request.kind === 'animal-reorg') r = s.resolveChoice(0, 'confirm', { zones: r.interaction.request.zones }); return { s, r } }
  it('E090 S2: two placed newborn animals may pay one food to plow', () => { const s = setup({ cardId: 'E090_DungCollector', round: 4, resources: { sheep: 2, boar: 2 } }); s.state.players[0]!.pastures = [{ id: 'sheep', size: 2, tiles: [{ row: 1, col: 0 }, { row: 1, col: 1 }], stables: 1, animalType: 'sheep', animalCount: 2 }, { id: 'boar', size: 2, tiles: [{ row: 2, col: 0 }, { row: 2, col: 1 }], stables: 1, animalType: 'boar', animalCount: 2 }]; prepareRoundEnd(s); s.performRoundEnd(); let r = s.resolveChoice(0, 'confirm', [{ id: 'sheep', zoneType: 'pasture', animalType: 'sheep', animalCount: 3 }, { id: 'boar', zoneType: 'pasture', animalType: 'boar', animalCount: 3 }]); r = resolveTriggerIfPresent(s, r, 'E090_DungCollector'); if (r.interaction.stateId === 'wait') r = choose(s, r, (o) => o.value !== '__skip__'); if (r.interaction.stateId === 'wait' && r.interaction.request.kind === 'farm-select') r = s.commitSelectionChoice(0, { tile: r.interaction.request.farm.selectableTiles[0]! }); expect(r.state.players[0]!.fields).toHaveLength(1) })
  it('E090 S3: one newborn animal gives no Dung Collector offer', () => { const { r } = dung(2); expect(JSON.stringify(r.interaction)).not.toContain('E090_DungCollector') })
  it('E101 S1: OA plays Blighter in round five but gains no bonus points', () => { const r = playOccupation(setup({ cardId: 'E101_Blighter', played: false, round: 5 }), 'E101_Blighter'); expect(r.state.players[0]!.occupationPlayed).toContain('E101_Blighter'); expect(bonus(r, 'E101_Blighter')).toBe(0) })
  it('E101 S2: Blighter prevents playing another occupation', () => { const s = setup({ cardId: 'E101_Blighter' }); s.state.players[0]!.occupationHand = ['A125_Priest']; s.loadState(s.state); const r = s.takeAction(0, 'lessons'); expect(r.ok).toBe(false); expect(r.state.players[0]!.occupationHand).toContain('A125_Priest') })
  it('E101 S3: OA plays Blighter in round eleven but still gains no bonus points', () => { const r = playOccupation(setup({ cardId: 'E101_Blighter', played: false, round: 11 }), 'E101_Blighter'); expect(r.state.players[0]!.occupationPlayed).toContain('E101_Blighter'); expect(bonus(r, 'E101_Blighter')).toBe(0) })
  it('E101 S4: playing Blighter in round fourteen gains no bonus points', () => { const r = playOccupation(setup({ cardId: 'E101_Blighter', played: false, round: 14 }), 'E101_Blighter'); expect(r.state.players[0]!.occupationPlayed).toContain('E101_Blighter'); expect(bonus(r, 'E101_Blighter')).toBe(0) })
  it.each([{ scenario: 'S5', round: 1 }, { scenario: 'S6', round: 8 }, { scenario: 'S7', round: 13 }])('E101 $scenario: OA plays Blighter in round $round but still gains no bonus points', ({ round }) => { const r = playOccupation(setup({ cardId: 'E101_Blighter', played: false, round }), 'E101_Blighter'); expect(r.state.players[0]!.occupationPlayed).toContain('E101_Blighter'); expect(bonus(r, 'E101_Blighter')).toBe(0) })
  it('E102 S1: Acquirer can be played as the first occupation', () => expect(playOccupation(setup({ cardId: 'E102_Acquirer', played: false }), 'E102_Acquirer').state.players[0]!.occupationPlayed).toContain('E102_Acquirer'))
  it.each([true, false])('E102 round start purchase take=%s', (take) => { const s = setup({ cardId: 'E102_Acquirer', round: 4, resources: { food: 22 } }); prepareRoundEnd(s); let r = s.performRoundEnd(); r = resolveTriggerIfPresent(s, r, 'E102_Acquirer'); if (r.interaction.stateId === 'wait') r = s.resolveChoice(r.interaction.playerIndex, take ? options(r).find((o) => o.value !== '__skip__')!.value : '__skip__'); if (take && r.interaction.stateId === 'wait') r = choose(s, r, (o) => o.effectPreview?.resourcesGained?.stone === 1); expect(r.state.players[0]!.resources).toMatchObject({ food: take ? 16 : 18, stone: take ? 1 : 0 }) })
  it('E105 S1: playing Pioneer gains one chosen resource and one food', () => { const s = setup({ cardId: 'E105_Pioneer', played: false }); let r = playOccupation(s, 'E105_Pioneer'); if (r.interaction.stateId === 'wait') r = choose(s, r, (o) => o.effectPreview?.resourcesGained?.stone === 1); expect(r.state.players[0]!.resources).toMatchObject({ stone: 1, food: 1 }) })
  it('E105 S2: using the most recent action gains one resource and food', () => { const s = setup({ cardId: 'E105_Pioneer', round: 8 }); s.state.roundActionOrder[7] = 'cattle-market'; s.state.actionSpaces.find((x) => x.id === 'cattle-market')!.resources.cattle = 0; s.loadState(s.state); let r = s.takeAction(0, 'cattle-market'); if (r.interaction.stateId === 'wait') r = choose(s, r, (o) => o.effectPreview?.resourcesGained?.wood === 1); expect(r.state.players[0]!.resources).toMatchObject({ wood: 1, food: 1 }) })
  it('E105 S3: another action gives no Pioneer reward', () => expect(setup({ cardId: 'E105_Pioneer', round: 8 }).takeAction(0, 'day-laborer').state.players[0]!.resources).toMatchObject({ wood: 0, food: 2 }))
  it.each([true, false])('E106 Emergency Seller take=%s', (take) => { const s = setup({ cardId: 'E106_EmergencySeller', played: false, resources: { wood: 1, stone: 1 } }); let r = playOccupation(s, 'E106_EmergencySeller'); for (let guard = 0; take && guard < 6 && r.interaction.stateId === 'wait'; guard += 1) { const resource = r.state.players[0]!.resources.wood > 0 ? 'wood' : 'stone'; const o = options(r).find((x) => x.effectPreview?.resourcesPaid?.[resource] === 1) ?? options(r).find((x) => x.value !== '__skip__'); if (!o) break; r = s.resolveChoice(r.interaction.playerIndex, o.value) } if (!take && r.interaction.stateId === 'wait') r = s.resolveChoice(r.interaction.playerIndex, '__skip__'); expect(r.state.players[0]!.resources, JSON.stringify(r.interaction)).toMatchObject(take ? { wood: 0, stone: 0, food: 5 } : { wood: 1, stone: 1, food: 0 }) })
  it.each([{ resource: 'wood', food: 2 }, { resource: 'clay', food: 2 }, { resource: 'reed', food: 3 }, { resource: 'stone', food: 3 }] as const)('E106 S3: one $resource sells for $food food', ({ resource, food }) => { const s = setup({ cardId: 'E106_EmergencySeller', played: false, resources: { [resource]: 1 } }); let r = playOccupation(s, 'E106_EmergencySeller'); for (let guard = 0; guard < 3 && r.interaction.stateId === 'wait' && r.state.players[0]!.resources[resource] > 0; guard += 1) { const sale = options(r).find((o) => o.effectPreview?.resourcesPaid?.[resource] === 1) ?? options(r).find((o) => o.value !== '__skip__'); expect(sale, JSON.stringify(r.interaction)).toBeDefined(); r = s.resolveChoice(r.interaction.playerIndex, sale!.value) } expect(r.state.players[0]!.resources[resource]).toBe(0); expect(r.state.players[0]!.resources.food).toBe(food) })
  it('E106 S4: a two-person family sells at most two building resources', () => { const s = setup({ cardId: 'E106_EmergencySeller', played: false, resources: { wood: 1, clay: 1, reed: 1 } }); let r = playOccupation(s, 'E106_EmergencySeller'); for (let guard = 0; guard < 6 && r.interaction.stateId === 'wait' && r.state.players[0]!.resources.food < 4; guard += 1) { const resource = r.state.players[0]!.resources.wood > 0 ? 'wood' : 'clay'; const sale = options(r).find((o) => o.effectPreview?.resourcesPaid?.[resource] === 1) ?? options(r).find((o) => o.value !== '__skip__'); expect(sale).toBeDefined(); r = s.resolveChoice(r.interaction.playerIndex, sale!.value) } expect(r.state.players[0]!.resources).toMatchObject({ wood: 0, clay: 0, reed: 1, food: 4 }) })
  it('E107 S1: Land Surveyor can be played as the first occupation', () => expect(playOccupation(setup({ cardId: 'E107_LandSurveyor', played: false }), 'E107_LandSurveyor').state.players[0]!.occupationPlayed).toContain('E107_LandSurveyor'))
  it.each([{ fields: 1, food: 16 }, { fields: 2, food: 17 }, { fields: 4, food: 18 }, { fields: 7, food: 20 }])('E107 harvest with $fields fields leaves $food food', ({ fields, food }) => { const s = setup({ cardId: 'E107_LandSurveyor', round: 4 }); s.state.players[0]!.fields = Array.from({ length: fields }, (_, i) => ({ row: Math.floor(i / 3), col: i % 3 + 2, stacks: [] })); prepareRoundEnd(s); expect(autoAdvanceRoundEnd(s).state.players[0]!.resources.food).toBe(food) })
})

describe('E110-E127 parity', () => {
  it('E110 S1: Dentist can be played as the first occupation', () => expect(playOccupation(setup({ cardId: 'E110_Dentist', played: false }), 'E110_Dentist').state.players[0]!.occupationPlayed).toContain('E110_Dentist'))
  it.each([true, false])('E110 harvest stores one wood take=%s and existing wood grants food', (take) => { const s = setup({ cardId: 'E110_Dentist', round: 4, resources: { wood: 1 } }); s.state.players[0]!.cardStates.E110_Dentist = { stack: ['wood', 'wood'] }; prepareRoundEnd(s); const r = autoAdvanceRoundEnd(s, { onChoice: (interaction, current) => { if (interaction.sourceCard !== 'E110_Dentist' && !interaction.request.options?.some((o) => o.sourceCard === 'E110_Dentist')) return undefined; const o = interaction.request.options?.find((x) => take ? x.value !== '__skip__' : x.value === '__skip__'); return o ? current.resolveChoice(interaction.playerIndex, o.value) : undefined } }); expect(getCardStack(r.state.players[0]!, 'E110_Dentist')).toHaveLength(take ? 3 : 2); expect(r.state.players[0]!.resources.food).toBe(take ? 19 : 18) })
  it('E111 S1: Recluse can be played as the first occupation', () => expect(playOccupation(setup({ cardId: 'E111_Recluse', played: false }), 'E111_Recluse').state.players[0]!.occupationPlayed).toContain('E111_Recluse'))
  it('E111 S2: no minors gains wood at harvest and food next round', () => { const s = setup({ cardId: 'E111_Recluse', round: 4 }); prepareRoundEnd(s); const r = autoAdvanceRoundEnd(s); expect(r.state.players[0]!.resources).toMatchObject({ wood: 1, food: 17 }) })
  it('E111 S3: a played minor suppresses both Recluse gains', () => { const s = setup({ cardId: 'E111_Recluse', round: 4 }); s.state.players[0]!.minorPlayed = ['E050_WildGreens']; prepareRoundEnd(s); const r = autoAdvanceRoundEnd(s); expect(r.state.players[0]!.resources).toMatchObject({ wood: 0, food: 16 }) })
  it('E118 S1: Kindling Gatherer can be played as the first occupation', () => expect(playOccupation(setup({ cardId: 'E118_KindlingGatherer', played: false }), 'E118_KindlingGatherer').state.players[0]!.occupationPlayed).toContain('E118_KindlingGatherer'))
  it('E118 S2: Day Laborer food gains one additional wood', () => expect(setup({ cardId: 'E118_KindlingGatherer' }).takeAction(0, 'day-laborer').state.players[0]!.resources).toMatchObject({ food: 2, wood: 1 }))
  it('E118 S3: collecting only clay grants no wood', () => { const s = setup({ cardId: 'E118_KindlingGatherer' }); s.state.actionSpaces.find((x) => x.id === 'clay-pit')!.resources.clay = 2; s.loadState(s.state); expect(s.takeAction(0, 'clay-pit').state.players[0]!.resources.wood).toBe(0) })
  it('E122 S1: Cottar can be played as the first occupation', () => expect(playOccupation(setup({ cardId: 'E122_Cottar', played: false }), 'E122_Cottar').state.players[0]!.occupationPlayed).toContain('E122_Cottar'))
  it('E122 S2: after paying an improvement cost Cottar gains chosen wood', () => { const s = setup({ cardId: 'E122_Cottar', resources: { clay: 2 } }); s.state.availableMajorImprovements = ['Major_Fireplace1']; s.loadState(s.state); let r = s.takeAction(0, 'major-improvement'); if (r.interaction.stateId === 'wait' && options(r).some((o) => o.value === 'Major_Fireplace1')) r = s.resolveChoice(0, 'Major_Fireplace1'); r = resolveTriggerIfPresent(s, r, 'E122_Cottar'); if (r.interaction.stateId === 'wait') r = choose(s, r, (o) => o.effectPreview?.resourcesGained?.wood === 1); expect(r.state.players[0]!.resources).toMatchObject({ clay: 0, wood: 1 }) })
  it('E122 S3: after paying an improvement cost Cottar may choose clay', () => { const s = setup({ cardId: 'E122_Cottar', resources: { clay: 2 } }); s.state.availableMajorImprovements = ['Major_Fireplace1']; s.loadState(s.state); let r = s.takeAction(0, 'major-improvement'); if (r.interaction.stateId === 'wait' && options(r).some((o) => o.value === 'Major_Fireplace1')) r = s.resolveChoice(0, 'Major_Fireplace1'); r = resolveTriggerIfPresent(s, r, 'E122_Cottar'); if (r.interaction.stateId === 'wait') r = choose(s, r, (o) => o.effectPreview?.resourcesGained?.clay === 1); expect(r.state.players[0]!.resources).toMatchObject({ clay: 1, wood: 0 }) })
  it('E126 S1: Tax Collector can be played as the first occupation', () => expect(playOccupation(setup({ cardId: 'E126_TaxCollector', played: false }), 'E126_TaxCollector').state.players[0]!.occupationPlayed).toContain('E126_TaxCollector'))
  it('E126 S2/S3: only a stone house receives the round-start choice', () => { for (const houseType of ['stone', 'clay'] as const) { const s = setup({ cardId: 'E126_TaxCollector', round: 4 }); s.state.players[0]!.houseType = houseType; prepareRoundEnd(s); let r = s.performRoundEnd(); if (houseType === 'stone') { r = resolveTriggerIfPresent(s, r, 'E126_TaxCollector'); if (r.interaction.stateId === 'wait') r = choose(s, r, (o) => o.effectPreview?.resourcesGained?.wood === 2) } expect(r.state.players[0]!.resources.wood).toBe(houseType === 'stone' ? 2 : 0) } })
  it('E127 S1: Diligent Farmer can be played as the first occupation', () => expect(playOccupation(setup({ cardId: 'E127_DiligentFarmer', played: false, playerCount: 3 }), 'E127_DiligentFarmer').state.players[0]!.occupationPlayed).toContain('E127_DiligentFarmer'))
  it('E127 S2: three maximum scoring categories allow one free room', () => { const s = setup({ cardId: 'E127_DiligentFarmer', played: false, playerCount: 3, resources: { grain: 8, vegetable: 4 } }); s.state.players[0]!.fields = Array.from({ length: 5 }, (_, i) => ({ row: Math.floor(i / 3), col: i % 3 + 2, stacks: [] })); s.loadState(s.state); let r = playOccupation(s, 'E127_DiligentFarmer'); r = resolveTriggerIfPresent(s, r, 'E127_DiligentFarmer'); if (r.interaction.stateId === 'wait' && options(r).some((o) => o.value !== '__skip__')) r = choose(s, r, (o) => o.value !== '__skip__'); if (r.interaction.stateId === 'wait' && r.interaction.request.kind === 'farm-select') r = s.commitSelectionChoice(0, { rooms: [r.interaction.request.farm.selectableTiles[0]!] }); expect(r.state.players[0]!.rooms).toBe(3) })
  it('E127 S3: only two maximum scoring categories give no free-room offer', () => { const s = setup({ cardId: 'E127_DiligentFarmer', played: false, playerCount: 3, resources: { grain: 8 } }); s.state.players[0]!.fields = Array.from({ length: 5 }, (_, i) => ({ row: Math.floor(i / 3), col: i % 3 + 2, stacks: [] })); s.loadState(s.state); const r = playOccupation(s, 'E127_DiligentFarmer'); expect(JSON.stringify(r.interaction)).not.toContain('E127_DiligentFarmer'); expect(r.state.players[0]!.rooms).toBe(2) })
  it('E127 S4: the free Diligent Farmer room may be declined', () => { const s = setup({ cardId: 'E127_DiligentFarmer', played: false, playerCount: 3, resources: { grain: 8, vegetable: 4 } }); s.state.players[0]!.fields = Array.from({ length: 5 }, (_, i) => ({ row: Math.floor(i / 3), col: i % 3 + 2, stacks: [] })); s.loadState(s.state); let r = playOccupation(s, 'E127_DiligentFarmer'); r = resolveTriggerIfPresent(s, r, 'E127_DiligentFarmer'); if (r.interaction.stateId === 'wait') r = s.resolveChoice(r.interaction.playerIndex, '__skip__'); expect(r.state.players[0]!.rooms).toBe(2) })
})
