#!/usr/bin/env tsx
/**
 * Generate `shared/cards/register-all.ts` — a single aggregation module that
 * imports every `<CARD_ID>_impl` export from the card files and exposes them
 * as `ALL_CARD_IMPLS` keyed by card id.
 *
 * Also generates `shared/cards/community/auto-catalog.ts` — aggregates all
 * community card definitions for catalog.ts to consume.
 *
 * Run manually after changing any card file that adds/removes an `_impl`:
 *   pnpm run generate:register-all
 *
 * Task 11 will wire `GameCore` to call `CardRegistry.loadImpl(cardId, impl)`
 * for each entry in `ALL_CARD_IMPLS`.
 */
import fs from 'node:fs'
import path from 'node:path'

const cardsRoot = path.resolve(process.cwd(), 'shared', 'cards')
const decks = ['A', 'B', 'C', 'D', 'E', 'major', 'community', '__stubs__']

const imports: string[] = []
const entries: string[] = []

const communityDefImports: string[] = []
const communityDefEntries: string[] = []

for (const deck of decks) {
  const deckDir = path.join(cardsRoot, deck)
  if (!fs.existsSync(deckDir)) continue
  const files = fs
    .readdirSync(deckDir)
    .filter(
      (f) =>
        f.endsWith('.ts') &&
        !f.endsWith('.test.ts') &&
        f !== 'auto-catalog.ts',
    )
    .sort()
  for (const file of files) {
    const filePath = path.join(deckDir, file)
    const source = fs.readFileSync(filePath, 'utf8')

    // Find `export const <ID>_impl` declarations.
    const implMatch = source.match(/^export const (\w+)_impl\s*[=:]/m)
    if (implMatch) {
      const cardId = implMatch[1]
      const moduleRel = `./${deck}/${path.basename(file, '.ts')}`
      imports.push(`import { ${cardId}_impl } from '${moduleRel}'`)
      entries.push(`  '${cardId}': ${cardId}_impl,`)
    }

  }
}

// Scan cards-display/community/ for community card definition exports
// (display consts live in cards-display after S6b split).
const cardsDisplayRoot = path.resolve(process.cwd(), 'shared', 'cards-display')
const communityDisplayDir = path.join(cardsDisplayRoot, 'community')
if (fs.existsSync(communityDisplayDir)) {
  const files = fs
    .readdirSync(communityDisplayDir)
    .filter(
      (f) =>
        f.endsWith('.ts') &&
        !f.endsWith('.test.ts') &&
        f !== 'auto-catalog.ts',
    )
    .sort()
  for (const file of files) {
    const filePath = path.join(communityDisplayDir, file)
    const source = fs.readFileSync(filePath, 'utf8')
    // Match `export const <ID> = CARD_DEF` or `export const <ID> = new (MinorImprovement|Occupation)`
    const defMatch = source.match(
      /^export const (\w+)\s*=\s*(?:CARD_DEF|new\s+(?:MinorImprovement|Occupation))/m,
    )
    if (defMatch) {
      const defId = defMatch[1]
      const moduleRel = `../../cards-display/community/${path.basename(file, '.ts')}`
      communityDefImports.push(`import { ${defId} } from '${moduleRel}'`)
      communityDefEntries.push(`  ${defId},`)
    }
  }
}

// Write register-all.ts
const output = `// GENERATED by scripts/generate-register-all.ts — do not edit by hand.
// Run \`pnpm run generate:register-all\` after adding or removing card _impl exports.
import type { CardImpl } from './registry'
// Load the catalog BEFORE pulling in card \`_impl\` modules. Catalog imports every
// card-definition file (e.g. \`A93_BedMaker\`) and builds global arrays at module
// scope; some card files (e.g. D117) circle back to catalog for helpers. If
// register-all is the first entry into this subgraph, the \`_impl\` imports below
// can reach catalog before its arrays are populated, surfacing undefined entries
// (pre-existing cycle). Importing catalog first forces the whole card-definition
// graph to finish initialising before we start harvesting \`_impl\` exports.
import './catalog'

${imports.join('\n')}

export const ALL_CARD_IMPLS: Readonly<Record<string, CardImpl>> = {
${entries.join('\n')}
}

export type AllCardImpls = typeof ALL_CARD_IMPLS
`

const outPath = path.join(cardsRoot, 'register-all.ts')
fs.writeFileSync(outPath, output, 'utf8')
console.log(`[generate-register-all] wrote ${entries.length} entries to ${outPath}`)

// Write community/auto-catalog.ts
const autoCatalogImportsBlock =
  communityDefImports.length > 0 ? '\n' + communityDefImports.join('\n') + '\n' : ''
const autoCatalogArrayBlock =
  communityDefEntries.length > 0 ? '\n' + communityDefEntries.join('\n') + '\n' : ''

const autoCatalogOutput = `// GENERATED by scripts/generate-register-all.ts — do not edit by hand.
// Run \`pnpm run generate:register-all\` after adding or removing community card definitions.
import type { MinorImprovement, Occupation } from '../../cards-display/types'
${autoCatalogImportsBlock}
export const allCommunityCards: Array<MinorImprovement | Occupation> = [${autoCatalogArrayBlock}]
`

const autoCatalogPath = path.join(cardsRoot, 'community', 'auto-catalog.ts')
fs.writeFileSync(autoCatalogPath, autoCatalogOutput, 'utf8')
console.log(
  `[generate-register-all] wrote ${communityDefEntries.length} community card defs to ${autoCatalogPath}`,
)
