#!/usr/bin/env tsx
/**
 * Generate `shared/cards/register-all.ts` — a single aggregation module that
 * imports every `<CARD_ID>_impl` export from the card files and exposes them
 * as `ALL_CARD_IMPLS` keyed by card id.
 *
 * Run manually after changing any card file that adds/removes an `_impl`:
 *   pnpm run generate:register-all
 *
 * Task 11 will wire `GameCore` to call `CardRegistry.loadImpl(cardId, impl)`
 * for each entry in `ALL_CARD_IMPLS`.
 */
import fs from 'node:fs'
import path from 'node:path'

const cardsRoot = path.resolve(process.cwd(), 'shared', 'cards')
const decks = ['A', 'B', 'C', 'D', 'E', 'major']

const imports: string[] = []
const entries: string[] = []

for (const deck of decks) {
  const deckDir = path.join(cardsRoot, deck)
  if (!fs.existsSync(deckDir)) continue
  const files = fs
    .readdirSync(deckDir)
    .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
    .sort()
  for (const file of files) {
    const filePath = path.join(deckDir, file)
    const source = fs.readFileSync(filePath, 'utf8')
    // Find `export const <ID>_impl` declarations.
    const match = source.match(/^export const (\w+)_impl\s*[=:]/m)
    if (!match) continue
    const cardId = match[1]
    const moduleRel = `./${deck}/${path.basename(file, '.ts')}`
    imports.push(`import { ${cardId}_impl } from '${moduleRel}'`)
    entries.push(`  '${cardId}': ${cardId}_impl,`)
  }
}

const output = `// GENERATED by scripts/generate-register-all.ts — do not edit by hand.
// Run \`pnpm run generate:register-all\` after adding or removing card _impl exports.
import type { CardImpl } from './registry'
// Load the catalog BEFORE pulling in card \`_impl\` modules. Catalog imports every
// card-definition file (e.g. \`A93_BedMaker\`) and builds global arrays at module
// scope; some card files (e.g. D117) circle back to catalog for helpers. If
// register-all is the first entry into this subgraph, the \`_impl\` imports below
// can reach catalog before its arrays are populated, surfacing undefined entries
// (pre-existing cycle). Importing catalog first forces the whole card-definition
// graph to finish initialising before we start harvesting \`_impl\` exports.
import './catalog'
import { registerCardListener } from './card-listeners'
import { registerCardEffect } from './card-effects'

${imports.join('\n')}

export const ALL_CARD_IMPLS: Readonly<Record<string, CardImpl>> = {
${entries.join('\n')}
}

export type AllCardImpls = typeof ALL_CARD_IMPLS

/**
 * Backward-compatibility bootstrap.
 *
 * PR-2 transitional layer: also register every card's listeners / effect into
 * the legacy module-level Maps in \`card-listeners.ts\` and \`card-effects.ts\`.
 *
 * Why: tests (and a handful of non-session call sites) still \`import\` a card
 * file purely for its side effect, then call \`getCardEffect()\` /
 * \`getRegisteredCardListeners()\` without constructing a \`GameSession\`. Before
 * the \`_impl\`-export migration (Task 6) those imports self-registered into the
 * legacy maps. Now they don't, so we top up the legacy side once per process
 * here. This is safe because:
 *   - Legacy registration happens exactly once (module load side effect).
 *   - \`getCardEffect\` / listener read paths prefer the per-session active
 *     registry when one is attached; they only fall back to legacy when no
 *     session is active (sandbox / test harness).
 *   - PR-3 deletes the legacy maps entirely, along with this bootstrap.
 */
let bootstrapped = false
if (!bootstrapped) {
  bootstrapped = true
  for (const [cardId, impl] of Object.entries(ALL_CARD_IMPLS)) {
    if (impl.listeners && impl.listeners.length > 0) {
      for (const listener of impl.listeners) {
        // Ensure listener targets this card id even if the declaration omitted it.
        const withCardIds =
          listener.cardIds && listener.cardIds.length > 0
            ? listener
            : { ...listener, cardIds: [cardId] }
        registerCardListener(withCardIds)
      }
    }
    if (impl.effect) {
      registerCardEffect(impl.effect)
    }
  }
}
`

const outPath = path.join(cardsRoot, 'register-all.ts')
fs.writeFileSync(outPath, output, 'utf8')
console.log(`[generate-register-all] wrote ${entries.length} entries to ${outPath}`)
