#!/usr/bin/env tsx
/**
 * Generate `shared/cards/register-all.ts` — a single aggregation module that
 * imports every `<CARD_ID>_impl` export from the card files and exposes them
 * as `ALL_CARD_IMPLS` keyed by card id.
 *
 * Run manually after changing any card file that adds/removes an `_impl`:
 *   pnpm run generate:register-all
 *
 * Task 11 will wire `GameCore` to call `CardRegistry.loadImpl(cardId, impl)`
 * for each entry in `ALL_CARD_IMPLS`.
 */
import fs from 'node:fs'
import path from 'node:path'

const cardsRoot = path.resolve(process.cwd(), 'shared', 'cards')
const decks = ['A', 'B', 'C', 'D', 'E', 'major']

const imports: string[] = []
const entries: string[] = []

for (const deck of decks) {
  const deckDir = path.join(cardsRoot, deck)
  if (!fs.existsSync(deckDir)) continue
  const files = fs
    .readdirSync(deckDir)
    .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
    .sort()
  for (const file of files) {
    const filePath = path.join(deckDir, file)
    const source = fs.readFileSync(filePath, 'utf8')
    // Find `export const <ID>_impl` declarations.
    const match = source.match(/^export const (\w+)_impl\s*[=:]/m)
    if (!match) continue
    const cardId = match[1]
    const moduleRel = `./${deck}/${path.basename(file, '.ts')}`
    imports.push(`import { ${cardId}_impl } from '${moduleRel}'`)
    entries.push(`  '${cardId}': ${cardId}_impl,`)
  }
}

const output = `// GENERATED by scripts/generate-register-all.ts — do not edit by hand.
// Run \`pnpm run generate:register-all\` after adding or removing card _impl exports.
import type { CardImpl } from './registry'

${imports.join('\n')}

export const ALL_CARD_IMPLS: Readonly<Record<string, CardImpl>> = {
${entries.join('\n')}
}

export type AllCardImpls = typeof ALL_CARD_IMPLS
`

const outPath = path.join(cardsRoot, 'register-all.ts')
fs.writeFileSync(outPath, output, 'utf8')
console.log(`[generate-register-all] wrote ${entries.length} entries to ${outPath}`)
