// GENERATED by scripts/generate-register-all.ts. Do not edit by hand.
import type { MajorCardDisplay } from './types'

export const majorCardDefinitionsList: readonly (MajorCardDisplay & { kind: 'major' })[] = [
  {
    "id": "Major_Fireplace2",
    "name": "Fireplace",
    "deck": "major",
    "number": 2,
    "cost": {
      "clay": 3
    },
    "vp": 1,
    "extraVp": false,
    "isCookery": true,
    "isBaking": true,
    "fireplaceIdentity": true,
    "desc": [
      "[Anytime]",
      "<VEGETABLE> <ARROW> 2<FOOD>      <PIG> <ARROW> 2<FOOD>",
      "<SHEEP> <ARROW> 2<FOOD>      <CATTLE> <ARROW> 3<FOOD>",
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW> 2<FOOD>"
    ],
    "exchanges": [
      {
        "from": {
          "sheep": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "boar": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "cattle": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_Fireplace2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "vegetable": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace2",
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_CookingHearth2",
    "name": "Cooking Hearth",
    "deck": "major",
    "number": 4,
    "cost": {
      "fee": {
        "clay": 5
      },
      "cards": {
        "type": "Major",
        "list": [
          "Major_Fireplace1",
          "Major_Fireplace2",
          "Major_Fireplace3"
        ]
      }
    },
    "vp": 1,
    "extraVp": false,
    "isCookery": true,
    "isBaking": true,
    "cookingHearthIdentity": true,
    "returnCards": [
      "Major_Fireplace1",
      "Major_Fireplace2",
      "Major_Fireplace3"
    ],
    "desc": [
      "[Anytime]",
      "<VEGETABLE> <ARROW> 3<FOOD>      <PIG> <ARROW> 3<FOOD>",
      "<SHEEP> <ARROW> 2<FOOD>      <CATTLE> <ARROW> 4<FOOD>",
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW> 3<FOOD>"
    ],
    "exchanges": [
      {
        "from": {
          "sheep": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_CookingHearth2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "boar": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_CookingHearth2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "cattle": 1
        },
        "to": {
          "food": 4
        },
        "sourceId": "Major_CookingHearth2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "vegetable": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_CookingHearth2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_CookingHearth2",
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_ClayOven",
    "name": "Clay Oven",
    "deck": "major",
    "number": 5,
    "cost": {
      "clay": 3,
      "stone": 1
    },
    "vp": 2,
    "extraVp": false,
    "isBaking": true,
    "ovenIdentity": true,
    "desc": [
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW-1X> 5<FOOD>",
      "[When you build it, you can Bake immediately]"
    ],
    "exchanges": [
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 5
        },
        "sourceId": "Major_ClayOven",
        "max": 1,
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_StoneOven",
    "name": "Stone Oven",
    "deck": "major",
    "number": 6,
    "cost": {
      "clay": 1,
      "stone": 3
    },
    "vp": 3,
    "extraVp": false,
    "isBaking": true,
    "ovenIdentity": true,
    "desc": [
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW-2X> 4<FOOD>",
      "[When you build it, you can Bake immediately]"
    ],
    "exchanges": [
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 4
        },
        "sourceId": "Major_StoneOven",
        "max": 2,
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_Well",
    "name": "Well",
    "deck": "major",
    "number": 7,
    "cost": {
      "wood": 1,
      "stone": 3
    },
    "vp": 4,
    "extraVp": false,
    "desc": [
      "[Put 1 <FOOD> on the 5 next turns. At the start of each turn, collect the <FOOD>]"
    ],
    "kind": "major"
  },
  {
    "id": "Major_Joinery",
    "name": "Joinery",
    "deck": "major",
    "number": 8,
    "cost": {
      "wood": 2,
      "stone": 2
    },
    "vp": 2,
    "extraVp": true,
    "waresSalesmanGains": [
      {
        "wood": 1,
        "reed": 1
      }
    ],
    "desc": [
      "[Harvest]",
      "<WOOD> <ARROW-1X> 2<FOOD>",
      "[Scoring]",
      "3/5/7<WOOD> <ARROW-1X> 1/2/3<SCORE>"
    ],
    "kind": "major"
  },
  {
    "id": "Major_Pottery",
    "name": "Pottery",
    "deck": "major",
    "number": 9,
    "cost": {
      "clay": 2,
      "stone": 2
    },
    "vp": 2,
    "extraVp": true,
    "potteryIdentity": true,
    "waresSalesmanGains": [
      {
        "clay": 1,
        "reed": 1
      }
    ],
    "desc": [
      "[Harvest]",
      "<CLAY> <ARROW-1X> 2<FOOD>",
      "[Scoring]",
      "3/5/7<CLAY> <ARROW-1X> 1/2/3<SCORE>"
    ],
    "kind": "major"
  },
  {
    "id": "Major_Basket",
    "name": "Basketmaker",
    "deck": "major",
    "number": 10,
    "cost": {
      "reed": 2,
      "stone": 2
    },
    "vp": 2,
    "extraVp": true,
    "waresSalesmanGains": [
      {
        "reed": 2
      }
    ],
    "desc": [
      "[Harvest]",
      "<REED> <ARROW-1X> 3<FOOD>",
      "[Scoring]",
      "2/4/5<REED> <ARROW-1X> 1/2/3<SCORE>"
    ],
    "kind": "major"
  },
  {
    "id": "Major_Fireplace3",
    "name": "Fireplace",
    "deck": "major",
    "number": 11,
    "cost": {
      "clay": 3
    },
    "vp": 1,
    "extraVp": false,
    "isCookery": true,
    "isBaking": true,
    "fireplaceIdentity": true,
    "desc": [
      "[Anytime]",
      "<VEGETABLE> <ARROW> 2<FOOD>      <PIG> <ARROW> 2<FOOD>",
      "<SHEEP> <ARROW> 2<FOOD>      <CATTLE> <ARROW> 3<FOOD>",
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW> 2<FOOD>"
    ],
    "exchanges": [
      {
        "from": {
          "sheep": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace3",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "boar": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace3",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "cattle": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_Fireplace3",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "vegetable": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace3",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace3",
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_CookingHearth3",
    "name": "Cooking Hearth",
    "deck": "major",
    "number": 12,
    "cost": {
      "fee": {
        "clay": 5
      },
      "cards": {
        "type": "Major",
        "list": [
          "Major_Fireplace1",
          "Major_Fireplace2",
          "Major_Fireplace3"
        ]
      }
    },
    "vp": 1,
    "extraVp": false,
    "isCookery": true,
    "isBaking": true,
    "cookingHearthIdentity": true,
    "returnCards": [
      "Major_Fireplace1",
      "Major_Fireplace2",
      "Major_Fireplace3"
    ],
    "desc": [
      "[Anytime]",
      "<VEGETABLE> <ARROW> 3<FOOD>      <PIG> <ARROW> 3<FOOD>",
      "<SHEEP> <ARROW> 2<FOOD>      <CATTLE> <ARROW> 4<FOOD>",
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW> 3<FOOD>"
    ],
    "exchanges": [
      {
        "from": {
          "sheep": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_CookingHearth3",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "boar": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_CookingHearth3",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "cattle": 1
        },
        "to": {
          "food": 4
        },
        "sourceId": "Major_CookingHearth3",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "vegetable": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_CookingHearth3",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_CookingHearth3",
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_Well2",
    "name": "Well",
    "deck": "major",
    "number": 13,
    "cost": {
      "wood": 1,
      "stone": 3
    },
    "vp": 4,
    "extraVp": false,
    "desc": [
      "[Put 1 <FOOD> on the 5 next turns. At the start of each turn, collect the <FOOD>]"
    ],
    "kind": "major"
  },
  {
    "id": "Major_ClayOven2",
    "name": "Clay Oven",
    "deck": "major",
    "number": 14,
    "cost": {
      "clay": 3,
      "stone": 1
    },
    "vp": 2,
    "extraVp": false,
    "isBaking": true,
    "ovenIdentity": true,
    "desc": [
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW-1X> 5<FOOD>",
      "[When you build it, you can Bake immediately]"
    ],
    "exchanges": [
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 5
        },
        "sourceId": "Major_ClayOven2",
        "max": 1,
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_StoneOven2",
    "name": "Stone Oven",
    "deck": "major",
    "number": 15,
    "cost": {
      "clay": 1,
      "stone": 3
    },
    "vp": 3,
    "extraVp": false,
    "isBaking": true,
    "ovenIdentity": true,
    "desc": [
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW-2X> 4<FOOD>",
      "[When you build it, you can Bake immediately]"
    ],
    "exchanges": [
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 4
        },
        "sourceId": "Major_StoneOven2",
        "max": 2,
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_Joinery2",
    "name": "Joinery",
    "deck": "major",
    "number": 16,
    "cost": {
      "wood": 2,
      "stone": 2
    },
    "vp": 2,
    "extraVp": true,
    "waresSalesmanGains": [
      {
        "wood": 1,
        "reed": 1
      }
    ],
    "desc": [
      "[Harvest]",
      "<WOOD> <ARROW-1X> 2<FOOD>",
      "[Scoring]",
      "3/5/7<WOOD> <ARROW-1X> 1/2/3<SCORE>"
    ],
    "kind": "major"
  },
  {
    "id": "Major_Pottery2",
    "name": "Pottery",
    "deck": "major",
    "number": 17,
    "cost": {
      "clay": 2,
      "stone": 2
    },
    "vp": 2,
    "extraVp": true,
    "potteryIdentity": true,
    "waresSalesmanGains": [
      {
        "clay": 1,
        "reed": 1
      }
    ],
    "desc": [
      "[Harvest]",
      "<CLAY> <ARROW-1X> 2<FOOD>",
      "[Scoring]",
      "3/5/7<CLAY> <ARROW-1X> 1/2/3<SCORE>"
    ],
    "kind": "major"
  },
  {
    "id": "Major_Basket2",
    "name": "Basketmaker",
    "deck": "major",
    "number": 18,
    "cost": {
      "reed": 2,
      "stone": 2
    },
    "vp": 2,
    "extraVp": true,
    "waresSalesmanGains": [
      {
        "reed": 2
      }
    ],
    "desc": [
      "[Harvest]",
      "<REED> <ARROW-1X> 3<FOOD>",
      "[Scoring]",
      "2/4/5<REED> <ARROW-1X> 1/2/3<SCORE>"
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_HorseSlaughterhouse2",
    "name": "Horse Slaughterhouse",
    "deck": "major",
    "number": 102,
    "cost": {
      "clay": 1,
      "stone": 1
    },
    "vp": 2,
    "extraVp": false,
    "isCookery": true,
    "desc": [
      "[Anytime]",
      "<SHEEP> <ARROW> 1<FOOD>      <PIG> <ARROW> 1<FOOD>",
      "<CATTLE> <ARROW> 2<FOOD>      <HORSE> <ARROW> 2<FOOD>"
    ],
    "exchanges": [
      {
        "from": {
          "sheep": 1
        },
        "to": {
          "food": 1
        },
        "sourceId": "Major_Moor_HorseSlaughterhouse2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "boar": 1
        },
        "to": {
          "food": 1
        },
        "sourceId": "Major_Moor_HorseSlaughterhouse2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "cattle": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Moor_HorseSlaughterhouse2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "horse": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Moor_HorseSlaughterhouse2",
        "triggers": [
          "anytime"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_Cookhouse2",
    "name": "Cookhouse",
    "deck": "major",
    "number": 104,
    "cost": {
      "fee": {
        "clay": 6
      },
      "cards": {
        "type": "Major",
        "list": [
          "Major_Fireplace1",
          "Major_Fireplace2",
          "Major_Fireplace3",
          "Major_CookingHearth1",
          "Major_CookingHearth2",
          "Major_CookingHearth3"
        ]
      }
    },
    "vp": 2,
    "extraVp": false,
    "isCookery": true,
    "isBaking": true,
    "cookingHearthIdentity": true,
    "returnCards": [
      "Major_Fireplace1",
      "Major_Fireplace2",
      "Major_Fireplace3",
      "Major_CookingHearth1",
      "Major_CookingHearth2",
      "Major_CookingHearth3"
    ],
    "desc": [
      "[Anytime]",
      "<VEGETABLE> <ARROW> 3<FOOD>      <PIG> <ARROW> 3<FOOD>",
      "<SHEEP> <ARROW> 2<FOOD>      <CATTLE> <ARROW> 4<FOOD>",
      "<HORSE> <ARROW> 2<FOOD>",
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW> 3<FOOD>"
    ],
    "exchanges": [
      {
        "from": {
          "sheep": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Moor_Cookhouse2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "boar": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_Moor_Cookhouse2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "cattle": 1
        },
        "to": {
          "food": 4
        },
        "sourceId": "Major_Moor_Cookhouse2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "horse": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Moor_Cookhouse2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "vegetable": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_Moor_Cookhouse2",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_Moor_Cookhouse2",
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_PeatCharcoalKiln",
    "name": "Peat-charcoal Kiln",
    "deck": "major",
    "number": 105,
    "cost": {
      "stone": 1
    },
    "vp": 1,
    "extraVp": true,
    "desc": [
      "[Special action: Cut Peat]",
      "Gain 1 extra fuel, or 2 extra fuel if you have at least 1 horse.",
      "[Scoring]",
      "3/5 fuel <ARROW> 1/2 bonus points."
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_ForestersLodge",
    "name": "Forester's Lodge",
    "deck": "major",
    "number": 106,
    "cost": {
      "wood": 1,
      "clay": 2
    },
    "vp": 1,
    "extraVp": true,
    "desc": [
      "[Special action: Fell Trees]",
      "Gain 1 extra wood, or 2 extra wood if you have at least 1 horse.",
      "[Scoring]",
      "Gain 1 bonus point for each forest in your farmyard."
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_RidingStables",
    "name": "Riding Stables",
    "deck": "major",
    "number": 107,
    "cost": {
      "wood": 2,
      "clay": 1,
      "reed": 1
    },
    "vp": 3,
    "extraVp": false,
    "desc": [
      "Place 1 food on each remaining round space.",
      "At the start of each round, gain that food if you have at least 2 horses."
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_MuseumOfTheMoors",
    "name": "Museum of the Moors",
    "deck": "major",
    "number": 108,
    "cost": {
      "clay": 1,
      "reed": 1,
      "stone": 1
    },
    "vp": 3,
    "extraVp": false,
    "desc": [
      "Selected major improvements cost you 1 fewer matching building resource."
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_HeatingOven",
    "name": "Furnace",
    "deck": "major",
    "number": 109,
    "cost": {
      "clay": 1,
      "stone": 1
    },
    "vp": 1,
    "extraVp": false,
    "ovenIdentity": true,
    "desc": [
      "Immediately gain 2 fuel.",
      "When heating, heat 1 fewer room than you have."
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_TiledOven",
    "name": "Heating Stove",
    "deck": "major",
    "number": 110,
    "cost": {
      "clay": 2,
      "stone": 1
    },
    "vp": 1,
    "extraVp": false,
    "ovenIdentity": true,
    "desc": [
      "Regardless of house size, you need at most 1 fuel to heat your entire home."
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_VillageChurch",
    "name": "Village Church",
    "deck": "major",
    "number": 111,
    "cost": {
      "wood": 2,
      "stone": 4
    },
    "vp": 4,
    "extraVp": true,
    "desc": [
      "Immediately gain 2 food.",
      "[Harvest]",
      "Once each harvest, you may pay 1 fuel to gain 1 bonus point."
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_FurnitureStall",
    "name": "Furniture Stall",
    "deck": "major",
    "number": 112,
    "cost": {
      "wood": 1,
      "stone": 1
    },
    "vp": 2,
    "extraVp": false,
    "desc": [
      "[Anytime]",
      "Exchange wood for the same amount of clay."
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_CeramicsStall",
    "name": "Ceramics Stall",
    "deck": "major",
    "number": 113,
    "cost": {
      "clay": 1,
      "stone": 1
    },
    "vp": 2,
    "extraVp": false,
    "desc": [
      "[Anytime]",
      "Exchange clay for the same amount of wood."
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_BasketStall",
    "name": "Basket Stall",
    "deck": "major",
    "number": 114,
    "cost": {
      "reed": 1,
      "stone": 1
    },
    "vp": 2,
    "extraVp": false,
    "desc": [
      "[Anytime]",
      "Exchange reed for the same amount of other building resources."
    ],
    "kind": "major"
  },
  {
    "id": "Major_CookingHearth1",
    "name": "Cooking Hearth",
    "deck": "major",
    "number": 3,
    "cost": {
      "fee": {
        "clay": 4
      },
      "cards": {
        "type": "Major",
        "list": [
          "Major_Fireplace1",
          "Major_Fireplace2"
        ]
      }
    },
    "vp": 1,
    "extraVp": false,
    "isCookery": true,
    "isBaking": true,
    "cookingHearthIdentity": true,
    "returnCards": [
      "Major_Fireplace1",
      "Major_Fireplace2",
      "Major_Fireplace3"
    ],
    "desc": [
      "[Anytime]",
      "<VEGETABLE> <ARROW> 3<FOOD>      <PIG> <ARROW> 3<FOOD>",
      "<SHEEP> <ARROW> 2<FOOD>      <CATTLE> <ARROW> 4<FOOD>",
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW> 3<FOOD>"
    ],
    "exchanges": [
      {
        "from": {
          "sheep": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_CookingHearth1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "boar": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_CookingHearth1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "cattle": 1
        },
        "to": {
          "food": 4
        },
        "sourceId": "Major_CookingHearth1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "vegetable": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_CookingHearth1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_CookingHearth1",
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_Fireplace1",
    "name": "Fireplace",
    "deck": "major",
    "number": 1,
    "cost": {
      "clay": 2
    },
    "vp": 1,
    "extraVp": false,
    "isCookery": true,
    "isBaking": true,
    "fireplaceIdentity": true,
    "desc": [
      "[Anytime]",
      "<VEGETABLE> <ARROW> 2<FOOD>      <PIG> <ARROW> 2<FOOD>",
      "<SHEEP> <ARROW> 2<FOOD>      <CATTLE> <ARROW> 3<FOOD>",
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW> 2<FOOD>"
    ],
    "exchanges": [
      {
        "from": {
          "sheep": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "boar": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "cattle": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_Fireplace1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "vegetable": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Fireplace1",
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_Cookhouse1",
    "name": "Cookhouse",
    "deck": "major",
    "number": 103,
    "cost": {
      "fee": {
        "clay": 6
      },
      "cards": {
        "type": "Major",
        "list": [
          "Major_Fireplace1",
          "Major_Fireplace2",
          "Major_Fireplace3",
          "Major_CookingHearth1",
          "Major_CookingHearth2",
          "Major_CookingHearth3"
        ]
      }
    },
    "vp": 2,
    "extraVp": false,
    "isCookery": true,
    "isBaking": true,
    "cookingHearthIdentity": true,
    "returnCards": [
      "Major_Fireplace1",
      "Major_Fireplace2",
      "Major_Fireplace3",
      "Major_CookingHearth1",
      "Major_CookingHearth2",
      "Major_CookingHearth3"
    ],
    "desc": [
      "[Anytime]",
      "<VEGETABLE> <ARROW> 3<FOOD>      <PIG> <ARROW> 3<FOOD>",
      "<SHEEP> <ARROW> 2<FOOD>      <CATTLE> <ARROW> 4<FOOD>",
      "<HORSE> <ARROW> 2<FOOD>",
      "[__Bake Bread__ action:]",
      "<GRAIN> <ARROW> 3<FOOD>"
    ],
    "exchanges": [
      {
        "from": {
          "sheep": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Moor_Cookhouse1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "boar": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_Moor_Cookhouse1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "cattle": 1
        },
        "to": {
          "food": 4
        },
        "sourceId": "Major_Moor_Cookhouse1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "horse": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Moor_Cookhouse1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "vegetable": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_Moor_Cookhouse1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "grain": 1
        },
        "to": {
          "food": 3
        },
        "sourceId": "Major_Moor_Cookhouse1",
        "triggers": [
          "bake-bread"
        ]
      }
    ],
    "kind": "major"
  },
  {
    "id": "Major_Moor_HorseSlaughterhouse1",
    "name": "Horse Slaughterhouse",
    "deck": "major",
    "number": 101,
    "cost": {
      "clay": 1,
      "stone": 1
    },
    "vp": 2,
    "extraVp": false,
    "isCookery": true,
    "desc": [
      "[Anytime]",
      "<SHEEP> <ARROW> 1<FOOD>      <PIG> <ARROW> 1<FOOD>",
      "<CATTLE> <ARROW> 2<FOOD>      <HORSE> <ARROW> 2<FOOD>"
    ],
    "exchanges": [
      {
        "from": {
          "sheep": 1
        },
        "to": {
          "food": 1
        },
        "sourceId": "Major_Moor_HorseSlaughterhouse1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "boar": 1
        },
        "to": {
          "food": 1
        },
        "sourceId": "Major_Moor_HorseSlaughterhouse1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "cattle": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Moor_HorseSlaughterhouse1",
        "triggers": [
          "anytime"
        ]
      },
      {
        "from": {
          "horse": 1
        },
        "to": {
          "food": 2
        },
        "sourceId": "Major_Moor_HorseSlaughterhouse1",
        "triggers": [
          "anytime"
        ]
      }
    ],
    "kind": "major"
  },
]

export const majorImprovementIdsList =
  majorCardDefinitionsList.map((card) => card.id)
