// GENERATED by scripts/generate-register-all.ts. Do not edit by hand.
import type { CardSource } from '../card-source'
import { Major_Fireplace2 } from './fireplace'
import { Major_CookingHearth2 } from './cooking-hearth'
import { Major_ClayOven } from './clay-oven'
import { Major_StoneOven } from './stone-oven'
import { Major_Well } from './well'
import { Major_Joinery } from './joinery'
import { Major_Pottery } from './pottery'
import { Major_Basket } from './basketmaker'
import { Major_CookingHearth1 } from './cooking-hearth'
import { Major_Fireplace1 } from './fireplace'

export const majorCardSources = [
  Major_Fireplace2,
  Major_CookingHearth2,
  Major_ClayOven,
  Major_StoneOven,
  Major_Well,
  Major_Joinery,
  Major_Pottery,
  Major_Basket,
  Major_CookingHearth1,
  Major_Fireplace1,
] as const satisfies readonly CardSource<'major'>[]

export const majorImprovementIdsList =
  majorCardSources.map((source) => source.meta.id)
