// GENERATED by scripts/generate-register-all.ts. Do not edit by hand.
import type { CardSource } from '../card-source'
import { Major_Fireplace2 } from './fireplace'
import { Major_CookingHearth2 } from './cooking-hearth'
import { Major_ClayOven } from './clay-oven'
import { Major_StoneOven } from './stone-oven'
import { Major_Well } from './well'
import { Major_Joinery } from './joinery'
import { Major_Pottery } from './pottery'
import { Major_Basket } from './basketmaker'
import { Major_Fireplace3 } from './fireplace'
import { Major_CookingHearth3 } from './cooking-hearth'
import { Major_Well2 } from './well'
import { Major_ClayOven2 } from './clay-oven'
import { Major_StoneOven2 } from './stone-oven'
import { Major_Joinery2 } from './joinery'
import { Major_Pottery2 } from './pottery'
import { Major_Basket2 } from './basketmaker'
import { Major_Moor_HorseSlaughterhouse2 } from './moor-horse-slaughterhouse'
import { Major_Moor_Cookhouse2 } from './moor-cookhouse'
import { Major_Moor_PeatCharcoalKiln } from './moor-peat-charcoal-kiln'
import { Major_Moor_ForestersLodge } from './moor-foresters-lodge'
import { Major_Moor_RidingStables } from './moor-riding-stables'
import { Major_Moor_MuseumOfTheMoors } from './moor-museum-of-the-moors'
import { Major_Moor_HeatingOven } from './moor-heating-oven'
import { Major_Moor_TiledOven } from './moor-tiled-oven'
import { Major_Moor_VillageChurch } from './moor-village-church'
import { Major_Moor_FurnitureStall } from './moor-furniture-stall'
import { Major_Moor_CeramicsStall } from './moor-ceramics-stall'
import { Major_Moor_BasketStall } from './moor-basket-stall'
import { Major_CookingHearth1 } from './cooking-hearth'
import { Major_Fireplace1 } from './fireplace'
import { Major_Moor_Cookhouse1 } from './moor-cookhouse'
import { Major_Moor_HorseSlaughterhouse1 } from './moor-horse-slaughterhouse'

export const majorCardSources = [
  Major_Fireplace2,
  Major_CookingHearth2,
  Major_ClayOven,
  Major_StoneOven,
  Major_Well,
  Major_Joinery,
  Major_Pottery,
  Major_Basket,
  Major_Fireplace3,
  Major_CookingHearth3,
  Major_Well2,
  Major_ClayOven2,
  Major_StoneOven2,
  Major_Joinery2,
  Major_Pottery2,
  Major_Basket2,
  Major_Moor_HorseSlaughterhouse2,
  Major_Moor_Cookhouse2,
  Major_Moor_PeatCharcoalKiln,
  Major_Moor_ForestersLodge,
  Major_Moor_RidingStables,
  Major_Moor_MuseumOfTheMoors,
  Major_Moor_HeatingOven,
  Major_Moor_TiledOven,
  Major_Moor_VillageChurch,
  Major_Moor_FurnitureStall,
  Major_Moor_CeramicsStall,
  Major_Moor_BasketStall,
  Major_CookingHearth1,
  Major_Fireplace1,
  Major_Moor_Cookhouse1,
  Major_Moor_HorseSlaughterhouse1,
] as const satisfies readonly CardSource<'major'>[]
